candlepin/subscription-manager

man/subscription-manager.8
src/subscription_manager/managercli.py
test/test_managercli.py

ie, 'subscription-manager attach' is now the same as
'subscription-manager attach --auto'. Using --pool or
--file turns off the default 'auto' mode.
'--auto' still works as well, though redundant now.

Make 'attach' auto unless otherwise specified.

---

src/subscription_manager/jsonwrapper.py
src/subscription_manager/managercli.py
src/subscription_manager/managerlib.py
test/test_jsonwrapper.py
test/test_managercli.py

subscription-manager list --available and --consumed will now
display the "Provides Management" row in its output to match the
information available from the GUI.

1180395: Added "Provides Management" to subman list output

---

src/daemons/rhsm_d.py
src/subscription_manager/managerlib.py
test/test_managerlib.py

If the info returned from a cert_sorter.get_compliance_status
didn't have keys we expected, we broke.
Attempt to be more lenient about the structure of compliance
status. Ignore missing keys, empty lists, etc.
Move refresh_compliance_status to managerlib, and add tests
to test_managerlib.

1183122: Fix KeyErrors building dbus ent status

---

etc-conf/rhsm-debug.completion.sh
man/rhsm-debug.8
src/rhsm_debug/debug_commands.py
test/test_rhsm_debug_command.py

Add a '--subscriptions' cli option now, and make '--no-subscriptions'
the default behaviour. For orgs with lots of subscriptions
available, the candlepin api request getSubscriptionsList can
be very slow.

1114117: Stop collecting subs info by default.

---

.gitignore
Makefile
src/rct/version.py.in
src/subscription_manager/utils.py
src/subscription_manager/version.py.in
subscription-manager.spec
test/test_utils.py

Instead of asking the rpm db for the versions
of "subsciption-manager" and "python-rhsm", we
generate a versions.py at build time with that
info.
"make set-versions" is the make target that
does it. It will use VERSION from the env
(the spec file passes this in), or if
not specified, it will build one based
on 'git describe'.
This removes code that was on average spending
about .5s every time we started up (including
cli). This reduces it to basically nothing.
This requires latest python-rhsm (>= 1.8.14-1)

976855: populate a "version.py" at build time

---

src/subscription_manager/gui/registergui.py

Removed the extraneous 's' from "Susbscriptions."

Fixed typo in subscription-manager-gui

---

src/subscription_manager/gui/firstboot/rhsm_login.py
src/subscription_manager/gui/registergui.py

In firstboot, if we encounter problems that may block
registration, return users to the "why register" info
page where there is an options to skip registering.
Previously it would return to either the login page
or stay on the current page in the face of those errors.
But in the context of firstboot, there was no escape
route to get out of firstboot.
Add hooks to registergui.RegisterScreen and
rhsm_login.moduleClass so they know there preffered
error_page. If error handlers are triggered, we
return to the info page on not fatal errors.

1191237: Fix problems exitting firstboot on errors

---

src/subscription_manager/gui/firstboot/rhsm_login.py

In the firstboot path, there was no gtk threads_init()
called. It's normally called via subscription-manager-gui,
but not by firstboot.

1191237: Fix proxy "test connection" in firstboot.

---

src/subscription_manager/gui/firstboot/rhsm_login.py

In firstboot, we were attempting to merge in any
existing RHN proxy configuration, but we were doing
it after the user provided proxy info in the network
configuration dialog and were overwritting it. For
the case of RHN proxy config existing, but with
proxyEnabled=0, we were unsetting the user provided
values and saving it.
This moves the RHN proxy info merging to before the
network config dialog, and also fixes the RHN proxy
info loading to not alter anything if it's disabled.

1191237: Make proxy config "save" work in firstboot.

---

tox.ini

W503 "line break before binary operator"
and was added to pep8 in version 1.6.2.

Ignore pep8 error W503

---

src/subscription_manager/cert_sorter.py
src/subscription_manager/managercli.py
src/subscription_manager/utils.py
tox.ini

"The preferred place to break around a binary operator is after the
operator, not before it."
Versions of pep8 >= 1.6.2 check that, so this makes the code
confirm.

Make code pass pep8 W503 warning

---

src/rct/printing.py
src/subscription_manager/cert_sorter.py
src/subscription_manager/cli.py
src/subscription_manager/dmiinfo.py
src/subscription_manager/exceptions.py
src/subscription_manager/gui/importsub.py
src/subscription_manager/gui/utils.py
src/subscription_manager/injection.py
src/subscription_manager/plugin/ostree/config.py
src/subscription_manager/plugins.py
test/modelhelpers.py
test/stubs.py
test/test_gui_utils.py
test/test_po_files.py

"Imports are always put at the top of the file, just after any module
comments and docstrings, and before module globals and constants."
pep8 checker versions since 1.6.2 check for this, so clean up
the places it finds. There are still modules that will fail, since
they alter sys.path and then do imports. Pep8 checker fails these
cases though pep 8 itself is vague about that case.

Move module imports to top of modules (pep8 E402)

---

src/subscription_manager/gui/widgets.py

If gtk finds that it's own translations for some of
the calendars widget's strings and labels is wrong, it
warns us. And users. Neither of which can fix it (its a
gtk translation error), so ignore it.

Quiet "Whoever translated calendar*" warnings.

---

Makefile
subscription-manager.spec

'jenkins' build target would run stylish and unittests, but
it was not compiling the C utils. So 'jenkins' target now
includes 'build' target and 'set-versions' is moved there.
Since 'build' (the default target) now creates the version
files, update spec file to set VERSION there as well.

'make jenkins' now hits 'build' to compile C code.

---

src/subscription_manager/gui/managergui.py

Gtk tries to track the list of most recently used files and
other settings in ~/.local/recently-used.xbel, but /root
does not typically have a ~/.local dir, so the warning:
GtkWarning: 'Attempting to set the permissions of
`/root/.local/share/recently-used.xbel'
is issued either to stdout, or the log.
Disable it by setting the gtk.Settings property 'gtk-recent-files-max-age'
to 0.

Stop 'recently-used.xbel' warnings, disable mru

---

src/subscription_manager/printing_utils.py
src/subscription_manager/utils.py

https://bugzilla.redhat.com/show_bug.cgi?id=1145077 
get_terminal_width() in utils.py now accounts for redirects
wrapped:
```
[root@jmolet-vm0 ~]# subscription-manager list --available 
+-------------------------------------------+
Available Subscriptions
+-------------------------------------------+
Subscription Name:   Red Hat Enterprise Linux Server, Premium (8
sockets) (Up to 4 guests)
Provides:            Red Hat Beta
Oracle Java (for RHEL Server)
Red Hat Enterprise Linux Server
Red Hat Software Collections Beta (for RHEL
Server)
SKU:                 RH0103708
Contract:            10697277
```
redirected:
```
[root@jmolet-vm0 ~]# subscription-manager list --available > blah && cat blah
+-------------------------------------------+
Available Subscriptions …
```

BZ: 1145077, disabled column wrapping during redirects

---

test/test_format_time.py

There seems to be a bug in python-dateutil 2.0 or
higher in the tz.tzstr() method, where it fails if
the arg passed in is a regular string and not a
unicode string. This works around that by changing
the test to pass the tz string as a unicode string.
See https://bugzilla.redhat.com/show_bug.cgi?id=1197791
and https://bugs.launchpad.net/dateutil/+bug/1331576 for
the dateutil bug.

1183382: Fix test case to work with dateutil 2.

---

src/subscription_manager/gui/messageWindow.py

As part of a workaround for #865702, we were
accessing a gtk.MessageDialogs private label so we
could detect if it failed to parse the markup in
error messages from the server, which at the time
was the clonepin proxy. Access the private label
causes a DeprecationWarning.
Those messages have since been updated, and clonepin
decommissioned, so the workaround is no longer
needed.

1133647: Fix messageWindow deprecation warning.

---

bin/subscription-manager-gui
src/subscription_manager/gui/widgets.py

Warnings like "Attempt to add property * after class was initialised"
can be ignore, the code that issued that was added in
glib2-2.40 and removed in glib2-2.42. So add a warnings
filter to ignore them.
Added in widgets.py so unit tests also ignore them.

Ignore glib warnings about class properties.

---

src/subscription_manager/managercli.py

- "subscription-manager attach --help" and "subscription-manager subscribe --help"
no longer indicate that --servicelevel requires --auto

1209519: Removed erroneous information in help message for subman

---

src/subscription_manager/managerlib.py

- managerlib.refresh_compliance_status now assigns a default value to
the state variable to prevent a crash from occurring when product_id
is a falsy value.

1198369: refresh_compliance_status now has a default value for state

---

src/subscription_manager/utils.py
test/test_utils.py

installedtab uses friendly_join to format the list
of contract numbers that apply to a product. If the order
info attached to an entitlement cert has no contract
number set, friendly_join would throw a TypeError.
So ignore None in the list of items now.

1207958: Fix traceback when contract # is None

---

man/rhsm.conf.5

Attempt to clarify the behaviour when manage_repos is set to 0 in rhsm.conf man
page. Leaving redhat.repo around would be a very quick path to broken yum as
soon as content changed, so we cannot leave the file laying around.

1170314: Clarify that manage_repos 0 will delete redhat.repo.

---

src/subscription_manager/cache.py

When deleting overrides, if it was the last one, the cache would
reload from disk since 'if not self.server_status' will be True
for []. This presented a race condition for the cash write and
repo_lib update threads, which made the bug hard to reproduce on
some slower systems.
The cache should be checking server_status against None since
[] does not mean that the cache was not read.
NOTE: There are no tests as I couldn't find a way to reliably test this scenario due to stubbing. I am open to suggestions.

1195501: Properly refresh repo file on override deletion

---

bin/subscription-manager
src/daemons/rhsm_d.py
src/subscription_manager/dbus_interface.py
src/subscription_manager/managercli.py
src/subscription_manager/managerlib.py
test/test_managerlib.py

Problematic in 7.1 and appearing again in 6.7, given the implementation is not
getting used yet and the feature needs a re-think, pulling this out for 6.7 as
well.
Revert "884285: Needs to maintain loop for dbus calls"
This reverts commit d38e4e58c709a45021307ffa60ae5926c09182b7.
Conflicts:
src/subscription_manager/logutil.py
Revert "1159266: rhsm-icon -i fails with "TypeError: 'NoneType' object has no attribute '__getitem__'""
This reverts commit e3b6516ed3a7e1e382a38746bb2f7e1dc190679d.
Conflicts:
src/daemons/rhsm_d.py
Revert "Send list of compliance reasons on dbus"
This reverts commit cedc122d3178f4853fc2135fc19457c8bf6fa475.
Remove some dbus testing no longer used.

1207306: Revert DBus compliance status code.

---

src/subscription_manager/gui/firstboot_base.py

This fix will properly wrap any long titles that might
appear in any rhsm firstboot module.

1147404: Fixed firstboot title length issues

---

etc-conf/logging.conf

Recent logging changes included a config for a presently unused syslog handler.
This however causes a full crash in yum plugin and subscription-manager when
trying to configure logging if rsyslog isn't running.
As this is meant to be an optional logging handler, remove it from the
configured handler and formatter keys.

1211557: Fix crash when rsyslog not running.

---

src/subscription_manager/repolib.py
test/fixture.py
test/test_entcertlib.py
test/test_repolib.py

The str() for repolib.RepoActionReport would fail if
it tried to join together str's that could not be
decoded into ascii, when combining the translation for
'Added (new)' and a unicode string of the content label
or a repo section id. So make sure content info is
encoded to utf8 for display.
This bug is dependent on the absence of python-simplejson
on RHEL7. The 'ourjson' module will use either the built
in python 'json' module or simplejson if it is installed.
python-simplejson is not an rpm dep however, so it is
optionaly. However, the API of python's 'json' and
'simplejson' differ slightly. The built in 'json' module
will deserialize JSON strings into unicode strings allways,
where simplejson does not.
So if python-simplejson was installed, the repolib report
does not cause the …

1199597: Fix UnicodeError from repolib's report

---

etc-conf/rhn-migrate-classic-to-rhsm.completion.sh
man/rhn-migrate-classic-to-rhsm.8
src/subscription_manager/migrate/migrate.py
test/test_migration.py

This commit builds on a previous effort to allow users to migrate from
RHN Classic without a password.  In this commit, the option for leaving
a profile on RHN Classic (it is the deletion of a profile that requires
a password) has been switched to a flag rather than an option as it was
previously.
Additionally this commit fixes an issue where users were not being
required to provide credentials to the destination when leaving a
profile on RHN Classic.

1180273: Migrate from RHN Classic without credentials

---

src/plugins/product-id.py
src/plugins/subscription-manager.py

If product-id yum plugin was installed and enabled, and
a yum transaction updates subscription-manager code, we
could end up with the old version of 'injection', and the
new version of 'injectioninit'.
The injectioninit import was not at module scope, and would
not load the module until the plugin hook is called. But
the other subman modules in productids module scope would
cause 'injection' to be imported.
So yum starts up, loads our 'product-id' yum plugin module,
which loads 'injection' module into the process. Then we
update subscription-manager, replacing all of our modules
include 'injection' and 'injectioninit'. After the rpm
transaction runs, then we run the 'posttrans_hook' product
id plugin, which would then load 'injectioninit' from the
filesystem and get the new injectioninit. …

1149095: Fix error when yum updates subman modules

---

src/subscription_manager/productid.py
src/subscription_manager/repolib.py
test/fixture.py
test/test_productid.py

If yum was invoked with --disablerepo=example-repo, and
example-repo is the only repo associated with a product id,
we would delete the product id.
The fix adds code to attempt to determine what yum repos
have been disabled temporarily. Temporarily in this case
meaning not via redhat.repo, but via the yum --disablerepo
command line option, or potentially via another yum plugin.
We load and parse redhat.repo ourself, and track repos that
are enabled there, and compare to the runtime list of enabled
repos yum computes (after it's cli options and config plugins
are applied). If anything is missing, we consider it temporarily
disabled.
When we check product certs looking for certs that may need to
be deleted, if that product is mapped to one of the temporarily
disabled repos, it is not …

1159163: Fix prod id del because of --disablerepo

---

man/subscription-manager.8

- The --servicelevel option in the man page for "attach" no longer
implies that --auto must be specified to use it.

Updated the manual pages for the attach command

---

src/subscription_manager/managercli.py
src/subscription_manager/migrate/migrate.py
test/test_migration.py

- Many calls to system_exit now specify an error code on exit instead
of using a common non-zero value
- Reverted an error code in manager_cli to be consistent with general error-code usage and the migrate script

1217835: Specified error codes on system_exit in rhn-migrate-classic-to-rhsm

---

man/rhn-migrate-classic-to-rhsm.8

- The --keep option has been added to the synopsis line in the man
page for rhn-migrate-classic-to-rhsm.
- Added a missing hyphen for the destination-user option in the
synopsis

1218377: Added missing option to the migration manual page

---

src/rhsm_debug/debug_commands.py
test/test_rhsm_debug_command.py

We were creating temp test dirs but never
deleting them. So do that in the tearDown().
Use a tempdir via tempfile.mkdtemp for test temp
directory instead of os.getcwd()/testing-dir. tempdir
tmp directory is also likely on tmpfs, so a little
faster.
Add a final_destination_path attribute to rhsm-debugs
SystemCommand that tracks the name of the archive
that was written, so tests can clean up.
Add some test helper methods to remove some
duplication.

Make rhsm-debug test cases clean up better.

---

test/test_widgets.py

DatePicker always uses isoformat() for date now, so
we don't need to test it for each locale.
Also removed a Capture() from a test, I believe the
py/gtk warnings capture in fixtures does the same thing
now.
Shaves off about .5sec off a unit tests run if nothing else.

Remove locale based DatePicker tests.

---

src/subscription_manager/managercli.py

Removal of entry completely means that default is the only value that will
be used going forward. By inserting the default insead, the behavoir is
correct, but future changes are not limited.

1223860: Revert to default value on remove command

---

src/subscription_manager/repolib.py
test/test_repolib.py

repolib.RepoActionInvoker.is_managed is used by some
openshift utilities, but it was busted when the rest of
repolib moved to using model.ent_cert.
Add a public matching_content method to the RepoActionCommand
class, so that RepoActionInvoker.is_managed works again.
Add test cases for RepoActionInvoker.is_managed, since it is
only used by external tools.

1223038: Fix API used by openshift clients.

---

test/stubs.py

A few stubs classes were doing things like:
def __init__(self, uep=StubUEP()):
Which means all of the test that use those
stub classes would get the same StubUep() reference.
That's kind of odd, but some of the stub classes
were tracking assumulating values and lists, and
causing some bogus test results.
Also update the rest of the classes to new style
classes.

Remove mutable default args in stubs

---

src/subscription_manager/hwprobe.py

fact collection was using 'LANG=en_US.UTF-8 lscpu' to
get lscpu facts, including the field descriptions, that
are marked for translations.
If the user env set a locale using LC_ALL instead of LANG,
the LC_ALL value would override the LANG used for lscpu, so
specify LC_ALL=en_US.UTF-8 when running lscpu now.
Previously, this would end up with garbled fact names
(ja_JP localized UTF8 strings manipulated with .lower()/.replace)
and would cause registration failures.
Users should set locale with the LANG env variable, not
LC_ALL, but let lscpu invocation override either with it's
own LC_ALL value.

1225435: Use LC_ALL instead of LANG for lscpu.

---

Makefile
subscription-manager.spec

Building a PIE requires both special CFLAGS and LDFLAGS.  We were
missing the LDFLAGS so our executables weren't PIEs.
Testing that an executable is hardened can be done via the
`hardening-check` package available in Fedora.
Save the following script as `pie-check.sh`:
```bash
#! /bin/bash
p=$1
echo "Checking $p"
rpm2cpio $p | cpio -idm
echo
find . -type f -exec file {} \; | grep -o '.*:.* ELF' | while read -r f
do
f=${f%:* ELF}
pushd ${f%/*} >/dev/null
readelf -W -l ${f##*/} > ~-/program_headers 2>  ~-/erroutput
readelf -W -d ${f##*/} > ~-/dynamic_section 2>> ~-/erroutput
readelf -W -h ${f##*/} > ~-/elf_header      2>> ~-/erroutput
popd >/dev/null
TYPE=$(grep -m1 -F 'Type:' elf_header | awk '{ print $2; }')
if [[ -s erroutput ]]
then
printf "PROCESSING FAILED: (%04d) %s : %s\n" $cnt …
```

1092564: Add LDFLAGS to make file so RPM can modify them.

---

src/plugins/subscription-manager.py
src/subscription_manager/cache.py
src/subscription_manager/certlib.py
src/subscription_manager/lock.py
src/subscription_manager/overrides.py
src/subscription_manager/repolib.py
test/test_lock.py

Previously the rhsm yum plugin 'subscription-manager'
would block waiting for the rhsm cert lock to be
released. This file based lock is used by rhsm
code (subscription-manager, rhsmcert-worker, the
yum plugins) to try to make changes to entitlement
certs and redhat.repo mostly atomic, and to prevent
multiple processes from colliding (for example,
rhsmcertd-worker and the yum plugin, both of which
may attempt to update the redhat.repo at the same
time).
If an rhsm process has acquired the rhsm cert lock
when the yum plugin attempts to acquire it, the yum
plugin would wait for the lock to be released. If
the lock ended up being long lasting, this could
block the yum process until the lock is release.
Now the ActionInvoker classes allow a different
Locker implementation to be passed in. The …

1224806: Prevent yum blocking on rhsm locks

---

src/daemons/rhsmcertd.c

We don't need to check the return value of
daemon, but do it anyway to quiet compiler warnings.

Cast return daemon() to void to quiet warnings.

---

etc-conf/rhsm-icon.desktop.in
etc-conf/subscription-manager-gui.desktop.in

It was complaining about GenericName and Comment being
redundant, and indeed, they were. So they have been
removed.
'Encoding' type is also now deprecated and UTF-8 is
the default, so remove it as well.
The Catagories 'System' and 'Settings' are both
'Main' categories. And validate wants only one
main category. 'Settings' seems unused by anything
now, so we removed it.

Make desktop-file-validate warnings.

---

subscription-manager.spec

/usr/bin/subscription-manager and
/usr/bin/subscription-manager-gui are both symlinks
to console helper.
Spec file was attempting to set %attr on the links,
which has no effect, so rpmbuild was warning about it
with a message like:
warning: Explicit %attr() mode not applicaple to symlink:
/BUILDROOT/subscription-manager-1.1-1.x86_64/usr/bin/subscription-manager
This removes the %attr to stop the warning.

Don't try to set file attrs on symlinks in spec

---

subscription-manager.spec

Note that this patch *does not* harden the build for RHEL 6.  RHEL 6 does not provide any PIE/PIC RPM macros and setting everything by hand would require a lot of GCC magic that I don't know (e.g. use `-fpie` unless you're on S390X, in which case use `-fPIE`).
Instead, this patch simply gets the builds running on RHEL 6 again.

Define global_ld_flags when not already defined.

---

Makefile
src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py
subscription-manager.spec

When initial-setup and anaconda were rebased to more
recent versions, some of the API changed. Most notably
the move of the 'ui.gui.categories' package to 'ui.categories'.
rhsm_gui.py was updated to reflect that.
The required module layout also changed in a similar manner,
so Makefile and spec file also updated to reflect that.
This should resolve errors loading our initial-setup
module.

1240801: Use latest initial-setup API

---

Makefile

Updated the sed command which updates the subman/src/version.py file to do both RPM_VERSION and GTK_VERSION in one execution to prevent the GTK_VERSION command from clobbering the work done by the RPM_VERSION command.

1241184: Updated Makefile to prevent version string clobbering

---

src/subscription_manager/api/__init__.py
src/subscription_manager/api/repos.py
test/test_api.py

How to test:
1. Attach to some valid subscriptions so that you have something present in `redhat.repo`
1. `cp /etc/yum.repos.d/redhat.repo /tmp/redhat.bak`
1. Take a look at `redhat.repo` and find some disabled repos
1. Run `PYTHONPATH=src/ python`
1. In the REPL, do the following.  (The argument passed to `enable_repositories` should be the ID for one of the repos you picked in step 3)
```
>>> from subscription_manager import api
>>> api.enable_repositories('rhs-big-data*')
```
1. The result should be non-zero
1. Quit the REPL with Ctrl-D
1. `diff -u /tmp/redhat.bak /etc/yum.repos.d/redhat.repo`
1. The only differences should be the newly enabled repositories. Additionally, `/var/log/rhsm/rhsm.log` should have messages generated when a repositories is enabled.

1232232: Add supported API to enable content repositories.

---

src/daemons/rhsm_d.py

The RHN Classic message is not unusual for RHN managed
systems, so lower it's syslog level from NOTICE to INFO.

1234413: lower log level of rhsmd RHN messages

---

setup.cfg
test/test_managercli.py

Despite src/subscription_manager/__init__.py having a
'__test__ = None' attribute, nose still attempts to load
all modules in src/subscription_manager/ga_impls/, which
fails. pygobject3-3.14 introduced some gobject/gi module
loading changes that raise exceptions if code attempts
to import 'gobject', if 'gi.repository' has been used.
Since nose tries to load both, and newer pygobject3 changes the
failure mode for that case, all the 'ga' using tests fail.
The 'excludes=.*ga_impls.*' added here is documented as "Don’t run tests that match
regular expression". We don't actually have any tests named that way,
but nose ends up loading module paths that could include that, and
this stops that.
--ignore-files or the '__test__ = None' seem like they should work
for this case, but seem to have no …

Fix nose failures caused by nose loading gtk2/gtk3

---

src/daemons/rhsmcertd-worker.py

For rhsmcertd-worker.py in particular, since it runs
as a child of rhsmcertd, which has very restrictive
selinux policy by default.
Because of either PYTHONPATH env var or system/site/user
changes to the pythonpath, rhsmcertd-worker.py could
end up attempting to find and open modules in path
that the selinux policy prevents it from accessing.
If the path ended up including '.', it would attempt
to read from cwd and cause denials.
So specify the '-E' and '-s' args to /usr/bin/python
-E     : ignore PYTHON* environment variables (such as PYTHONPATH)
-s     : don't add user site directory to sys.path; also
PYTHONNOUSERSITE

1136163: Ignore pythonpath to avoid selinux AVCs

---

src/rct/printing.py

rct cat-cert was sorting the products shown by the
product id, but it was comparing them as strings.

Cast product.id to int for sort in cat-cert

---

subscription-manager.spec

- Changed one of the required packages for
subscription-manager-initial-setup-addon from initial-setup to
initial-setup-gui

Updated initial-setup-addon package requirement to initial-setup-gui

---

subscription-manager.spec

Add a Requires to to subscription-manager-plugin-container
on the same version-release of subscription-manager package.

1165771: -plugin-container requires subman

---

src/daemons/rhsm_d.py

ga_GLib.idle_add only exists on RHEL7 where
ga.GLib -> gi.repository.GLib.
On RHEL6, ga_GLib doesn't have idle_add, but
ga_Gobject does. So update to use that. RHEL 7
also has ga_Gobject.idle_add, so this works for
both.

Use idle_add from ga_Object for 6.x

---

bin/subscription-manager-gui
src/subscription_manager/ga_impls/ga_gtk2/GObject.py
src/subscription_manager/ga_impls/ga_gtk2/Gtk.py
src/subscription_manager/ga_impls/ga_gtk2/__init__.py
src/subscription_manager/ga_impls/ga_gtk2/gtk_compat.py
src/subscription_manager/ga_impls/ga_gtk3.py
src/subscription_manager/ga_loader.py

ga_gtk2/GObject.py was importing gtk to wrap
TreeRowReference, so code that imported just
ga.GObject were also pulling in gtk, which
fails if there is no $DISPLAY set.
Likewise, the common threads_init was moved to
gtk_compat.threads_init.
Glade file location helpers were also moved to
gtk_compat.

Move gtk_compat features to sub ga module.

---

src/subscription_manager/async.py
src/subscription_manager/ga_impls/ga_gtk2/__init__.py
src/subscription_manager/ga_impls/ga_gtk3.py
src/subscription_manager/gui/data/glade/repositories.glade
src/subscription_manager/gui/data/ui/repositories.ui
src/subscription_manager/gui/progress.py
src/subscription_manager/gui/reposgui.py
src/subscription_manager/gui/storage.py
test/test_repogui.py

Instead of immediately sending repo override changes to
the server on each checkbox click, queue them up and send
them when the 'Apply' button is clicked.
All communication with the server while saving/loading
data, is done async, and the user will be presented with
a progess window until the request completes.
Closing the dialog will detect if there were any local
changes made, and prompt the user to save changes before
closing.
The Remove All Overrides button will only be enabled if
there are currently overrides on the server for the
selected repository.
This commit also addresses varions layout/display issues
for GTK3.
**Testing Notes**
This change affects the dialog in both RHEL6 and RHEL7. When testing, please check both.

1161157,1155954: Improve performance of Repository Dialog

---

src/subscription_manager/gui/widgets.py

The behaviour of widget.get_names() isn't neccasarily
the same name used for the widget/object 'id' in the
ui builder xml. And with Gtk.Builder, it usually
is not.
The proxy dialog init would try to set the state of the
dialog based on the widget names, but would fail because
of above mentioned change. So the state of the buttons
is incorrect.
To fix it, widgets.SubManBaseWidget's pull_widget() method
was changed to set the expected widget name, as well as
to elevate the widget name to the objects attributes.

1243260: Make proxy config dialog work.

---

src/subscription_manager/gui/preferences.py

The combobox widgets for release version and service level
in the preferences dialog were showing up empty. They were
missing a CellRendererText() added to the entries, and were
not being rendered.

1245557: Fix release and service level preferences

---

src/subscription_manager/gui/data/ui/installed.ui
src/subscription_manager/gui/data/ui/subdetails.ui

Old gtk/glade used a string value for hadjustment/vadjustment attributes
for widgets, but newer versions want a GtkAdjustment object name
instead, so update these ui definations to do that.
This eliminates warnings like:
(subscription-manager-gui:28289): Gtk-WARNING **: No object called: 0 0
396 39.600000000000001 356.40000000000003 396

1248664: Fix GtkAdjustment related warnings

---

src/subscription_manager/ga_impls/ga_gtk2/Gtk.py
src/subscription_manager/gui/widgets.py

DatePicker is a subclass of HBox, so self.get_parent()
doesn't make sense, so clicking on the date picker would
throw an error:
TypeError: argument parent: Expected Gtk.Window, but got
gi.overrides.Gtk.Box

1248821: All subs date picker was failing.

---

src/subscription_manager/gui/data/ui/filters.ui

The window type hint for the filter dialog was previously
'menu', which causes the window to appear undecorated
and unfocussed. This changes it to 'dialog' to correct
that.

1248729: All subs filter dialog was not focused.

---

src/subscription_manager/async.py
src/subscription_manager/gui/networkConfig.py
src/subscription_manager/gui/utils.py

This makes the logging format '%(threadName)s' much more
useful, instead of 'Thread-1', etc.

Specify a thread name for any threads we start.

---

src/subscription_manager/gui/allsubs.py
src/subscription_manager/gui/contract_selection.py
src/subscription_manager/gui/mysubstab.py
src/subscription_manager/gui/networkConfig.py
src/subscription_manager/gui/progress.py
src/subscription_manager/gui/reposgui.py

Gtk.Widget.is_toplevel() is only available for
gtk 2.22 and higher, so RHEL6 versions with older
gtk would throw an attribute error on is_toplevel().
Remove use of is_toplevel(), since the places it
was used also have a reference to the parent window
so we use that instead.

Remove use of Widget.is_toplevel()

---

subscription-manager.spec

If %{rhel} wasn't defined, builds failed.
Remove check for 7.2+ and default to building
initial-setup addons on RHEL7.

Fix spec file build errors

---

src/subscription_manager/gui/managergui.py

The timeout that called the file monitor objects was
not returning True, so it would run once, and then be
removed from the event loop sources. Now it returns
True forever.
This fixes issues where changes to certificate directories
(/etc/pki/entitlement/ for ex) were not being noticed by the
gui. This included changes by running the cli command at the
same time, or using the "Import cert" dialog to import an
entitlement certificate.

1240553: Fix detection of cert dir changes

---

subscription-manager.spec

ostree isn't provided in RHEL7, so the dep can't be
resolved, and it's a base dep on atomic. This allows
for testing/dev on non-atomic RHEL7.

1185958: Remove ostree plugins req on ostree

---

src/initial-setup/com_redhat_subscription_manager/ks/rhsm_ks.py

This module doesn't really do anything yet, but at least now
it does nothing correctly. Previous the setup() method
of RHSMAddonData was calling super().__init__ mistakenly,
but also the method signature changed when initial-setup was
rebased.

1253275: Fix initial-setup ks mode

---

src/subscription_manager/gui/widgets.py

The quantity column in the contract selection dialog
uses a spin button cell renderer to adjust quantity.
Gtk3 versions expand horizontal instead of vertical,
causing the column contents to be hidden by the
spin button.
Set a max/min width on the quantity column so it
is a fixed width large enough for the spin button. The
column is not set to expand to avoid it using all
extra space if the window is widened horizontally.

1246429: Stop spinbutton from blocking quantity

---

src/subscription_manager/gui/data/glade/repositories.glade

The 'swapped=no' on signal handlers in glade file confuses
some old versions of libglade. So ran 'make fix-glade' to
fix them.

Fix 'make gladelint' errors in repositories.glade

---

src/subscription_manager/managercli.py

def username(self) is called in more places than we need the "Registering to" message, so moved the message so that its displayed only when a user is registering.
fixes [1254353 , 1254349 , 1254578, 1256960](https://bugzilla.redhat.com/buglist.cgi?quicksearch=1256960%2C%201254578%2C%201254353%2C1254349%20&list_id=3760820)

1254349: move Resgistering to message

---

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py

Set help file name for the Subscription Manager spoke so that the Anaconda build in help system can show help content for it.

Set help file name for the Subscription Manager spoke

---

etc-conf/subscription-manager.completion.sh

There was no help options on the first tab when using bash_completion

Enabled help options on first tab

---

Makefile
src/subscription_manager/gui/widgets.py

Makefile 'make gettext' target also now created a dir
of symlinks to the data/ui/*.ui files with the link names
ending with .glade so that intltool recognizes them as
glade files and extracts strings from them.

1257460: Set text domain on Gtk.Builder widgets

---

src/rhsm_debug/debug_commands.py

And disconnect them from anything aside from a log
message that they no longer do anything. This avoids
breaking any scripts that specify --subscriptions, and
doesn't change any behaviour against most server versions.

1246680: Hide rhsm-debug --subscriptions options

---

test/stubs.py
test/test_registrationgui.py

Instead of expecting the state of the notebook widget
to be updated by the time the 'register-error' handler
fires, instead wait for a notify signal from the notebooks
'page' property to indicate we successfully changes pages
(or that we didn't change pages in this case for
test_registergui.py)

Use Notebook 'page' prop notify signal for tests

---

src/subscription_manager/managercli.py
src/subscription_manager/repolib.py

The configuration.get_int handles blanks where int() does not.

1251853: Manage repos config entry needs to allow blank value

---

src/subscription_manager/plugin/ostree/config.py
src/subscription_manager/plugin/ostree/model.py
test/stubs.py
test/test_ostree_content_plugin.py

This extract the proxy port, hostname, username, password
from rhsm.conf to the ostree repo's 'proxy' setting.

1168268: Add rhsm.conf proxy info to ostree repo

---

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.ui
src/subscription_manager/gui/data/ui/activation_key.ui
src/subscription_manager/gui/data/ui/allsubs.ui
src/subscription_manager/gui/data/ui/choose_server.ui
src/subscription_manager/gui/data/ui/confirmsubs.ui
src/subscription_manager/gui/data/ui/contract_selection.ui
src/subscription_manager/gui/data/ui/credentials.ui
src/subscription_manager/gui/data/ui/environment.ui
src/subscription_manager/gui/data/ui/mainwindow.ui
src/subscription_manager/gui/data/ui/register_dialog.ui
src/subscription_manager/gui/data/ui/registration.ui
src/subscription_manager/gui/data/ui/registration_info.ui

For wide windows or dialogs, most widgets were set to
use a align mode of 'fill'. This causes things like entry
boxes to expand to the entire width of the parent. Combined
with widget package that was causing the RegisterWidget to
expand to cover the widgets register screen, many widgets
fill the entire width of the screen.
Make Entry widgets set a min and max width, but allow them
to expand and fill up to that max width.
Tweak most of the Labels to auto wrap. Enabling end ellipsing
on most labels, but also give them plenty of room to expand with
by setting the suggest number of lines before ellipsing. Labels
also get set to expand. That combo removes the behavior of
labels that require a ton of horizontal space, forcing the
RegisterWidget to be very wide (and causing entries and the
like …

884288: Make register widgets handle resizing.

---

src/subscription_manager/gui/data/ui/allsubs.ui

Revert to the previous version. The reverted
version did not resize properly and the
GtkAdjustment use isn't a problem in this
dialog.

1267287: Fix allsubs tab ui regression

---

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py
src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.ui
src/subscription_manager/gui/data/glade/register_dialog.glade
src/subscription_manager/gui/data/ui/register_dialog.ui
src/subscription_manager/gui/registergui.py
test/test_registrationgui.py

Replace 'cancel' with stock 'back' button.
register_dialog.ui was using the stock 'cancel', but
rhsm_gui.ui was not. But change both to stock 'back'
Add a RegisterWidget.applied_screen_history that
tracks screens shown to the user, so that back
and error handling can do the right thing. This
uses UniqueList to keep only the last time a
screen was visited.
Make back button blocked/insens when in async
screen pre(). This avoid changing screens while
waiting for a thread to finish. It also blocks
the buttons until the screens are ready().
'back' now attempts to go back to the last gui
screen that was shown to the user.

1262075,1267179: Fix back/cancel nav

---

src/subscription_manager/gui/registergui.py

Replace 'back' usage of _last_screen() with
_pop_last_screen() that keeps better track of the
stack of visited screens.
_last_screen() only understands the last uniq screen
visited, so would prevent 'back' from allowing
user to go back more than one screen.

Allow 'back' to go back multiple times.

---

src/subscription_manager/gui/mysubstab.py

I'm a little *meh* about this fix, but given time constraints, I think it will have to suffice.  I don't like that when you unsubscribe an item say 4 rows down in the TreeView that the selection jumps back up to row 0 after the unsubscribe is finished.
I tried
```python
selection.store.remove(selection.tree_iter)
```
which moves the selection up one row, but something else is running shortly thereafter that moves the selection back to 0.

1266480: Refresh TreeView selection after subscriptions are removed.

---

src/subscription_manager/gui/utils.py

@alikins This seems to work well except for the fact that the message reads
```
Unable to register the system.
Network error, unable to connect to server. Please see /var/log/rhsm/rhsm.log for more information.
Please see /var/log/rhsm/rhsm.log for more information.
```
Should we just chop the "Please see" out of the SOCKET_MESSAGE or does that message get displayed independently?
On a more general note, the error reporting code seems really complicated and looks to have some redundancies between handle_gui_exception and a lot of the other ones.  Could we unify the reporting into one method that renders the error message?
```python
INFO = "INFO"
ERROR = "ERROR"  
def handle_gui_exception(e, msg, parent, format_msg=True, log_msg=None):
(message, level) = render_message(e, msg, format_msg, …
```

1266929: Fix bug with exception reporting in register dialog.

---

src/subscription_manager/gui/registergui.py

When using initial-setup to register a system, if the
'Manually attach subscriptions after registration' option
was selected in the credentials page, the gui would
start the select sla screen before starting the 'done'
process. So the done screen could be shown, then a
now paused progress bar, then eventually the results of
the select sla screens startup.
Fix is just to either finish, or start select sla, not
both.

1268028: Fix skipped auto attach in registergui

---

src/subscription_manager/managercli.py
src/subscription_manager/repolib.py
test/test_managercli.py
test/test_repolib.py

Move managercli.managed_repos_disabled to repolib.manage_repos_enabled()
Make the function handle potential ConfigParser errors, and make
it return a bool.
Update managercli and repolib to use it.
Add test cases to test_repolib.py

1251853: Fix errors if "manage_repos = " in cfg

---

src/subscription_manager/gui/managergui.py
src/subscription_manager/gui/registergui.py

I am a little uncertain about the `destroy` versus `hide` signal.  The Autobind dialog seems to `hide` itself upon successful completion although it seems to me like it should `destroy` itself.  Regardless, it can still be `destroy`ed if you right-click then close it while it's running.

1268102: Stop main window from opening duplicate dialogs.

---

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py
src/subscription_manager/gui/registergui.py

Implemented suggestions 2 (with barnaby's addendum) and 3 as quoted from jsefler below
>Here are my suggestions...
>
>1. Move "The system has been registered with ID: %s " from beneath the spoke icon to the final >panel of the subscription-manager-initial-setup-addon workflow where you are currently displaying >"Registration with Red Hat Subscription Management is Done!"  I think this is more informative and >avoids seeing the word "Done" on the final screen in two places.
>
>2. Display a short message "This system is registered." beneath the spoke icon after registration is >done.  (Note: this string does not exist among the translated 1.15.X strings)
>
>3. Display a short message "This system is currently not registered." or "System is not registered." >beneath the spoke icon before …

1268088 trim spoke status

---

src/subscription_manager/gui/data/ui/selectsla.ui
src/subscription_manager/gui/registergui.py

The box of Gtk.RadioButton widgets on SelectSLAScreen
causes an assortment of odd behavior.
Most notably, it sometimes obscures some of the available
options by having them in offscreen areas of a scrollwindow.
With default themes, it is not very obvious there is an option
to scroll and see other radio buttons.
The scrolled window was originally added to handle cases where
there is a large number of options, and a Gtk.Box of radio buttons
would cause all sorts of layout issues. Especially when the
register widgets window is a small fixed size (RHEL6 firstboot
for example).
To alleviate some of those issues, replace the box of radio
buttons with a Gtk.ComboBox.

1268095: Replace SLA radio buttons w/ combobox

---

src/subscription_manager/gui/managergui.py

There was a crash report being generated when the registeration dialog was completed after s-m-gui was started by clicking 'Register Now' on rhsm-icon. This was a result of the widget (that started the registeration process) being set to None. The fix is to check if the widget being handled is None.

1270204: Crash report no longer sent when widget is none

---

src/subscription_manager/gui/about.py

- Clicking the "Credits" button in the about dialog in subman GUI
now displays generic credits

1254460: Fixed the credits button in the about dialog in subman GUI

---

src/subscription_manager/cache.py
test/test_cache.py

The 'package_upload' yum plugin from katello-agent
will call packageprofilelib._do_update with
consumer_uuid=None, resulting in an invalid request
to the rhsm REST API, if the consumer system is
not registered to rhsm.
So if we get as far as CacheManagers update_check with
consumer_uuid=None, just log it and return. We can't
raise an exception in that case without causing yum
to show the exception message on stderr for what is
a valid configuration.
For 'package_upload', it doesn't check if the consumer
if registered and calls into ActionClient.profilelib._do_update,
which is past any checks for registration. This change
just prevents it from making a request to the rhsm REST
API like 'PUT /consumers/None/packages'.
Rhsm registered systems with a valid consumer_uuid will
continue to make …

1264964: Ignore uuid=None on package sync

---

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py
src/subscription_manager/gui/registergui.py

And reference it via RHSMSpoke's 'status' python property
that queries RegisterInfo's 'register-status' gobject property.
This makes RegisterInfo's 'register-status' the only source of
that string.
Remove RHSMSpokes 'notify::register-status' handler since
RHSMSpoke.status is only read when initial-setup needs to
(ie, when revisiting the hub)

Set register-status in RegisterInfo init.

---

src/subscription_manager/gui/data/glade/register_dialog.glade

It is not a splash screen. Not even the
most boring splash screen in the world.
So remove the bogus 'splashscreen' type hint.

Fix register_dialog window type hint.

---

src/subscription_manager/lock.py

It was grabbing the logger based on file name instead
of module name, so it would end up with the logger
named 'rhsm-app./usr/share/rhsm/subscription_manager/lock.py'
instead of 'rhsm-app.lock'

Fix the logger name lock.py requests.

---

src/subscription_manager/managercli.py

Reset cp_provider so we get new requests.Sessions
(both basic auth and client auth).
Before we would create a client cert uep at start up
of register --force, then unregister, then create a new
basic auth to register with, but cp.provider.get_consumer_auth_cp
would return the origin uep connection with the now invalid
consumer cert.
cp_provider.clean() unsets any state on cp_provider.

After unregister, call cp_provider.clean()

---

test/test_lock.py

It will often fail if a system is slow or overloaded or
it will require a long timeout which just slows down the
entire test suite.

Disable the blocking test in test_lock.py

---

man/subscription-manager.8

So it matches the rest of the sub command options
entries.

Make 'service-level' man page title all caps.

---

src/subscription_manager/ga_impls/ga_gtk2/GLib.py
src/subscription_manager/gui/managergui.py
src/subscription_manager/managercli.py

The server version check can be slow and is mainly just for debugging purposes
so there is little point in blocking while making the check.

976859: Run the server version check asynchronously

---

src/subscription_manager/managercli.py

- When a x509 error occurs during a CLI command, or the active consumer was deleted
on the server, subman now returns a non-zero error code and prints the message to
stderr rather than stdout

1262989: Changed the error code returned when the consumer has been deleted on the server

---

src/daemons/rhsmcertd-worker.py
src/subscription_manager/managercli.py

- The error messages that can occur in subman when a consumer is
deleted from the server before unregistering now include the
consumer's UUID in the error messages.
- Log messages related to this issue are no longer translated

1262989: Updated error message to include consumer UUID

---

src/subscription_manager/managercli.py
test/test_managercli.py

* adds the help message as suggested in the BZ:
```
$subscription-manager attach --help
Usage: subscription-manager attach [OPTIONS]
Attach a specified subscription to the registered system
Options:
-h, --help            show this help message and exit
--proxy=PROXY_URL     proxy URL in the form of proxy_hostname:proxy_port
--proxyuser=PROXY_USER
user for HTTP proxy with basic authentication
--proxypassword=PROXY_PASSWORD
password for HTTP proxy with basic authentication
--pool=POOL           the ID of the pool to attach (can be specified more
than once)
--quantity=QUANTITY   number of subscriptions to attach
--auto                Automatically attach compatible subscriptions to this
system. This is the default action.
--servicelevel=SERVICE_LEVEL
Automatically attach only subscriptions …
```

1265904: requires auto help message

---

src/subscription_manager/logutil.py

This reverts commit 17163bb84ec26f2bafbac1bbb9207a478567d001.
FileHandler breaks nosetests. Revert for the time being.

Revert "Remove logrotating in favor of logrotate daemon"

---

src/subscription_manager/managercli.py
test/stubs.py
test/test_managercli.py

Logs Restlib exceptions returned instead of adding them to the output.
Also checks for 'remove_by_pool_id' capability during validation if the --pool option is specified.

1285004: Adds check for access to the required manager capability

---

Makefile

Something was causing these files to be installed with mode 755 where they previously were installed with mode 644. This simply specifies the intended mode with the install command.

Install docs with mode 644

---

src/daemons/rhsm_d.py
src/subscription_manager/cert_sorter.py

Stop "Register System For Support and Updates" message
when system has imported entitlements. This is the indicator of
an intentional offline system.

1263037: Change RHSM Icon reporting of unregistered system

---

src/subscription_manager/gui/firstboot/rhsm_login.py

The bug was caused by a missing 'backend' attribute. Making the backend variable here an attribute of ModuleClass fixes it.

1292013: Retain reference to backend for use in proxy config

---

src/subscription_manager/cert_sorter.py

This fixes the flake8 error that jenkins is presently upset about.

Removes the additional blank line before the StackingGroupSorter class.

---

src/subscription_manager/repolib.py

This is a simple fix to restore the behavior of subscription-manager described in a different bz (https://bugzilla.redhat.com/show_bug.cgi?id=1176219)

1298327: Handles exception in repolib

---

subscription-manager.spec

Testing this will require a recent build of RHEL 6.8. I checked it against the nightly one.

1282961: Update yum version to current RHEL 6.8 one

---

src/daemons/rhsm_d.py
src/rhsm_icon/rhsm_icon.c

This changes rhsm_icon.c to use the entitlement
status returned from it's call to 'check_status'
dbus method for the intial_check and daily checks.
Previously, the status returned from 'check_status'
was ignored, instead being triggered by the
'entitlement_status_changed' dbus signal. However,
rhsm_d.py was prone to emitting this too often
because of multiple bugs that are now fixed.
See commit 35aa7e7eba82f601504bb64ab56aebe6dee4e786.
Since rhsm_icons display_icon knows how to handle
a RHSM_VALID state (ie, don't do anything), we can
pass any entitlement status to it, instead of waiting
for a entitlement_status_changed signal.
The 'check_status' dbus method now only emits a
entitlement_status_changed signal if the current status
is different than the last know status.

1046132: rhsm_icon uses status from check_status

---

scripts/test_hwprobe.sh
src/subscription_manager/hwprobe.py

For ppc64 guests running under KVM, the virt.uuid
is available from '/proc/device-tree/vm,uuid' so
collect it from there.
Also update scripts/test_hwprobe.sh to DWIM.

1300805: Add support for ppc64 virt.uuid

---

src/subscription_manager/cpuinfo.py
src/subscription_manager/hwprobe.py
test/data/cpuinfo/ppc64-power8-160cpu-powernv
test/data/cpuinfo/ppc64-power8-16cpu-kvm
test/data/cpuinfo/ppc64-power8-powernv
test/data/cpuinfo/ppc64le-power8-16cpu-lpar
test/test_cpuinfo.py

This includes the 'platform' and 'machine' fields,
which indicate baremetal/virt/lpar.
Make *CpuInfo classes subclass of BaseCpuInfo
Move split_by_processor out of class to module
scope and change to split_kv_list_by_field()
Add ppc64le tests

1300816: Add proc_cpuinfo facts for ppc64/le

---

src/subscription_manager/gui/data/glade/selectsla.glade

Another one liner fix for a regression.
BZ here: https://bugzilla.redhat.com/show_bug.cgi?id=1300259

1300259: Select service level label no longer overlaps dropdown box

---

src/subscription_manager/cpuinfo.py

This PR removes two lines of debug print statements that were added by 80eb39098c6f7721f747415762cb3ebd381840c0

Removes debug print statments from cpuinfo

---

bin/subscription-manager-gui

It would be nice to log the exception, but adding the `log.exception(e)` line results in the complaint `No handlers could be found for logger "rhsm-app.subscription-manager-gui"`.  I presume this is because `logutil.init_logger()` hasn't been called yet.  @alikins Can you confirm?

1290885: Display formatted error if no DISPLAY exists.

---

src/subscription_manager/hwprobe.py
test/test_hw.py

f8416137a3b426aa54608116e005df7273abfada changed virt.uuid
fact collection so that it starts with a default value of
'Unknown' where previously the virt.uuid fact wouldn't
be created (no 'hw.allhw['virt.uuid'] entry). That
was reasonable and expected so change back to that
behavior.

1308732: Leave hw fact virt.uuid unset if unknown

---

src/subscription_manager/gui/firstboot/rhsm_login.py

The issue here was that we had not connected a handler to changes in the 'screen-ready' property of RegisterWidget (or in this case FirstbootWidget). This fix sets navigation sensitivity to the value of the 'ready' property of register_widget.current_screen.

1308523: Navigation buttons sensitivity matches the current_screen.ready

---

src/subscription_manager/gui/firstboot/rhsm_login.py
src/subscription_manager/gui/registergui.py

The wrong args were getting passed along with the register-error signal. As it turns out we need not emit the register-error signal in the places updated by this PR at all. Instead we can have the desired effect simply by emitting a register-message signal and fixing up rhsm_login to handle those signals (in this case we just display a message dialog box with the appropriate message type).

1311935: Emit register-message for user errors

---

etc-conf/logging.conf

Leave the console handler (SubmanDebugHandler) untouched since we want debug logging when it is enabled.

1266935: Turn sub-man logging to INFO level.

---

src/subscription_manager/gui/widgets.py

Ends up in odd state where the previous selection is not reachable.
Now the proper window with lack of connection information is
displayed.
To test you need to run 'sudo ifdown [eth0 or the like]' before you attempt an unbind.

1315591: Catches exception and allows process to continue

---

src/subscription_manager/gui/mysubstab.py

When unregistering with the gui, if there are more
than one subscriptions attached, there is a traceback
on the console.
The on_selection callback is getting called with a
selection that points to a serial/cert that isn't
valid by the time the callback runs. So the the
cert lookup returns None, and the rest of the code
didn't expect that. So just check for that and return.

1268094: Avoid traceback on unreg with >1 sub

---

src/rhsmlib/dbus/private/register_service.py

Since a private connection is not a "bus", we have to treat
it slightly differently. In particular there are no names,
no discovery and so on.

dbus: Fix RegisterService registered on private connection

---

build_ext/utils.py

This code was originally added to augment the built-in Python XML parser
so that it would report line numbers.  Eventually, I determined that the
built-in parser wouldn't cut it and switched to LXML but forgot to
remove this code.  This snippet breaks yum because yum is explicitly
attempting to import the C implementation.

Remove sys.path shenanigans that break yum imports.

---

test/fixture.py

The Python documentation explicitly states that running getlocale
against the LC_ALL category is unsupported.

Read current locale from LC_CTYPE instead of LC_ALL.

---

Makefile

Also do not recompile when `make install` is called.  This recompilation
creates a problem because only the `make` command receives the proper
CFLAGS and LDFLAGS settings during an RPM build.  `make install` leaves
those values unset and creates binaries that are not hardened.

Set default target as first in Makefile.

---

build_ext/lint.py
src/rhsm_debug/debug_commands.py
src/subscription_manager/managercli.py
src/subscription_manager/migrate/migrate.py

Good: _("Hello %s") % name
Bad: _("Hello %s" % name)
The "bad" example doesn't work correctly because the key gettext tries
to lookup isn't constant.  The key varies based on the value of name.

Flag interior string formatting for the gettext method

---

src/subscription_manager/gui/registergui.py
test/test_registrationgui.py

Previously the decision was made based on individual products.
Unmapped guest entitlements make the system status partial even though
all products are covered.

1335371: Allow auto-attach in GUI when system status is partial

---

src/subscription_manager/managerlib.py

Dep injection was set to return an instance of Identity instead of the required ConsumerIdentity object.
This undoes the change to managerlib from the following commit:
https://github.com/candlepin/subscription-manager/commit/18310e65308fe562b04a4baddeb12bd50078460f

1353662: Explicitly use ConsumerIdentity keypath and certpath methods

---

src/subscription_manager/gui/managergui.py

Reports an error on the command line and log and then exits.

1327179: Check proxy configuration at GUI startup

---

build_ext/PKG-INFO
build_ext/entry_points.txt
build_ext/lint.py
setup.py
test-requirements.txt

Flake8 3.x changed the way it loads plugins.  Before we were
piggy-backing on PEP8's plugin loading functionality, but that doesn't
work in the 3.x world.  This patch loads our plugins as a "virtual"
Python egg with an entry point defined for "flake8.extensions."

Fix breakage caused by API changes in Flake8 3.x

---

src/subscription_manager/ga_loader.py
src/subscription_manager/managercli.py

- When the refresh command is issued on the CLI, subman will request
entitlement certificate regeneration (lazily) for the active consumer

1360909: The refresh command now requests entitlement cert regeneration

---

src/initial-setup/com_redhat_subscription_manager/ks/rhsm_ks.py

``setup()`` and ``execute()`` methods now have ``payload`` class accessible for addons.
These methods were changed in *anaconda-21.48.22.67* for RHEL-7 and *anaconda-25.9* for Rawhide (for the next Fedora 25).
Also removing the ``AddonData.setup()``. The parent's ``setup()`` method should not be called. It's placeholder for overriding only.
*Resolves: rhbz#1362138*
Reported-by: Michal Kovarik ``<mkovarik@redhat.com>``

Change method signature for Anaconda addon (#1362138)

---

src/subscription_manager/managercli.py

- Service unavailable errors will no longer raise an exception
whilst running the refresh command

1366301: Entitlement regeneration failure no longer aborts refresh

---

src/subscription_manager/managercli.py
test/test_managercli.py

Reverts candlepin/subscription-manager#1470
(needs a squash, my bad)

Revert "1331739: Validate repo-override --remove non-empty"

---

src/subscription_manager/managercli.py
test/test_managercli.py

Same as #1470, except squashed.

1331739: Validate repo-override --remove non-empty [squashed]

---

bin/subscription-manager-gui
src/subscription_manager/gui/managergui.py

Confirmed on RHEL 7.2, RHEL 6.8 and Fedora 23.

Account for keyboard interrupt

---

Makefile
etc-conf/logging.conf
subscription-manager.spec

On upgrade of subman from a version older than (7218097e03b9255e74c41e13772698fc52f92ec6)
to any version newer than or equal to the aforementioned hash ^, an error message regarding failure to find section named 'formatters' is displayed.
The reason for this - and consequently for the fix itself - is during upgrade old subscription-manager plugins are run which look for the logging.conf file that was previously erased from the spec file and Makefile. This would cause a deletion of this file on the filesystem of the upgrading host. When the old plugin attempted to read this file, and found it missing, it fails and prints the exeception to stdout (which is what we see in the referenced bz 1368362).
The fix is to leave the now defunct logging.conf file (as well as a nice comment telling …

1368362: Do not display logging config error on upgrade

---

src/subscription_manager/gui/utils.py
test/test_gui_utils.py

When candlepin returns an error message that includes characters often found in markup (like '<>' for example) our gui error and info dialogs fail as GTK tries to parse those items as markup. These small changes ensure we are escaping our info and error messages properly to avoid displaying empty dialog boxes.

1367657: Properly escape gui error/info messages

---

etc-conf/rhn-migrate-classic-to-rhsm.completion.sh
src/subscription_manager/migrate/migrate.py
test/test_migration.py

Note that once `--remove-rhn-packages` is used, the script fails to
function as it depends on up2date_client provided by rhn-client-tools.
Aside from general feedback, I'm also looking for feedback specifically on the package list in `LEGACY_PACKAGES` and the legacy service list in `LEGACY_DAEMONS`: are they exhaustive? Any problems with handling any of those as implemented?

1185914: migrate - handle legacy services/packages

---

src/subscription_manager/repolib.py

While in a container we should not be checking for a releaseVer set for the host consumer. Overrides such as that are meant to be set for the host consumer alone and not bleed over into the container.

1366799: Do not check for a releaseVer override when in container

---

src/rhsm_debug/debug_commands.py
src/subscription_manager/managercli.py

Interpret `~` and `~user` as most other programs do. Additionally, make
the import command certificate not found message less confusing.

1367509: fix cert not found message, expand tilde

---

src/subscription_manager/gui/registergui.py

When the user attempted to register with an activation key and
got a failure they could back out to the first screen. If they
then proceeded without an activation key the remnant of the
first attempt would confuse the logic.

1376014: Clear activation key list when checkbox unchecked

---

src/subscription_manager/gui/registergui.py
src/subscription_manager/managercli.py
src/subscription_manager/utils.py

Improves upon changes in 7ce6801fc1cc38edcdeb75dfb5f0d1f8a6398c68
- make is_valid_server_info handle proxy settings
- detect 407 (proxy auth) http errors in is_valid_server_info
- treat exceptions during test_proxy_connection as failures

1176219: Error out if bad proxy settings detected

---

src/subscription_manager/gui/widgets.py

If you don't set the parameters on each spinner, it will bleed over
from another one.

1366523: Ensure that each quantity spinner has proper settings

---

src/subscription_manager/gui/registergui.py

Fix for a bug I introduced w/ #1486.

1176219: Treat port as integer for GUI conn test

---

subscription-manager.spec

Also removed the rhsmcertd enable command. Proper way
is for the release team to add it to the preset file.
BZ created for that to happen.

1163968: Use macro for service restart

---

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py
src/subscription_manager/gui/registergui.py

In registergui, we now keep track of the threads that are spawned for
AsyncBackend, and AsyncBackend provides a method: block_until_complete
which blocks until all tracked threads are done.
To address initial-setup being closed before async actions are complete,
we now call the block_until_complete method in execute, meaning that
waiting for the threads to complete is part of the normal finish.
Additionally, we now notify the hub directly of any changes to the
registration status, so that if a user leaves the spoke early, the
status will be updated asynchronously.

1259768: initial-setup: notify and block for async

---

src/rct/manifest_commands.py

Adds a blank line to keep the output consistent with invocation without
the --no-content option.

1369577: Fix rct cat-manifest --no-content format

---

src/subscription_manager/managercli.py

This affects two CLI commands:
- register with --autoattach which now will report server exceptions
on stdout and will raise other exceptions during auto-attach
- attach with --auto will now raise all exceptions during auto-attach
In the testing I did of the change, the behavior of subscription-manager
register command is different in *output only*, but attach exits early
if auto-attach fails (entitlement certs aren't updated and certification
is *not* re-checked), which I think is valid behavior.

1382355: Don't swallow CLI autoattach exceptions

---

src/subscription_manager/gui/managergui.py

Because we use the same registration dialog for both the menu item and
the register button on the install tab, we need to account for the menu
item in the destroy handler. Prior to this change, the handler
unconditionally (re)-enabled whatever the widget that triggered the
dialog was, which is wrong for the register menu item.

1382897: Don't always reenable register menu item

---

src/plugins/subscription-manager.py

I was playing about with a few things and noticed that when I broke my test Katello server my clients were complaining about real RHSM.  Not many people find themselves in that situation, but this probably makes some sense in Fedora land.

debrand so my Katello server errors don't point to real RHSM

---

src/subscription_manager/logutil.py
test/test_logutil.py

In 2.7, `setLevel` seems to handle this for us, but in 2.6, the level is
blindly set, which leads to the logger misbehaving (since strings are
effectively a higher value than the highest logging level, CRITICAL, a
number, we saw no output).

1389559: Parse log levels properly from config

---

src/subscription_manager/managercli.py
src/subscription_manager/migrate/migrate.py

Related to [python issue 1927](http://bugs.python.org/issue1927),
workaround is to import readline. When readline is imported, it causes
raw_input to always use stdout for the prompt.
Since adding readline causes additional behaviors, I also added
`readline.clear_history` after every raw_input() to reduce funtionality
change (we can always remove later).

1390549: Force input prompts to use stdout

---

src/subscription_manager/migrate/migrate.py

For both the rhn-migrate-classic-to-rhsm and sat5to6 tools, disallow
states where the system should continue to use rhn packages (i.e. states
where the system is still registered).
For RHN/RHSM, the only state is keep, where migration is performed, but
no changes are made to the legacy registration.
For the Satellite case, this is either unentitle, where the system is
still registered to the Satellite instance, and keep, where the system
is registered and consuming.

1390258: Validate --remove-rhn-packages conflicting options

---

man/rhn-migrate-classic-to-rhsm.8
man/sat5to6.8

For both rhn-migrate-classic-to-rhsm and sat5to6.

1390712: Add --remove-rhn-packages to man pages

---

src/rct/manifest_commands.py

Expands the rct command to show which products are provided for subscription types that have derived products
~~~
Subscription:
Name: Red Hat Enterprise Linux for Virtual Datacenters, Premium
Quantity: 19
Created: 2016-07-14T16:44:20.000+0000
Start Date: 2015-02-28T05:00:00.000+0000
End Date: 2018-02-28T04:59:59.000+0000
Service Level: Premium
Service Type: L1-L3
Architectures: 
SKU: RH00001F3
Contract: [REDACTED]
Order: [REDACTED]
Account: [REDACTED]
Virt Limit: unlimited
Requires Virt-who: True
Entitlement File: export/entitlements/8a85f98b55e3a2d30155ea4b70b16c4e.json
Certificate File: export/entitlement_certificates/5189219367084232490.pem
Certificate Version: 3.2
Provided Products:
Derived Products:
69: Red Hat Enterprise Linux Server
70: Red Hat Enterprise Linux Server - Extended …

1388207: show Derived Provided Products for products that have them

---

src/subscription_manager/gui/installedtab.py
src/subscription_manager/gui/managergui.py
src/subscription_manager/gui/mysubstab.py
src/subscription_manager/gui/registergui.py
test/test_managergui.py

Fixed by moving the blocking calls to candlepin to separate threads. One
small downside to this is that more GUI updates happen asynchronously,
and thus this _might_ be harder to test/verify. We can possibly fix that
without reverting this fix by having the registergui hang around a
little longer if necessary.
This is by no means comprehensive for fixing usage of HTTP calls on the
main thread in subscription-manager-gui...

1261215: Fix frozen progress bars

---

src/subscription_manager/gui/managergui.py

This prevents weird behavior, like having gedit show raw HTML. Instead,
we show an error with the URL, so that the user can do something useful
with it.
The browser detection has the potential to be outdated if a new browser
is released, but as long as the user has at least one of the coded
browsers present, it should respect their default browser, and
otherwise, they can copy the URL from the error dialog.

1360427: Show error if browser is not detected

---

src/subscription_manager/managercli.py

There is a short-circuit to return True (as if the proxy
connection test had passed) if there is no proxy configuration
from either the cli or the rhsm config file.
This fix ensures that this short-circuit check for the absence of
config info.

1403387: Fix proxy conn test short-circuit

---

bin/subscription-manager

Otherwise since #1513 (fix for BZ#1390549), with certain configurations,
`import readline` outputs extra characters.

1402009: Unset TERM inside subscription-manager

---

src/subscription_manager/hwprobe.py

`socket.getfqdn()` and `hostname -f` give different results when ipv4
and ipv6 dns entries differ. `hostname -f` appears to prefer ipv4 while
`socket.getfqdn()` prefers ipv6.
By changing to `hostname -f`, we can at least stay consistent with
puppet fact collection (on my machine, `fqdn.rb` uses `hostname -f` at
this time at least).

1401394: Collect fqdn via `hostname -f`

---

subscription-manager.spec

Fixes issue revealed doing build for Fedora 25:
```
+ make -f Makefile VERSION=1.18.6-1.fc26 'CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic' 'LDFLAGS=-Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld' OS_DIST=.fc26 GTK_VERSION=3
cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld `pkg-config --cflags --libs glib-2.0` src/daemons/rhsmcertd.c -o bin/rhsmcertd
cc -O2 -g -pipe …
```

Add missing Requires and BuildRequires needed by F25.

---

Makefile
rpmlint.config
src/subscription_manager/repolib.py
src/zypper/services/subscription-manager
subscription-manager.spec

Testing
-------
- On any machine, with this version of subman installed, create `/etc/rhsm/zypper.repos.d`.
- Observe that when repos update, it adds a zypper variant of `redhat.repo`.
- Observe that `src/zypper/services/subscription-manager` prints the above zypper repo on stdout.
- To see full functionality, can build, install, register on an opensuse machine, and observe that subman-repos are added (ex. `zypper lr`).

Add zypper repo logic, service plugin

---

etc-conf/rhsmcertd.init.d

`/etc/rc.d/init.d/functions` does not exist on this configuration. We
are only using it to provide `status`, so I implemented a fallback which
uses idiomatic SUSE implementation.
Testing
-------
- On a SLES11 machine with this version installed, see that `service rhsmcertd status` works (vs. not working without the change)

Fix rhsmcertd status command on SLES11

---

Makefile

When you run `make install` and PYTHON_VER is not set, then install process will be terminated with error.

Fix "make install"

---

subscription-manager.spec

On install of subman gui, there are icons installed into the
hicolor theme. From what I've seen it seems that gtk (at least
the version of gtk in RHEL 6 at the time of writing this) will do
the following (with regards to retriving a given named icon):
1) Check if the folder /usr/share/icons/THEME_NAME has a cache
2) If there is a cache and it is valid, look for the named icon
in the cache ONLY. (Meaning if the named icon is not in the
cache, return the default icon).
3) If the cache is invalid or nonexistant, look for the icon by
navigating through the filesystem (Descend into subdirs of
/usr/share/icon/THEME_NAME to find the right icon).
In the bz this commit is meant to fix it seems that something is
causing the cache file to exist and be valid, but to not include
the …

1421930: Force update of icon cache on install of subman gui

---

src/subscription_manager/managercli.py
test/stubs.py
test/test_managercli.py

They're not associated to subscriptions as other entitlement certs are,
so we won't show them.

1425438: Hide content access certs from list cmd

---

python-rhsm/src/rhsm/m2cryptohttp.py
python-rhsm/test/unit/connection-tests.py

Looks like this happens because the httplib code that handles
socket.error expects socket.error to be in a certain state. I'm guessing
this occurs when the socket.error raised is initialized with a string,
rather than a code and string.
Anyways, this will handle the case specially by having the m2crypto
wrapper detect IndexError explicitly, and raise a socket.error. Even
though there's a risk that the IndexError is raised internally for some
other reason, it seems harmless to simply map any IndexError encountered
in an m2crypto request to a socket.error.

1423443: Handle IndexError during m2crypto request

---

src/subscription_manager/managerlib.py
src/subscription_manager/repolib.py

Both issues are arguably valid, but errors are handled
elsewhere in the code:
- `repolib.py`: `is_set` checks for `None` explicitly.
- `managerlib.py`: `verify_valid_entitlement` checks for `None`.

Address code paths with Coverity FORWARD_NULL

---

scripts/suse_build.sh
scripts/suse_functions.sh
scripts/suse_upload.sh

Two scripts: `scripts/suse_upload.sh` and `scripts/suse_build.sh`
The upload script prepares and uploads sources based on the currently
checked out HEAD, while build performs a local build with prepared
sources.
There is single mandatory arugment which is the name of the project to
work on. The project should be prepared in OBS ahead of running this
script. Any additional arguments are passed to the underlying `osc`
subcommand.
For the upload command, like `git`, omitting the commit message will
cause an editor to spawn, which is okay for interactive uses. For
automation, it is useful to specify the commit message with `-m`. See
`osc commit --help` for more details.
Example: `scripts/suse_upload.sh home:kahowell -m "Test commit"`
Example: `scripts/suse_build.sh home:kahowell …

Add scripts for working with OBS

---

playpen/noserc.ci
playpen/noserc.dev
playpen/noserc.zypper
setup.cfg
test/zypper_test/test_productidplugin.py
test/zypper_test/test_serviceplugin.py

They are not invoked by default. Using the nose attribute plugin, they
are marked as "zypper" tests, and I altered noserc files to ignore these
(except for noserc.zypper, which can be used to run these explicitly).

Add tests for zypper functionality

---

etc-conf/dbus/com.redhat.RHSM1.Facts.conf
etc-conf/dbus/com.redhat.RHSM1.conf

This patch allows users to actually call the DBus interfaces we expose.  Testing it is a bit annoying, but basically, you would install the old version and run
```
$ sudo dbus-send --system --print-reply --dest=com.redhat.RHSM1 '/com/redhat/RHSM1/Config' com.redhat.RHSM1.Config.GetAll
```
And get an error.
If you apply this patch, running the same command will return the current subscription-manager configuration.

1423013: Allow DBus calls to the com.redhat.RHSM1 interfaces

---

src/subscription_manager/managercli.py

At the time the catch-all was put into place, it seems it was being used
to handle the 410 Gone, but as of 5c48d059, it is handled in
`managerlib.unregister`, so the catch-all is now unnecessary, and
causing the register to proceed regardless of whether an unregister was
successful.
This change makes it so that `subscription-manager register --force`
behaves much more like `subscription manager unregister &&
subscription-manager register`, in that if there is a failure to
communicate with the server during the unregister, then the register
will not occur (we'll exit with an error code instead).
This prevents some cases where a consumer is registered twice (thus
effectively losing the original consumer, since it is deleted locally,
but remains server-side).

1429657: Remove catch-all on register --force

---

python-rhsm/src/rhsm/certificate2.py
src/subscription_manager/entcertlib.py
src/subscription_manager/model/__init__.py
src/subscription_manager/model/ent_cert.py
test/test_repolib.py

Had to move the constant CONTENT_ACCESS_CERT_TYPE to prevent a circular
dependency.
How to test: see the bug in bugzilla or the unit test changes.

1427069: Prioritize content from Basic entitlements

---

src/daemons/rhsmcertd-worker.py

The first thing that rhsmcertd-worker does is write a lock
(/var/run/rhsm/cert.pid), this means that if rhsmcertd-worker cannot
communicate with the server(ex. if rhsm.conf *does not* contain
necessary proxy info), but subscription-manager does (ex. proxy
configured in the command or environment), then the timeout must occur
before actions that require the lock can complete.
This patch fixes it by having rhsmcertd-worker pre-load the capabilities
thus, raising an exception if a connection cannot be established,
*before* acquiring the lock.

1433479: rhsmcertd - check connection before lock

---

src/subscription_manager/managercli.py

Necessary because all of the command classes are initialized in the flow
of subscription-manager commands, we only care about the correlation ID
from the one that actually runs.

1434860: Only log correlation ID for specified cmd

---

man/rct.8
src/rct/manifest_commands.py
test/manifestdata.py

With this PR, rct now shows the Content Access Mode of a manifest
~~~
rct cat-manifest /tmp/manifest.zip
+-------------------------------------------+
Manifest
+-------------------------------------------+
General:
Server: 
Server Version: 0.9.51.21-1
Date Created: 2017-03-20T17:02:55.850+0000
Creator: candlepin_admin
Consumer:
Name: ExampleCorp
UUID: c319a1d8-4b30-44cd-b2cf-2ccba4b9a8db
Content Access Mode: org_environment
Type: satellite
~~~
It is assumed that if the  `contentAccessMode` attribute in `consumer.json` is null, blank, or not present (as it would be on older manifests), that the Content Access Mode is `entitlement` unless it is explicitly set to `org_environment`

1424614: add support to rct to print contentAccessMode attribute

---

src/daemons/rhsmcertd-worker.py

So it turns out that `systemd stop` will send SIGTERM initially; without
an appropriate signal handler set in python, it causes the process to
immediately terminate. This meant that even though we had `finally` blocks
that would release the acquired lock (`/var/run/rhsm/cert.pid`), those
`finally` blocks weren't being executed... The lock logic was robust
enough that it didn't seem to matter (on an attempt to lock it checks
the pid validity), but left the `cert.pid` file around when it *should*
have been cleaned up.
Signal explanation here: http://stackoverflow.com/a/41840796

1431659: Let rhsmcertd-worker clean up on SIGTERM

---

src/subscription_manager/managercli.py
test/test_managercli.py

Previously we were relying on subsequent yum commands to regenerate
redhat.repo, but this is problematic because if the lock can't be
acquired, due to behavior introduced in f9715503 (bz 1224806), the repo
is simply left alone.
This change makes it so that the release command is responsible for
updating the repo. Furthermore, the release command will block if the
lock is held, until it can be acquired (with default timeout, this
should be no longer than 3 minutes).

1428435: Make release set/unset regenerate repos

---

etc-conf/rhsm.conf
etc-conf/rhsmcertd.completion.sh
man/rhsmcertd.8
src/daemons/rhsmcertd.c

The intervals for heal and cert are maintained but we do not start those timers until the completion of the initial delay. In this way if many systems are started all at the same time, they will perform their cert and heal checks at slightly different times. This was done in an attempt to reduce peak load as a result restarting a large number of systems simultaneously.
There is a new cli option ('-m', '--max-splay-minutes') as well as a new config value read from /etc/rhsm/rhsm.conf rhsmcertd section 'maxSplayMinutes'. By default the random offset generated for checkins is in the range [0, 600] seconds. Setting the new value (specified in minutes) will override this default to allow for more or less splay. Setting the max-splay-minutes to 0 will cause splay not to be added at all.
If the …

1435013: Add splay to all checks done by rhsmcertd

---

python-rhsm/src/rhsm/connection.py

This regression amounts to a typo.
Changes 'proxy_host' to 'proxy_hostname' in the problem area.

1438552: Allows releases to be listed through a proxy

---

man/rhsm.conf.5

Updates the man page for rhsm.conf to include the new maxSplayMinutes value used by rhsmcertd (that man page was already updated in the RFE PR #1577).

1440922: Add a description of maxSplayMinutes to the rhsm.conf man page

---

src/rhsmlib/facts/dmiinfo.py
src/rhsmlib/facts/firmware_info.py

There are two cases where we need to clear the warnings:
1. Non-blacklisted platforms, where this change restores old behavior of
logging the warnings if they are present.
2. Blacklisted platforms, where we don't even attempt to use dmidecode,
even though it is imported, where this change blindly clears the
warnings.

1438869: Clear dmidecode warnings

---

src/daemons/rhsmcertd.c

Requested by jselfer. Please include this in future builds as related to the RFE bug that originally implemented splay.

Update log message to be more clear about the splay time being used

---

src/rhsmlib/dbus/facts/base.py
src/rhsmlib/dbus/facts/constants.py
src/rhsmlib/facts/all.py
src/rhsmlib/facts/collector.py
src/rhsmlib/facts/custom.py
src/subscription_manager/facts.py
src/subscription_manager/gui/registergui.py
src/subscription_manager/managercli.py

Instead, we use the same underlying service, which is also exposed via
D-Bus.
This involved refactoring the aggregation into a separate service -
`AllFactsCollector`, and then using that to implement `AllFacts`.
I also moved the default configuration of the collectors into their
classes.
Also, I removed now outdated comments and logging that suggested we are
using D-Bus for facts collection.

1438561: Do not use D-Bus for facts collection

---

etc-conf/rhsm.conf
etc-conf/rhsmcertd.completion.sh
man/rhsm.conf.5
man/rhsmcertd.8
src/daemons/rhsmcertd.c
src/subscription_manager/gui/about.py

This is a second implementation of the splay feature added to
rhsmcertd. This adds a 'splay' option. The new option is a bool
and can be set in the rhsm.conf and disabled via the new
'--no-splay' cli option. With this feature enabled, a random
offset in seconds is chosen for both cert checks and auto attaches.
There are different offsets chosen for each type of check.
The offsets chosen will always be from 0 to the interval amount
of time. For example, if the autoAttachInterval is set to 60
seconds, the offset for splay will be between 0 and 60 seconds.
Both initial checks will be delayed by the chosen amount. After
the initial delay, the checks will be performed on the intervals
set in the config (or on the cli). In this way, the peak load on
the server that a series of systems are all …

1435013: Add splay option to rhsmcertd, randomize over interval

---

src/subscription_manager/managercli.py

Bug fix for following bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1426685
I can confirm that subscription-manager already returns non-zero exit code in this case.
I'm not sure about log level severity now. May be log.warning() would be enough.

1426685: Bug fix: subman doesn't log errors when repository enabling failed

---

bin/subscription-manager-gui

When an unprivileged user tries to run `subscription-manger-gui` and consolehelper can not be executed due to missing X auth coockie, then user should be warned about it with correct output message: "Error: this command requires root access to execute". More information in [bugzilla](https://bugzilla.redhat.com/show_bug.cgi?id=1405314).

1405314: Better output message, when subman gui is launched with non-root user

---

src/rhsmlib/facts/virt.py

This ensures that we do not run the VirtUuidCollector if the host_type returned by virt-what is one from which we cannot retrieve a valid virt uuid.
See [this bz](https://bugzilla.redhat.com/show_bug.cgi?id=1438085)

1438085: Do not include virt.uuid for platforms where it is not known

---

subscription-manager.spec

This small change of RPM spec adds dependencies to:
* Cantarella font RPM when gtk3 is used (RHEL7)
* Dejavu-Sans font RPM when gtk2 is used (RHEL6)

1441698: Install missing rpm package with fonts.

---

python-rhsm/src/rhsm/connection.py

Implementing API addition based on [Candlepin bug 1414426](https://bugzilla.redhat.com/show_bug.cgi?id=1414426) and [API spec](http://www.candlepinproject.org/swagger/?url=candlepin/swagger-2.0.25.json#!/owners/listPools). This functionality is available since Candlepin 2.0.24 (backported to the 0.9.51.21)
It allows user to list future pools via `getPoolsList()` method of the `UEPConnection` class. This PR is introducing a new parameter `future`, which can be either `None`, `"add"` or `"only"` according to how the future pools should be listed.
Possible values:
- `None` - there's no change in behavior.
- `'add'` - the `add_future=true` param is added to the GET call.
- `'only'` - API is called with `only_future=true` param in the query.
This work flow is using rather one param than two …

Add support to list future subscription pools

---

test/fixture.py
test/test_handle_gui_exception.py
test/test_managercli.py

This reduces pollution of test environments that was causing PR test
failures seen first in #1589.
`test/test_managercli.py` was the actual culprit.
I went ahead and fixed `test/test_handle_gui_exception.py` while I was
at it.
Also, I went ahead and added the `warning` method to `FakeLogger`.

Use patch for mocking loggers and show_error_window

---

python-rhsm/src/rhsm/connection.py

Adding a call to Candlepin API
`HTTP PUT /owners/<owner_key>/subscriptions`
with optional parameters `auto_create_owner` and `lazy_regen`
Cite from API documentation [[ref]](http://www.candlepinproject.org/swagger/?url=candlepin/swagger-2.0.25.json#!/owners/refreshPools):
_Tickle an owner to have all of their entitlement pools synced with their subscriptions._
We're using this call in our app (Red Hat Ethel) and since we use `python-rhsm` for every other request to Candlepin, it would be nice to have this one also covered in there (`python-rhsm` can track future API changes better than we can)

Add Update subscriptions pools API call

---

src/rhsmlib/dbus/objects/register.py
src/subscription_manager/cp_provider.py
test/rhsmlib_test/test_register.py
test/stubs.py

The DBus registration service had an error where it did not consult the
settings in rhsm.conf when attempting to register.  Any settings not
specified explicitly in the options hash were set to application
defaults.

1426357: Fix DBus register service configuration issue.

---

src/daemons/rhsmcertd.c

This replaces all "(s)" with "s". It also removes unnecessary "s" characters.

1443205: Simplify rhsmcertd log message plurality

---

src/rhsmlib/facts/dmiinfo.py
src/rhsmlib/facts/firmware_info.py

Previously tried to fix with #1584, but with that fix, only some of the
cases were covered. This change covers more cases by making `get_all`
responsible for importing dmidecode and then making sure any warnings
are cleared.
In this way, dmiinfo more fully encapsulates dmidecode, not even
exposing the module outside of that method (except to pass to other
helper functions).

1438869: Capture dmidecode errors at fact gathering

---

src/subscription_manager/ga_impls/ga_gtk2/Gtk.py
src/subscription_manager/gui/managergui.py

Bug fix for this bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1443554
Note: it will work at RHEL7/Fedora as well at RHEL6, because xdg-utils RPM package is installed there due to dependencies.

1443554: Clicking at Help->Getting Started opens yelp.

---

etc-conf/dbus/rhsm-facts.service
scripts/smoke_dbus.sh

BusName defined in .service file has to the be same as bus name
used and asquired by rhsm-fact-service. More details are here:
https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=

1429505: Facts dbus service does not start properly due to timeout.

---

src/daemons/rhsmcertd.c

There was one more `g_timeout_add()` function with wrong last argument.

1443215: bug fix of writing time stamps.

---

Makefile
etc-conf/dbus/com.redhat.SubscriptionManager.policy

There are policy files for com.redhat.RHSM1 and
com.redhat.RHSM1.Facts, but policy file for
com.redhat.SubscriptionManager was missing.

1444800: Added mising policy file for com.redhat.SubscriptionManager .

---

src/rhsmlib/facts/host_collector.py
test/rhsmlib_test/test_host_collector.py

That is if the language code from `getdefaultlocale`[1] is `None`, then
special case this as 'Unknown'.
[1]: https://docs.python.org/2/library/locale.html#locale.getdefaultlocale

1445387: Set locale fact to Unknown if value cannot be determined

---

src/subscription_manager/managercli.py

Bug fix for: https://bugzilla.redhat.com/show_bug.cgi?id=1357152
Right order of actions is IMHO following: gather information about products from product certificates and then ask server for validity of this information. More details in BZ.

1357152: Print right dates on subscription-manager list --installed

---

src/rhsmlib/facts/dmiinfo.py

* When DMI dump_file was not specified, then it tried to use
this default value (None) as dump file (dmidecode.set_dev()).
It raises exception visible in log rhsm.log file.
* This bug fix uses current dmidecode dump file (usually
/dev/mem), when dump file wasn't specified.
* Note: `subscription-manager facts --list | grep dmi` returns something again.
* Bugzilla report: https://bugzilla.redhat.com/show_bug.cgi?id=1444714

 1444714: Error reading system DMI information

---

bin/rct
python-rhsm/src/rhsm/certificate2.py

When rct tried to display candlepin certificate (IMHO self-signed), then it was terminated with error described in this BZ bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1426343

1426343: fixed rct to display cert without subjectAltName.

---

man/subscription-manager.8

Just wrong spelling: https://bugzilla.redhat.com/show_bug.cgi?id=1440319

1440319: fixed wrong spelling.

---

bin/rct
bin/rhn-migrate-classic-to-rhsm
bin/rhsm-debug
bin/sat5to6
bin/subscription-manager

* Method `setdefaultencoding()` is available in `sys` module at
Python start-up. Thus reloading of sys module. More informatin:
http://stackoverflow.com/questions/3828723/why-should-we-not-use-sys-setdefaultencodingutf-8-in-a-py-script
* This also make remote debugging in PyCharm more seamless.
* Finally it fixes this bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1446469
It was caused by removing of: `import site` in this commit:
dc665c1dab8b45cbbc7337b28e3bd2a550e29067

1446469: Use sys.setdefaultencoding('utf-8') in better way.

---

subscription-manager.spec

It's not necessary, even for subscription-manager-gui. It looks like
subscription-manager-gui will just ignore any failures in acquiring the
session bus: see 90ca1d4cb582a5576051eece5b1522fd86471ce0
Also we did some smoke tests w/ removing it on EL7, with no issues.

1446638: Remove dbus-x11 dependency

---

src/subscription_manager/gui/data/glade/factsdialog.glade
src/subscription_manager/gui/data/ui/factsdialog.ui
src/subscription_manager/gui/factsgui.py

* BZ bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1444512
* I made facts dialog little bit wider to display message about
deleted/wrong uuid.
* I'm not sure about displaying such error message in label, but
it is better than nothing.

1444512: Display deleted uuid in facts dialog correctly.

---

src/daemons/rhsmcertd.c

Simple bug fix of failure reported in BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1445204

1445204: Update timestamp during intitial cert check.

---

Makefile
src/subscription_manager/repolib.py
subscription-manager.spec
test/test_repolib.py

The tests work to confirm function, but I am not sure if they are the best way. There are 2 mocked files, but only one is available to be probed at the end of the tests.
Suggestions for improvement are welcomed.

1427069: Add secondary file to determine external repo file changes

---

src/subscription_manager/cache.py
src/subscription_manager/facts.py
src/subscription_manager/repolib.py

* Fixes bug: https://bugzilla.redhat.com/show_bug.cgi?id=1447211
* Added more debug print, when it is not possible to read any
cache json file.
* Refactored code a little bit to not use protected method.

1447211: Don't try to read non-existing json cache file.

---

src/subscription_manager/cache.py
src/subscription_manager/entcertlib.py

* Bug fix of: https://bugzilla.redhat.com/show_bug.cgi?id=1448855
* Golden ticket entitlement was not removed when you set
contentAccessMode to " " back from "org_environment".
* When candlepin returned modified/empty list of ent. certificates,
then rogue ent. certificates were removed from
/etc/pki/entitlemens, but golden ticket certs were not removed.
* Small refactoring and code style tweaks.

1448855: golden ticket entitlement was not removed.

---

src/rhsmlib/facts/hwprobe.py
test/rhsmlib_test/test_hwprobe.py

Also, I changed the way we are overriding by using 'LANGUAGE' rather
than 'LC_ALL' since https://docs.python.org/2/library/locale.html#locale.getdefaultlocale
explains that 'LANGUAGE' has the highest precedence.

1450210: Make lscpu ignore locale again

---

etc-conf/dbus/system.d/com.redhat.SubscriptionManager.conf

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1450818
* Any user was able to popup on an user logged in graphic mode.
The popup will contain warnings about subscription/entitlements
status, but it does not allow any modifications.
* Thus local user was able to do abuse & prank to an user logged
in graphical mode.
* Only root user should be able to trigger method update_status
now. e.g. using this command:
```bash
busctl call com.redhat.SubscriptionManager /EntitlementStatus \
com.redhat.SubscriptionManager.EntitlementStatus update_status i 5
```
* Common user should be able to trigger only check_status method
now e.g. using this command:
```bash
busctl call com.redhat.SubscriptionManager /EntitlementStatus \
com.redhat.SubscriptionManager.EntitlementStatus check_status
```
It …

1450818: Bug fix of com.redhat.Subscriptionmanager D-Bus policy

---

src/subscription_manager/migrate/migrate.py

Since systemd supports services placed in /etc/init.d. Also changed the
command to list-units.

1432231: Support /etc/init.d daemon even on EL7

---

python-rhsm/src/rhsm/connection.py

I tested using mitmproxy, and before the change, I see the Host header
set to the proxy hostname/IP, afterward I see it set to the rhsm
hostname/IP.

1451166: Fix Host header when using proxy

---

src/subscription_manager/identity.py

* Bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1451003
* AltName can contain two values with begining: DirName:/CN= in
product certificate. Only second value contains valid name.
The first value contains UUID. As you can see command:
rct cc /etc/pki/consumer/cert.pem | grep "Alt Name:"
can return something like this:
DirName:/CN=c3e72e3f-bb86-4f87-ac67-9c0e6eed7658, \
DirName:/CN=localhost.localdomain
or this:
Alt Name: URI:CN=rhel01.localdomain
The second case is old type of format and it has to be supported
too.

1451003: identity reports right info in name field

---

src/subscription_manager/gui/networkConfig.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1452737
* It is possible to save no_proxy settings from settings now.
* Added more comments and fixed some typo.

1452737: Enable saving no_proxy settings from GUI

---

python-rhsm/src/rhsm/config.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1443159
* Added default value to rhsmcertd.splay. It is important,
when you run following command:
subscription-manager config --list,
then default values are displayed inside [] brackets.
Example of output (autoattachinterval has changed value):
[rhsmcertd]
autoattachinterval = 100
certcheckinterval = [240]
splay = [1]

1443159: Added default value for splay configuration

---

python-rhsm/src/rhsm/connection.py
python-rhsm/test/functional/connection-tests.py
python-rhsm/test/unit/connection-tests.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1443164
* Method proxy_bypass_environment() from urllib does not
support no_proxy with items containing asterisk
(e.g.: *.redhat.com). Thus values in this environment variable
is preprocessed and leading asterisks are stripped.
* There will be opened PR for urllib to address this problem
in proper way.

1443164: no_proxy matches the host name when *.redhat.com is used

---

python-rhsm/src/rhsm/certificate2.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1414529
* Log rhsm.log will include path to wrong certificate not only
string: "Error loading certificate"

1414529: Raise exception with path to wrong certificate.

---

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py

This allows you to press Alt+S in initial-setup to go directly into
subscription-manager registergui.

1365472: Add mnemonic for subscription-manager spoke

---

etc-conf/rhsm-debug.completion.sh

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1441397
* Forgot to add --noproxy bash completion for rhsm-debug in this PR: #1638

1441397: added --noproxy for rhsm-debug auto-completion

---

src/subscription_manager/gui/managergui.py
src/subscription_manager/gui/networkConfig.py
src/subscription_manager/gui/registergui.py

* When subman gui is started without working network, then
file /etc/resolv.conf does not include any record for
DNS server. When network is up again, then glibc does not
reread this file automaticaly and function getaddrinfo()
fails. It is necessary to reread this file explicitly
using reset_resolver()
* I tried to triger reset_resolver() using D-Bus signals
from NetworkManager, but it didn't work in subman-gui
for some reason. Simple example of this approach is in
this gist:
https://gist.github.com/jirihnidek/4759643a12abcd5d39f41d9d206512d5
* More information about reseting resolv.conf:
https://stackoverflow.com/questions/30360029/if-getaddrinfo-fails-once-it-fails-forever-even-after-network-is-ready

1448501: subman gui can unregister, when network is up again

---

src/content_plugins/container_content.py
subscription-manager.spec
test/test_container_content_plugin.py

In order to accomplish this, I added an invocation of `python
content_plugins/container_content.py` to the post-install scriptlet of
`subscription-manager-plugin-container`.
I added the main method to `container_content.py`, as this kept the
logic of invoking the hook close to the hook itself, and avoided
complexities with adjusting the `PYTHONPATH`.
By invoking the hook (rather than say, calling rhsmcertd-worker), we
avoid going to the network, and instead simply reference entitlements
already present to update the client certs for registry access
(currently at /etc/docker/certs.d).
Testing requires an entitlement with a product with matching tags and
content of type "containerimage".

1422196: Update container certs after plugin install

---

python-rhsm/src/rhsm/connection.py
src/subscription_manager/exceptions.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1392709
* When connection to candlepin server is ended with socket.gaierror
and proxy is configured, then raise ProxyException
* Added special message for ProxyExeption
* Small refactoring.

1392709: Display better error msg., when wrong proxy is set up

---

python-rhsm/src/rhsm/connection.py
python-rhsm/test/unit/connection-tests.py
src/subscription_manager/utils.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1457197
* Command line argumnet --noproxy=* is not ignored too
* Added log.debug print with new content of NO_PROXY
* Added more unit tests covering no_proxy=* and some other
cases: no_proxy/NO_PROXY
* Small refactoring

1457197: Env. variable no_proxy=* is not ignored

---

src/subscription_manager/branding/redhat_branding.py
src/subscription_manager/gui/data/ui/credentials.ui

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1457348

1457348: Use https for the redhat.com/forgot_password label.

---

src/rhsm_debug/debug_commands.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1455681
* Report directory should not be created with permissions:
drw-------
, but it should be created with permissions:
drwx------
to be possible to change this report directory as working
directory.
* Files are still created with -rw------- permissions.

1455681: rhsm-debug created report dir with wrong perms

---

src/subscription_manager/exceptions.py
src/subscription_manager/managercli.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1452075
* Print only readable part of SSL error to console
* When handling exception in register --force command, then do
map_message to have nice error message.

1452075: print only readable SSL error to console

---

src/subscription_manager/gui/managergui.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1459194
* When no LANG env. variable is set, then try to open default URL.

1459194: open Online Documentation, when env. var. LANG is unset

---

README.md
Vagrantfile
vagrant/roles/subman-devel/defaults/main.yml
vagrant/roles/subman-devel/tasks/main.yml
vagrant/roles/subman-devel/vars/openSUSE Leap.yml

This adds a vagrant configuration for an openSUSE 42.2 box.
There are a number of differences between the openSUSE box and the others.
In this PR these differences are dealt with using the ansible_distribution var. Some tasks are run only when the ansible_distribution is 'openSUSE Leap'.
A future version of this might include tasks unique to a given distribution in a way much like the variables that are unique to a given distribution (that being in a separate file named for the distribution).
The new box can be created using the command 'vagrant up opensuse42.2'

Adds a new vagrant box "opensuse42.2"

---

src/subscription_manager/managercli.py
test/test_registration.py

This patch resolves BZ 1463325 which is a request for subscription-manager to output the hostname of the system that was registered along with the uuid.

Output the hostname of the system that was registered along with the UUID

---

bin/rct
bin/rhn-migrate-classic-to-rhsm
bin/rhsm-debug
bin/sat5to6
bin/subscription-manager
src/subscription_manager/managercli.py
src/subscription_manager/migrate/migrate.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1350402
* When some output (stdout/stderr) of subscription-manager
process is blocked (not listening piped process in this case),
then try to flush it at end. When flushing is not possible,
then write error message to rhsm.log.
* More details here:
https://stackoverflow.com/questions/12790328/how-to-silence-sys-excepthook-is-missing-error

1350402: Try to flush all outputs during exit process

---

src/plugins/subscription-manager.py

`yum-config-manager` does not load plugins of type `TYPE_INTERACTIVE`.
According to http://yum.baseurl.org/wiki/WritingYumPlugins, `TYPE_INTERACTIVE`
indicates that a plugin may terminate yum early or output extra information.
We don't terminate yum... while we do provide some extra information, we do
similarly in the `product-id` plugin.
This change improves the user experience, by being able to use
`yum-config-manager` without first running a yum command to populate
redhat.repo.

1329349: Add subscription-manager plugin to yum-config-manager

---

src/subscription_manager/productid.py

We do indeed update product certs (added in 9ee2f98), the comments were
not updated to reflect this. By updating them, hopefully the next
developer won't trip over this.

Remove stale product cert update FIXME

---

python-rhsm/src/rhsm/certificate2.py
python-rhsm/test/unit/certificate-tests.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1472715
* Noticed this, when I was working at PR for virt-who:
https://github.com/virt-who/virt-who/pull/83
* The rhsm module has to reaise exception not call exit(),
otherwise the application is not able to resurect from
such situation.
* Added unit test for this case.

1472715: Python module rhsm should never call exit()

---

etc-conf/subscription-manager.completion.sh
man/subscription-manager.8
src/subscription_manager/managercli.py
test/test_registration.py

still allows the default of 'system' and the option 'rhui'.
does not show in help.

1461003: Deprecate --type option on register command

---

src/subscription_manager/managercli.py
src/subscription_manager/release.py
test/test_release.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1464571
* Sub-man prints error message for releases command, when
more RHEl-# products are installed. This can happen
during testing phase.
* Removed some unuseful method call (caused by copy paste?).
* Added one unit test for this unusual situation.
* Some refactorings (indentation).

1464571: 'sub-man release' prints error for more prod. certs.

---

src/subscription_manager/repolib.py

Otherwise, the first time the repository was brought into the clean
copy, it had `enabled = 1` regardless.

1480659: Properly initialize clean repo copy

---

src/subscription_manager/cache.py
test/test_cache.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1481384
* When connection limit is exceeded then this exception is
handled properly and redhat.repo is not updated

1481384: Do not update redhat.repo at RateLimitExceededException

---

cockpit/package.json
cockpit/spec/DummySpec.js
cockpit/spec/dbus/DBusSpecRunner.html
cockpit/spec/dbus/dbus.test.js
cockpit/spec/dbus/override.json
cockpit/spec/dbus/utils.js
cockpit/spec/support/jasmine.json
cockpit/webpack.config.js
cockpit/yarn.lock

Run unit tests via `npm run jasmine`
See integration tests via vagrant (see DBus Testing page).
Integration tests have access to a live instance of cockpit.
Original work for D-Bus testing page comes from stoner (@rarebreed).
Unit tests are declared in files that end in [sS]pec.
Integration tests are included in dbus-testing.js via webpack.

Add jasmine & placeholder unit/integration tests

---

src/subscription_manager/managercli.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1485008
* subscription-manager register --type="RHUI" or --type="rhui"
should both work as documented in various KBase articles

1485008: subman register --type="RHUI" should work

---

etc-conf/rhsm.conf
python-rhsm/src/rhsm/config.py
src/subscription_manager/gui/managergui.py
src/subscription_manager/managercli.py
src/subscription_manager/repolib.py
test/test_repolib.py

* BZ [RFE]: https://bugzilla.redhat.com/show_bug.cgi?id=1319927
* Enable automatic enabling of yum plugins for sub-man CLI
* Automatic enabling of yum plugin is also implemented for sub-man GUI
* It is not implemented for initial-setup, because case desctibed
in BZ bug report will be covered by sub-man CLI or GUI
* Add some unit tests for this case
* Added template to rhsm.conf file

1319927: [RFE] sub-man automatically enables yum plugins

---

src/subscription_manager/logutil.py

polymorphy can only be properly handled on the reference level, not at the object level.
Especially calling "__init__" of a different class than direct ancestors is most definitive going to blow up.
In this case, the maxBytes variable is missing after initializing with the wrong initializer.

Fix polymorphy for RHSMLogHandler

---

vagrant/roles/subman-devel/tasks/main.yml

I do not know if these instructions do any harm, but they enable me to subscribe the debian vagrant box to a forklifteded katello dev instance.
Comments are welcome.

add tasks to setup hacking environment in debian

---

etc-conf/rhsm.conf
src/subscription_manager/gui/managergui.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1489877
* Fixed typo in rhsm.conf comment and in sub-man gui

1489877: minor typo in /etc/rhsm/rhsm.conf comment

---

src/rhsmlib/dbus/objects/attach.py
src/rhsmlib/dbus/objects/entitlement.py
src/rhsmlib/dbus/objects/products.py
src/rhsmlib/dbus/objects/unregister.py
src/rhsmlib/services/entitlement.py
src/subscription_manager/async.py
src/subscription_manager/certdirectory.py
src/subscription_manager/managercli.py
test/rhsmlib_test/test_entitlement.py

* Added three new public methods to entitlement service
* Added three new methods to D-Bus entitlement interface
(com.redhat.RHSM1.Entitlement)
RemoveAllPools
RemovePoolsByIds
RemovePoolsBySerials
* It is possible to test new API using following commands:
$ busctl introspect com.redhat.RHSM1 \
/com/redhat/RHSM1/Entitlement
$ dbus-send --system --print-reply --dest='com.redhat.RHSM1' \
'/com/redhat/RHSM1/Entitlement' \
com.redhat.RHSM1.Entitlement.RemoveAllPools \
dict:string:string:"",""
$ dbus-send --system --print-reply --dest='com.redhat.RHSM1' \
'/com/redhat/RHSM1/Entitlement' \
com.redhat.RHSM1.Entitlement.RemovePoolsBySerials \
array:string:'6959731507094690613' dict:string:string:"",""
$ dbus-send --system --print-reply --dest='com.redhat.RHSM1' \
'/com/redhat/RHSM1/Entitlement' \ …

D-Bus service for removing pools (all/ID/serial num.)

---

src/subscription_manager/api/repos.py
src/subscription_manager/managercli.py
src/subscription_manager/migrate/migrate.py
src/subscription_manager/productid.py
src/subscription_manager/repolib.py
test/fixture.py
test/test_api.py
test/test_certdirectory.py
test/test_managercli.py
test/test_migration.py
test/test_repolib.py

I want to introduce a base class in order to be able to implement repository filetypes that do not follow the configfile layout (e.g. apt sources).
RFC: Should we rename the class RepoFile to YumRepoFile, as subscription-manager is trying to become more generic about packet / archive formats?

restructure RepoFile hierarchy

---

src/subscription_manager/migrate/migrate.py

* Bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1466453
* It reuses code from sub-man. See also BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1319927
* It enables yum plugins: subscription-manager and product-id
* This automatic enablement can be disabled in rhsm.conf

1466453: [RFE] rhn-migrate-classic-to-rhsm auto-enable yum plugins

---

src/subscription_manager/api/__init__.py
test/test_api.py

The issue can be replicated in master with
```
nosetests  --randomly-seed=1506092144 test.test_api:RepoApiTest.test_enable_repo test.test_managercli:HandleExceptionTests.test_he_unicode
```
The failure is dependent on the RepoApiTest running before HandleExceptionTests.

Fix issue where tests run in a certain order caused encoding errors.

---

src/subscription_manager/repolib.py
test/test_repolib.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1489917
* Configuration file of yum plugin can contain values of
`enabled` option:
```
enabled = true
enabled = false
enabled = 1
enabled = 0
```
* Code can handle other unusual situations:
- Option `enabled` does not have valid value, e.g.: 1.0, 4, etc.
- Option `enabled` is missing or uncommented
- Section `main` is missing or uncommented
* Added more unit tests
* Note: When iniparse module is not able to parse config file,
then this config file is skipped. Only in this situation yum
plugin is not enabled, because yum plugin will not be able
to read too.

1489917: More robust reading of yum plugin file

---

README.md
Vagrantfile
cockpit/README.md
cockpit/webpack.config.js
vagrant/roles/subman-devel/defaults/main.yml
vagrant/roles/subman-devel/files/com.redhat.RHSM1.conf
vagrant/roles/subman-devel/files/sitecustomize.py
vagrant/roles/subman-devel/tasks/cockpit.yml
vagrant/roles/subman-devel/tasks/main.yml
vagrant/roles/subman-devel/vars/openSUSE Leap.yml

Changes:
- `/vagrant/src` and `/vagrant/python-rhsm/src` are now in the python path for all processes, by using `sitecustomize.py`
- `/usr/libexec/rhsm-service` is a now symlink to `/vagrant/bin/rhsm-service`
- webpack is now configured the same in the VM
- `/usr/local/share/cockpit/subscription-manager` is now a symlink to `/vagrant/cockpit/dist`
- Excludes are now adjusted to avoid problems when rsyncing
- The dbus config file for RHSM1 is replaced with a shim that includes `/vagrant/etc-conf/dbus/system.d/com.redhat.RHSM1.conf`
- selinux is set to permissive to allow the aforementioned shim to work.
- `nvm` is used to install npm, instead of relying on the version in EPEL
With these changes, a developer should be able to simply checkout the code, `vagrant up`, and see the results in …

Improve the cockpit plugin dev experience

---

etc-conf/rhsm.conf
man/rhsm.conf.5
python-rhsm/src/rhsm/config.py
src/rhsmlib/dbus/inotify.py
src/rhsmlib/dbus/server.py
src/rhsmlib/services/attach.py
src/subscription_manager/entcertlib.py
src/subscription_manager/healinglib.py
src/subscription_manager/identity.py
src/subscription_manager/identitycertlib.py
subscription-manager.spec

- Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1477958
- I-notify is used for checking of changes in /etc/pki/consumer
to trigger reloading of `identity`.
- When `pyinotify` module or i-notify at all is not possible to use, then it
falls back to periodical directory polling. This code is used
by sub-man gui.
- Small changes in subscription-manager.spec file, because new
Python module is required at RHEL7 and Fedora.

1477958: Use inotify for checking changes of consumer certs

---

src/subscription_manager/managercli.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1501889
* Warning message is printed after output of sub-command.

1501889: Enable yum plugins after sub-man subcommand is executed

---

cockpit/package.json
cockpit/src/Select/Select.jsx
cockpit/src/index.html
cockpit/src/index.js
cockpit/src/subscriptions-register.jsx
cockpit/src/subscriptions-view.jsx
cockpit/webpack.config.js
cockpit/yarn.lock

I had to switch from react-lite to react because react-lite was not
tolerant of the DOM-tree changes that bootstrap-select uses.
PR Note: right now the base is the branch used for #1693, as this builds on work in that branch. Before merging, let's make sure #1693 is addressed, and then I'll update the base of this PR to `feature/cockpit`.
i.e. at time of writing: review is okay, but merge should wait until #1693.

Implement bootstrap-select component

---

cockpit/package.json
cockpit/src/cockpit-components-dialog.jsx
cockpit/src/index.js
cockpit/src/subscriptions-client.js
cockpit/src/subscriptions-register.jsx
cockpit/src/subscriptions-view.jsx
cockpit/src/subscriptions.css
cockpit/webpack.config.js
cockpit/yarn.lock
src/rhsmlib/dbus/exceptions.py
src/rhsmlib/dbus/objects/products.py
subscription-manager.spec
test/rhsmlib_test/test_products.py

Implementation is from https://github.com/cockpit-project/cockpit/blob/c04c148225c59d2f053300d80b6b4731e421b8e6/pkg/lib/cockpit-components-dialog.jsx .
It's been cleaned up a bit in order to satisfy switching to React from
react-lite, as well as to clean up a few warnings. See the diff of
src/cockpit-components-dialog.jsx to the link above for changes.
I also made a few changes in order to get the registration flow to work
and general improvements:
- fixed the registration method in subscriptions-client.js
- removed the ensure registered requirement from the products service
- removed tracebacks from error messages emitted by the D-Bus services
- added the extract-text-webpack-plugin to webpack to produce subscriptions.css

Cockpit: Implement modal dialog

---

build_ext/i18n.py
cockpit/package.json
cockpit/src/index.html
cockpit/src/index.js
cockpit/src/subscriptions-register.jsx
cockpit/src/subscriptions-view.jsx
cockpit/webpack.config.js
cockpit/yarn.lock
subscription-manager.spec

This means:
- build the translations from those po files use po2json
- import the resulting files into cockpit via `cockpit.locale`
- hook js/jsx files into our xgettext usage via setup.py
In index.html, we now reference `po.js`.
Cockpit will automatically serve `po.${language}.js` instead when present.

Cockpit: use translations from root dir

---

cockpit/src/subscriptions-register.jsx

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1506970
* Chnaged string from: subscription.rhn.redhat.com (wrong value)
to: subscription.rhsm.redhat.com

1506970: Fixed default custom URL in cockpit plugin

---

src/rhsm/config.py
src/subscription_manager/gui/managergui.py
src/subscription_manager/gui/utils.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1421010
* When proxy requires authentication and no/wrong proxy_user and
proxy_password is set in rhsm.conf, then error message is
displayed now too
* Refactored code a little
* There are two variants of error dialog:
* No `proxy_user` and/or `proxy_password`:
* Wrong `proxy_user` and/or `proxy_password`:

1421010: Subman-GUI shows error dialog (wrong proxy settings)

---

Vagrantfile
vagrant/roles/subman-devel/tasks/main.yml

Make sure to install the required subscription-manager-rhsm*
packages along with subscription-manager.
It seems we needed the build_ext module for some of our ./setup.py steps. This no longer excludes that folder for our vagrant setup.
One of the steps of the deploy attempted to install the packages just built by tito. After we renamed python-rhsm to subscription-manager-rhsm* we now have a need to install that first (done by changing the globing).

Updates vagrant bits post python-rhsm package rename

---

src/subscription_manager/cache.py
src/subscription_manager/cert_sorter.py
src/subscription_manager/injection.py
test/test_cache.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1500106
* Argument on_date is not lost between calling sub-man CLI command
line option and calling REST API
* TODO: add unit tests covering this case

1500106: subscription-manager status --ondate do not ignore date

---

src/rhsmlib/facts/virt.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1514067

1514067: Call virt-what using absolute path

---

src/subscription_manager/managercli.py
src/subscription_manager/migrate/migrate.py
src/subscription_manager/repolib.py

This makes translations inconsistent. (We generally don't have newlines in the translations themselves).

1319927: Remove newline from auto enable message

---

src/rhsm/connection.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1507158
* TODO: verify this bug fix with proxy server requiring this
header. Waiting for more info from BZ reporter.

1507158: Provide Host: in http CONNECT header

---

cockpit/src/manifest.json

Both RPMs can be installed, but when subscription-manager-cockpit is
installed, it will take priority over cockpit-subscriptions.
This is accomplished by name and priority changes in manifest.json.

Replace cockpit-subscriptions

---

src/subscription_manager/gui/preferences.py
src/subscription_manager/managercli.py
src/subscription_manager/release.py
test/stubs.py

Made the error message and the translated message consistent. Also moved
the translation to a method on the exception, and added error handling
to the preferences GUI. (See
https://bugzilla.redhat.com/show_bug.cgi?id=1464571 comments 6-8 for
source of these requests)

1464571: Improve multiple product certs errors

---

po/as.po
po/gu.po
po/hi.po
po/kn.po
po/pa.po
po/ta_IN.po
po/te.po

Indic languages that had incorrect translations where server:port/prefix
wrong. I chose to do these manually, rather than through zanata to limit
the scope of the change.
NOTE: this change already landed in subscription-manager-1.19.21-1,
unintentionally did not land in master yet.

1463765: Fix wrong Indic-language translations

---

cockpit/src/subscriptions-client.js
src/rhsm/connection.py
src/rhsmlib/dbus/objects/attach.py
src/rhsmlib/dbus/objects/config.py
src/rhsmlib/dbus/objects/entitlement.py
src/rhsmlib/dbus/objects/products.py
src/rhsmlib/dbus/objects/register.py
src/rhsmlib/dbus/objects/unregister.py
src/rhsmlib/dbus/util.py
src/subscription_manager/i18n.py
test/rhsmlib_test/test_attach.py
test/rhsmlib_test/test_config.py
test/rhsmlib_test/test_entitlement.py
test/rhsmlib_test/test_products.py
test/rhsmlib_test/test_register.py
test/rhsmlib_test/test_unregister.py

* Implemented changing language on the fly
* Following format of language codes are supported:
* de
* de_DE
* de_DE.UTF-8, de_DE.utf-8
* de_AT, de_LU, de_AT.utf-8, etc.
* It also set environment variable LC_ALL, because rhsm.connection
use it to determine requested language. Candlepin returns localized
error messages according HTTP header: "Accept-Language"
* Added locale parameter to all D-Bus methods
* Error messages from D-Bus methods are returned as JSON string
e.g.: '{"exception": "EsceptionName", "message": "Error message"}'
Error message can be easily parsed and displayed in cockpit plugin
* Modified all unit tests to reflect changes in D-Bus API
* Modified subscription-client.js to use benefit of new API

Add parameter to D-Bus API to pass locale for localization of errors

---

src/subscription_manager/cache.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1510727
* GoneException is child of connection.RestlibException and
therse is no need to raise this exception.
* Tested many subman CLI commands and it works as expected in
this situation (consumer has been deleted).
* Note: This bug was caused by this PR #1685. The GoneException
did not have any effect before this PR was merged, because
there was 'wrong' order of exceptions. Moving GoneException
was not good idea.

1510727: Enable starting of subman GUI, when consumer has been deleted

---

src/rhsmlib/dbus/facts/base.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1304056#c6
* D-Bus path should be: /com/redhat/RHSM1/Facts and not:
/com/redhat/RHSM1
* Notice that output of 'busctl tree com.redhat.RHSM1.Facts' is now:
```console
└─/com
└─/com/redhat
└─/com/redhat/RHSM1
└─/com/redhat/RHSM1/Facts
```
* You can use introspec subcommand like this:
```console
busctl introspect com.redhat.RHSM1.Facts /com/redhat/RHSM1/Facts
```
* You can tests API using following command:
```console
dbus-send --system --print-reply --dest='com.redhat.RHSM1.Facts' \
'/com/redhat/RHSM1/Facts' com.redhat.RHSM1.Facts.GetFacts
```
* Fixed indentation and white space in policy file

1304056: Fix D-Bus path of com.redhat.RHSM1.Facts

---

etc-conf/rhsm.conf
man/asciidoc/rhsm.conf.5.asciidoc
man/rhsm.conf.5
src/rhsm/config.py
src/subscription_manager/repolib.py
test/rhsm/unit/config-tests.py
test/rhsmlib_test/test_config.py
test/stubs.py

This repo metadata signing key will be used in addition to any RPM signing keys that are configured for each repository.
This is necessary to support the use of repo_gpgcheck=1 with Satellite, since Satellite must sign the metadata using a local GPG key, while the RPMs in each repository will be signed using the upstream repository's GPG key as specified in the entitlement certs.
See https://bugzilla.redhat.com/show_bug.cgi?id=1410638

Support the configuration of a repo metadata signing key

---

src/subscription_manager/repolib.py

Per https://github.com/candlepin/subscription-manager/pull/1749#discussion_r159297538 I adjusted the logic in that PR such that gpgcheck would be enabled if a repo metadata gpg key is configured.
Unfortunately, I had forgotten why I originally implemented it to disable gpgcheck if only a repo metadata gpg key is configured ... After further testing of the merged commit, I've re-discovered that this causes problems for repositories that contain unsigned RPMs and therefore do not have a non-metadata gpg key configured.  If the only configured gpg key on a repository is the metadata gpg key, then only the global repo_gpgcheck yum configuration option should be enabled, and the per-repository gpgcheck configuration option should be disabled.

Do not enable gpgcheck if the only a metadata gpg key is configured

---

src/rct/manifest_commands.py
test/manifestdata.py

this is useful for debugging why a satellite cannot access the distributor :)

rct cat-manifest: show Web and API urls from consumer.json

---

build_ext/i18n.py
src/rhsm/connection.py
src/subscription_manager/exceptions.py
test/test_exceptions.py

The message printed to the console doesn't include the official error title (Page Not Found, Internal Service Error, etc.) because we don't have translations for them and I feel that the sense of the message -- that there was an error server-side -- is conveyed well enough with the phrase "HTTP error code".
I am a little concerned about error messages coming back in UTF8.  I used our "convert this to unicode if you can" utility method, but it feels like kind of a hack and none of the other error messages need to bother with it.
Testing this can be annoying.  Here is how I do it.
1. Set up a local Candlepin and register to it.
2. Go into the `rhsm.conf` file and change the port to 3131
3. Drop the following in a file named `500.response`
```
HTTP/1.1 500 Internal Server Error
Server: …
```

1507030: RestlibExceptions should show they originate server-side

---

src/subscription_manager/gui/managergui.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1527813
* I guess that somebody considered URL containing only lower
case characters as more sexy ;-)

1527813: subman-gui use new URL of Online Documentation

---

README.md
setup.cfg
test/gui/test_about.py
test/gui/test_contract_selection_gui.py
test/gui/test_facts_gui.py
test/gui/test_gui_utils.py
test/gui/test_handle_gui_exception.py
test/gui/test_managergui.py
test/gui/test_network_config_gui.py
test/gui/test_preferences.py
test/gui/test_progress_gui.py
test/gui/test_registrationgui.py
test/gui/test_repogui.py

Since we're planning on not supporting the GUI w/ Python 3, and they
were causing issues on F27 (segfaults!) that were non-trivial to
determine the root cause of, we'll just stop running them by default.
Ran into these issues while developing #1761, so it may be necessary to
pull these changes in to test that PR against Python 3...
C-I should still be running them by using a different config file for
nose.

Don't run gui tests by default

---

src/subscription_manager/productid.py
test/test_productid.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1526622
* Yum plugin product-id should never delete product certificate
in protected directory /etc/pki/product-default, because such
certificates are provided only by RPM and we should not delete
files provided by any RPM
* Modified smoke test (it can be removed)
* Added one unit test covering new case

1526622: Do not delete product certificates in protected directory

---

src/subscription_manager/productid.py
test/test_productid.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1525238
* This test isn't neccessary anymore, because bug fix of 1526622

1525238: Do not protect rhel prod. cert with special case

---

src/rhsm/connection.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1540204
* virt-who wasn't able to get "Retry-After:" header in some cases

1540204: Raise RateLimitExceededException with headers

---

subscription-manager.spec

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1537473

1537473: Subman rpm requires python-setuptools

---

src/subscription_manager/rhelproduct.py
test/test_rhelproduct.py

For now we'll support just rhel-alt additionally, though it wouldn't be
hard to change to a more general matcher in the future if needed.
Comment left in the code to that effect.

1510024: Handle rhel-alt product tags properly

---

subscription-manager.spec

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1533905
* Removed requirements on yum and chconfig for non-suse distribution

1533905: Remove dependency on yum and chkconfig.

---

po/zanata.xml

We're removing the project version, as the release nanny tooling has
been updated to specify --project-version based on the latest releaser.
The configured languages are also tweaked.
Also, the zanata instance we're using has changed.
See also candlepin/candlepin#1832

Update zanata config

---

src/rhsm/profile.py
test/test_cache.py

This fixes the issue I raised in https://bugzilla.redhat.com/show_bug.cgi?id=1543639
```
[root@fedora27 vagrant]# subscription-manager register --username admin --password changeme --force
Unregistering from: centos7-katello-3-5.strangeways.example.com:443/rhsm
The system with UUID 7fba2e9f-7d27-45d6-b096-87a92b45a7fd has been unregistered
All local data removed
Registering to: centos7-katello-3-5.strangeways.example.com:443/rhsm
The system has been registered with ID: bc460d08-76aa-4492-a026-3bfe1d6e5777
The registered system name is: fedora27.strangeways.example.com
[root@fedora27 vagrant]# 
```
If solution is approved I'll write some tests.

1543639 - Properly encode package profile data

---

src/rhsmlib/facts/dmiinfo.py

Calls to `dmidecode.connector()` can fail with a "list assignment index
out of range" error (for reasons that are currently unknown).  In this
case, our code should return an empty dictionary instead of None since
the return value is dereferenced later where it is assumed to be a
dictionary.
Additionally, if there are failures during fact gathering, we should
display the stacktrace in the logs for debugging purposes.

1528625: Prevent dmidecode failure from returning None

---

subscription-manager.spec

See https://fedoraproject.org/wiki/Packaging:C_and_C%2B%2B#Packaging
I got an [announcement email](https://lists.fedoraproject.org/archives/list/devel-announce@lists.fedoraproject.org/thread/IJFYI5Q2BYZKIGDFS2WLOBDUSEGWHIKV/) from Igor Gnatenko at Fedora Project stating that this is a new requirement.

Add BuildRequires for gcc

---

subscription-manager.spec

Subscription manager wasn't building in Fedora 27.  When running 'make'
to build '_certificate.so', 'make' was invoking 'setup.py' with 'python'
instead of 'python3'.  The result was that '/usr/include/python2.7' was
added to the 'gcc' command.  That was fine in Fedora 26 as that
directory and header files were already in the buildroot for whatever
reason.  In Fedora 27, something changed and our buildroot only had
'/usr/include/python3.6m' so we need to run 'setup.py' under 'python3'
so that 'gcc' will receive the correct include path.
This commit also removes duplicate BuildRequires for %{py_package_prefix}-devel.

Define python version when calling make command.

---

subscription-manager.spec

* "python3-python-rhsm" never existed.  The actual name was
"python3-rhsm".
* Remove Obsoletes and Provides directives that were self-referential.

Remove unneeded spec file directives

---

src/rhsm/profile.py

In python 2.6 on Centos 6 (and equivalent versions of RHEL), the decode method of strings does not accept the errors argument as a keyword argument.
This was causing very strange behaviour during firstboot (subscription-manager would attempt to auto-attach when it should not, as well as much more).

1551465: Fix unicode decode issue on py 2.6

---

subscription-manager.spec

* It is still necessary to define BuildRoot on SLES 11

Fix building on SLES 11

---

.gitignore
Vagrantfile
vagrant/roles/pxe-server/defaults/main.yml
vagrant/roles/pxe-server/tasks/main.yml
vagrant/roles/pxe-server/templates/default.j2
vagrant/roles/pxe-server/templates/dhcpd.conf.j2
vagrant/roles/pxe-server/templates/ifcfg-eth1.j2
vagrant/roles/pxe-server/templates/ks_centos7.cfg.j2
vagrant/roles/pxe-server/templates/ks_fedora27.cfg.j2
vagrant/vagrant.yml
vagrant/vagrant_data/README.md
vagrant/vagrant_pxe_server.yml

* New Vagrant file is in new directory anaconda, because it was
the simpliest way to not trigger other ansible scripts
* It downloads image of Centos7 minimal image
* I have plan to modify Ansible scripts to support Fedora 27
in the future
* The IP address of pxe server has to be static, because it is
necessary to know it before VM with PXE server is created.
The is used, when private network is created. Otherwise
client will not boot using PXE.
* The client for testing machine can be created simply in
virt-manager, but it will requires at least 2GB RAM due to
some bug in anaconda.

New Vagrant file for creating PXEBOOT server

---

Vagrantfile

Noticed this while reviewing #1797 .
As we now define a private network for use with the PXE server / client, the vagrant hostmanager plugin seems to pick the static ip for all of the boxes defined in our vagrantfile.
Adding this configuration option effectively stops this from happening.
To repro the original issue run `vagrant up` on the master branch from a clean checkout. After this, check your /etc/hosts file and notice that all the addresses listed are '192.168.111.5'.
See the [hostmanager plugin](https://github.com/devopsgroup-io/vagrant-hostmanager) for more details.

Do not use private network addresses for vagrant hostmanager

---

Vagrantfile
vagrant/roles/pxe-server/defaults/main.yml
vagrant/roles/pxe-server/tasks/main.yml
vagrant/roles/pxe-server/templates/default.j2

* File updates.img is copied to pxe-server as part of:
vagrant up pxe-server
* File updates.img is downloaded to pxe-client during boot using
ftp protocol. PXE server is already running vsftp server. Thus
there is no need to use e.g. HTTP for this purpose.
* Tested with updates.img generated on Fedora 27

Apply updates.img druing PXE boot

---

README.md
TESTING.md
vagrant/roles/rhsm-services/defaults/main.yml
vagrant/roles/rhsm-services/files/rhsm-services.service
vagrant/roles/rhsm-services/tasks/main.yml
vagrant/vagrant.yml

`rhsm-services` is a test service that offers tasks for system tests for cockpit plugin.
The service runs in tested machine.
This PR brings an ansible role `rhsm-services` that installs the service in a tested machine.
There is an env variable `subman_with_system_tests` that enables this task.

ansible for rhsm testing services

---

README.md
Vagrantfile
vagrant/roles/proxy-server/defaults/main.yml
vagrant/roles/proxy-server/files/squid.conf
vagrant/roles/proxy-server/tasks/main.yml
vagrant/vagrant_proxy_server.yml

There is an authorization proxy server in Vagrantfile. It can be used for testing purposes mainly.
```shell
cd src/subscription-manager
vagrant up proxy-server
```
See README.md for details.

a new VM 'proxy-server' in a vagrant stack

---

src/rhsmlib/facts/hwprobe.py

Reduces the log level for exceptions caught during resolution of
the 'network.ipv4_address' and 'network.ipv6_address' facts to
DEBUG. As these facts are non-critical, we should not concern
end users with ERROR level messages regarding them.
See http://bugzilla.redhat.com/show_bug.cgi?id=1559743

1559743: Reduce log level of network address fact collection to debug

---

src/rhsm/certificate2.py
src/subscription_manager/managercli.py

Not able to present content access mode, as it is an attribute of
the organization that is not shared in the certificate.
To enable the content access mode you need your system to be set to 'hosted':
Execute this on the candlepin machine:
curl -k -u admin:admin --request PUT --data '{"contentAccessMode":"org_environment"}' --header 'accept:application/json' --header 'content-type: application/json' https://localhost:8443/candlepin/owners/snowwhite
Then register the client system against the org snowwhite.
When you run subsctiption-manager status you should get the content access message.

1425766: Additional message in status to indicate content access

---

src/subscription_manager/scripts/rhsmcertd_worker.py

This is the same fix applied to rhsmcertd_worker as in other places in the codebase.
[Bug](https://bugzilla.redhat.com/show_bug.cgi?id=1568214)

1568214: rhsmcertd no longer uses reload on py3

---

src/dnf-plugins/subscription-manager.py
src/plugins/subscription-manager.py
src/zypper/services/subscription-manager

This enables new content to be utilized by a system when the full_refresh_on_yum setting is used.
This should allow content from new environments or content views to be retrieved when new packages are installed (or updated).
Based on branch awood/1439645-yum-plugin
[RFE Bug](https://bugzilla.redhat.com/show_bug.cgi?id=1439645)

1439645: Perform a full entitlement refresh in the yum/dnf/zypper plugins

---

src/rhsmlib/facts/hwprobe.py
test/rhsmlib_test/test_hwprobe.py

Last system boot time is now reported as proc_stat.btime
[Bug](https://bugzilla.redhat.com/show_bug.cgi?id=1527727)

1527727: Add proc_stat.btime fact

---

.tito/lib/rhsmtagger.py
.tito/tito.props
Makefile
README.md
packages/intentctl/Pipfile
packages/intentctl/Pipfile.lock
packages/intentctl/README.md
packages/intentctl/setup.cfg
packages/intentctl/setup.py
setup.py
src/intentctl/cli.py
src/intentctl/intentfiles.py
src/intentctl/main.py
src/intentctl/utils.py
subscription-manager.spec
test/intentctl/base.py
test/intentctl/test_intentfiles.py
test/intentctl/test_utils.py

This PR adds a new cli utility to the subman/rhsm universe that allows for tracking a system's intended product offerings, service level agreement, and usage.
In order to support tracking this package along with the other pieces of the subman, but allow for it to be installed / developed separately, I have added the relevant ./setup.py and support files under a new packages directory. This PR also includes a new VersionTagger for tito that supports keeping the version in multiple setup.py files in subdirectories of a project in sync (as I think we might like to keep the version of all these utilities in sync) (if we were to release this utility completely independently I might suggest having a truly independent version).
The utility itself is rather simple: It manipulates and maintains a …

Add a new utility for managing system intent

---

Vagrantfile
vagrant/roles/proxy-server/tasks/main.yml

A proxy server was not able to resolve 'candlepin.example.com'. 
Tried Tested Trusted.

fix for proxy-server provisioning - resolving of 'candlepin.example.com'

---

setup.py

This fixes compatibility with platforms that don't have kitchen
available, such as EL6 and SUSE.

Remove kitchen from install_requires

---

src/daemons/rhsmcertd.c

On certain architectures, long int is overflowed by RAND_MAX + 1.
To fix it across the board, expand to long long's.

1574529: Fix rhsmcertd integer overflow on i386 & i686

---

Vagrantfile
scripts/autobuild_updates_img.sh
scripts/build_updates_img.sh
vagrant/roles/pxe-server/defaults/main.yml
vagrant/roles/pxe-server/files/autobuild_updates_img.service
vagrant/roles/pxe-server/tasks/main.yml

* When PXE server is provisioned, then new service is started.
This service starts shell script watching for changes in
source code of subscription-manager using inotify. When
source is changed, then new updates.img for Anaconda installer
is build.
* Source code of subscription-manager has to be synced using
"vagrant rsync pxe-server" or "vagrant rsync-auto pxe-server"
* Note: I added option: "-W" to vagrant rsync configuration,
because command: "vagrant rsync pxe-server" was failing due to
inotify running on pxe-server.

Automatic rebuilding of updates.img on PXE Server

---

build_ext/template.py

-https://bugzilla.redhat.com/show_bug.cgi?id=1555384
-Function can be found in build_ext/template.py, produces the file
etc-conf/dbus/system-services/com.redhat.SubscriptionManager.service.template
-Added everything after "decode" in first return value of try statement

1555384: get_libexecdir now returns a string instead of bytes

---

src/rhsm/connection.py

* https://bugzilla.redhat.com/show_bug.cgi?id=1560727
* Proxy authentication failures are handled the same way on RHEL6 and RHEL7.

1560727: Search for proxy auth message in whole error string

---

src/subscription_manager/intentstore_interface.py
src/subscription_manager/managercli.py
test/test_intentstore_interface.py
test/test_managercli.py

- Now, when the following commands are run successfully, intent.json is updated with the new SLA value passed by the user:
* subscription-manager service-level --set/--unset
* subscription-manager attach --auto --servicelevel
* subscription-manager register --auto-attach --servicelevel
- If the commands fail (their query to CP fails), intent.json is not updated.
- If the intentctl module cannot be imported, the commands continue normal operation and print a warning.

ENT-481 service-level command & options now update intent metadata

---

subscription-manager.spec

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1574706
* This RPM packaged included _certificate.so for Python3 and
not for Python2. Thus it couldn't work :-). The package also
included `__pycache__` for Python3
* The package contains _certificate.so for Python 2 now and
it should not have dependency on Python 3.

1574706: Create python2-subscription-manager-rhsm properly

---

src/subscription_manager/managercli.py

Without this, default proxy port is used, which breaks deployments that need proxy to register with rhn.

Respecting proxy port configured in rhsm.conf

---

Makefile
etc-conf/subscription-manager-cockpit.desktop.in
setup.py
subscription-manager.spec

* When subman cockpit plugin is installed and subman gui is not
installed, then install subscription-manager-cockpit.desktop
file to /usr/share/application.
* Clicking on icon should just open http://localhost:9090/subscriptions
in default browser
* The .desktop file include one [Desktop Entry], but type is not
Link, because icon with Subscription Manager is not displayed
in Gnome 3. Thus type is Application and URL is opened using
xdg-open. This should open URL with default web browser on all
desktop environments following freedesktop.org specification.

ENT-447 Create .desktop file that opens web page with our cockpit plugin

---

Makefile
scripts/autobuild_updates_img.sh
src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py
src/rhsmlib/facts/hwprobe.py
vagrant/roles/pxe-server/tasks/main.yml

* Fixed instalation of ga_impls. It is installed to
/usr/lib64/... and not to /usr/lib/python/... The Anaconda
wasn't able to display our Addon for this reason.
* Fixed some typo in comments
* Temporary display our Addon on ProgressHub (second screen).
It is necessary to do so, because Anaconda skips SummaryHub
quicky (first screen) due to loading all required options
from kickstart file (in our testing environment). We could
move our Addon back to SummaryHub, when this
https://bugzilla.redhat.com/show_bug.cgi?id=1584160
is implemented in Anaconda.
* Replaces log.warn with log.warning in hwprobe.py, because
log.warn is marked as deprecated (lot of warnings in
/tmp/anaconda.log)
* Disabled SELinux on PXE server, because vsftpd wasn't able to
provide updates.img (this file has became too …

ENT-169 Get Initial Setup Addon to run during installation in Vagrant

---

etc-conf/subscription-manager.completion.sh
man/subscription-manager.8
src/subscription_manager/managercli.py

- https://bugzilla.redhat.com/show_bug.cgi?id=1568609
- help message now includes "...only used with --available"
- --after now exists in subscription-manager man page list options
- name is still --after, not --afterdate

1568609: Updated man page for --after list option

---

subscription-manager.spec

This updates the license of the subscription-manager-cockpit-plugin to be GPLv2.

Update the license of the subman-cockpit-plugin to GPLv2

---

setup.py
test-requirements.txt
test/test_format_time.py

Looks to no longer be necessary.
See #882
It looks like when the tests were changed to use a mocked tz, the local
time no longer impacts tests.

Remove freezegun

---

vagrant/roles/subman-devel/tasks/main.yml
vagrant/vagrant.yml

Prior to this PR, running `vagrant up` on fedora 28 could result in false unit test failures involving missing locales or X11 initialization failure.
The glibc-common bits are to solve the locale issue (thanks for the fix JC!).
The Xauth issue can be reproduced by running `vagrant up` twice. This causes the /home/vagrant/.Xauthority file to be modified to be owned by root:root. This causes the vagrant user to be unable to touch this file.
The fix was to ensure the /home/vagrant/.Xauthority file exists prior to attempting to make the symbolic link.

Fix up our Centos 7 Vagrant setup

---

src/rhsm/connection.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1510920
* The permission to use is controlled by the server

1510920: Allow access to job cancellation API

---

cockpit/src/subscriptions-client.js
cockpit/src/subscriptions-view.jsx

* Added a "safe call" mechanism that makes the initial dbus calls (entitlementService, configService, productsService) only if the service is available, tries to restart the rhsm service if possible, and otherwise failing gracefully.
* Added new UI curtain that provides a meaningful message and advice to the end user.
* Re-added utility method statusUpdateFailed that was accidentally deleted.

1553266: When d-bus methods are unavailable, show appropriate message (ENT-576)

---

setup.py
subscription-manager.spec

- When subman cockpit plugin is installed, then icons has to be
installed too.
- When I created #1826, then I tested it on old fedora installation
and these icons were already installed in the system.

ENT-447 Add icons to RPM package for subman cockpit plugin

---

subscription-manager.spec

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1581410
* dnf plugin should be required on Fedora

1581410: ENT-572: subman should require dnf-plugin-subscription-manager

---

etc-conf/dbus/system.d/com.redhat.RHSM1.conf
src/rhsmlib/dbus/constants.py
src/rhsmlib/dbus/objects/consumer.py
src/rhsmlib/dbus/util.py
src/rhsmlib/services/consumer.py
src/subscription_manager/scripts/rhsm_service.py
test/rhsmlib_test/test_consumer.py

* Added new path: `/com/redhat/RHSM1/Consumer`
* Added new interface `com.redhat.RHSM1.Consumer`
* This new interface has new method `GetUuid` and signal
`ConsumerChanged`
* Method requires one string argument with locale and it
returns string with UUID of consumer
* Signal returns integer with status of change
* To test new feature you have to install configuration files:
```console
$ sudo make dbus-install
$ sudo make install-conf
```
* To test new feature start rhsm service using:
```console
$ PYTHONPATH=./src sudo python -m subscription_manager.scripts.rhsm_service
```
* You can view new path using:
```console
$ sudo busctl tree com.redhat.RHSM1`
```
* You can introspec method using:
```console
$ sudo busctl introspect com.redhat.RHSM1 /com/redhat/RHSM1/Consumer
```
* To test getting …

ENT-478 com.redhat.RHSM1.Consumer D-Bus service object

---

src/rhsmlib/dbus/util.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1581777
* When exception is reraised, then it has to be reraised as
instance of new exception in Python 3. It cannot be string.

1581777: Reraise exception properly. ENT-566

---

src/rhsmlib/dbus/objects/products.py
src/rhsmlib/dbus/server.py

- integrated with filesystem watcher so that fired on creation,
deletion, or modification
- watches rhsm.productCertDir in /etc/rhsm/rhsm.conf
- added init_logger to start logging

ENT-476: Add signal InstalledProductsChanged

---

src/rhsmlib/dbus/objects/entitlement.py
src/rhsmlib/services/entitlement.py
src/subscription_manager/managercli.py
test/rhsmlib_test/test_entitlement.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1594733
* When method GetStatus was called with first argument (on_date),
then it could return wrong status.
* Refactored code a little bit. Thus parsing of on_date is
shared between rhsm.service and subscription-manager
* Method get_status was also fixed. Calling GetStatus with
different values of on_date returns correct results.
* Added some unit tests for testing of parsing date.

1594733: Fix GetStatus in com.redhat.RHSM1.Entitlement ENT-641

---

src/subscription_manager/printing_utils.py
src/subscription_manager/unicode_width.py
subscription-manager.spec
test/test_i18n.py

The needed methods are duplicated into subscription-manager to relieve the dependency

Removal of python-kitchen

---

src/rhsmlib/dbus/server.py

Loading the log facilities in module scope causes unicode decode errors
in the HandleExceptionTests class when the TestFactsDBusObject is loaded
after it.  Most likely because TestFactsDBusObject is importing the
rhsmlib.dbus.server module and causing some interference in how the
character encoding is set.
---
Test by running
```
nosetests --randomly-seed=1506092144 test.test_managercli test.rhsmlib_test.test_facts
```

Fix indeterminate unit test failure.

---

setup.py

This makes the package more portable, as `pip install --user` will work.
This doesn't affect `make install`, as the `Makefile` always passes an
argument to setup.py.

Do not install subman-gui from setup.py by default

---

subscription-manager.spec

- Updates our dependencies for GTK3 in the python3 case to point to the right package. Apparently the '3' in pygobject3 refers to the gtk version not python version.
- The relevant packages seem to be available for Suse / SLES as well (AFAICT).

1512944: Fix up remaining python2 deps ENT-724

---

syspurpose/src/syspurpose/cli.py
syspurpose/src/syspurpose/files.py
syspurpose/test/syspurpose/test_syspurposefiles.py

- 'add' will now not override an existing value, if that turns out to be scalar (added by the 'set' command), but it will be maintained and added in a list along with the newly added value.
- 'remove' will now unset the current value, if that turns out to be scalar instead of being contained in a list.

ENT-590 Enhanced SyspurposeStore add/remove operations

---

syspurpose/src/syspurpose/cli.py
syspurpose/src/syspurpose/files.py
syspurpose/src/syspurpose/utils.py
syspurpose/test/syspurpose/test_syspurposefiles.py
syspurpose/test/syspurpose/test_utils.py

- All syspurpose operations now support UTF-8
- syspurpose.json now has user-friendly indentation

ENT-584 syspurpose UTF-8 support & better formatting

---

src/subscription_manager/managercli.py
src/subscription_manager/syspurposelib.py
test/test_managercli.py

* Part of RFE: https://bugzilla.redhat.com/show_bug.cgi?id=1602056
* Added subcommand role. It can have two mutually exclusive
options `--set` and `--unset` used for setting and unsetting
syspurpose role.
* When role subcommand is used without any option, then current
syspurpose role is printed
* TODO: proxy options are not used, because syspurpose does not
support it yet.

1602056: Added role subcommand ENT-719

---

src/subscription_manager/managercli.py
syspurpose/src/syspurpose/files.py
syspurpose/test/syspurpose/test_syspurposefiles.py

* When addons in syspurpose.json are null and then you want to
add (not set) new value to addons, then syspurpose or sub-man
command crashed. This issue is fixed
* Add-ons could be scalar value (e.g. "foo"). Priting such value
in subman returned: 'f', 'o', 'o'

Two simple fixes for syspurpose (addons)

---

syspurpose/src/syspurpose/files.py

We were raising the wrong thing 'e' at this point, it should be 'ioerr'.

Raise ioerr when necessary during sp read

---

src/subscription_manager/action_client.py
src/subscription_manager/scripts/rhsmcertd_worker.py
src/subscription_manager/syspurposelib.py
src/subscription_manager/utils.py
test/test_certmgr.py
test/test_syspurposelib.py

Adds the necessary pieces to allow the system purpose values to be synced
with the server the system is registered to on each run on rhsmcertd as well
as any run of ReposCommand or AttachCommand.
* Adds SyspurposeSyncActionCommand
- This is the ActionCommand responsible for syncing the local system purpose
values with the latest available on the server.
It performs a three-way-merge between the contents of USER_SYSPURPOSE file
and the remote values from the server with a base of the last cached
values.
* Adds SyspurposeSyncActionReport for compatibility with the existing
- ActionClient expectations. Used to report expections that occur
during the sync.
* Adds SyspurposeSyncActionInvoker
- This allows the SyspurposeSyncActionCommand to be performed
for both the regular ActionClient and the …

ENT-715 Sync syspurpose with server

---

src/rhsm/connection.py
src/subscription_manager/managercli.py
syspurpose/src/syspurpose/cli.py
syspurpose/src/syspurpose/files.py
syspurpose/src/syspurpose/sync.py
syspurpose/src/syspurpose/utils.py
syspurpose/test/syspurpose/base.py
syspurpose/test/syspurpose/test_syspurpose_sync.py
test/test_registration.py

* Added new module sync to package syspurpose. This module
includes new class SyspurposeSync
* Class SyspurposeSync is created only in situation, when it is
possible to import rhsm module. Otherwise exception is raised.
* Method for sending new syspurpose is implemented and
behavior of updateConsumer was modified a little to be possible
to reduce list od Add-ons.
* It is possible to set and unset role, sla, usage and addons.
It is also possible to add new or remove existing values to/from
list of Add-ons
* Fixed a little bit sending of syspurpose during registration.
* Implemented several unit tests.

ENT-717: Syncing of syspurpose store with candlepin

---

src/rhsmlib/__init__.py
src/subscription_manager/ga_loader.py
src/subscription_manager/plugins.py
test/rhsmlib_test/test_import_class.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1609048
* Module imp is deprecated and it can be replaced with
importlib. The imp is used for Python 2.7 in plugins.py,
because the implementation of importlib in Python 2.7
is limited.
* Added one unit test for import_class method.

1609048: Replacement of imp module with importlib; ENT-758

---

syspurpose/src/syspurpose/sync.py
syspurpose/test/syspurpose/test_syspurpose_sync.py

* Caused by #1887 (renaming 'usage_type' to 'usage').

Fix synchronization of usage with candlepin

---

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py
subscription-manager.spec

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1596294
* It was necessary to implement own should_run() method to be
sure that RHSM Spoke is visible in Anaconda and Initial Setup
* Moved icons to rhsm-gtk, because icons are required by
subman-gui as well by RHSM Spoke

1596294: Fix displayin RHSM Spoke in Initial Setup, ENT-753

---

src/subscription_manager/syspurposelib.py

Fixes a simple typo which resulted in inaccurate diff messages when a key of syspurpose changes.
Now the old and new values will be used to form the appropriate message.

Display both new and old value in syspurpose diff message

---

src/dnf-plugins/product-id.py
src/plugins/product-id.py
test/test_yum_content_plugin.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1613968
* Temporary directory was deleted too early (with statement)
* It is necessary to refresh list of installed packages to get
new repository in list of active repositories
* Replaced warn with warning and fixed one unit test

1613968: DNF product-id plugin can install product cert; ENT-789

---

README.md
src/subscription_manager/managercli.py
src/subscription_manager/managerlib.py
src/subscription_manager/syspurposelib.py
test/gui/test_registrationgui.py
test/stubs.py
test/test_managercli.py
test/test_syspurposelib.py

This revises the Role, Usage, Addons, and ServiceLevel Commands.
Each of these now perform the sync action and display a message with a course of action if the result is not as expected.
The way to get this message to show up is in the reproducer steps in [This bug](https://bugzilla.redhat.com/show_bug.cgi?id=1615404)

Sync the syspurpose on runs of each relevant command

---

src/subscription_manager/dbus_interface.py

The log message about there being any sort of dbus exception was already at the DEBUG level. This logs the applicable traceback at the DEBUG level as well instead of at the exception level (so as not to unnecessarily worry folks).

1600694: Log dbus exception tracebacks at the debug level

---

src/subscription_manager/managercli.py

Noticed this while reviewing some test cases with John. The Service-level command did not seem to be outputting the correct messages as it never set the name of the attribute it was manipulating through the attr keyword arg.
You can see these failures yourself just as simply as running the Service-level command. The output (in the event that the option is unset) will be similar to "None not set" instead of "service_level_agreement not set".

Use the "service_level_agreement" attribute for the SlaCommand

---

Makefile
etc-conf/rhsm.conf
man/rhsm.conf.5
setup.py
src/subscription_manager/gui/managergui.py
src/subscription_manager/managercli.py
src/subscription_manager/migrate/migrate.py
src/subscription_manager/repolib.py
src/subscription_manager/syspurposelib.py
src/subscription_manager/version.py
subscription-manager.spec
test/test_repolib.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1623262
* subscription-manager can autoenable yum as well dnf plugins
* Modified unit tests and added one unit test to be dnf specific
* Removed `use_dnf` from `version.py`.

1623262: Make automatic enablement of yum plugins working again; ENT-820

---

.tito/cockpit-build.sh

We have noticed twice now, at least, that the yarn cache can get into a
bad state. Once, @cnsnyder ran out of disk space, and the cache ended up
with empty directories where there should have been node modules.
`yarn cache clean` ensures we don't run into these issues in the case
that the yarn cache is bad.

For tito build, clean the yarn cache

---

src/rhsm/connection.py
src/rhsm/profile.py
src/subscription_manager/cache.py
test/test_cache.py

* rhsmcertd did send profile containing list of installed RPMs, but it
didn't send some another information e.g. list of enabled repositories
and other tools had to be used for this purpose
* This commit adds functionality that allows to send list of dictionaries
containing desired data
* ProfileManager can be backward compatible and it can report only list
of installed packages, when candlepin server does not have capability
"combined reporting"
* Added two blind classes: EnabledReposProfile and ModuleProfile.
Functionality for these classes will be added in next commits.
* Fixed several unit tests

Use Combined Profile reporting; ENT-832

---

subscription-manager.spec

We had an issue where the package was removed from the rhel 8 build. It was
reinstated, but this will ensure that the need is documented and enforced.

Explict requires added for package we use directly

---

src/rhsm/profile.py
test/test_cache.py

* Combined profile contain list of enabled repositories
* Part of code was copy pasted from Katello:
https://github.com/Katello/katello-host-tools/blob/master/src/katello/enabled_report.py
* Code was modified: e.g. our iniparse is used for parsin repo file.
* Making this PR against my feature branch ATM. #1915 is blocking this PR.

Added list of enabled repos to combined profile; ENT-833

---

src/rhsm/connection.py
src/subscription_manager/release.py
test/fixture.py
test/rhsm/unit/connection-tests.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1607955
* When all entitlement certificates and key are loaded to SSL
context, then only last loaded pair of certificate and key
is used during TLS handshake
* We have to try all entitlement certificates until we get 200
status from CDN server (we try to do several connections to
server)
* It is possible to provide limited list of cert-key pairs to
method _request
* Fixed two unit tests

1607955: Try to use all entitlement certs for connection with CDN; ENT-757

---

subscription-manager.spec

* Some *.py files were not touched before byte compiling. This
issue was Python3 specific.

Fix RPMDiff issue with multilib

---

syspurpose/src/syspurpose/cli.py

This is an alternative to #1925. It also prints the help when there are no args provided to the syspurpose cli tool.

1615944: Show help when no args are provided

---

src/rhsmlib/facts/dmiinfo.py

The message "SMBIOS implementations newer than version 2.7 are not fully
supported by this version of dmidecode." is benign: it only means that
information that was added in later revisions of SMBIOS 2.x won't be
accessible via the python dmidecode library.
The real issue was our handling of bytes/strings not working properly in
Python 3.
Easiest was to see the difference is `sudo subscription-manager facts`
on Fedora (can test this change via `sudo PYTHONPATH=./src
subscription-manager facts`).

1614943: Fix bytes/unicode handling of dmi data ENT-801

---

syspurpose/src/syspurpose/sync.py

Now when the syspurpose tool attempts to sync the syspurpose with CP, it checks that CP has the "syspurpose" capability. If it does not it outputs a suitable error message.

1633575: Update error message when syspurpose is not supported by server

---

src/subscription_manager/managercli.py
src/subscription_manager/syspurposelib.py

To make subman versions that have syspurpose compatible with older
candlepins, when setting the SLA on the server, dont check the
syspurpose capability, since SLA pre-dates the syspurpose feature.

1632384: Sync SLA regardless of capability (ENT-912):

---

syspurpose/src/syspurpose/files.py
syspurpose/src/syspurpose/utils.py

- Changed the behavior of the SyspurposeStore to no longer suppress
data malformation errors in the backing JSON data store. If a
ValueError occurs, an error will be generated via the system_exit
call

[M] syspurpose no longer supresses JSON malformation errors (ENT-907)

---

src/subscription_manager/managercli.py
src/subscription_manager/utils.py
syspurpose/src/syspurpose/files.py
syspurpose/src/syspurpose/sync.py
syspurpose/test/syspurpose/test_syspurpose_sync.py
syspurpose/test/syspurpose/test_syspurposefiles.py

- The unset command now removes keys from the backing dictionary
rather than setting the values to an empty value
- syspurpose syncronization now considers missing keys and null
valued keys to be the same
- The unset command now makes an exception for the
service_level_agreement field to retain an empty string rather
than None or unsetting the key entirely, for consistency with
its non-standard behavior in Candlepin
- The remove command now calls into unset for scalar values to
retain consistent behavior
- syspurposelib has been updated with standardized behavior for
some of its utility methods
- Standardized some of the syspurpose command behavior within
subscription manager
- Updated a few tests in accordance with the new behavior

[M] Updated how syspurpose handles unsetting values (ENT-902)

---

src/subscription_manager/i18n.py

Ended up being fairly straightforward.
This sets the language used with our Locale class to that read from the environment. This can still be overwritten by the dbus interfaces.

1616366: Use LANG from environment (ENT-803)

---

src/subscription_manager/managercli.py

Ignore the failed check for system registration in the case the user is trying to set or unset the service-level attribute.

1632248: User should be able to set/unset while not registered [ENT-897]

---

syspurpose/src/syspurpose/sync.py
syspurpose/test/syspurpose/test_syspurpose_sync.py

Was previously "Unable to read consumer certificate" which may confuse
users.

1623390: Fix unregistered messaging in syspurpose ENT-875

---

scripts/localhost.yml
scripts/setup_local_devel_environment.sh

Uses the same role as the Vagrant environment.
The role itself will require some related changes. (see candlepin/ansible-role-subman-devel#4)

Add scripts to setup local development environment

---

src/subscription_manager/managercli.py

The prior method assumed the locale was en-us or similar. The new form of displaying the error message does not work when the locale is anything else.
For an example try this reproducer:
(On a system that is not yet registered)
1) LANG=de_DE.UTF-8 subscription-manager service-level --list --org foobar --user <SOME_VALID_USERNAME> --pass <SOME_VALID_PASSWORD>
Observe that the http error code is still displayed in the translated resulting message.
Compare this to running the command as follows (with LANG set to en_US.UTF-8):
2) LANG=en_US.UTF-8 subscription-manager service-level --list --org foobar --user <SOME_VALID_USERNAME> --pass <SOME_VALID_PASSWORD>

1636381: Fix up our detection of missing org for service-level list

---

src/rhsm/profile.py

Previously, if the vendor contains utf8 characters, the rpm
comparison will fail.

1639086: Fix vendor comparison

---

src/rhsm/profile.py

This commit fixes an issue where the installed profiles was selected for
all modules without checking on the stream information. This commit will curate installed_profiles only if the module stream is enabled.

Module MD - Show installed profiles only for enabled modules

---

src/dnf-plugins/subscription-manager.py
src/plugins/subscription-manager.py
src/zypper/services/rhsm

For the yum, dnf, and zypper subscription-manager plugins, do not attempt to update the entitlement certificates on the system if it appears that we are in a container.
Without this, running yum repolist - or equivalent in other package managers - will cause all entitlement certificates to be removed from within the container causing loss of access to all repos granted thereby when pointing to a Satellite.

1645205: Do not update ent certs inside containers

---

src/subscription_manager/i18n.py
test/test_i18n.py

Just a quick fix. No longer call Locale.set if the LANG env variable is unset (causes unexpected behaviour).

1642271: Do not set a None lang

---

Makefile

Some tooling (mock specifically), touches /etc/os-release, so it's
unsafe to assume that its absence implies anything.

Detect sles11 via /etc/SuSE-release

---

src/rhsm/profile.py
test/test_cache.py

Prior to this commit
If there are duplicate repos in a list, subman will send duplicate
modules over the wire. 
This commit fixes that by uniquifying based on
"name", "stream", "version", "context", "arch"

Uniquify the module list

---

src/dnf-plugins/product-id/product-id.c
src/dnf-plugins/product-id/productdb.h
src/dnf-plugins/product-id/util.c
src/dnf-plugins/product-id/util.h

* When some directories does not exist, then create these
direcotiries including parent all parent directories.
* Do not print debug messages to productid.log, when
CMAKE_BUILD_TYPE is set to Release
* Changed type of some log messages
* Fixed bug that caused crashes of PackageKit daemon.

Small fixes of libdnf product-id plugin

---

src/dnf-plugins/product-id/CMakeLists.txt
subscription-manager.spec

- Add json-c dependencies to spec file
- Use arch-specific lib directory for CMake build

Fix builds of product-id plugin

---

syspurpose/src/syspurpose/files.py
syspurpose/src/syspurpose/utils.py
syspurpose/test/syspurpose/test_utils.py

* Look at this document about Python 3.7:
https://docs.python.org/3/whatsnew/3.7.html
* Several undocumented internal imports were removed. One example
is that `os.errno` is no longer available; use `import errno`
directly instead.
* Note: `errno` module is available in Python 2.7

Fix several issues with os.errno

---

Makefile

Currently dbus-python does not install egg metadata if installed via
RPM. As a result, setuptools entrypoints (i.e. all our bin files) fail
to discover the dbus-python package and refuse to start.
This hack simply drops the line afterwards from requires.txt

1651669: Remove dbus-python from egg requirements

---

src/dnf-plugins/upload-profile.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1650323
* This commit adds new dnf plugin. This plugin adds new
dnf subcommand called "upload-profile". It could be used
for uploading combined profile.

1650323: dnf subcommand for profile uploads; ENT-984

---

src/dnf-plugins/product-id/product-id.c
src/dnf-plugins/product-id/product-id.h
src/dnf-plugins/product-id/test-product-id.c

* The API of libdnf is going to be changed. See this PR:
https://github.com/rpm-software-management/libdnf/pull/642
* Our plugin was tested with development version of libdnf
and PackageKit linked against this development version
of libdnf. Microdnf was tested with development version
of libdnf too.
* Fixed some unit tests to use new API.

Use new API of libdnf to be able to work with PackageKit

---

src/dnf-plugins/product-id/CMakeLists.txt

* When cmake -DCMAKE_BUILD_TYPE="Release" is used, then we have
to include debug information in product-id.so to be included
in debuginfo RPM package.

Bug fix: include debuginfo in RPM with debuginfo information

---

man/rhsm.conf.5

This adds a short description on how to update (or remove) a local selinux policy to allow rhsmcertd to work after setting the rhsm.conf proxy_port value to anything aside from 3128.

1642888: Add semanage advice on setting non-default proxy_port; ENT-840

---

src/subscription_manager/managercli.py
src/subscription_manager/syspurposelib.py

This uses the old method of setting the service-level when the server does not have the "syspurpose" capability. it was due to a failure of setting that the --show option also appeared to be broken.
This can be tested by removing the "syspurpose" capability from candlepin and registering to that instance then running `subscription-manager service-level --set Premium` (with no value previously set).
After that `subscription-manager service-level --show` should show "Premium".

1638153: Restore service-level command for older servers

---

src/subscription_manager/cache.py

- When the server is unreachable and the syspurpose status cache
is missing, then don't traceback, but show status as 'Unknown'.
- Also, when the server is reachable, but the system is unregisted,
show the 'Unknown' syspurpose status, but don't cache it.

1633380: show syspurpose status Unknown when cache missing [ENT-1009]

---

etc-conf/rhsm.conf
man/rhsm.conf.5

This adds a rhsm.conf.5 man page entry for the new disable option in the rhsmcertd section.
In addition it adds an example/default for the disable option to the rhsm.conf template/default file.

1654873: Add man entry for rhsmcertd.disable

---

man/rhsm.conf.5

This adds an entry to the rhsm.conf.5 man page detailing the use of package_profile_on_trans.

1654868: Add man page docs of the package_profile_on_trans option

---

src/subscription_manager/managercli.py
syspurpose/src/syspurpose/files.py
syspurpose/test/syspurpose/test_syspurposefiles.py
test/test_registration.py

There was one case that was left out of the last PR for this BZ, that of registration.
If there is no syspurpose defined for a system, and a user registers and then attempts to set some attribute of syspurpose, they are met with an incorrect message warning about conflicting changes made serverside.
This PR updates the local and cached syspurpose with the values returned from the server (as they were already submitted during registration). This prevents the issue and ensures the existing values from local (or the defaulted values from the server) do not conflict with one another.

1633264: Ensure we sync syspurpose on register

---

src/rhsmlib/file_monitor.py
test/rhsmlib_test/test_file_monitor.py

- Now, the ConfigChanged event will be sent not only when a monitored
file is edited in place, but also when the whole file is replaced
with another who is moved/renamed to the same location & name.

1625214: send ConfigChanged event when file replaced [ENT-838]

---

src/dnf-plugins/product-id.py
src/subscription_manager/productid.py

* When new DNF API is available then use it.
* Use cache file to store productid certificates, then dnf API doesn't load productid from repository nor cache. For this reason it is necessary to use own cache.
* Refactoring of reading cache files

Use new API of DNF

---

src/rhsm/connection.py
src/subscription_manager/managercli.py
test/rhsm/unit/connection_tests.py

- When running service-level --list with invalid credentials,
dont traceback, but show the proper error to the user.
- This is handled when either the --serverurl, or --username
and --password options are used.

1636852 & 1646384: better auth handling when listing service-levels [ENT-922 & ENT-991]

---

src/dnf-plugins/subscription-manager.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1643128
* `config()` is name of hook.

1643128: Do not execute subscription-manager dnf plugin twice; ENT-987

---

src/dnf-plugins/product-id.py
src/subscription_manager/productid.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1661219
* This bug fix is not specific for DNF, but it fixes same issue
for YUM too.
* When repository in redhat.repo is disabled using:
`subscription-manager repos --disable=repo-id`
then corresponding product certificate should not be removed
* When cached certificate for given repository is "null", then
do not try to create new certificate from None

1661219: Do not delete product certs for disabled repos; ENT-1034

---

src/subscription_manager/managercli.py
test/test_managercli.py

When listing repos, prior to this PR, we were treating anything that wasn't '0' as if it were enabled. This PR expands that list to include items whose enabled value are "false".

1656598: Treat false as disabled when listing repos

---

etc-conf/syspurpose/valid_fields.json

Removes the "Red Hat Enterprise Linux Client/Desktop" option from the vaild_fields.json file installed with syspurpose.

1663254: Remove "Red Hat Enterprise Linux Client/Desktop" role option

---

src/subscription_manager/repofile.py
src/subscription_manager/repolib.py
test/test_repolib.py

Thanks long-lived instances of the RepoFile class, subscription-manager
was reading the underlying file twice.  The duplicate reads resulted in
the number of comment nodes doubling in the instance and then getting
written out when it was time to save the file.  Every write of the
redhat.repo file culminated in a doubling of the comment nodes leading
to an exponential growth in file size.
This patch fixes the issue but instantiating the RepoFile class late
into the process and then letting the object get GCed at the end of the
perform method in RepoUpdateActionCommand.

1658409: Stop redhat.repo from growing exponentially

---

etc-conf/subscription-manager.completion.sh
etc-conf/syspurpose.completion.sh

A few cases were not correct according to https://bugzilla.redhat.com/show_bug.cgi?id=1624859#c2
This simplifies the bash completion for syspurpose tool and fixes those cases that were broken for subscription-manager.

1624859: Simplify syspurpose bash completion

---

src/subscription_manager/managercli.py

We forgot to sync syspurpose on execution of the status command. This PR does that.

1655083: Sync syspurpose on status command

---

src/rhsmlib/services/syspurpose.py
test/test_managercli.py

- Now, the new syspurpose statuses 'matched', 'mismatched' and
'not specified' returned by the server will also be handled and shown.
- In addition, for backwards compatibility, if the server returns one of
'valid', 'invalid' or 'partial' status, those will still be handled and
shown too by subscription-manager.

1652870: handle new syspurpose status states [ENT-1011]

---

Makefile
subscription-manager.spec

When using dnf we do not need to include the configuration file for the no longer included search-disabled-repos plugin.

1634033: do not install conf file for non-existant dnf plugin

---

src/subscription_manager/managercli.py

When Candlepin doesn't have a 'syspurpose' capability, subman uses different branch of code to set service level. This code doesn't print the result of the operation.
- Add output message for the successful setting of service level
- Add output message for the successful unsetting of service level

1661414: No message display when set service level by subscription manager[ENT-1106]

---

Vagrantfile
src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py
vagrant/roles/pxe-server/defaults/main.yml
vagrant/roles/pxe-server/tasks/main.yml
vagrant/roles/pxe-server/templates/ifcfg-eth1.j2
vagrant/roles/pxe-server/templates/ks_fedora29.cfg.j2

- Also, now the RHSM spoke in anaconda initializes and logs
in the rhsm.log.

ENT-978: Upgrade pxe-server/client to fedora29

---

src/subscription_manager/gui/registergui.py

- Registering through initial-setup will now persist & use the syspurpose
values that were set during the anaconda installation process.

1668152: take into account syspurpose during initial-setup [ENT-1109]

---

scripts/autobuild_updates_img.sh
scripts/build_updates_img.sh
vagrant/roles/pxe-server/defaults/main.yml
vagrant/roles/pxe-server/tasks/main.yml
vagrant/roles/pxe-server/templates/ks_fedora29.cfg.j2

* I had to do following updates during my testing of #2018
* Subman requires more modules on Fedora 29 (ethtool)
* Updated build script to copy Python eggs
* Stop autobuild service during provisioning, because
command: `vagrant provision pxe-server` did not work properly
* Clean all *.pyc file, because `vagrant rsync pxe-server`
copy all files to VM. *.pyc files in ./build directory can
break bulding of updates.img

More reliable PXE server and PXE client; ENT-1121

---

man/rhsm.conf.5

This adds a single line to the description of the report_package_profile entry of the rhsm.conf man page clarifying that options interaction and governance over the behaviour of the "dnf uploadprofile" command.

1666512: Add some details on dnf uploadprofile to rhsm.conf man page

---

src/subscription_manager/i18n.py
src/subscription_manager/managercli.py
src/subscription_manager/repofile.py
test/test_cache.py
test/test_managercli.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1668947
* We should set 'enable_metadata' to "0" for disabled repositories.
Otherwise PackageKit tries to download metadata for all
repositories.

1668947: set enable_metadata to 0 for disabled repos; ENT-1146

---

src/dnf-plugins/product-id/CMakeLists.txt
src/dnf-plugins/product-id/product-id.c
src/dnf-plugins/product-id/product-id.h
src/dnf-plugins/product-id/test-product-id.c

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1633216#c15
* When RHEL production repository is used, then any dnf client
has to use client certificate to authentication. We used
librepo for downloading productid certificate in new connection,
but this connection didn't use client certificate for
authentication.
* New librepo API introduced in this PR:
https://github.com/rpm-software-management/libdnf/pull/652
is used for downloading productid certificate
* New API also provides decompresing of any downloaded file
including productid certificate. We use benefits of thi API too.
* Removed dependency on zlib.
* Several unit tests were modified.

1633216: Use new libdnf API to reuse connection to repo; ENT-1111

---

src/subscription_manager/cache.py

Our previous attempt to solve this broke one of our dnf/yum usecases (see [this](https://bugzilla.redhat.com/show_bug.cgi?id=1650157#c13))
This should allow the following:
Only report on the transaction hook of dnf actions when the report_package_profile setting *and* the package_profile_on_trans setting are set to 1. Should either of them be set to 0 this should not report package profile info.
With the previous fix, if report_package_profile was set to 1 and we were not forcing the package profile upload subman would not report any package profile info.

1666516: Allow reporting of profile info on dnf transactions

---

src/dnf-plugins/product-id/product-id.c

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1673838

1673838: Set trailing character '\0' at the end of cert content

---

cockpit/src/subscriptions-client.js

- Now the syspurpose status in the cockpit UI will get updated
every time either the syspurpose.json changed, our subscriptions
changed, or the system got registered/unregistered.

1665409: Update syspurpose status in cockpit addon; ENT-1096

---

etc-conf/rhsm.conf
man/rhsm.conf.5
src/rhsm/config.py
src/subscription_manager/repofile.py
test/test_repolib.py

This adds a new proxy_scheme option to rhsm.conf.
It allows users to specify what scheme should be used for the proxy url when writing repo definitions. It defaults to http (as that appears to be most common and will solve this bug).

1654531: Add proxy_scheme to rhsm.conf

---

src/subscription_manager/migrate/migrate.py

This uses regex to find the likely RHEL version from /etc/redhat-release. Should be more flexible than earlier iterations.
As we cannot proceed very far in the migration process if we can't determine the release, we exit on error with the regex.

1655778: Increase RHEL major version detection reliability

---

src/subscription_manager/managercli.py

subscription-manager currently creates the repo file if an entitlement
cert is imported on an offline system.  This change enables selecting
which of those repos are enabled without having to pass --enablerepo
to every yum invocation.  Should also allow use of the rhsm_repository
ansible module on these offline systems.

allow offline repo management

---

src/rhsmlib/services/register.py
src/subscription_manager/managercli.py
test/rhsmlib_test/test_register.py
test/test_registration.py

This moves our syspurpose reading and syncing done for registration down into the register service.
This consequently causes syspurpose info not to be lost on registration using cockpit.

1673973: Read syspurpose on register using cockpit

---

src/rhsmlib/dbus/objects/attach.py
src/rhsmlib/services/register.py

Using a singleton for the SyncedStore (as the get_sys_purpose_store method does) causes us to hold onto the old consumer uuid when unregistered and the dbus service is still running. This causes nasty exceptions to surface on cockpit when registering and unregistering repeatedly.
The proposed fix is to create the SyncedStore objects with the correct uep / consumer_uuid as needed in the dbus usages of SyncedStore.
There is one additional issue that was uncovered for this bug by QE. The current implementation of our cockpit pieces overrides the SLA set everytime regardless of the syncing logic put in. The prior PR addressed the issue for all aspects of syspurpose aside from SLA.
Update: This PR now ignores the '' passed in to the attach service from cockpit.

1673973: Do not override the user SLA syspurpose on registration using cockpit

---

src/rhsmlib/services/register.py
syspurpose/src/syspurpose/files.py
syspurpose/test/syspurpose/test_syspurposefiles.py
test/rhsmlib_test/test_register.py

As we have no way of setting the value in CP to null (in order to reset) we need to make sure to always send the empty string on register AND on syncing for reset. This will work either in the case that CP continues to actually store those values (the empty strings) OR CP resets those attributes to null when having received the empty string.
:man_facepalming:

1666845: Always submit empty string for reset

---

src/dnf-plugins/product-id/product-id.c

The issue can be reproduced via the steps in this comment: https://bugzilla.redhat.com/show_bug.cgi?id=1685037#c11
Before those steps install the following (as it is required for the reproducer): `dnf install createrepo_c rpm-build PackageKit`

1685037: Ignore null repos when running using packagekit

---

src/rhsmlib/services/syspurpose.py
src/subscription_manager/cert_sorter.py

When golden ticket is on for the org, The overall status and the syspurpose status will not be calculated. Marked as disabled in the output.

1591704: Disable status when golden ticket is in play

---

etc-conf/plugin/subscription-manager.conf
src/plugins/subscription-manager.py

In case the host repositories are managed by the subscription-manager
(e.g. with katello), it is expected that only the repositories activated
by the subscription-manager are enabled. This is even more important on
CentOS / Fedora distribution in which the basic repo files exists.

Allow subman yum plugin to disable all system repo

---

src/plugins/subscription-manager.py
src/subscription_manager/repolib.py

* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1621275
* Added several hooks to minimize communication with candlepin
server.
* Do not try to communicate with candlepin server, when "local
yum commands are executed (e.g. yum --help, list, check,
history, etc.).
* The presence of identity and entitlements certificates on
the disk of host is checked in postconfig hook
* Updating of redhat.repo is done in prereposetup_hook
* When rhsm.full_refresh_on_yum == 0, then the plugin doesn't
communicate with candlepin server at all, because it wasn't
necessary at all.
* Small refactoring of code

1621275: Less communication with candlepin server from sub-man plugin; ENT-923

---

.tito/cockpit-build.sh
.tito/lib/rhsmbuild.py
subscription-manager.spec

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1657171
* Bug specific for SLES12 has been already fixed
* Bug specific for SLES11 is fixed in this commit
* Side effect of this PR: it is possible to build rpm on SLES
using tito

1657171: Bug fix of .spec file specific for SuSE; ENT-1056

---

src/plugins/subscription-manager.py
src/subscription_manager/managercli.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1591315
* Do not print confusing warnings, when golden ticket is used.

1591315: Fewer warning messages when golden ticket is used; ENT-671

---

src/rhsm/m2cryptohttp.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1637090
* RHEL6 still uses m2crypto wrapper, but we decided to not use
m2crypto wrapper in RHEL7 and Fedora23. Thus we had to fix
abscence of "Host" header in connection.py. See e.g. this
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1507158
* Previous bug fixes caused this issue.
* It is still possible to use m2crypto wrapper on RHEL7, when
environment variable RHSM_USE_M2CRYPTO=1 is set, but this
approach is not supported with Python3 (different API).

1637090: Do not send Host header twice, when m2crypto is used; ENT-1100

---

src/subscription_manager/managercli.py
src/subscription_manager/repofile.py
test/test_managercli.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1696428
* This bug fix use right option "enabled_metadata" and not
"enable_metadata".
* You can check that PackageKit does not download metadata for
disabled repositories by observing content of directory:
/var/cache/PackageKit/<release_version>/metadata/

1696428: use enabled_metadata = 0 for disabled repositories

---

syspurpose/src/syspurpose/files.py

When installing a new RHEL 8 system with anaconda, if you do not configure any network at all (but still set some syspurpose info), on reboot the syspurpose info is lost.
In addition, when the network is unreachable, all related syspurpose commands fail with a traceback (in both subman and syspurpose). This PR should fix these cases.

1698645: Ensure we use local syspurpose when there are network issues

---

subscription-manager.spec

On RHEL 7, python2-librepo is called python-librepo.

1698468: require python-librepo for rhel 7

---

src/subscription_manager/repofile.py

The `section` function from the `AptRepoFile` class is broken.
This causes problems for the Debian version of the subscription-manager.
For example `subscription-manager refresh` won't update `/etc/apt/sources.list.d/rhsm.sources` at all.
This breaks all `apt` actions since the repos are associated with the wrong certificates.

Fix broken AptRepoFile section function

---

src/dnf-plugins/product-id/product-id.c
src/dnf-plugins/product-id/product-id.h
src/dnf-plugins/product-id/test-product-id.c

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1681171
* This bug fix prevents installing two product certificates,
when two repositories provide same RPM, but RPM is downloaded
only from one of them. The product-id certificate installs
only one certificate from the certificate that is actually
used.
* NOTE: Behavior of yum product-id is different. It installs
both certificates, but installing only one certificate is
IMHO correct behavior.

1681171: Install only one prod cert, when RPM is available in more repos.

---

subscription-manager.spec

It is no longer necessary to default to building the python2 version of subscription-manager-rhsm on later versions of RHEL.

1701406: Do not build subman-rhsm with python2 on later versions of rhel

---

subscription-manager.spec

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1657173
* Replace `libexec` with `lib` on SLES during creation of RPM

1657173: Install cron service properly on SLES; ENT-1250

---

src/rhsm/connection.py
src/subscription_manager/capabilities.py
src/subscription_manager/repofile.py
src/subscription_manager/repolib.py
test/stubs.py
test/test_capabilities.py
test/test_managercli.py
test/test_repolib.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1700445
* This issue was cauded by #2051
* To avoid REST API calls with same results, results are saved to
cache file. Example of such REST API call is "/".
* New file: capabilities.py
* TODO: use it on more places

1700445: Do not disabled repos in redhat.repo; ENT-1261

---

src/rhsm/connection.py
src/rhsm/utils.py
src/subscription_manager/gui/managergui.py

If the RHSM server subscription-manager is connecting to is covered by
the server.no_proxy setting, do not perform a check on the availability
of the proxy.
---
No tests, but I didn't see any serious tests for the MainWindow class anyway.  Not ideal, but given this bug is a priority and there's no foundation to start on, I chose to dispense with the tests.  I could be persuaded otherwise though.  Let me know your thoughts.

1699345: Do not perform proxy check under some circumstances.

---

src/subscription_manager/repofile.py
test/test_repolib.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1704662
* When proxy_scheme is empty, then create redhat.repo with default
scheme. It should be http in this case.
* Added one unit test for this case.

1704662: Do not create corrupted redhat.repo (wrong scheme); ENT-1306

---

src/rhsm/certificate.py

To better enable users running rootless containers which require
access to content provided by subscription-manager/RHSM, the
entitlement certificates (and their keys) are now readable by
"other".

1710564: Make entitlement certs and keys world-readable

---

src/subscription_manager/identity.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1702239
* The traceback is displayed, when the LANG is not en_EN,
(it is e.g. cs_CZ.utf8), system is not registered and
default_log_level is set to DEBUG.

1702239: Fix traceback for syspurpose on rhel7; ENT-1286

---

Vagrantfile

Because we have some images that use private networking, it's easier to
set up to *not* use qemu:///session
For me, this fixed `vagrant up` issues on Fedora 30

Modify Vagrantfile to force qemu:///system

---

src/dnf-plugins/product-id.py
src/plugins/product-id.py
src/subscription_manager/productid.py
test/test_yum_content_plugin.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1703607
* Different hook is used to have information about repos in the
list of installed packages
* Improved log message
* TODO: more testing of this change on DNF and with this patch:
https://github.com/dmnks/yum/commit/907abe0fe55ba4ebcfce8d793dcd6faf35610a7f

1703607: Remove productid cert, when it is not needed; ENT-1300

---

etc-conf/plugin/subscription-manager.conf
src/dnf-plugins/subscription-manager.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1713626
* The original functionality was provided by community only for yum plugin, but the template of dubsription-manager plugin is the same for dnf and yum plugin
* It was easier to implement this functionality for dnf plugin then create special template of conf file for dnf plugin
* Updated comment in template of plugin configuration file

1713626: Option disable_system_repos didn't work with DNF; ENT-1350

---

src/initial-setup/com_redhat_subscription_manager/ks/rhsm_ks.py

Since anaconda commit
https://github.com/rhinstaller/anaconda/commit/78fd1e82 ,
anaconda addons should no longer expect an install class to be
passed to their setup() and execute() methods. Without this fix,
the addon breaks recent versions of anaconda.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1713109
Signed-off-by: Adam Williamson <awilliam@redhat.com>

Anaconda addon: setup() and execute() no longer get instclass

---

src/rhsmlib/facts/all.py
src/rhsmlib/facts/insights.py
test/rhsmlib_test/test_insights.py

* Insights generates unique id (uuid) to file
/etc/redhat-access-insights/machine-id or
/etc/insights-client/machine-id
* The path is read from insights configuration, when insights is
installed.
* The fact is reported as insights_id: <UUID>

Report insights id as fact, when insights is installed.

---

debian-stuff/deb_package_profile_upload

When a Debian host uses a language that is not English (for example German), the `deb_package_profile_upload` will not parse the output of `subscription-manager identity` correctly.
This PR fixes this by setting `LANG=C` for the relevant command.

Set LANG to run subscription-manager and get proper output

---

src/subscription_manager/cache.py
src/subscription_manager/managercli.py
test/test_managercli.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1673662
* When syspurpose status is not valid, then try to print list of
reason, why system is not valid
* Added one unit test.

1673662: Print reasons, why syspurpose status is mismatch; ENT-1247

---

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py

Fix one more remaining place where we were affected by anaconda
removing install classes. As with the earlier fixes to rhsm_ks,
handle both old and new anaconda so we can work with either.
Signed-off-by: Adam Williamson <awilliam@redhat.com>

Also handle anaconda removal of install classes in rhsm_gui.py

---

src/dnf-plugins/subscription-manager.py

We need to disable system repos only when the value of the "disable_system_repos" is "1" (as per the comment in the subscription-manager.conf file). Prior to this setting any value (including "0") would trigger the disabling of system repos.

1713626: Only disable system repos if the disable_system_repos is "1"

---

subscription-manager.spec

I don't think we want this addon installed by default on Fedora.
AIUI it does not and cannot really do anything useful on Fedora,
it will only confuse people.
Signed-off-by: Adam Williamson <awilliam@redhat.com>

spec: Don't supplement initial-setup-gui on Fedora

---

syspurpose/README.md
syspurpose/src/syspurpose/cli.py
syspurpose/src/syspurpose/files.py
syspurpose/test/syspurpose/base.py
syspurpose/test/syspurpose/test_cli.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1708105
* This bug was mostly caused by absence of any unit tests for
modul cli
* I added serveral unit tests for the cli module
* Fixed few minor issues (code style, confusing debug prints)
* Updated documentation in README.md and added there tip how to test syspurpose code. It can be handy, when you try to do e.g. remote debuging in PyCharm

1708105: Fixed unsetting syspurpose attributes; ENT-1330

---

cockpit/src/subscriptions-client.js

The value is always a D-Bus variant, so we need to look inside.  The
same is true for port, username, and password.

1719697: cockpit - Fix detection of proxy while attaching

---

src/rhsm/profile.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1708438
* When two product certificates are installed (Beta and GA), then
dnf isn't able to synchronize cache for one of them.

1708438: Don't print traceback during list --available; ENT-1331

---

cockpit/src/subscriptions-client.js
cockpit/src/subscriptions-view.jsx

Don't call methods on a proxy that has failed, that is pointless and
will likely just crash since the proxy doesn't have the expected
methods defined on it.
Propagate the failure reason as the client subscription status when a
status update fails.
Don't unconditionally show the spinner until the config has loaded,
only while there is no other failure status yet.

1719709: cockpit - Improve behavior when connection to D-Bus fails

---

cockpit/src/subscriptions-client.js

Use a simple local variable to keep the state of overlapping requests
separate.

1719702: cockpit - Fix overlapping update requests

---

src/rct/printing.py
src/rhsm/certificate2.py
src/rhsmlib/services/entitlement.py
src/subscription_manager/managercli.py
test/stubs.py
test/test_managercli.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1717903
* When version of entitlement certificate is higher than 3.3,
then list --consumed prints syspurpose attributes, when
the version smaller than 3.4, then syspurpose attributes are
no printed, because there cannot be any.
* Modified output of "rct cc" command
* Fixed few unit tests
* Note: the output of list --available and list --consumed is
little bit different, when e.g. roles/addons contains multiple
values (e.g. ADDON1, ADDON2).

1665167: list --consumed print syspurpose attributes from ent. cert; ENT-1315

---

src/rhsmlib/facts/insights.py
test/rhsmlib_test/test_insights.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1722238
* The old version of insights client didn't have attribute
`machine_id_path`. Thus it couldn't work on RHEL7.
* Added one unit test for this case

1722238: Fix reporting insights id in facts on RHEL7

---

src/rhsm/config.py

The config file is read asynchronously by at least the file watches of
dbus/server.py, and if it is just overwritten in place the file watch
handler might read it when it has only been partially written.

1719725: rhsm - Write config file atomically

---

src/subscription_manager/repofile.py
test/test_repolib.py

The variable is no longer supported by DNF.
Also the displayed value in `dnf repolist` under the "repo id" column
should be the actual repoid and not the repoid combined with vars.

Drop ui_repoid_vars from repo config.

---

src/subscription_manager/managercli.py

When registering a client to a satellite with an activation key,
package lists for a client on the satellite was updated as expected.
However, "Installable Updates" on the satellite page was not updated.
It seems a bug.
This happens because subscription-manager reported the repository
informations of the client before updating repositories as specified in
the activation key. In this case, subscription-manager reported an empty
repository informations. The empty repository informations didn't
contribute to the "Installable Updates".
The reporting should be done after updating repositories.
Signed-off-by: Masatake YAMATO <yamato@redhat.com>

Send package profiles after updating repositories

---

syspurpose/src/syspurpose/cli.py
syspurpose/test/syspurpose/test_cli.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1708494
* When user tries to add more existing addon values, then the
function is not exited immediately, when existing addon value
is detected, but it tries to add all new addons
* Added two unit tests for this case

1708494: Proper messaging of syspurpose add-addons; ENT-1332

---

man/subscription-manager.8

* Removed --org option (command redeem) from man pages
* subscription-manager redeem --help doesn't print anything about
--org option and in fact this option is not supported due
to e.g. back compatibility too

Updated man pages (redeem command does not have --org option)

---

src/plugins/subscription-manager.py

When we started producing combined package profile reports (which encompassed the enabled_repos report and module reports for newer versions of fedora / RHEL), we started sending those updates on dnf transactions based on the value of the setting package_profile_on_trans.
A similar update was not made to our yum plugins. This can cause neither subman nor katello-host-tools to report the package profile (when used with newer versions of katello-host-tools which check the value of package_profile_on_trans in rhsm.conf to determine whether or not to upload the package profile).
The solution is for our subscription-manager yum plugin to also check the package_profile_on_trans setting in rhsm.conf and to report the package profile post transaction based on that.

1742208: Send package profile on yum transactions

---

subscription-manager.spec

To allow users to install newer versions of subman where changes are not necessary for the dnf-plugin-subscription-manager on RHEL 7, update the spec file.
Please note that this means we'll need to be conscious of any changes in the subman codebase which would cause an incompatibility between the two packages.

1743729: Update dnf-plugin dependencies for RHEL 7

---

test-requirements.txt

This is necessary for building vm images which do not support python3 (Centos7, RHEL7.x, and similar).

Require the python2 version of Sphinx when necessary

---

etc-conf/rhsm.conf
etc-conf/rhsmd.cron
man/rhsm.conf.5

Added a configuration option for a timeout on the rhsmd cron job run, as well as documented it in man for rhsm.conf and reconfigured the cron.daily script to utilize the timeout and verify the process has ended - otherwise we terminate it.
Since this runs daily, it will also clean up other rhsmd runs that hang for any reason hopefully, and prevent some of the issues we have seen around migrations to Satellite environments.

1643189: Added timeout for rhsmd cron job

---

src/rhsm/config.py
test/rhsmlib_test/test_config.py

Left this out of the first PR, will give us the default visualization from `subscription-manager config` output, etc.

1643189: Updated defaults to include rhsmd.processtimeout

---

subscription-manager.spec

* RPM groups for SUSE now fits guidelines
* service files and sysvinit macros for SUSE are now added and used
* run dir is different for SLES <= 11 (/run symlinks to /var/run)
a build log which proofs SUSE compatiblity is here:
https://build.opensuse.org/package/show/home:seilerphilipp:katello/subscription-manager
Now it build successfully (used v1.25.11 generated with tito) for the following distributions:
* SLES11 SP4
* SLES12 SP4
* SLES15 (SP1)
* openSUSE Tumbleeed
It also fixes a lot of rpmlint warnings and errors for SUSE distributions on the OBS.
I also want to maintain the package on the OBS. I already was in contact with the maintainers of the project.
Thank you very much!

better SUSE distributions integration

---

src/subscription_manager/managercli.py
syspurpose/src/syspurpose/cli.py
syspurpose/test/syspurpose/test_cli.py
test/test_managercli.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1698606
* The advice message is little bit different, when there is conflict
between value on server, chached value and new value
* It is possible to test conflict using:
- Set syspurpose attribute role using subscription-manager:
$ subscription-manager role --set 'Bar'
- Create testing syspurpose json file `new_syspurpose.json` with
following content:
```yaml
{
'role': 'Foo'
}
```
- Set syspurpose attribute role on the server using:
curl -ik -u admin:admin --request PUT \
"https://localhost:8443/candlepin/consumers/58ed1af1-6213-4314-b08b-f586b73f32f7" \
-d @./new_syspurpose.json --header "Content-Type: application/json"
- Try to set role once again using subsription-manager:
$ subscription-manager role --set 'Bar'
* Added one unit test …

1698606: Better advice message for syspurpose conflict; ENT-1341

---

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.ui

Drop the app_paintable option preventing the RHSM addon spoke
header from having the correct background color.
I hope this is the correct branch. :)
I've only tested this on RHEL7 - originally it looks like this:
This is how it looks like with the fix:

Fix RHSM addon spoke header background

---

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.ui

* The RHSM spoke was aligned to left in past.
* This commit changes horizontal alignment to center. Other spokes are
aligned to center too (e.g. Users) .

Align RHSM spoke to center

---

src/subscription_manager/logutil.py
test/test_logutil.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1687523
* When /var/log/rhsm doesn't exist, then subscription-manager or
yum plugin tries to silently recreate. When it is not possible
(permission, file system is in read-only mode, etc.), then error
with reason is printed and all other log messages are printed
to stderr
* Added one unit test for this case

1687523: Try to create /var/log/rhsm directory; ENT-1406

---

Vagrantfile
vagrant/vagrant.yml

A small PR to update our existing fedora vagrant box to a more recent version.
This should work just as the other boxes do, it is not pre-provisioned like the centos7 one though so it will take a little bit of time to run the ansible playbook against it.

Add fedora30 vagrant box

---

README.md
Vagrantfile

* Update to use sshfs instead of rsync
* Update README with instructions for using sshfs & testing the sub-man deployment ansible role.

Update Vagrantfile to use sshfs instead of rsync.

---

cockpit/lib/service.js
cockpit/src/cockpit-components-dialog.jsx
cockpit/src/index.js
cockpit/src/insights.jsx
cockpit/src/manifest.json
cockpit/src/subscriptions-client.js
cockpit/src/subscriptions-register.jsx
cockpit/src/subscriptions-view.jsx
integration-tests/check-subscriptions
test/files/mock-insights

This implements part of [this mockup](https://github.com/cockpit-project/cockpit-design/blob/master/subscriptions/insights.png).
It uses a brittle method for retrieving the local client status.  See https://github.com/RedHatInsights/insights-core/issues/1939 for some plans to improve that.
Still to do:

cockpit: Add support for Red Hat Insights

---

subscription-manager.spec

The reordering of the spec file (just a bit) also allows us to ensure the same mtime on even the __pycache__ files.

Include only container_content __pycache__ for container_content plugin

---

src/rhsmlib/__init__.py

On some slightly older versions of python (namely python 2.6.9), the importlib module has not been backported (from python 3+).
This PR let's us switch between using imp and importlib based on availability.

Do not use importlib unless available

---

integration-tests/run

Cockpit bots are in their own project now.
Make the target phony so that `make bots` updates an existing checkout.
---
https://github.com/mvollmer/subscription-manager/pull/7 test run completed here

cockpit: Update bots target for moved GitHub project

---

subscription-manager.spec

As an artefact of #2167 we started requiring python-inotify on suse. This really is a weak dependency at best and not something we have historically supported. As such this PR removes it.

No need for inotify on suse

---

integration-tests/run

Ported from recent changes to starter-kit. The first one is crucial to ensure that our CI and image updates changes don't break subscription-manager.

Cockpit CI updates

---

subscription-manager.spec

SLES15 changed several python2 package names (this was fixed for subscription-manager, but not for subscription-manager-rhsm)

fixed wrong package name for dependency in >= SLES15

---

src/rhsm/connection.py
src/subscription_manager/i18n.py
src/subscription_manager/managercli.py
src/subscription_manager/scripts/subscription_manager.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1703054#c10
* When some locales are used (e.g. Turkish), then behavior of
lower() and upper() methods is influenced by locale and
e.g. parsing of ini file doesn't work as expected. We can
also expect unexpexted behavior of other parts of sub-man.
* When unsupported locale is specified, then sub-man is not
terminated.
* When you add some custom section and custom attributes to
rhsm.conf. Something like this:
```
[foo]
bar = 0
```
then subscription-manager config --help will not contain
option --foo.bar=FOO.BAR, but it will contain only options
with default values (supported by subscription-manager).

1703054: Blacklist some locales for Python2.x; ENT-1288

---

syspurpose/src/syspurpose/cli.py
syspurpose/src/syspurpose/files.py
syspurpose/test/syspurpose/test_cli.py
syspurpose/test/syspurpose/test_syspurposefiles.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1738764
* The BZ bug report contained actually two issues.
- It wasn't possible to add other list than addons (minor issue)
- When some attribute was removed and user tried to add new
one again, then confusing warning was printed to stdout.
It happened, because server set removed attribute to empty
string, but removed attribute is completely removed from
syspurpose.json. Maybe we should be consisten on client and
server side too, because current implementatin is not
clean. Topic for discussion.
* Fixed some style issues
* Added several unit tests for these two cases

1738764: Fix issue with syspurpose three-way merge; ENT-1564

---

integration-tests/check-subscriptions

The old "candlepin" image does not exist any more, it's part of the new
"services" image now. This has a different (static) IP.
See https://github.com/cockpit-project/bots/pull/208

cockpit: Use new services image instead of candlepin

---

src/zypper/services/rhsm

With this change, if subman cannot reach Candlepin, then the repo file
should be written properly anyways (using last known state).

1764340: Handle RestlibException in zypper plugin

---

Makefile
etc-conf/zypper.conf
src/subscription_manager/repofile.py
src/zypper/services/rhsm
subscription-manager.spec

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1764265
* This is workaround for Zypper. Repo file is generated with
option gpgcheck equal to 0.

1764265: Set gpgcheck to 0, when zypper is used; ENT-1758

---

Makefile

/etc/SuSE-release was removed in SLE15...

Make Makefile SLE15 compatible

---

subscription-manager.spec

In the prior iteration of this bug fix we were missing an obsoletes to let dnf/rpm know that the subscription-manager-plugin-container package could be uninstalled. Without this, upgrades from systems with the subscription-manager-plugin-container of the subscription-manager package fail with conflicting requirements.

1728054: Obsolete sm-plugin-container on RHEL 8

---

subscription-manager.spec

Both rhsm-gtk and subscription-manager-cockpit packages claimed
ownership of /usr/share/icons/hicolor/scalable/apps/subscription-manager.svg.
As they both have a need for that icon (and all under /usr/share/icons*),
this commit splits the icons out into their own package.
It is only built when either the rhsm-gtk package is built or
the subscription-manager-cockpit package is built.

Add rhsm-icons package to contain all icons required by gui interfaces

---

src/rhsmlib/services/entitlement.py
src/subscription_manager/jsonwrapper.py
src/subscription_manager/printing_utils.py

* When list of available or consumed list is returned, then the
list of provided products was changed to dictionary. Key is
id of provided product and value is name of provided product.
It will be easier to reference provided product in cockpit
plugin. This change was introduced in PR #2176.
* Listing of consumed and available subscriptions is not affected
in subscription-manager CLI or GUI

D-BUS API: Better listing of provided products

---

cockpit/src/subscriptions-view.jsx

Transporting error details into a DismissableError component via its
children doesn't seem to be allowed anymore.

cockpit: Don't use objects as React children for error details

---

subscription-manager.spec

As these two packages previously contained the icons now contained in
rhsm-icons package, we need to specify the logical complement to a
"Requires", which is "Conflicts". With any luck the underlying
depsolver will cause the removal of this package if the request
is to downgrade either of the following to a version below these
requirements.

Fix downgradability due to conflicts with rhsm-icons

---

scripts/suse_build.sh
test/zypper_test/test_serviceplugin.py

* The subscription-manager installed in the system is not used
for functional tests, but current sub-man entry point is used
* Automatically trust to new repositories used for build projects,
because build process on jenkins slave is not interactive

Fix unit test and build process specific for suse

---

subscription-manager.spec

So this is a fairly long story but one worth capturing.
Python compiles py source files to pyc python bytecode files.
There is a really good intro to python bytecode here [0].
The result of python compiling it's source is a pyc file.
This file has a specific format dependent on the version of
python used to compile. Regardless of which python version
was used, the first chunk of the pyc file is a header with
metadata about the actual bytecode (which appears later in
the file).
As mentioned before, the exact format of this pyc file (header and
even the bytecode) is dependent on the version of python used but
there is a general format to it (as follows, afaict the bytes are
always little-endian):
unsigned short magic_number;
unsigned short magic_number_micro;
long mtime_of_source_file;
long …

Make sure to set the mtime of the py files before creating pyc

---

src/rhsm/profile.py

When multiple repos are enabled on the client, Yum will attempt
to load the subscription-manager plugin multiple times (equal
to the number of enabled repos). This is causing unnecessary or
duplicate https traffics to the rhsm server. This commit fixed
the issue.

1741183: Yum loaded subscription-manager plugin multiple times

---

man/subscription-manager.8
src/rhsm/connection.py
src/rhsmlib/services/register.py
src/subscription_manager/managercli.py
test/rhsmlib_test/test_register.py
test/test_managercli.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1667792
* When system is registered using CLI tool and activation key is
used, then --disable-auto-attach option can be used and
auto-attach process is disabled during registration process
* New option --disable-auto-attach cannot be used with --auto-attach
option
* Added two unit tests for this case
* Modified man pages
* Modified register service to support auto-attach
* Added unit test for auto-attach option in register service
* TODO: fix issue in candlepin server, because candlepin server
ignores autoheal option during registration

1667792: added --disable-auto-attach option to register command; ENT-1684

---

src/rhsm/utils.py
src/rhsmlib/facts/all.py
src/rhsmlib/facts/kpatch.py
test/rhsm/unit/util_tests.py
test/rhsmlib_test/test_kpatch.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1761566
* Information about live kernel patches are included in reported
facts. There are new keys: "kpatch.installed" and
"kpatch.loaded". These keys are reported only in case that
kpatch binary is installed.
* Added two unit tests for new facts
* Added which method to rhsm.utils. Functionality of this method
is similar to which linux command.
* Added unit tests for which method

1761566: include kpatch in facts; ENT-1700

---

src/rhsm/certificate2.py

When comparing for equality (or not equality) with certificates
try to use the 'serial' attribute of the other object.
Check for the 'serial' attribute first and require their values
to be equal for the certificates to be equal (likewise for ne).
This allows us to ensure we are comparing something equitable.

Ensure serial existence before comparison

---

etc-conf/subscription-manager.completion.sh
man/subscription-manager.8
src/rhsmlib/services/entitlement.py
src/subscription_manager/cache.py
src/subscription_manager/cert_sorter.py
src/subscription_manager/managercli.py
test/test_cert_sorter.py
test/test_managercli.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1794826
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1796088
- Cloned BZ for RHEL 7
* Added option --force for command refresh. When this option is
used, then entitlement certificates are regenerated on
candlepin server.
* Also REST API calls were optimized and following call:
GET /candlepin/consumers/{uuid}/compliance
is called only once (not 4 times). This optimization should
influence other commands (e.g. register). It is optimized,
because status is cached in memory. It is attribute of
class ComplianceManager
* TODO:
- Do more testing due to caching of status. It will be
probably necessary to obsolete this in memory cache
in some cases.
- Write some unit tests for new functionality

1794826: Added option --force for command refresh; ENT-2033

---

etc-conf/zypper.conf
src/subscription_manager/repolib.py
src/zypper/services/rhsm

This is the same functional change as https://github.com/candlepin/subscription-manager/pull/2211, but specifically for the 1.20 back-revved subscription-manager for SLES 11sp4.
There is a bug in zypper in SLES 11 that does not honor changes to the autorefresh value after the repo file has been created, but that bug is being addressed by SUSE separately.  Once that bugfix is released, the updates in this PR will be functional

1797386: Allow service plugin for zypper (SLES 11 only) to set autorefresh

---

src/subscription_manager/managercli.py

* I figured out that it would be useful to list user's
organizations during registration, when subscription-manager
CLI tool is used. It is not necessary to do another REST API
call, because GET /candlepin/users/{username}/owners is called
anyway. All we do now is listing results of this call before
user has to enter the organization name.

List user's organization during registration process on CLI

---

src/rhsmlib/dbus/base_object.py
src/rhsmlib/dbus/objects/register.py
test/rhsmlib_test/test_register.py

* Implemented GetOrgs() D-Bus method for Register service
- It has 4 arguments. The first argument is username,
the second argument is password, the third argument
is dictionary with connection options and the last
argument is string with locale
* Add one unit test for new method
* It can be tested using:
```
[root@localhost ~]# dbus-send --system --print-reply \
--dest='com.redhat.RHSM1' '/com/redhat/RHSM1/RegisterServer' \
com.redhat.RHSM1.RegisterServer.Start string:""
...
string "unix:abstract=/var/run/dbus-LDibqhpU9H,guid=660..."
[root@localhost ~]# export \
my_addr="unix:abstract=/var/run/dbus-LDibqhpU9H,guid=660..."
[root@localhost ~]# busctl introspect --address="${my_addr}" \
com.redhat.RHSM1 /com/redhat/RHSM1/Register
NAME                                TYPE      SIGNATURE …
```

Implementation of getting organization using D-Bus API; ENT-1760

---

src/subscription_manager/managercli.py

* When organization contains more than one environment and
environment is not specified using command line option,
then subscription-manager prints hint with list of
available entitlements now. So user can easily choose
one of them.

Hint about environments is printed by subscription-manager during registration.

---

src/dnf-plugins/product-id.py
src/dnf-plugins/subscription-manager.py
src/plugins/subscription-manager.py
src/subscription_manager/repolib.py

* Changed names of methods to be more pythonic
* Do not try to get content overrides twice, when configuration
option rhsm.full_refresh_on_yum is set to 1. Same optimization
was implemented for YUM plugin
* Fixed small bug in repolib.py
* Added support for debug print to DNF subscription-manager plugin
* Do not try to connect to candlepin server, when
rhsm.full_refresh_on_yum is set to 0, because it is useless.
* Changed one debug print in product-id plugin
* Some long strings were split into more lines

Refactoring of DNF subscription-manager plugin; ENT-1906

---

src/rhsm/connection.py
src/subscription_manager/managercli.py
test/rhsm/unit/connection_tests.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1763271
* When you register and content access mode for specified
origanization is org_environment and CLI option --auto-attach
is used, then do not print list of installed products,
because it does not make sense to print status of installed
product in this case
* Fixed bug in connection.py
* Fixed two unit tests

1763271: Golden ticket: do not print list of products; ENT-2017

---

Pipfile
README.md
setup.py
src/subscription_manager/branding/__init__.py

* Only Fedora30 or RHEL/CentOS 8 are supported
* Installation is still quite complicated using Pipenv
* More details are in REDME.md

Added basic support for Pipenv for subscription-manager; ENT-1755

---

subscription-manager.spec

The dependency of yum isn't required anymore as the katello-host-tools and the subscription-manager zypper plugin can be used pretty good without yum.

Remove yum for suse

---

src/dnf-plugins/product-id/CMakeLists.txt

This change make it possible to build libdnf plugin on RHEL/CentOS 7 systems. It is useful for building and testing.

Enable building of libdnf product-id plugin on RHEL 7.

---

Makefile
setup.py
src/subscription_manager/dbus_interface.py
src/subscription_manager/scripts/rhsm_d.py
subscription-manager.spec

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1775714
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1780028
* Stop rhsmd, when rhsm-icon is not running, because only
rhsm-icon can be listening for D-Bus service on
`com.redhat.SubscriptionManager`
* Do not install rhsmd on RHEL8
* Do not install configuration file related with D-Bus service
com.redhat.SubscriptionManager
* Do not try to build rhsm-icon, when WITH_SUBMAN_GUI is false

1775714: Do not install rhsmd and rhsm-icon on rhel8; ENT-1959

---

cockpit/src/insights.jsx

If we can't get the start of the monotonic clock, we only have to
ignore timers that use the monotonic clock.  We can still use the real
time clock.

cockpit: Be more robust when showing the time for next Insights upload

---

src/rhsm/profile.py

import "zypp_plugin" will somewhere redirect stdout -> stderr.
Therefore, printing the repo to stdout will fail (as it will be actually
printed to stderr).

Fix broken zypepr repo print

---

syspurpose/src/syspurpose/files.py
syspurpose/test/syspurpose/test_cli.py
syspurpose/test/syspurpose/test_syspurposefiles.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1821747
* When /etc/rhsm/syspurpose does not exist, then it is
automatically created
* When /var/lib/rhsm/cache does not exist, then it is also
automaticlly created
* Added two unit tests and fixed several unit tests

1821747: Automatically create /etc/rhsm/syspurpose

---

src/subscription_manager/managercli.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1688702
* When entitlement certs and keys are imported in off-line mode
using: "subscription-manager import" command, then it is
possible to print repositories provided in entitlement certs,
but it wasn't possible to enable any repository, because
redhat.repo wasn't created yet.

1688702: Generate redhat.repo in off-line mode; ENT-2302

---

src/rhsm/connection.py
src/rhsmlib/services/register.py
src/subscription_manager/managercli.py
test/rhsmlib_test/test_register.py

* When CLI option --servicelevel is set for register command, then
two REST API calls were removed. Service level is set only
in POST /candlepin/consumers
* You can also test changes using this:
```
[root@localhost syspurpose]# PYTHONPATH=./src:./syspurpose/src \
python -m syspurpose.main set-sla "Super"
[root@localhost syspurpose]# PYTHONPATH=./src:./syspurpose/src \
python -m syspurpose.main show
[root@localhost syspurpose]# dbus-send --system --print-reply \
--dest='com.redhat.RHSM1' '/com/redhat/RHSM1/RegisterServer' \
com.redhat.RHSM1.RegisterServer.Start string:""
method return time=1587110291.947024 sender=:1.4529 -> destination=:1.4575 serial=45 reply_serial=2
string "unix:abstract=/var/run/dbus-BZsXJp8NJf,guid=5aff4cdf83827f689069534f5e996193"
[root@localhost syspurpose]# export …
```

Reduced REST API calls during register, when SLA is set; ENT-2229

---

src/subscription_manager/scripts/rhsm_d.py
src/subscription_manager/utils.py
test/test_utils.py

This let's us determine if a particular named process is running without the use of psutil or any additional external dependency (apparently ps isn't installed by default in RHEL 8 ubi containers...).
There is one outstanding issue which I have yet to figure out, for some reason the mocking of os.listdir and open works for one test but then fails for the second test despite using the same code paths.
Any feedback or insights would be much appreciated. (There might also be some small change required for stylish).

1823523: Read from proc instead of using psutil

---

src/dnf-plugins/subscription-manager.py
src/plugins/subscription-manager.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1830994
* We added line breaks as part of one refactoring effort and side-effect
is wrong printing of warning messages in DNF/YUM subscription-manager
plugin.
* Warning message looks the same generated by DNF and YUM plugin now.

1830994: Fix warning messages in dnf/yum

---

src/subscription_manager/managercli.py
src/subscription_manager/syspurposelib.py
test/test_syspurposestore_interface.py

* It wasn't possible to sync SLA with candlepin server.
* It is possible to do it now, but current usage of this function doesn't require this functionality ATM
* Make the code more explicit about syncing SLA with server

Refactoring of save_sla_to_syspurpose_metadata; ENT-2228

---

setup.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1837244
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1838690
* When --rpm-version was provided as command line option for
python ./setup.py install, then this option wasn't propagated to
build class or any other class

1837244: Fix wrong version provided by subscription-manager version

---

src/subscription_manager/scripts/rhsm_d.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1834792
* Don't be so agresive about terminating rhsmd
- Wait timout defined in StatusChecker class (120 seconds)
- After timout is reached, then check if --keep-alive
CLI option was used and rhsm-icon is running. If any
of this criteria is met, then rhsmd can be terminated
- If the D-Bus API will be required again, then rhsmd will
automatically started by dbus service

1834792: Try to terminate rhsmd after timeout; ENT-2368

---

syspurpose/src/syspurpose/files.py

When populating SyncResult, update [remote|local|cache] only when either
has changed. That prevents namely redundant update of syspurpose to the
RHSM server when no change has been detected.
Signed-off-by: Pavel Moravec <pmoravec@redhat.com>

1838012: prevent redundant remote syspurpose sync

---

src/subscription_manager/managercli.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1725525
* One string was not marked for localization
* Many strings had bad ending of function _("string").
- When the string contains something like this:
"{attr}".format(attr=some_variable), then the _()
has to be used like this:
_("{attr}").format(attr=some_variable)
and not like this:
_("{attr}".format(attr=some_variable))
The second case is wrong, because gettext will try to find
translation for string that is included in some_variable.

1725525: Better translation of syspurpose; ENT-1680

---

src/subscription_manager/syspurposelib.py

ActionReport message formating does not fit the syntax of the
SyspurposeSyncActionReport messages

1789457: Syspurpose exception message parsing

---

integration-tests/run

We moved some stuff over to test/common/run-tests, tests need to be run via run-tests in order to have correct tap output and to have bots/tests-policy run on the output.

cockpit: Call run-tests from common to run cockpit integration tests

---

Makefile
subscription-manager.spec

* Do not build rhsm-icon, when it is not installed to the system
* Do not require to have installed following packages, when the
rhsm-icon is not build/installed:
- GConf2-devel
- gtk3-devel
- dbus-glib-devel
* Changed a little bit logic of installing initial-setup and
firstboot to be ready to completely remove initial-setup
* To be able to build rpm on Fedora 32 using tito, then you
will also apply patch from this tito PR:
https://github.com/rpm-software-management/tito/pull/378

Fix building sub-man on Fedora 32

---

src/rhsm/certificate.py
subscription-manager.spec

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1741364
* New entitlement certs/keys are readable by others. This changes
was introduced in this PR:
#2084
but existing entitlement keys still have 0600 permissions.
* Permissions are changed during post installation script
* Small refactoring of code

1741364: Make existing ent. cert/keys readable by others; ENT-1593 

---

src/rhsmlib/facts/insights.py
test/fixture.py
test/rhsmlib_test/test_insights.py

Prior the insights-client machine-id (the id used to uniquely
identify a system for Red Hat Insights) was located in the filesystem
at '/etc/redhat-access-insights/machine-id'.
It is (as of 3.0.13+ of insights-client) moved to
'/etc/insights-client/machine-id'.
Subscription-manager needs to report this in order to ensure we
do not end up with two records for the same system (one created
during registration using insights-client and another created
in hosted based on the new consumer registration to RHSM)
Now subscription-manager will first try to read the machine id:
1) from the file specified in insights_client.constants.machine_id_file
2) from "/etc/insights-client/machine-id"
3) from "/etc/redhat-access-insights/machine-id"
Also added a new test function to allow mocking of an …

1848636, 1849074: Update insights machine-id path

---

subscription-manager.spec

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1840364
* The rhsmd is not part of RHEL8 anymore. Thus it is good to
kill this service at the end of installation process, when
the RPM package of subscription-manager is upgraded.
* The rhsmd is also killed, when the package is installed
on Fedora.

1840364: Kill rhsmd during post-install on rhel8; ENT-2449

---

Makefile
setup.py
subscription-manager.spec

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1770864
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1832054
* The RPM package subscription-manager-migration is not built on
Fedora, because it has dependency on rhn RPM package
and this package is not available on Fedora anymore.
* This PR is blocked by  #2266

1770864: Do not create sub-man-migration rpm for Fedora; ENT-1961

---

etc-conf/subscription-manager.completion.sh
man/subscription-manager.8
src/rhsmlib/services/register.py
src/rhsmlib/services/unregister.py
src/subscription_manager/managercli.py
test/rhsmlib_test/test_register.py
test/rhsmlib_test/test_unregister.py
test/test_managercli.py

Insights client plans to implement a process to watch the consumer cert
directory and perform registration automatically when we land a consumer
cert in this directory.
In order to disable this functionality during registration, this change
adds the `--no-insights` option, which disables the planned systemd
unit.
If the systemctl command fails to disable the unit, we proceed with
registration. There may be some use cases (e.g. container where systemd
does not run) where failure to mask may be a non-issue.
This PR also adds messaging to the registration output.
There are four scenarios:
1. `--no-insights` passed, insights-client not present
2. `--no-insights` passed, insights-client present
3. `--no-insights` not passed, insights-client not present
4. `--no-insights` not passed, …

Add --no-insights option; ENT-2471

---

cockpit/src/index.js
cockpit/src/insights.jsx
cockpit/src/subscriptions-client.js
cockpit/src/subscriptions-register.jsx

This makes the following changes:
- checks the "Connect this system to Red Hat Insights" option by default
- passes the no_insights option through when the option is unchecked
- reduces any errors encountered during Insights registration to
warnings
Note I wrapped the use of `cockpit.spawn` in one place to adapt
cockpit promises to standard Promises, this was necessary to get error
logic working properly.
To test
-------
Try a centos 7 machine without insights-client packages available. Not
that by default, you'll see a warning about not being able to install
the insights-client package.
Try unchecking the box and observe the masking introduced in ENT-2471
happens.
Try unregistering via cockpit and observe the registration is unmasked.
Note that there may be some additional cleanup to do …

Support Insights registration by default in cockpit

---

cockpit/lib/cockpit-components-dialog.jsx

For accessibility and usability reasons, Patternfly recently
changed the guidelines on button location and button order.
https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/forms#buttons
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1850993
This commit changes the order

cockpit: change button order to conform with patternfly guidelines

---

Makefile
etc-conf/subscription-manager.conf.tmpfiles
src/daemons/rhsmcertd.c
src/rhsmlib/dbus/server.py
src/subscription_manager/gui/about.py
src/subscription_manager/lock.py
src/subscription_manager/utils.py
subscription-manager.spec
test/rhsmlib_test/test_register.py

* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1657269
* The directory `/var/run` is marked as obsoleted and it is
also hard link to `/run`
* Chnaged all occurance of `/var/run` to `/run`
* Prepared the code for similar change in virt-who

1657269: Do not use /var/run, but use /run; ENT-1086

---

subscription-manager.spec

* When subman-cocpit rpm package was removed then node_modules
was not removed and /usr/share/cockpit/subscription-manager
was not removed too.

Mark node_modules as part of rpm package.
