candlepin/subscription-manager

src/subscription_manager/managercli.py
The "Status Details" row of list --consumed will now be populated
with the subscription status when no other status details are
available. This follows the logic used by the GUI when displaying
the status details.
=> 1180400: "Status Details" are now populated on CLI

src/subscription_manager/managercli.py
Fix datetime.now() to datetime.datetime.now()
=> Add missing import of GMT()

test/test_utils.py
rhsm version tests had bits of the old api
left in it. Updating mocking to mock the new api.
Update server version check to use injected invalid
consumer id instead of a custom mock.
Stylish fixes.
=> Fix test_utils.py bad merge.

Makefile
Otherwise the subman version files aren't populated.
=> Add make 'set-versions' part of 'jenkins' targets.

src/subscription_manager/gui/registergui.py
If subscription-manage-gui or firstboot starts before
the network is completely started (dhcp has created
/etc/resolv.conf, etc) then any attempt to use
socket.getaddrinfo() will fail and will continue
to fail for the life of the process. Unless we call
the glibc res_init() method to force a re-init of
the name resolution setup (reload resolv.conf
essentially) and purge the cache of the negative
name lookups.
So this adds a reset_resolver() method that the
registration gui and firstboot will call whenever
they go past the "Choose Server" screen.
Network errors in other parts of firstboot will
return the ui to the "Info Screen" preceding the
"Choose Server" screen, and therefore call
reset_resolver() as they progress.
=> 1191241: Handle network starting after subman does.

test/fixture.py
Otherwise code that uses that will fail tests.
=> Add a isatty() to fixture.Capture.Tee

src/rhsm_icon/rhsm_icon.c
fixing easy bugs out of boredom.
=> BZ:1163398, fixing rhsm-icon --help descriptions

src/subscription_manager/logutil.py
Needs to be hooked into configuration somewhere to be useful, but posting for
review/testing/thoughts.
=> Add syslog logging handler.

src/subscription_manager/hwprobe.py
Reverts candlepin/subscription-manager#1117
=> Revert "Added check for /etc/oracle-release in hwprobe"

src/subscription_manager/reasons.py, test/test_reasons.py
Reasons that include an 'entitlement_id' attribute that
references a entitlement id that is not currently in
cert_sorters valid_entitlement_certs (for ex, a
cert that has since expired) were causing tracebacks.
Add test cases to cover that scenario, and some additional
tests in test_reasons.py to improve coverage.
=> 1201727: Handle reasons with expired ent id

man/subscription-manager.8
- Added the missing documentation for the --release option for
the register command.
=> 1204012: Added missing documentation for the --release option

src/subscription_manager/gui/firstboot/rhsm_login.py
Before, if the firstboot proxy setup dialog wrote
the rhn up2date config's enableProxy option as 0,
we would not apply any of the http proxy settings from
the config file nor apply them to the current connection.
You could check into the enable proxy hotel, but you could
never check out.
Since rhsm config object don't have a enableProxy option, we
have to unset proxy_hostname to disable proxies.
If we always apply RHN's up2date config enableProxy value that
way, we would never fall through to use the rhsm.conf values.
So now we only apply RHN's up2date config enableProxy value if
we know we unset it via the settings dialog.
=> 1228807: Make disabling proxy via gui apply

etc-conf/plugin/search-disabled-repos.conf, src/plugins/search-disabled-repos.py, subscription-manager.spec
New plugin as discussed in https://bugzilla.redhat.com/show_bug.cgi?id=1232232#c10
=> Add search-disabled-repos plugin.

bin/subscription-manager-gui, src/daemons/rhsm_d.py, src/daemons/rhsmcertd-worker.py, test/smoke.sh
rhsm_d and rhsmcertd needed to be updated to the latest api.
Add invocations of rhsm_d and rhsmcertd-worker to
test/smoke.sh
=> 1241247: Fix ga ImportError in rhsmcertd

src/subscription_manager/gui/data/ui/registration.ui
This is mostly widget fill and expand options, so the
widgets adjust to the dialog more uniformly.
=> 1248546: Refine the aesthics of register dialog.

src/subscription_manager/gui/data/ui/organization.ui, src/subscription_manager/gui/data/ui/registration.ui
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1249053
=> 1249053: Fixed layout/blank button issues on owner selection dialog

src/subscription_manager/ga_loader.py
And remove some unused debug code.
=> Turn off ga loading debug messages.

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py, src/subscription_manager/gui/firstboot/rhsm_login.py, src/subscription_manager/gui/registergui.py
For initial-setup, error screen is also the choose server
screen.
If we finish, and are "done", hide the cancel and register
buttons.
=> 1243704: Goto error screen on 'cancel'

src/subscription_manager/gui/data/ui/allsubs.ui
https://bugzilla.redhat.com/show_bug.cgi?id=1251493
=> Fixing All Subscriptions layout issues

src/subscription_manager/managercli.py, test/test_managercli.py, test/test_registration.py
* Doesnt allow using --force with --consumerid
* Stopped --consumerid = distributor id
=> consumerid=distributor id

src/subscription_manager/gui/registergui.py
The handler for activation key changes wasn't unsetting
username/password.
=> 1254550: Fix activation key usage in gui.

src/subscription_manager/gui/registergui.py
This fixes registering, then unregistering, then
hitting Register again and ending up at the 'Done'
page.
=> Re initialize() RegisterWidget on RegDialog show

src/subscription_manager/managerlib.py
After an unregister, the cache file for ReleaseStatusCache
(injected as RELEASE_STATUS_CACHE) would leave it's on
disk cache (/var/lib/rhsm/cache/releasever.json) around.
=> Delete the 'release' status cache on clean all.

src/daemons/rhsm_d.py, src/subscription_manager/cli.py, src/subscription_manager/managercli.py, src/subscription_manager/utils.py
- Added a print_error function to print a message to stderr
- Updated the error printing in autoattach during register to
use the print_error function
=> 1262919: Added convenience function for printing to stderr

src/subscription_manager/plugin/ostree/model.py, test/test_ostree_content_plugin.py
If the ostree content plugin is installed on a system that
doesn't have ostree installed and/or it is not an active
ostree deployed system, more or less ignore ostree plugin
errors.
Add a new exception type for gi_wrapper related errors, and
give it a unthreatening str() to avoid cluttering logs with
generally harmless tracebacks.
It should be every uncommon for a user to get in this situation
unless they have specifially installed the ostree content plugin
on a system that does not use ostree.
=> 1185958: Quieter ostree plugin sans ostree

src/subscription_manager/gui/widgets.py
* if subscription isnt expired or expiring, reset its original color
=> 1249012: fix start-end date original color FIXME

po/as.po, po/bn_IN.po, po/de_DE.po, po/es_ES.po, po/fr.po, po/gu.po, po/hi.po, po/it.po, po/ja.po, po/kn.po, po/ko.po, po/ml.po, po/mr.po, po/or.po, po/pa.po, po/pt_BR.po, po/ru.po, po/ta_IN.po, po/te.po, po/zh_CN.po, po/zh_TW.po
- Updated the .po files to inclued the translation updates and corrections
made in the 1.15.X branch
=> 1265347, 1265371: Added translation updates and corrections from 1.15.X

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.py
Farewell 'face-cool-symbolic' guy.
=> 1266994: Use our icon for initial-setup spoke icon

src/subscription_manager/gui/registergui.py
If we got here with an unexcepted RestlibException,
nothing would signal that the attach was finished
(in the sense that there is nothing else it can do).
In particular, 401's that have a valid candlepin
error response. Which could happen if you have the
CA certs for current serverurl, but have a valid consumer
cert from a different server, and you fail the consumer
cert auth check.
=> 1267034: Handle 401 with cert based auth

src/subscription_manager/gui/managergui.py, src/subscription_manager/gui/registergui.py
Not sure if this is any better, or if it's not worse, but for review.
=> Another approach, merge if intereting.

src/subscription_manager/gui/data/glade/register_dialog.glade, src/subscription_manager/gui/data/ui/register_dialog.ui, src/subscription_manager/gui/managergui.py, src/subscription_manager/gui/registergui.py
Add a 'Cancel' button back to s-m-gui register dialog.
=> 1268060: Add 'cancel' back to s-m-gui register.

src/subscription_manager/gui/data/glade/selectsla.glade, src/subscription_manager/gui/registergui.py
Also remove use of a of 'slice' operator of
a tree model iter, it's not supported on gtk2.
=> Add glade for selectsla combobox for rhel6

etc-conf/subscription-manager.completion.sh, man/subscription-manager.8, src/subscription_manager/certdirectory.py, src/subscription_manager/managercli.py, test/stubs.py, test/test_remove.py
Updates tests for remove, and stubs
Updates remove pool option to work in the unregistered case.
=> 1198178: Adds pool option to remove, unsubscribe command

src/subscription_manager/managercli.py
976859 is about the server version check done by
the cli being slow, which it is (at least for
invocations that otherwise don't use the network)
315d08e880 moved the check to use a thread so as
to not block, but 1284120 was a bug in it.
For simplicity, this commit removes the threading,
but also removes the server version check from all
cli sub commands except 'register' and 'version'
since it was of limited utility in practice.
=> 976859: Only check server version if asked.

src/subscription_manager/gui/registergui.py, src/subscription_manager/printing_utils.py
Also corrected a couple of stylish issues.
=> 1283749: Upgrade the dialogs to error when required fields are blank.

src/subscription_manager/gui/data/glade/repositories.glade
Rearranged the various containers such that the layout of the repository management dialog on GTK2 matches the GTK3 version.
=> 1297313: Fixed layout issues with the repository management dialog on GTK2

src/subscription_manager/gui/managergui.py, src/subscription_manager/gui/reposgui.py
Proper show/hide for repo details box
Capture gtk warnings when opening help
=> 1303092: GUI issues in Repos and Help

src/subscription_manager/healinglib.py
To fix
https://github.com/candlepin/subscription-manager/issues/1409
=> issue #1409

playpen/noserc.ci, playpen/noserc.dev, src/dnf-plugins/product-id.py, src/plugins/product-id.py, src/plugins/subscription-manager.py
Fix Flake8 & other issues found by the updates to our jenkins builders.
=> Fix Flake8 Errors

src/subscription_manager/gui/widgets.py, test/test_widgets.py
I have a stage account set up with a myriad array of subscriptions with varying quantities that can be used to verify the fix. Ping me for the credentials.
=> 1325083: Fix available sort order

Makefile, etc-conf/rhsmcertd.init.d, setup.py, subscription-manager.spec
=> Added basic SLES compatibility.

build_ext/i18n.py, po/keys.pot
Our xgettext extraction requires several passes due to our use of C,
Python, and desktop files, so we want xgettext to append to a single
file for each pass.  However, we want to start with a fresh file each
time so we don't end up with orphaned strings that languish in the keys
file forever.
=> Do not endlessly add to the keys file.

src/subscription_manager/gui/preferences.py, test/test_preferences.py
Will need to use sniff from the package dogtail to test.
=> 1333904: Append accessible name to contain selected value

src/daemons/rhsm_d.py
The initial issue, as reported in the bz, has to do with the default selinux policy of the system. This policy prevents rhsmd from having access to files in /tmp. The check made for the existence of the directory '/tmp/product-default' on initialization of a new instance of ProductCertificateDirectory returns false due to the lack of permissions. This, in turn, causes the ProductCertificateDirectory instance to attempt to create it. The inevitably fails as in the bz above, the directory does in fact exist.
The issue that this PR actually fixes is not the one described above. The problem fixed here is that after a failure as described above rhsmd continues to run and hold on to objects that are in a stale state. This is the result of some of our injection code.
The solution was to ensure …
=> 1351370: Ensure rhsmd exits on exceptions

src/rct/manifest_commands.py, test/manifestdata.py
=> 1336880: Print virt_limit attributes with rct cat-manifest.

man/rct.8
Language based loosely on description for --no-content for cat-cert, but
slightly more concise.
=> 1373922: Add cat-manifest --no-content desc to man

src/initial-setup/com_redhat_subscription_manager/gui/spokes/rhsm_gui.ui, src/subscription_manager/gui/data/glade/activation_key.glade, src/subscription_manager/gui/data/glade/choose_server.glade, src/subscription_manager/gui/data/glade/credentials.glade, src/subscription_manager/gui/data/glade/register_dialog.glade, src/subscription_manager/gui/data/glade/selectsla.glade, src/subscription_manager/gui/data/ui/activation_key.ui, src/subscription_manager/gui/data/ui/choose_server.ui, src/subscription_manager/gui/data/ui/credentials.ui, src/subscription_manager/gui/data/ui/register_dialog.ui, src/subscription_manager/gui/data/ui/selectsla.ui, src/subscription_manager/gui/registergui.py
This essentially boiled down to adding mnemonics for register GUI in
GTK3. Also did the same for GTK2.
=> 1365472: Add keyboard mnemonics for initial-setup

src/subscription_manager/gui/registergui.py
=> 1362731: Change titles when moving to subscription attachment

src/subscription_manager/cache.py, src/subscription_manager/exceptions.py, src/subscription_manager/gui/networkConfig.py, src/subscription_manager/identity.py, src/subscription_manager/managercli.py, src/subscription_manager/migrate/migrate.py, src/subscription_manager/release.py, src/subscription_manager/utils.py, test/test_handle_gui_exception.py, test/test_managercli.py, test/test_migration.py, test/test_release.py
Necessary changes in subscription manager for candlepin/python-rhsm#184.
=> Replace m2crypto references

src/subscription_manager/migrate/migrate.py
We check to see if the service is installed before attempting to
disable/stop it in order to have less output.
Also, we now use chkconfig for SysV (was trying to use "disable"
mistakenly before).
=> 1390341: Disable SysV/systemd services properly

src/subscription_manager/gui/registergui.py
The issue was that we were not handling the ProxyException being thrown in is_valid_server_info().
The new behaviour is to inform the user when there has been an exception involving the credentials provided.
=> 1395659: Handle ProxyExceptions that occur during GUI operation

src/subscription_manager/gui/managergui.py
If a proxy issue is detected, allow the user to change network settings
by presenting a dialog informing them of the issue. Additionally, this
change allows them to jump straight to the network config dialog by
selecting OK. Otherwise, we exit the GUI immediately.
It would be possible to enter the main window once the network settings
are fixed, but that was a much larger change.
=> 1404930: Provide GUI flow to fix proxy settings

test/rhsmlib_test/test_register.py, test/test_registrationgui.py
Found a few erring tests in last PR that are unrelated to the PR.
=> Fix initialization of a couple of tests

test/stubs.py
Oops! This was causing master to have test failures.
=> Fix entitlement_type for stub entitlement

Makefile, src/zypper/commit/product-id, subscription-manager.spec
Please see #1540 first, as this builds upon work there. Only commit 838a1a5 is unique to this PR.
=> Add zypper product-id plugin

src/dnf-plugins/product-id.py
fixing
'Query' object has no attribute 'na_dict'
=> Query.na_dict() has been renamed in dnf 2.0

python-rhsm/src/rhsm/connection.py, src/daemons/rhsmcertd-worker.py, src/subscription_manager/cp_provider.py, src/subscription_manager/managercli.py, src/subscription_manager/utils.py, test/stubs.py, test/test_managercli.py
Random UUID for uniqueness.
Related to candlepin/candlepin#1487.
=> Add correlation ID to each cmd & rhsmcertd run

python-rhsm/src/rhsm/m2cryptohttp.py
Older versions of M2Crypto do not support the "family" parameter in
M2Crypto.SSL.Connection.  This parameter allows one to create an IPv4 or
IPv6 connection.  This patch checks to see if "family" is supported and
if so, it provides the correct value.  Otherwise, nothing is supplied.
Usage of an older version of M2Crypto will limit python-rhsm to IPv4
but this was always the case in actual fact.  Usage of newer versions
will be able to use either IPv6 or IPv4.
=> 1435475: Support older versions of M2Crypto

etc-conf/rhsm.conf, man/asciidoc/rhsm.conf.5.asciidoc, man/rhsm.conf.5, man/subscription-manager.8, python-rhsm/src/rhsm/config.py, python-rhsm/src/rhsm/connection.py, python-rhsm/test/unit/connection-tests.py, src/subscription_manager/cp_provider.py, src/subscription_manager/gui/data/glade/networkConfig.glade, src/subscription_manager/gui/data/ui/networkConfig.ui, src/subscription_manager/gui/networkConfig.py, src/subscription_manager/managercli.py, test/test_network_config_gui.py
The precedence is command-line > config > environment, as with other
proxy options.
=> 1420533: Add --noproxy option and "no_proxy" config

src/daemons/rhsmcertd.c
When I tried to build subscription_manager at CentOS 7, then building of src/daemons/rhsmcertd.c failed. The main reason is absence of SYS_getrandom or getrandom() at systems with kernel < 3.17.0. More details are in this bug report:
https://bugzilla.redhat.com/show_bug.cgi?id=1440251
I just added simple fix. May be, it would be better to seed pseudo-random generator with something like this:
```c
unsigned int seed;
FILE* urandom = fopen("/dev/urandom", "r");
fread(&seed, sizeof(unsgined int), 1, urandom);
fclose(urandom);
srand(seed);
```
BTW: semicolon at the end of definition is not good idea. All random generating was IMHO useless. Do not ignore warnings :-).
=> 1440251: Fix building of rhsmcertd at RHEL

src/daemons/rhsmcertd.c
This fixes a regression introduced by the RFE in #1577.
Please note this PR might conflict with #1579 (similar changes were made to ensure the random splay values are actually used). This was done in this PR to ensure the reviewer could successfully test the PR as is. Whenever this, or the other PR is merged, the other can be rebased.
Note to future self: Mind your pointers.
=> 1440934: Ensure rhsmcertd performs both types of checks

src/rhsmlib/facts/custom.py, src/subscription_manager/logutil.py
Could not reopen #1578 because a force push to the branch on which this work was completed was necessary to maintain a clean history. (Bizarre)
=> 1435771: Fix UnboundLocalError during custom facts collection

man/asciidoc/rhsm.conf.5.asciidoc, man/rhsm.conf.5, man/subscription-manager.8
Looking for feedback especially on language used (clarity, etc).
=> 1428002: Add proxy configuration info to man page

src/rhsmlib/dbus/facts/base.py, src/rhsmlib/facts/all.py, src/rhsmlib/facts/host_collector.py
* Class `StaticFactsCollector` contains default value for
system.certificate_version and it was called as last. Thus it
overwrote custom fact.
* Custom facts was read twice. It was read in `HostCollector` too.
* Refactored base.py. When you will consider as too crazy, then
let me know.
=> 1443693: Enable to overwrite system.certificate_version with custom fact

src/subscription_manager/managercli.py
Also, I special cased the message when an SSL error is generated when
attempting to unregister, since the mapped message was misleading.
=> 1443101: Provide feedback for force register

src/rhsmlib/facts/hwprobe.py
* Bug: https://bugzilla.redhat.com/show_bug.cgi?id=1447722
* SELinux was preventing calling hostname at RHEL 7.4 and this
is more Pythonic solution.
=> 1447722: use socket.getaddrinfo() to mimic hostname -f cmd

src/rhsmlib/facts/host_collector.py
* Bug fix for: https://bugzilla.redhat.com/show_bug.cgi?id=1449824
* When LANG was set to something wrong e.g. LANG=foo, then
running `subscription-manager facts` returned only:
unknown locale: foo
* When LANG is set to something wrong, then system.default_locale
is set to "Unknown". It is same behaviour as LANG is unset
or LANG is equal to "C".
* When LANG is set to something wrong, then warning is written to
rhsm.log too.
=> 1449824: facts collection aborts with unknown locale

etc-conf/rhn-migrate-classic-to-rhsm.completion.sh, etc-conf/rhsm-debug.completion.sh, etc-conf/rhsm-icon.completion.sh, test/test_completion.py
Also added a test that will execute each script with `bash --posix`, so
if we regress, it should show up in unit test failures.
=> 1450049: Replace `-` with `_` in completion functions

src/subscription_manager/entcertlib.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1450862
* When there was obsolete golden ticket(s), then it wasn't
removed during register --force
=> 1450862: remove obsolete certiciates of golden ticket

README.md, Vagrantfile, vagrant/roles/subman-devel/tasks/main.yml
Also, README updated to explain how these are used.
=> Add insecure and port options to Vagrantfile

etc-conf/subscription-manager.completion.sh
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1441397
=> 1441397: Added --noproxy to bash completion script

src/subscription_manager/gui/managergui.py, src/subscription_manager/gui/utils.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1421010
* Modification of PR #1532
* Small bug in test_proxy_connection()
* Refactored the name and added some comments
* Moved test_proxy_connection to utils, because it can be used
for solving other issues.
=> 1421010: GUI opens network dialog due to bad proxy during startup

man/subscription-manager.8
- bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1443570
=> 1443570: Update retired article reference

src/rhsmlib/facts/firmware_info.py, src/subscription_manager/repolib.py
- Fix dmidecode detection
- Fix zypper repo __init__ method
=> Make SUSE tests pass again

src/subscription_manager/cache.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1380341
* Dialog window popup with message:
"Unit <consumer-id> has been deleted"
=> 1380341: Better dialog in GUI, when consumer is deleted at CP.

src/subscription_manager/gui/utils.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1468297
=> 1468297: Fix gui proxy check

src/subscription_manager/cli.py, src/subscription_manager/utils.py, test/fixture.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1462456
* Sub-man can be terminated with `system_exit()` and it requires
flushing of stdout and stderr too.
=> 1462456: flushing of stdout and stderr once again

src/subscription_manager/gui/widgets.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1472746
=> 1472746: Correct sorting of dates in subman gui

src/subscription_manager/gui/registergui.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1330036
* It seems that argument `exc_info` is not used for anything
useful. I decided to use it for passing error_code.
* Screenshot of initial-setup with new error message:
=> 1330036: Better status error message for initial-setup

src/subscription_manager/identity.py, src/subscription_manager/managercli.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1400326
* Fixed regresion in reported error.
* Small refactoring.
=> 1400326: Better error print, when comsumer cert is corrupted

python-rhsm/src/rhsm/connection.py, python-rhsm/test/unit/connection-tests.py, src/subscription_manager/cache.py
=> 1481384: Do not update redhat.repo at RateLimitExceededException

src/subscription_manager/repolib.py
Just a small improvement to not repeat code.
This should not change any behavior.
=> refactor RepoFile: make create polymorph

src/rhsmlib/facts/hwprobe.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1476817
* When there is no record for hostname in DNS or /etc/hosts, then
set network.ipv4_address from list of addresses of all
interfaces in the system (loopback is skipped).
* Do similar for network.ip6_address, but use only interfaces
with global addresses.
=> 1476817: Set network.ipv4_address properly, when DNS misconfigured.

man/rhsm.conf.5
* Buf fix: https://bugzilla.redhat.com/show_bug.cgi?id=1491842
=> 1491842: Add man page doc for [rhsm] auto_enable_yum_plugins

src/rhsmlib/services/entitlement.py, src/subscription_manager/managercli.py
Also fixes some underlying issues with the --pool-only option.
=> 1493711: Fix --matches option for the list command.

bin/rhsm-service
* Possible bug fix for: https://bugzilla.redhat.com/show_bug.cgi?id=1483746
=> 1483746: Force UTF-8 encoding in rhsm-service

src/daemons/rhsm_d.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1448313
=> 1448313: Do not log error, when rhsm_icon.json does not exist

src/rhsm/m2cryptohttp.py
For very old m2crypto (such as what's present in SLES11), settimeout was
not present. This change allows subscription-manager to function in such
environments by using `set_socket_read_timeout` and
`set_socket_write_timeout`.
=> Implement fallback for settimeout on old m2crypto

cockpit/package.json, cockpit/spec/dbus/dbus.test.js, cockpit/src/subscriptions-client.js, cockpit/src/subscriptions-view.jsx, cockpit/src/subscriptions.css, cockpit/webpack.config.js, cockpit/yarn.lock, subscription-manager.spec
* It is possible to properly list installed products
* It add another dependencies:
- patternfly-react
- react-bootstrap
- some loaders: file-loader and url-loader
* All informations about products including start and end date
are gathered from output of D-Bus
* Note: icons used in ListView can be changed, but it is IMHO
necessary to have there any, because CSS does not work
properly without these icons
=> Cockpit - listing of installed products using patternfly-react

cockpit/src/Select/Select.jsx, cockpit/src/index.js, cockpit/src/subscriptions-client.js, cockpit/src/subscriptions-register.jsx, cockpit/src/subscriptions-view.jsx, src/rhsm/connection.py, src/subscription_manager/managercli.py
Also added logic that config must be loaded before the curtains are
hidden.
Had to adjust the Select component to take in more props (specifically
for value).
Also removed the default settings from `subscriptions-register.jsx`.
=> 1487688: Load config settings for cockpit plugin

src/subscription_manager/cli.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1462456
=> 1462456: Flush stdout and stderr on more places

vagrant/roles/subman-devel/defaults/main.yml, vagrant/roles/subman-devel/tasks/main.yml, vagrant/roles/subman-devel/vars/Debian.yml
This patch disables all cockpit and nodejs related roles on debian9.
=> Make debian provision again

cockpit/src/index.js, cockpit/src/subscriptions-client.js, cockpit/src/subscriptions-register.jsx
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1487600
* Try to save all settings from register dialog
* Do not try to auto-attach, when registration failed
* TODO: auto-attach can fail, when proxy server is used
* Automaticaly request update of page, when dialog is closed
=> 1487600: Cockpit - Save configuration from register dialog

cockpit/src/subscriptions-client.js
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1516439
=> 1516439: Cockpit reports error during unregister when candlepin unavailable

Makefile, README.md, setup.py, src/subscription_manager/migrate/migrate.py, src/subscription_manager/plugins.py, src/subscription_manager/scripts/rct.py, src/subscription_manager/scripts/rhn_migrate_classic_to_rhsm.py, src/subscription_manager/scripts/rhsm_d.py, src/subscription_manager/scripts/rhsm_debug.py, src/subscription_manager/scripts/rhsm_facts_service.py, src/subscription_manager/scripts/rhsm_service.py, src/subscription_manager/scripts/rhsmcertd_worker.py, src/subscription_manager/scripts/sat5to6.py, src/subscription_manager/scripts/subscription_manager.py, src/subscription_manager/scripts/subscription_manager_gui.py, subscription-manager.spec
This does a lot for us, but especially lets the python used to run setup
automatically be the one used to run the scripts (important for Python 3
compatibility).
=> Generate bin scripts via setuptools entry_points

Makefile, subscription-manager.spec
While trying to wrap this up in a debian package, i thought, that we can use the PREFIX variable in a more standardized way along with the DESTDIR variable.
Think of DESTDIR being `/` or the location of the chroot you want to install in.
Think of PREFIX being `/usr/local/` or for packages `/usr/`.
I hope, i caught all paths here.
Ping: @kahowell
=> Fix Makefile use of $(PREFIX) and $(DESTDIR)

etc-conf/dbus/polkit/com.redhat.RHSM1.Facts.policy
This change was originally part of PR #1742.
=> Fixed indentation and deleted some white space in policy file.

Makefile
=> Fix forgotten reference to $(PREFIX) in Makefile

src/subscription_manager/cache.py, src/subscription_manager/scripts/rhsm_d.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1448313#c9
* Another case, when rhsmcertd is restarted
=> 1448313: Do not log error, when rhsmcertd is restarted

cockpit/src/Select/Select.jsx, cockpit/src/cockpit-components-dialog.jsx, cockpit/src/subscriptions-register.jsx, cockpit/src/subscriptions-view.jsx, vagrant/roles/subman-devel/tasks/main.yml
* Use React.Component at all places
* Other changes related to using classes
* Remove warning about PropTypes
* Removed warning about missing keys in register dialog
when Proxy server is used (the br was not necessary there)
* Replaced many var keyword with let keyword
* Removed other warnings
=> Use more ES6 syntax and React 0.16.0 API

subscription-manager.spec
#1743 should land first, and then I'll just change the base to master. I wanted to go ahead and get this out for folks to review early (if they'd like).
=> Package for Python 3 on Fedora

cockpit/src/index.js
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1527392
* Made index.js more compliant with ES6
=> 1527392: Clear credential data in register dialog

src/rhsm/profile.py, test/test_cache.py
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1519512
=> 1519512: Handle non-UTF8 RPM vendors

test/gui/test_mysubstab.py, test/gui/test_widgets.py, test/rhsmlib_test/test_hwprobe.py
- Missed some GUI tests in #1762
- Fixed a test that should use encode rather than decode
=> Fix Python 3 test issues

src/rhsm/connection.py, src/rhsmlib/dbus/objects/entitlement.py, src/rhsmlib/services/entitlement.py, src/subscription_manager/managercli.py, src/subscription_manager/managerlib.py, test/test_managercli.py, test/test_managerlib.py
After looking at the following PR[1], it occurred to me that we did not have an implementation on the subman side for this feature.
This PR implements RFE 1479353 using the existing candlepin query parameters.
Should the candlepin PR be accepted, I will update this PR to match the new implementation.
[1]: https://github.com/candlepin/candlepin/pull/1862
=> 1479353: Add --after option to list command

README.md, Vagrantfile
=> vagrant: Forward cockpit port on VirtualBox

cockpit/src/subscriptions-client.js
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1535974
=> 1535974: Close register dialog, when status is changed

cockpit/src/subscriptions-client.js
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1527396
=> 1527396: Subman cockpit plugin - fix registration using act. keys

Vagrantfile
* It is possible to create new VM booting from PXE server
* You have to create PXE BOOT server first using:
vagrant up pxe-server
* When PXE BOOT server is installed and running, then you can
create another VM booting from this PXE server using
vagrant up pxe-client
* The client will be kickstarted and Anaconda (GUI installer)
will start boot process, because all required settings are
present in ks.cfg configuration file.
* The client is halted at the end of installation process,
but vagrant will still wait for SSH to become available.
=> Added PXE BOOT client to the vagrant setup

.gitignore, Makefile, Vagrantfile, scripts/build_updates_img.sh
* Adds a script that takes the result of make install and
compresses it using cpio and gzip to a format suitable for
use with anaconda installer.
=> Adds tool to make updates.img file for use with anaconda

subscription-manager.spec
This allows us to continue building/packaging the python2 package
of subscription-manager-rhsm to support pulp.
See the following bug for more details:
http://bugzilla.redhat.com/show_bug.cgi?id=1551044
=> Add the option to build both {python3-,}subscription-manager-rhsm

src/subscription_manager/identity.py
Log messages about missing identity cert / key at the debug level.
=> 1559227: Do not log Error messages for missing identity cert/key

src/intentctl/cli.py, src/intentctl/intentfiles.py, test/intentctl/base.py, test/intentctl/test_intentfiles.py
- Added generic set, unset, add and remove commands to intentctl
for updating arbitrary keys in the intent.json file
=> Added generic set/unset and add/remove commands to intentctl

vagrant/roles/subman-devel/tasks/main.yml
- https://github.com/ansible/ansible/issues/37912
=> ansible-fix: fixed ansible failing during vagrant up

src/dnf-plugins/subscription-manager.py, src/plugins/subscription-manager.py, src/zypper/services/subscription-manager
* Bug fix: https://bugzilla.redhat.com/show_bug.cgi?id=1576582
=> 1576582: Make rhsm.full_fresh_on_yum=1 working again (ENT-534)

etc-conf/plugin/search-disabled-repos.conf, src/plugins/search-disabled-repos.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1571998
=> 1571998: Ignore HTB repos (ENT-533)

Vagrantfile, vagrant/roles/subman-devel/defaults/main.yml, vagrant/roles/subman-devel/tasks/main.yml
- Make our setup compatible with what is used in current forklift plugins
- Allow box YAML to define `vars` to override ansible vars
- Add a couple of new variables to make devel setup more flexible
=> Make vagrant setup more flexible

src/rhsmlib/dbus/objects/config.py, src/rhsmlib/dbus/server.py
- integrated with filesystem watcher to be fired on creation, deletion,
or modification
- watches /etc/rhsm/rhsm.conf
- need init_logger to start logging
=> ENT-475: Add signal ConfigChanged

src/rhsmlib/dbus/objects/entitlement.py, src/rhsmlib/dbus/server.py
- integrated with filesystem watcher so it is fired on creation,
deletion, or modification events
- watches rhsm.entitlementCertDir path in /etc/rhsm/rhsm.conf
- need init_logger to start logging
=> ENT-477: Add signal EntitlementsChanged

src/subscription_manager/utils.py, test/test_utils.py
The three_way_merge function takes in three dictionaries,
base, remote, and local. It returns the combination of those three
taking non-conflicting changes and additions or removals from remote
and local. Keys and values which remain in all three dictionaries are
left in the result.
=> ENT-710: Add three_way_merge utility function

src/syspurpose/cli.py
- Removed commands 'add-offerings', 'remove-offerings', 'unset-offerings'
- Added commands 'set-role' and 'unset-role'
=> ENT-731 Replaced syspurpose 'offerings' commands with 'role'

cockpit/src/cockpit-components-dialog.jsx, cockpit/src/subscriptions-client.js, src/rhsmlib/dbus/objects/config.py, src/rhsmlib/dbus/objects/entitlement.py, src/rhsmlib/dbus/server.py, src/rhsmlib/file_monitor.py, src/rhsmlib/services/entitlement.py, test/rhsmlib_test/base.py, test/rhsmlib_test/test_file_monitor.py
- related to ENT-145, ENT-474, ENT-727, ENT-573
- ENT-573: https://bugzilla.redhat.com/show_bug.cgi?id=1563785
- ENT-145: https://bugzilla.redhat.com/show_bug.cgi?id=1504588
- Cockpit gui now synced with cmdline commands related to dbus signals
- Improved Cockpit gui
- Register dialog box closes when register is completed
- Status now changes correctly
=> Integrate Dbus signals with Cockpit GUI

ansible.cfg
=> ansible vagrant QOL fixes

src/subscription_manager/managercli.py, src/subscription_manager/syspurposelib.py, test/test_managercli.py
- Adds the "addons" subcommand (and associated tests)
=> ENT-720 Adds the addons subcommand

cockpit/src/index.js, cockpit/src/subscriptions-client.js, cockpit/src/subscriptions-view.jsx, etc-conf/dbus/system.d/com.redhat.RHSM1.conf, src/rhsmlib/dbus/base_object.py, src/rhsmlib/dbus/constants.py, src/rhsmlib/dbus/objects/__init__.py, src/rhsmlib/dbus/objects/syspurpose.py, src/rhsmlib/dbus/server.py, src/rhsmlib/file_monitor.py, src/rhsmlib/services/syspurpose.py, src/subscription_manager/managercli.py, src/subscription_manager/scripts/rhsm_service.py, vagrant/roles/subman-devel/files/rhsm_service_shim.py, vagrant/roles/subman-devel/tasks/main.yml
- added syspurpose status, displaying it
- added syspurpose signal
- displaying syspurpose info
=> ENT-332: Integrate Syspurpose DBus Signal with Cockpit

Makefile, rpmlint.config, setup.py, src/subscription_manager/repolib.py, src/subscription_manager/version.py, subscription-manager.spec, test/test_repolib.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1581445
* Moved dnf plugins to /usr/lib/python3.6/site-packages/dnf-plugins
=> 1581445: ENT-564: rhsm configuration manage_repos is not working on RHEL8

syspurpose/src/syspurpose/cli.py
=> Adds the addons set of commands to syspurpose

syspurpose/setup.py
Fixes compat with older setuptools.
=> Remove extraneous include in setup()

src/daemons/rhsmcertd.c
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1602702
=> 1602702: rhsmcertd did not close lock file; ENT-736

.tito/releasers.conf
=> Start releasing to f29

src/dnf-plugins/product-id.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1620136
* It is necessary to create own base object and fill it with
fresh data in some cases, because base object provided by
dnf.Plugin provides obsolete and incomplete data. This
can happen, when user is running dnf command at the first time
with subcommand "remove" and there is no cache of package-repo
mapping.
* Creating two base object is not safe. So we try to avoid it
and cache file with package-repo mapping is used.
* When dnf command is used, then it is necessary to re-read all
repo files, because list of enabled repos is empty during
dnf remove.
* It is also necessary to create own sack object to get
complete list of installed packages.
* See also: https://bugzilla.redhat.com/show_bug.cgi?id=1622153
=> 1620136: dnf plugin deletes prod cert as expected; ENT-773

etc-conf/syspurpose/valid_fields.json
- Various syspurpose values from valid_fields.json have been updated
to be in line with those specified in the original requirements
doc
=> 1621783: Updated syspurpose fields to match expected values (ENT-899)

src/rhsm/profile.py, test/test_cache.py
We need subscription manager to send us information on the modules that
got enabled, modules that got disabled and modules who's status is
unknown (i.e neither enabled or disabled aka default)
=> Add module enabled and disabled information

Makefile, debian-stuff/80package-profile-upload, debian-stuff/deb_package_profile_upload, debian-stuff/katello, setup.py, src/subscription_manager/repofile.py, src/subscription_manager/repolib.py, src/subscription_manager/utils.py, src/zypper/services/rhsm, test/test_repolib.py
Finally found the time to rebase this stuff.
I guess, the debian-stuff directory will move to https://github.com/Katello/katello-host-tools or the yet to come foreman-host-tools.
Would be great to hear some feedback.
=> WIP: apt support

src/rhsm/config.py, src/subscription_manager/scripts/rhsmcertd_worker.py
Allow force to bypass disable on single run
=> Disable rhsmcertd by config entry

src/rhsm/connection.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1599801
=> 1599801: fix Python2 and Python3 incompatibility

syspurpose/src/syspurpose/cli.py, syspurpose/src/syspurpose/files.py
- The syspurpose tool will now log all communication with the server
in the rhsm.log
- Added a lot of log statements in the key actions of the syspurpose
tool itself, to help with debugging.
=> 1633277: syspurpose tool will now log in rhsm.log [ENT-974]

Makefile, build_ext/build_ext/i18n.py, subscription-manager.spec, syspurpose/po/de.po, syspurpose/po/es.po, syspurpose/po/fr.po, syspurpose/po/it.po, syspurpose/po/ja.po, syspurpose/po/ko.po, syspurpose/po/pt_BR.po, syspurpose/po/ru.po, syspurpose/po/zh_CN.po, syspurpose/po/zh_TW.po, syspurpose/setup.py
* Add missing aspects to makefile and syspurpose setup.py
to ensure the syspurpose translations are included in
the resulting rpm
=> 1658383: Ensure syspurpose has translations

src/dnf-plugins/product-id/product-id.c, src/dnf-plugins/product-id/product-id.h, src/dnf-plugins/product-id/productdb.c, src/dnf-plugins/product-id/test-product-id.c
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1666373
* Similar to BZ bug 1661219 fixed in PR #2002, but this is bug fix
for libdnf plugin
=> 1666373: Do not delete product certs for disabled repos; ENT-1034

subscription-manager.spec
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1660520
=> 1660520: Modify spec file to require right version of libdnf.

src/subscription_manager/cache.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1666516
=> 1666516: Don't send package list, when report_package_profile=0; ENT-1097

etc-conf/rhsm.conf
/me facepalm
We forgot the default value in /etc/rhsm/rhsm.conf for proxy_scheme... :(
=> 1654531: Add default for proxy_scheme in rhsm.conf

syspurpose/src/syspurpose/cli.py
We were making two calls to syspurposestore.sync (one in the show_command function and one in the main function). The net effect was that locks on the consumer could be created preventing updates until the first sync was complete server side.
=> 1676982: Do not make duplicate sync calls on syspurpose show

syspurpose/src/syspurpose/files.py, syspurpose/test/syspurpose/test_syspurposefiles.py
This has been tested against stage and Sat 6.5.
=> 1666845: Do not set role or usage to the empty string

src/dnf-plugins/product-id/product-id.c
* Bug fix introduced by Chris in this PR:
https://github.com/candlepin/subscription-manager/pull/2048
Was lost in solving merge conflict in this PR:
https://github.com/candlepin/subscription-manager/pull/2044
* I added more checks for NULL pointers.
=> Restore bug fix of product-id lost during solving merge conflict.

src/dnf-plugins/product-id/productdb.c, src/dnf-plugins/product-id/test-productdb.c
* This issue has been found out by Rehana, when she edited
/var/lib/rhsm/productid.js and she corrupted this file.
* When the file is corrupted in some way, then it can
crash packagekit daemon.
* This commit makes reading of this file more reliable.
=> Make reading of productdb more robust and reliable.

cockpit/lib/form-layout.less, cockpit/lib/variables.less, cockpit/package.json, cockpit/src/subscriptions-register.jsx, cockpit/src/subscriptions.css, cockpit/webpack.config.js, cockpit/yarn.lock, subscription-manager.spec
Fix the alignment and layout issues by porting to cockpits
form-layout classes.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1582244
=> cockpit plugin: Fix alignment and layout issues in register dialog

src/subscription_manager/cache.py, src/subscription_manager/gui/managergui.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1709728
=> 1709728: Dialog with proxy conf didn't pop-up; ENT-1333

po/fr.po, src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1703054
=> 1703054: Do not crash sub-man during unregistering; ENT-1288

src/subscription_manager/gui/mysubstab.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1703768
=> 1703768: Display 'Status Details' correctly in GUI; ENT-1305

src/dnf-plugins/product-id/README.md
* Use benefits of changes in candlepin deploy script.
=> Updated documentation about libdnf (testing section).

src/rhsm/profile.py, src/rhsm/utils.py
To reliably reproduce, the BZ's description was sufficient for me. I made an internal RHEL7 vagrant box that can be used to reproduce and then see the fix, please reach out to me for details.
Also, I found that you can reproduce by attempting to attach the second pool over and over :smile:.
=> 1697563: Suppress output when collecting profile

src/subscription_manager/managercli.py
Updating the information, from `System Type` to `Entitlement Type` on `subscription-manager list --consumed` or `subscription-manager list --available`
=> Updated from System Type to Entitlement Type

cockpit/package.json, cockpit/src/index.js, cockpit/src/subscriptions-client.js, cockpit/src/subscriptions-register.jsx, cockpit/src/subscriptions-view.jsx, cockpit/src/subscriptions.css, cockpit/yarn.lock, src/rhsmlib/dbus/service_wrapper.py, src/rhsmlib/dbus/util.py, src/subscription_manager/scripts/rhsm_service.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1703148
* When golden ticket is used, then registration dialog should be
closed, when registration is successful. Auto-attach is not
possible to finish in such case. Thus warning dismissable
message is displayed on the top of the page.
* Fixed closing of dismissable error message
* Fixed several CSS style imperfections.
=> 1703148: Fix cockpit plugin, when golden ticket is used; ENT-1287

.cockpit-ci/run, .gitignore, integration-tests/check-subscriptions, integration-tests/run, integration-tests/vm.install
This also brings the necessary infrastructure.
=> test: Add check-subscriptions to test the Cockpit UI

cockpit/src/subscriptions-client.js
* Mark several strings for translation and address several
Bugzilla bug reports
* Placeholder: https://bugzilla.redhat.com/show_bug.cgi?id=1689974
* List of bug reports:
https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&columnlist=product%2Ccomponent%2Cassigned_to%2Cbug_status%2Cshort_desc%2Cchangeddate%2Ccf_pm_score%2Cpriority%2Cbug_severity%2Cflagtypes.name%2Ctarget_release&f1=short_desc&f3=OP&f4=component&f5=component&f6=component&j3=OR&known_name=RHSM%20-%20General%20Untriaged&list_id=10094495&o1=substring&o4=equals&o5=equals&o6=equals&product=Red%20Hat%20Enterprise%20Linux%208&query_based_on=RHSM%20-%20General%20Untriaged&query_format=advanced&v1=ALL%20LANG&v4=python-rhsm&v5=subscription-manager&v6=virt-who
=> 1689974: Mark several strings for translation; ENT-1246

Makefile, subscription-manager.spec
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1728054
* Make installation of container plugin (docker) optional
* It is not installed by default on RHEL8
=> 1728054: Do not install container plugin on RHEL8; ENT-1488

syspurpose/po/de.po, syspurpose/po/es.po, syspurpose/po/fr.po, syspurpose/po/it.po, syspurpose/po/ja.po, syspurpose/po/keys.pot, syspurpose/po/ko.po, syspurpose/po/pt_BR.po, syspurpose/po/ru.po, syspurpose/po/zh_CN.po, syspurpose/po/zh_TW.po
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1663432
* Updated keys.pot
* Updated *.po files (existing *.po files merged with new keys.pot)
* TODO: update *.po file, when all strings are translated
=> 1663432: Updated keys.pot for syspurpose CLI; ENT-1246

etc-conf/rhsmd.cron
Also corrected pkill to be specific to the actual rhsmd process
=> 1752059: corrected cron receving stdout mail for rhsmd run

src/rhsm/connection.py, src/subscription_manager/managercli.py, src/subscription_manager/managerlib.py, src/subscription_manager/repolib.py
Modified as per
https://bugzilla.redhat.com/show_bug.cgi?id=1520383#c13
=> 1520383: Update to logging levels

subscription-manager.spec
=> On sles15+ require python2-python-dateutil

src/dnf-plugins/product-id.py
There were two weird cases exposed when trying to apply an errata to a system using Satellite:
1) self.base.transaction can be None, which afaict has the same meaning as it's length being 0. 
2) Our cache file might not exist, which we should not scare anyone with a traceback / exception in the log (if we can detect that case, which we can).
This PR fixes those two issues enabling a smoother overall experience.
=> 1750546: Fix minor product-id issues

cockpit/lib/cockpit-components-dialog.css, cockpit/lib/cockpit-components-dialog.jsx, cockpit/src/index.js, cockpit/src/insights.jsx
And move it to lib/.
This gives us support for standard JavaScript promises and dynamic
cancelling.
=> cockpit: Update cockpit-component-dialog

cockpit/lib/packagekit.js, cockpit/src/index.js, cockpit/src/insights.jsx, cockpit/src/subscriptions-client.js, cockpit/src/subscriptions-register.jsx, integration-tests/check-subscriptions, integration-tests/packagelib.py
=> cockpit: Install insights-client package on demand

cockpit/package.json, cockpit/yarn.lock
* https://github.com/candlepin/subscription-manager/network/alerts
- braces
- js-yaml
- jquery
- randomatic
- deep-extend
- cryptiles
- lodash
- hoek
- moment
=> Security upgrades of javascript packages

po/zanata.xml, syspurpose/po/zanata.xml
- Switched url to fedora zanata
- Removed deprecated locales block
=> ENT-1682: Update build process to use Fedora Zanata

integration-tests/packagelib.py, integration-tests/run
This fixes tests for the rhel-8-2 image.
=> cockpit: Sync with current Cockpit test API

src/subscription_manager/logutil.py, test/test_logutil.py
Previously to handle the case of not being able to create
the /var/log/rhsm/rhsm.log file to log to, we were logging an error level message
by doing `logging.error("Our error message here"). Doing that at a point where
there is nothing configured for the root logger causes a StreamHandler to be added to
the root logger. That then caused all dnf python logging to be written to stderr.
To be able to output the log messages which happen during set up, we queue the errors
and log them using our resulting logger which has been setup (after adding our own
StreamHandler but not to the root logger).
=> 1782910: Log errors in logging set up after set up completes

cockpit/src/Select/Select.jsx, cockpit/src/index.js, cockpit/src/subscriptions-client.js, cockpit/src/subscriptions-register.jsx, cockpit/src/subscriptions-view.jsx, cockpit/src/subscriptions.css, integration-tests/check-subscriptions, src/rhsmlib/dbus/server.py, src/rhsmlib/services/entitlement.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1751200
* Modified registration dialog according this design mockup:
https://github.com/cockpit-project/cockpit-design/blob/master/subscriptions/subscription-authentication.png
* Fixed width of <select/> element
* Auto-attaching is optional now
* Dialog shows information about current process next to spinner
during registration process
* Fixed some CSS issues and made registration dialog more slick
=> 1751200: Cockpit plugin: select registration method; ENT-1651

etc-conf/logrotate.conf
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1803783
* Added copytruncate option to our configuration file for
logrotate.
=> 1803783: Added copytruncate option to logrotate conf file; ENT-2114

etc-conf/subscription-manager.completion.sh, man/subscription-manager.8, setup.cfg, src/rhsm/connection.py, src/rhsmlib/services/register.py, src/subscription_manager/cp_provider.py, src/subscription_manager/exceptions.py, src/subscription_manager/managercli.py, test/rhsm/unit/connection_tests.py, test/test_managercli.py
Dependent PR [candlepin/candlepin#2385](https://github.com/candlepin/candlepin/pull/2385)
Command to execute : `subscription-manager register --token "<Refresh-Token>"`
GET _Refresh-Token_ from candlepin/token endpoint
=> ENT-1440 Adding --token option in subscription-manager

Makefile, debian-stuff/katello, src/subscription_manager/repofile.py
Some fixes I stumbled over while trying to build `subscription-manager` for Ubuntu 20 with pyhton3
=> Debian python3 fixes

src/rhsmlib/dbus/objects/config.py
* https://bugzilla.redhat.com/show_bug.cgi?id=1774187
* When something is changed using D-Bus method Set() or SetAll()
in section logging, then it is neccesarry to re-initialize
logger to take effect. Without this change it was necessary
to restart rhsm.service
=> 1774187: Reinitialize logger, when necessary; ENT-1960

po/README.md, po/keys.pot
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1796833
* Added README.md with instruction how to create keys.pot
=> 1796833: New keys.pot with new strings; ENT-2058

src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1816926
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1818769
* This bug was introduced in this PR:
https://github.com/candlepin/subscription-manager/pull/2215
- We tried to reduce number of REST API calls, but it
had bad side effect for attach command with option --auto
* When we do auto-attach in attach command, then we do extra
call to get information if system is compliant
=> 1816926: Fix "attach --auto" command; ENT-2242

src/certificate.c, src/dnf-plugins/product-id/productdb.c
This fixes a few errors that are uncovered when compiling with clang.
=> Clang fixes

debian-stuff/katello
I should do more python programming :wink:
introduced with #2226
=> Fix apt-plugin for subscription-manager

src/rhsm/connection.py
* Some changes introduced in this PR: #2197 have been lost
during merging #2129 to master. This PR should fix this issue
* Running: subscription-manager list --available was terminated
with following error:
getPoolsList() got an unexpected keyword argument 'page'
=> Fix issue with getPoolsList

Makefile
Fix build bug for Debian and Ubuntu
Makefile:134: *** Recursive variable 'EXCLUDE_PACKAGES' references itself (eventually). Stop.
=> Bug fix of Makefile for Debian

src/rhsm/connection.py, src/subscription_manager/repofile.py, src/subscription_manager/utils.py, syspurpose/src/syspurpose/files.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1700441
* When /etc/yum.repos.d is missing, then this directory is created
* When syspurpose directories are missing, then these directories are
automatically created too
=> 1700441: Create directories, when missing; ENT-2461

containers/Containerfile, containers/README.md, containers/build
* Added README.md to containers directory
* Added many rpm packages to containers/Containerfile to be able
to build and run subscription-manager
=> Added basic documentation about creating podman test env; ENT-2332

src/rhsm/ourjson.py, test/rhsm/unit/json_tests.py
for datetime.datetime is not JSON serializable.
=> 1845399: List available subscriptions ondate option fails

src/rhsm/connection.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1838423
* The list of releases is simple plaintext and not json document
=> 1838423: Fix getting list of releases from CDN; ENT-2601

src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1859532
* When you register and then you set wrong configuration for
proxy server, then usage/list/addon/service-level --list
printed traceback to console
* When you try to reproduce this BZ bug report, remember
to delete cache file: /var/lib/rhsm/cache/valid_fields.json
=> 1859532: No traceback, when wrong proxy conf is used; ENT-2654

src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1862419
* Caused by refactoring in PR #2283
=> 1862419: Make repo-override working again; ENT-2710

src/subscription_manager/managercli.py, syspurpose/src/syspurpose/files.py, test/test_managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1862425
* This regresion was caused by refactoring.
* Fixed unit test that should cover this issues
* Added one more unit test
=> 1862425: Fix setting service-level; ENT-1862425

src/subscription_manager/i18n.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1841601
* When locale specified in LANG is not listed in `locale -a`, then
defulat locale (C) was set, but it was set without UTF-8
encoding. It caused traceback during attempt to log localized
message to rhsm.log
* Do not print warning about unsupported locale, when this locale
is not supported by subscription-manager.
* When locale is not listed by `locale -a`, but is it supported
by subscription-manager, then try to use better messaging
=> 1841601: Set default encoding properly; ENT-2499

subscription-manager.spec
Successful scratch build: https://brewweb.engineering.redhat.com/brew/taskinfo?taskID=30992901
=> Additional updates for fedora

Jenkinsfile, jenkins/nose-tests.sh, jenkins/python3-tests.sh, jenkins/stylish-tests.sh, jenkins/suse-tests.sh, jenkins/tito-tests.sh
This is in conjunction with https://github.com/candlepin/candlepin-jobs/pull/61
This may conflict with: https://github.com/candlepin/candlepin-jobs/pull/60
Note that there will need to be some management of existing PRs once these two are accepted and merged.  We'll be in a state were the old tests will still exist - which have to be manually deleted/disabled - and any branch that has this Jenkinsfile will be running both the new and old stuff until the old jobs are disabled.
=> adding Jenkinsfile

src/subscription_manager/managercli.py, test/test_managercli.py
--org was not allowed on command line with --set option
org was requested when --set was called and not registered
=> 1875595: Service-Level set issues

test/zypper_test/test_serviceplugin.py
* Do not use rhsm and sub-man Python modules installed to the
system, but use code from the PR
=> Try to fix suse test.

subscription-manager.spec
* When Fedora 33 or higher is used, then RPM containing only
libdnf plugin is build (libdnf-plugin-subscription-manager)
and DNF plugins (product-id and subscription-manager) are
part of subscription-manager RPM
* When RHEL8 is used, then dnf and libdnf modules are included
in dnf-plugin-subscription-manager RPM.
* This approach makes future cherry-picking easier
=> Fix building libdnf-plugin RPM; ENT-3192

Jenkinsfile
This removes all tests except those relevent to the release
target for this branch.
=> Remove unnecessary tests

src/subscription_manager/managercli.py
Same as https://github.com/candlepin/subscription-manager/pull/2374
=> 1904541: Catch ProxyException when checking available orgs

src/subscription_manager/cache.py, src/subscription_manager/injectioninit.py, src/subscription_manager/utils.py, test/fixture.py, test/stubs.py
This is a backport of #2402 to the subscription-manager 1.24 branch.
=> 1886772: Query the content access mode no more than once every 4 hours

Jenkinsfile, build_ext/build_ext/lint.py, etc-conf/cloud/aws.conf, etc-conf/rhsm.conf, etc-conf/rhsmcertd.completion.sh, jenkins/python3-tests.sh, jenkins/stylish-tests.sh, jenkins/tito-tests.sh, man/rhsm.conf.5, man/rhsmcertd.8, src/daemons/rhsmcertd.c, src/rhsm/config.py, src/rhsm/connection.py, src/rhsmlib/cloud/README.md, src/rhsmlib/cloud/collector.py, src/rhsmlib/cloud/detector.py, src/rhsmlib/cloud/providers/aws.py, src/rhsmlib/cloud/providers/azure.py, src/rhsmlib/cloud/providers/gcp.py, src/rhsmlib/cloud/utils.py, src/rhsmlib/facts/all.py, src/rhsmlib/facts/cloud_facts.py, src/rhsmlib/facts/collector.py, src/rhsmlib/facts/host_collector.py, src/rhsmlib/services/register.py, src/subscription_manager/scripts/rhsmcertd_worker.py, subscription-manager.spec, test/rhsmlib_test/test_aws_instance.py, test/rhsmlib_test/test_cloud.py, test/rhsmlib_test/test_register.py
Backport the cloud auto registration work to subman 1.27.
=> [1.27] Cloud auto registration

src/daemons/rhsmcertd.c
* Interval for checking certificate was used for
auto-registration too.
=> Fix issue with auto-registration interval.

src/daemons/rhsmcertd.c
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1922173
=> 1922173: Repeat auto-register only, when first attempt fail

src/subscription_manager/managercli.py
Will use is_simple_content_mode to determine state in all cases
Added comment to output to acknowledge the lack of cert in simple
content access mode
=> 1886772: Update SCA mode detection on status screen

src/rhsm/logutil.py, test/test_logutil.py
Check the log level set by the user,if it is not valid: tell the user it is invalid and setting to INFO, tell the user how to set it to a valid level.
=> 1608820: Check the Log Level to make sure it is valid, if not set it to INFO

src/rhsmlib/facts/hwprobe.py, test/rhsmlib_test/test_hwprobe.py
=> 1928667: Added UTC to the last_boot fact (ENT-3566)

src/rhsm/logutil.py, test/test_logutil.py
Redid this to be against the correct branch instead of master
=> 1920020: Set default_log_level to INFO when an invalid value is passed on the command line

src/rhsm/connection.py
same change as ENT-3630 except this is for master
=> 1682943: add space to message to separate 2 sentences

syspurpose/man/syspurpose.8
Change foo to usage and quote the commands
=> 1634780: typo in syspurpose man page

src/subscription_manager/cli_command/abstract_syspurpose.py
Once merged, the other branches will need to rebase on master
=> Correction for condition that was breaking 3 nosetests

cockpit/src/insights.jsx, src/rhsmlib/dbus/objects/syspurpose.py, src/subscription_manager/gui/mysubstab.py
Spotted when reviewing other PRs and/or translating.
=> Few plural forms fixes

src/subscription_manager/cli_command/abstract_syspurpose.py
Suppress the warning message when setting syspurpose values
=> 1879856: suppress the warning message when setting syspurpose values

etc-conf/subscription-manager.completion.sh
There is already the helper function for it, it was simply not exposed
as available subcommand.
Card ID: ENT-3702
=> 1940658: bash: complete also the syspurpose subcommand

src/syspurpose/files.py
No-op change to avoid using a plain value.
=> Replace hardcoded errno value with constant

Jenkinsfile
=> adding timoeout to jenkins pipeline

src/rhsmlib/facts/hwprobe.py, test/rhsmlib_test/test_hwprobe.py
Tweak the way we collect facts for IP v4/v6 addresses: instead of
directly adding the information to the dictionary of the returned facts,
collect them before and then assemble them as facts. This has two
advantages:
- we have all the collected keys at once, so we can use the first item
for single-value facts (like the primary IP v4/v6 address)
- there is no need to keep updating the facts dictionary
Adapt test_network_interfaces_multiple_ipv4 to the new behaviour, and
add a new test case for multiple IP v6 addresses of the same scope.
Card ID: ENT-1591
(cherry picked from commit e446fb20d81464e32af424e96475a776882c5134)
Backport of #2592 to 1.28.
=> [1.28] 1898552: refactor/fix collection of IP v4/v6 address info

etc-conf/subscription-manager.completion.sh
These old aliases were removed.
=> 1953047: bash: drop completion for subscribe & unsubscribe

.flake8, build_ext/setup.py, jenkins/python3-stylish-tests.sh, jenkins/python3-tests.sh, src/rhsm/connection.py, src/rhsm/m2cryptossl.py, src/subscription_manager/scripts/rhn_migrate_classic_to_rhsm.py, src/subscription_manager/scripts/rhsm_facts_service.py, src/subscription_manager/scripts/sat5to6.py, src/subscription_manager/scripts/subscription_manager_gui.py, test-requirements.txt, test/rhsm/unit/connection_tests.py, test/test_ostree_content_plugin.py
Various small improvements for build/CI, in preparation of the switch of the stylish job to Python 3.
=> Miscellaneous build/CI improvements

src/rhsm/certificate2.py
* Cherry-pick PR to master branch
* Card ID: ENT-3807
* Original PR: #2466 was created against subscription-managaer-1.24 branch
=> 1896715: [cherry-pick] Master: Set proper read permissions on certs

src/rhsm/certificate2.py
* Cherry-pick PR to 1.28 branch
* Card ID: ENT-3807
* Original PR: #2466 was created against subscription-managaer-1.24 branch
=> 1896715: [Cherry-pick 1.28] Set proper read permissions on certs

containers/Containerfile, containers/README.md
* Use dnf and yum command
* Removed Python2 packages
* Fixed small mistake in README file
=> Updated Containerfile to use Fedora 34

man/rhsm.conf.5
Add a brief description of the format of the file, mentioning a couple
of known limitations.
=> 1968420: improve description of rhsm.conf format

subscription-manager.spec
uninstall the subscription-manager-initial-setup-addon and rhsm-gtk packages when installing or updating.
=> 1941904:  Uninstall Packages

src/cloud_what/providers/aws.py, src/rhsm/profile.py
* Original PR: #2556
- Included only one commit: 91a13e9e141869160a786edde20457bc388f36ad
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1924126
* Card ID: ENT-3583
* Fix AWS RHUI repo url, when data for profile are gathered.
Replace REGION with value provided in AWS metadata
=> [1.28] 1924126: Fix profile upload on AWS systems

src/subscription_manager/cli_command/override.py
* Card ID: ENT-4228
Following 0b0f38b this part was accidentally missed.
=> ENT-4228: Format rhsmlib exception

.flake8, setup.py, src/rct/cli.py, src/rhsm/connection.py, src/rhsm/https.py, src/rhsmlib/facts/hwprobe.py, src/subscription_manager/base_action_client.py, src/subscription_manager/certdirectory.py, src/subscription_manager/cli_command/abstract_syspurpose.py, src/subscription_manager/cli_command/service_level.py, src/subscription_manager/cli_command/unregister.py, src/subscription_manager/i18n.py, src/subscription_manager/repofile.py, src/subscription_manager/scripts/package_profile_upload.py, src/subscription_manager/scripts/rct.py, src/subscription_manager/scripts/rhsm_debug.py, src/subscription_manager/scripts/rhsm_service.py, src/subscription_manager/scripts/rhsmcertd_worker.py, src/subscription_manager/scripts/subscription_manager.py, src/subscription_manager/utils.py, src/syspurpose/utils.py, test/__init__.py, test/cli_command_test/test_import_cert.py, test/syspurpose/base.py, test/test_certlib.py, test/test_po_files.py, test/test_rhsm_debug_command.py
* Card ID: ENT-4091
* Card ID: ENT-4090
* Card ID: ENT-4089
This series of commits resolves some of the flake8 issues we have set to be ignored in the past.
```
F841: local variable is assigned to but never used
F821: undefined name
E741: ambiguous variable name
```
=> Fix some flake8 issues

containers/Containerfile
Experiment if it is possible to remove more packages from `Containerfile`.
=> Removed more packages from Containerfile to reduce build time.

integration-tests/check-subscriptions, integration-tests/run, test/files/mock-insights
I am trying to enable rhel-8.4 tests for this branch, lets see if this is enough
=> [1.28.13] Enable cockpit tests

.flake8, example-plugins/facts.py, setup.py, src/content_plugins/container_content.py, src/content_plugins/ostree_content.py, src/rct/printing.py, src/rhsm/certificate2.py, src/rhsm/https.py, src/rhsmlib/facts/dmiinfo.py, src/rhsmlib/facts/hwprobe.py, src/subscription_manager/api/__init__.py, src/subscription_manager/lock.py, src/subscription_manager/scripts/package_profile_upload.py, src/subscription_manager/scripts/rct.py, src/subscription_manager/scripts/rhsm_debug.py, src/subscription_manager/scripts/rhsm_facts_service.py, src/subscription_manager/scripts/rhsm_service.py, src/subscription_manager/scripts/rhsmcertd_worker.py, test/__init__.py, test/test_cpuinfo.py
* Card ID: ENT-4083
E402: Module level import not at top of file
=> ENT-4083: Fix flake8 error E402

.flake8, src/subscription_manager/plugin/container/__init__.py
* Card ID: ENT-4085
E713: Test for membership should be 'not in'
=> ENT-4085: Fix flake8 error E713

.tito/lib/rhsmtagger.py, src/rct/manifest_commands.py, test/fixture.py, test/rhsmlib_test/test_hwprobe.py, test/stubs.py, test/syspurpose/base.py, test/test_plugins.py, test/test_rct_manifest_command.py, test/test_repolib.py
=> ENT-4275: Switch away from six.BytesIO and six.StringIO

src/subscription_manager/certlib.py, test/test_certlib.py
=> 1719690: Update to message formatting [m]

subscription-manager.spec
* Original PR provided by Philipp Seiler <p.seiler@linuxmail.org>
- PR: #2842
- Commit: 1fd20198fd8c4f8e9e1b84484e06d75858ca4b38
* Simplified this PR due to another PR provided by Pino #2854
* Fixed few issues from origin PR
* SUSE specific parts are grouped together
* We build only 4 packaged for SUSE. Thus it was possible to remove
{suse_version} from many places, because it was useless
=> More SUSE compliance

Jenkinsfile
I created this PR to test some quick workaround.
=> Try to not use junit('coverage.xml')

etc-conf/subscription-manager.completion.sh, man/subscription-manager.8, src/rhsm/connection.py, src/rhsmlib/services/register.py, src/subscription_manager/cli_command/environments.py, src/subscription_manager/cli_command/identity.py, src/subscription_manager/cli_command/register.py, test/cli_command_test/test_register.py, test/rhsmlib_test/test_register.py, test/stubs.py, test/test_environments.py, test/test_registration.py
Once this is reviewed, please merge. We want it tested against non-multi candlepin also so it is not waiting for the Candlepin work to be finished.
=> Feature branch for multi-environment changes

src/rhsm/certificate2.py, src/rhsm/connection.py, src/rhsm/profile.py, src/rhsmlib/facts/dmiinfo.py, src/rhsmlib/services/entitlement.py, src/subscription_manager/injection.py, src/subscription_manager/printing_utils.py, src/subscription_manager/productid.py, src/subscription_manager/release.py, test/modelhelpers.py, test/test_entcertlib.py, test/test_ostree_content_plugin.py, test/test_rhsm_debug_command.py
=> ENT-4587: Switch away from six types

cockpit/src/subscriptions-client.js, src/rhsmlib/dbus/objects/config.py, src/rhsmlib/dbus/objects/register.py, src/rhsmlib/dbus/server.py, src/rhsmlib/file_monitor.py, src/rhsmlib/services/attach.py, src/rhsmlib/services/entitlement.py, src/rhsmlib/services/products.py, src/rhsmlib/services/register.py, src/rhsmlib/services/syspurpose.py, src/subscription_manager/cache.py, src/subscription_manager/cert_sorter.py, test/rhsmlib_test/test_register.py, test/test_cache.py
Backport of PR #2860 and PR #2910 to 1.28.
=> 1955480: Backport of D-Bus registration

src/rhsm/connection.py
* Card ID: ENT-4671
This is a backport of 1366b13 (PR #2951).
- Show proxy information if SUBMAN_DEBUG_PRINT_REQUEST is set.
- Save optional tracebacks to /tmp/rhsm/, not /tmp/sub-man/
(this makes our directory names more predictable).
- Only create /tmp/rhsm/ directory if we want to save some files
there (e.g. don't create it only because we enabled debug prints).
- Use pathlib.Path to write the output, instead of tempfile.
=> [1.28] ENT-4671: Improve debug logging to stdout

etc-conf/subscription-manager.completion.sh, man/subscription-manager.8, src/rhsm/connection.py, src/rhsmlib/services/register.py, src/subscription_manager/managercli.py, test/rhsmlib_test/test_register.py, test/stubs.py, test/test_environments.py, test/test_registration.py
This is the backport of:
- PR #2920
- PR #2963
- PR #2967
Before merging, make sure that it is expected and we are satisfied with its inclusion based on its testing in main.
=> 1994056: Multiple environment capability [1.28]

Makefile, src/cloud_what/README.md, src/cloud_what/_base_provider.py, src/cloud_what/provider.py, src/cloud_what/providers/aws.py, src/cloud_what/providers/azure.py, src/cloud_what/providers/gcp.py, subscription-manager.spec, test/cloud_what/test_cloud_what.py
* Card ID: ENT-4645
* Only source code of cloud-what Python package was back-ported
to support Python 2.7 and related unit tests. It means that
no f-string is used (method format() is used instead). No
type hints are used. It was also necessary to use update()
method for dictionary, function bytes() does not have
encoding and json module does not have any special exception.
* All unit tests works as expected.
* I did smoke tests on AWS and Azure and the code works there
without any problem.
=> Back-ported cloud-what for Python 2.7

test/cloud_what/test_cloud_what.py
* When you created some custom facts e.g. /etc/rhsm/facts/foo.facts
and you added some facts related to public clouds like:
{"dmi.chassis.foo": "microsoft", "virt.host_type": "hyperv",
"virt.is_guest": true, "dmi.chassis.bar": "azure"}, then
unit tests were influenced by this file with custom facts.
* Added another mock to avoid this issue.
* Added one more unit test for overriding of host facts by
custom facts.
=> Custom facts should not influence unit tests of cloud-what

etc-conf/rhsm.conf, man/rhsm.conf.5
* Backported few fixes of grammar mistakes from #3011
=> Fix few grammar mistakes in rhsm.conf and man page

.flake8, jenkins/stylish.sh, test/test_rhsm_debug_command.py
- remove one flake8, amending commit afdeb6aa9640afa34ec93e0781585d59d51e3c6a
- drop no more needed stuff from `.flake8`
- make sure that the stylish CI script actually fails on flake8 issues
=> Small flake8 changes

po/keys.pot
Notable change: the removal of the cockpit messages.
=> New extraction for translatable strings

.flake8, src/syspurpose/files.py
* Card ID: ENT-4088
E731: Do not assign a lambda expression, use a def
=> ENT-4088: Fix flake8 error E731

etc-conf/rhsm-debug.completion.sh
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2096446
* Card ID: ENT-5111
=> 2096446: Make 'rhsm-debug' autocomplete --no-progress-messages

src/subscription_manager/repolib.py, test/test_repolib.py
* Card ID: ENT-5215
- Cherry picked ab708de4289c07f8d8394c7d1e18961a42388f4d
- Cherry picked 33438f3e44db39725b721520593a311c4da25b92
Backport of PR #3083 and PR #3084.
=> [1.28] ENT-5215: Handle errors raised in DNF plugin

src/subscription_manager/cli_command/attach.py, src/subscription_manager/cli_command/cli.py, src/subscription_manager/cli_command/register.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2094942
* Card ID: ENT-5115
* Changed warning message according suggestion in BZ bug report.
* Refactored code a little (fixed typo in method name)
=> 2094942: [RFE] Improve the message, when  SCA is enabled

INSTALL.md, TESTING.md, pytest.ini
This is a side result of updating DBus tests.
=> Update documentation of setup and tests

src/subscription_manager/cli_command/cli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2094942
* Card ID: ENT-5411
=> 2094942: Improve warning message (auto-attach in SCA mode)

src/rhsmlib/facts/all.py, src/rhsmlib/facts/cleanup.py, src/rhsmlib/facts/cloud_facts.py, src/rhsmlib/facts/collection.py, src/rhsmlib/facts/collector.py, src/rhsmlib/facts/cpuinfo.py, src/rhsmlib/facts/custom.py, src/rhsmlib/facts/dmidecodeparser.py, src/rhsmlib/facts/dmiinfo.py, src/rhsmlib/facts/firmware_info.py, src/rhsmlib/facts/host_collector.py, src/rhsmlib/facts/hwprobe.py, src/rhsmlib/facts/insights.py, src/rhsmlib/facts/kpatch.py, src/rhsmlib/facts/pkg_arches.py, src/rhsmlib/facts/virt.py
=> ENT-5102: Type-hint rhsmlib/facts

src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2097672
* Manual backport of original PR: #3138
* Original commit: 2e62d0f4bb422bc1191f2d664a70dc292294af0a
* Card ID: ENT-5411
=> 2097672: [1.28] Improve warning message (auto-attach in SCA mode)

src/subscription_manager/cli_command/org.py
- Resolves additional issue discovered in previously merged PR: https://github.com/candlepin/subscription-manager/pull/3148#issuecomment-1289262771
- BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2097679
- Card ID: ENT-5117
=> 2097679: Additional fix for non-interactive parameters

.github/workflows/libdnf.yml
* Card ID: ENT-5543
Requires #3208 to be merged first.
=> ENT-5543: Test libdnf plugin using GitHub Actions

.github/workflows/tito.yml
=> ENT-5542: Build package using GitHub Actions

.github/workflows/tito.yml
=> [1.28] ENT-5542: Build package using GitHub Actions

.github/workflows/libdnf.yml, src/daemons/rhsmcertd.c, src/dnf-plugins/product-id/CMakeLists.txt, src/dnf-plugins/product-id/product-id.c, src/dnf-plugins/product-id/product-id.h, src/dnf-plugins/product-id/productdb.c, src/dnf-plugins/product-id/productdb.h, src/dnf-plugins/product-id/test-product-id.c, src/dnf-plugins/product-id/test-productdb.c
=> [1.28] Test libdnf plugin using GitHub Actions 

src/subscription_manager/cert_sorter.py
In SCA mode, the compliance status from Candlepin does not include any products. Because of that, the installed products will be considered as "unentitleed", being logged as such.
Since this situation is expected, avoid collecting unentitled products from the installed products when in SCA mode.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1982670
(cherry picked from commit ff10c63cbe3822e927a943b24af4e22a35f43dc5)
Backport of PR #3226 to 1.28.
=> [1.28] 1982670: do not collect unentitled products in SCA mode

test/test_cert_sorter.py
Create a new unit test that setups an SCA-like environment to test the fix for 1982670.
Followup of commit 08407d97387c9a4483c9a42b3e287bb593f3b6c9.
(cherry picked from commit ef4b587179368b8fa5b820398651093fe7b19355)
Backport of PR #3229 to 1.28.
=> [1.28] test: add simple test for 1982670

src/subscription_manager/base_action_client.py, src/subscription_manager/cache.py, src/subscription_manager/certdirectory.py, src/subscription_manager/cli.py, src/subscription_manager/cli_command/cli.py, src/subscription_manager/cp_provider.py, src/subscription_manager/cpuinfo.py, src/subscription_manager/entcertlib.py, src/subscription_manager/managercli.py, src/subscription_manager/managerlib.py, src/subscription_manager/productid.py, src/subscription_manager/repofile.py, src/subscription_manager/repolib.py, src/subscription_manager/scripts/rhsmcertd_worker.py, src/subscription_manager/scripts/subscription_manager.py, test/test_certmgr.py
=> ENT-5549: Fix issues found while type-hinting

test/rhsmlib/test_file_monitor.py
The `file_monitor` module already handled the lack of the `pyinotify` module, falling back to a polling-based file watcher. Unfortunately, the tests for `file_monitor` assumed that `pyinotify` was always present.
Hence, make it possible to run test_file_monitor successfully in case `pyinotify` is not available:
- create a inotify-based filesystem watcher only when `pyinotify` is available
- mark the tests that assume the presence of `pyinotify` directly or indirectly
- adjust `test_inotify_avail` to the actual availability of `pyinotify`
- add a new `test_create_fsw_real` to check the actual filesystem watcher depending on what is available
=> tests: fix test_file_monitor without pyinotify

src/rhsm/config.py, test/rhsm/unit/test_config.py
* Card ID: ENT-5610
UBI images (by accident or oversight) come with /etc/rhsm-host/ directory already existing. This makes our detection fire every time, even if the host mapping is disabled and this directory is empty.
This patch also uses /etc/pki/entitlement-host/ to perform container detection, not just /etc/rhsm-host/.
(Cherry-picked from 3f4918d)
=> [1.28] ENT-5610: Explicitly check for provided entitlement certificates

src/dnf-plugins/subscription-manager.py, src/plugins/subscription-manager.py, src/subscription_manager/managercli.py, test/test_managercli.py
PR for <https://issues.redhat.com/browse/ENT-5611> 
Backport of PR #3294.
=> [1.28] Update messaging around the "container mode"

test/rhsmlib/dbus/test_consumer.py
=> fix(test): Properly stop method mock

test/rhsmlib/dbus/test_consumer.py
* Card ID: CCT-508
(Cherry-picked from 796f42b01ac91d7cf1b993317e1b98816c0de1ff)
=> [1.29.33] fix(test): Properly stop method mock

test/rhsmlib/dbus/test_consumer.py
* Card ID: CCT-508
(Cherry-picked from 796f42b01ac91d7cf1b993317e1b98816c0de1ff)
=> [1.29.26] fix(test): Properly stop method mock

test/rhsmlib/dbus/test_consumer.py
* Card ID: CCT-508
(Cherry-picked from 796f42b01ac91d7cf1b993317e1b98816c0de1ff)
=> [1.29] fix(test): Properly stop method mock

test/rhsmlib/dbus/test_consumer.py
* Card ID: CCT-508
(Cherry-picked from 796f42b01ac91d7cf1b993317e1b98816c0de1ff)
=> [1.29.40] fix(test): Properly stop method mock

.github/workflows/libdnf.yml, .github/workflows/pytest.yml, .github/workflows/tito.yml
* Original PR:
* https://github.com/candlepin/subscription-manager/pull/3396
* Original commits from 1.29 branch:
* 5436a3eae11c8737b1827fa78b96daa695925bc2
* f1138bd7eb608feaa8b502ef286d82cf895543e2
=> Fix build for subscription-manager-1.29.40

man/subscription-manager.8, src/subscription_manager/cli_command/addons.py
=> [1.29] feat: Deprecate 'syspurpose addons'

src/subscription_manager/scripts/rhsmcertd_worker.py
* Card ID: CCT-654
Since the feature is not completed yet, we're disabling it client-side.
=> feat: Disable anonymous cloud registration temporarily

src/subscription_manager/scripts/rhsmcertd_worker.py
* Card ID: CCT-654
Since the feature is not completed yet, we're disabling it client-side.
=> [1.29] feat: Disable anonymous cloud registration temporarily

cockpit/src/insights.jsx, integration-tests/check-subscriptions, test/files/mock-insights
Backport a fix for cockpit, and some fixes to CI bits to help with non-legacy-upload, and CERT-based authentication; the PRs are:
- https://github.com/candlepin/subscription-manager-cockpit/pull/71
- https://github.com/candlepin/subscription-manager-cockpit/pull/72
- https://github.com/candlepin/subscription-manager-cockpit/pull/74
=> [1.28] cockpit: code fix and CI fixes from subscription-manager-cockpit

.packit.yml
* Card ID: CCT-740
* Make builds on all fedoras and Centos Stream 10 ATM
=> feat: Added basic configuration for Packit

.packit.yml
* Card ID: CCT-740
* Make build only on and Centos Stream 9 ATM
=> feat: [1.29] Added basic configuration for Packit

subscription-manager.spec
_Goes on top of https://github.com/candlepin/subscription-manager/pull/3521_
Fallout from 8dddb545597e31a45304bec0d33e89e52a8fa705
=> spec: Fix the dependencies on json-c and libdnf

src/subscription_manager/scripts/rhsmcertd_worker.py
* Backport commit to 1.29 branch
* Original PR: #3588
* Original commit: https://github.com/candlepin/subscription-manager/commit/94c06e059bee2b9af3b1d576197799d0a4ed3516
* Card ID: CCT-1545
* Card ID: RHEL-106161
* We have to wait random time before reaching IMDS for metadata
and signature. Otherwise many VM started at the same time
could cause something like DDoS to IMDS server and these
IMDS servers could refuse to provide required metadata.
Without metadata & signature auto-registration cannot happen.
* Modified generating of random seed, because cloud metadata are
not available at this point. We do not call random.seed() at
all, because it can cause troubles. Instead we use
`random.SystemRandom()`. This should generate really random
values, because it uses `os.urandom()` under hood. …
=> fix: [1.29] Wait random time before reaching IMDS server

integration-tests/constants.py, integration-tests/files/valid-fields.json, integration-tests/test_syspurpose.py, integration-tests/utils.py, systemtest/tests/integration/test.sh
Card-ID: CCT-742
there is a DBus object Syspurpose in dbus api.
Integration tests verify all cases (positive, negative ones) for all methods in the object.
- GetSyspurpose
- SetSyspurpose
- GetValidFields
=> integration tests for DBus Syspurpose object

integration-tests/README.md, integration-tests/scripts/post-environments.sh, integration-tests/scripts/run-local-candlepin.sh, integration-tests/test_register.py, integration-tests/test_register_get_orgs.py, integration-tests/test_syspurpose.py, systemtest/tests/integration/test.sh
* No functional changes
* Mostly fixed typos
* Extended documentation a little
* Small tweaks of Python and Bash scripts
=> chore: small fixes of integrations tests
