- cockpit/org.candlepinproject.subscription_manager.metainfo.xml
`<launchable>` must coincide with the actual URL path defined by the
manifest.
https://bugzilla.redhat.com/show_bug.cgi?id=1856638
> cockpit: Fix AppStream launchable metainfo

- src/subscription_manager/managercli.py
- syspurpose/src/syspurpose/files.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1857100
* The candlepin server can return empty string as valid value.
It is useless to show empty string as valid value.
* I also fixed this issue for syspurpose CLI tool.
> 1857100: Do not print empty string as valid value; ENT-2634

- src/rhsm/config.py
Changes to rhsm.conf start as a tempfile which has mode 0600.
Check the mode of the current rhsm.conf and restore it (typically it
is 0644) on the new rhsm.conf.
BZ: https://bugzilla.redhat.com/1838670
Signed-off-by: Jeffrey Bastian <jbastian@redhat.com>
> set permissions on rhsm.conf

- src/subscription_manager/managercli.py
* https://bugzilla.redhat.com/show_bug.cgi?id=1859532
* When system is not registered, rhsm.conf contains wrong proxy
configuration and following command is used:
```
[root@localhost ~]#   subscription-manager role --list --username user --password secret
```
then traceback was printed to stdout.
* The decent message about wrong proxy configuration is printed
to stdout now.
> 1859532: Role --list handle wrong proxy conf (unregistered case)

- etc-conf/rhsm.conf
- man/rhsm.conf.5
- src/rhsm/config.py
- src/subscription_manager/managercli.py
- src/subscription_manager/utils.py
- test/test_utils.py
Improves messaging for auto insights register and unregister.
Now we check to see that insights-register.path is enabled before
messaging anything about automatic insights registration.
Likewise for unregistration.
> 1832990: Add rhsm.no_insights config option, improve messaging

- src/rhsm/profile.py
- src/subscription_manager/syspurposelib.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1858296
* DNF api probably started to return the list of installed profiles
as tuple. We store cache in JSON document. () == [] is False
* Removed one debug print
> 1858296: Do not report unchanged profile; ENT-2639

- src/rhsm/config.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1860434
* When configuration file /etc/rhsm/rhsm.conf does not exists and
config command is used, then it was not possible to set any
value
* When /etc/rhsm directory does not exist, then this directory
is also created
> 1860434: Create rhsm.conf, when config command is used

- src/rhsmlib/dbus/objects/register.py
- test/rhsmlib_test/test_register.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1841600
* When activation key is used for registration over D-Bus API
and auto-attach was enabled on activation key, then entitlement
certificates were not installed to the system.
* It is possible to reproduce this issue using following script.
Note: this script doesn't work on Fedora32, because there is
some bug in busctl and busctl doesn't work as expected, when
unix socket is used. I used this script on CentOS 7:
```bash
#!/bin/bash
echo "starting RegisterServer..."
dbus-send --system --print-reply --dest='com.redhat.RHSM1' \
'/com/redhat/RHSM1/RegisterServer' \
com.redhat.RHSM1.RegisterServer.Start string:"" \
> /root/register_server_output.txt
if [[ $? -eq 0 ]]
then
export my_addr=`cat /root/register_server_output.txt \
| gawk …
```
> 1841600: D-Bus - update ent. cert., when act. key is used; ENT-2453

- src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1861255
* When some exception occurs, then traceback should be printed
to rhsm.log not to console
> 1861255: Catch all exception and print traceback to rhsm.log

- src/subscription_manager/cache.py
- src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1862415
* Play game with exceptions properly and handle gone exception
in CliCommand class
* Messages should be consistent across all commands, when consumer
is deleted from server. Only following message should be used
in all cases:
```
Consumer profile "aabbccdd-aaaa-bbbb-cccc-aabbccddeeff" has been
deleted from the server. You can use command clean or unregister
to remove local profile.
```
This message used to be displayed in this case:
```
Unit aabbccdd-aaaa-bbbb-cccc-aabbccddeeff has been deleted
```
> 1862415: Print proper message, when consumer is deleted; ENT-2709

- src/dnf-plugins/subscription-manager.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1855893
* When full_refresh_on_yum is set to 1, then the dnf plugin
subscription-manager did not update redhat.repo properly
according content-override. This issue was caused by too
agresive optimization. It was introduced in PR: #2210
> 1855893: Generate redhat.repo properly; ENT-2636

- src/subscription_manager/managercli.py
- test/test_registration.py
A small PR to refine the behaviour of insights auto registration.
When the server does not have the "insights_auto_register" capability, subscription-manager register command will mask the insights-register.path unit (regardless of the presence of "--no-insights" or setting of "no_insights" in the rhsm.conf).
When the server does have the "insights_auto_register" capability (as master CP does now), subscription-manager register command will only mask the insights-register.path unit when given the "--no-insights" cli option or with "no_insights" set in rhsm.conf to something truthy.
> 1832990: Only register insights when server supports "insights_auto_register"

- src/subscription_manager/managercli.py
- test/fixture.py
- test/test_registration.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1868936
* When it is not possible to upload profile to server during
registration, then do not print traceback to console
* This issue has been partially fixed in this PR:  #2305
but this commit should avoid printing any warning message
to console. When REST API endpoint is not available,
then profile will be uploaded next time by `rhsmcertd`
* Added unit test for this case
* Added one unit test for normal registration
> 1868936: Do not print traceback, when profile upload failed

- src/subscription_manager/repofile.py
- subscription-manager.spec
* One issue is related to building rpm on new suse box
* Second issue is related to os.makedirs. Argument exist_ok
is not necessary and it is not supported on Python2
> Two fixes of issues related to suse

- src/subscription_manager/managercli.py
- test/test_plugins.py
We were recently able to reproduce this.
This solution is already verified via QE.
> 1615429: Fix sorting of plugin hooks

- etc-conf/zypper.conf
- src/subscription_manager/repofile.py
* this is useful for pulp repositories as gpg signments for
rpms are still checked
> support to disable repo_gpgcheck only

- integration-tests/check-subscriptions
- src/rhsmlib/dbus/objects/consumer.py
- src/rhsmlib/dbus/objects/register.py
- src/rhsmlib/dbus/util.py
- src/rhsmlib/services/register.py
- src/subscription_manager/managercli.py
- test/rhsmlib_test/test_register.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1753236
* When user tries to register using application that uses our
D-Bus API and no organization is specified, then error is
raised. Most of our users are member of only one organization
and they do not aware that they are member of any organization.
It is hard for them to find the organization ID. So this
bug fix should automatically select this organization, when
user is member only of one organization.
* This PR also introduces option to select organization, when
user is member of more ogranizations. In this case new signal
UserMemberOfOrgs is triggered. This signal has string argument
including JSON dump of simplified list of available
organizations for given user.
* When user is member of no organization, then some exception
is …
> 1753236: D-Bus Register properly, when org not specified; ENT-2096

- src/rhsmlib/services/register.py
- src/subscription_manager/syspurposelib.py
- syspurpose/src/syspurpose/files.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1868734
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1875988
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1875624
* This bug was probably caused by optimization, when we tried to
reduce number of REST API calls during registration. This effort
had side-effects described in BZs. In general, when some
syspurpose attribute is set on activation key or ogranization
then these syspurpose attributes are ignored during registration
and these syspurpose values are deleted from consumer.
* Solution for this issues: values returned in consumer
JSON object are used in three-way merge during registration.
No extra REST API call is required.
* Refactored some code
* TODO: more refactoring and more testing
> 1868734: Fix issue with syspurpose attrs. set in act. key; ENT-2851

- cockpit/src/index.js
- cockpit/src/subscriptions-client.js
- cockpit/src/subscriptions-view.jsx
- integration-tests/check-subscriptions
- src/rhsm/connection.py
- src/rhsmlib/dbus/objects/entitlement.py
- src/rhsmlib/services/entitlement.py
- src/rhsmlib/services/syspurpose.py
- src/subscription_manager/cert_sorter.py
- src/subscription_manager/i18n.py
- src/subscription_manager/reasons.py
- test/rhsm/unit/connection_tests.py
- test/rhsmlib_test/test_entitlement.py
- test/test_cert_sorter.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1870567
* There were three reasons, why locale og GetStatus returned
strings with wrong locale
* REST API calls were called with wrong Accept-Language header,
because the header was set for session and it was used for
all REST API calls
* Some strings (e.g. "Invalid") were translated during start
of rhsm.service according system settings of locale and then
these translated strings were used
* Some strings are translated on candlepin server. Unfortunately
some translated strings were saved in cache files and strings
with unwanted translations were returned by GetStatus method
* So, some global variables with translated strings were moved
to methods. Thus these strings are translated everytime, when
method si called
* Caching of …
> 1870567: Fix issue with locale and D-Bus method GetStatus; ENT-2772

- subscription-manager.spec
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1855437
* RPM including syspurpose CLI tool has dependency on RPM including
subscription-manager now
> 1855437: syspurpose CLI should require sub-man rpm; ENT-2602

- subscription-manager.spec
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1847910
* Introduction: DNF plugins were in separate RPM and there was
circular dependency between RPM including subscriptions-manager
(subscription-manager required rpm with DNF plugin and DNF plugins
required subscription-manager). DNF plugins were in separate plugin
due to RHEL7 (dnf was experimental on RHEL7).
* DNF plugins were moved to subscription-manager RPM
* New libdnf-plugin-subscription-manager was introduced, because
microdnf really needs it. This RPM includes only libdnf plugin.
It would be inefficient to require dependency of libdnf plugin
on subscription-manager.
> 1847910: DNF plugins are part of sub-man RPM, libdnf RPM; ENT-2536

- src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1826300
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1831082
* When simple content access mode is used, then do not try to
auto-attach and print appropriate message to stdout.
> 1826300: Ignore auto-attach, when SCA mode is used

- src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1826300
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1831082
* When simple content access mode is used, then do not try to
auto-attach and print appropriate message to stdout.
This is just a backport/cherry-pick of 7a187c99a0914726ad9cd30892bc6e6b48a1131c for subscription-manager-1.24*
> 1826300: Ignore auto-attach, when SCA mode is used; ENT-2341

- src/subscription_manager/cp_provider.py
- test/test_cp_provider.py
- test/test_managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1886745
* The initialization of variables in CPProvider caused this
regression. It was introduced in the PR: #2328
* The path to concumer cert and consumer key was None.
> 1886745: Fix __init__ of CPProvider; ENT-3147

- src/rhsm/connection.py
- src/subscription_manager/managercli.py
- src/subscription_manager/syspurposelib.py
- test/test_managercli.py
* Added new syspurpose command
* It has only --show option at this moment
* When system is registered, then the sub-man tries to get
consumer's syspurpose valyes and then do three-way merge
* When system is not registered, then it is possible only
display values stored in /etc/rhsm/syspurpose/syspurpose.json
* When no options is provided, then current syspurpose values
are displayed too
* Added unit tests for new command
* Modified a little bit behavior of other syspurpose commands
(role, usage, addons, service-level). When the system is
not registered, then --show option print current syspurpose
value stored in /etc/rhsm/syspurpose/syspurpose.json
> Added new syspurpose command; ENT-3060

- po/fr.po
- po/ja.po
- po/ko.po
- po/zh_CN.po
- po/zh_TW.po
- src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1826300#c8
* Display organization ID and not organization name in the
warning message.
> 1826300: Print org id in warning message; ENT-3175

- po/fr.po
- po/ja.po
- po/ko.po
- po/zh_CN.po
- po/zh_TW.po
- src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1831082
* Changed message a little. We do not show organization name, but
we show organization id to be consistent with other messages
* Copied translation for some languages (fr, ko, jp, cn) from
candlepin server
> 1831082: Better messages for attach --auto for SCA mode; ENT-3175

- src/subscription_manager/cache.py
- test/test_cache.py
This is a cherry-pick of commit : 90e3201f03730ce4c55bab37a4d2de176f15526e
No other changes have been made aside from those in that commit.
> 1850624: Uncaught JSONDecodeError when content_access.json is empty

- po/fr.po
- po/ja.po
- po/ko.po
- po/zh_CN.po
- po/zh_TW.po
- src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1826300#c8
* Changed message a little. We do not show organization name, but
we show organization id to be consistent with other messages
* Copied translation for some languages (fr, ko, jp, cn) from
candlepin server (I noticed that korean translation had small
issues. So, it is fixed for this branch)
> 1826300: Better messages for attach --auto for SCA mode; ENT-3175

- src/subscription_manager/managercli.py
There's a discrepancy between the man page and attach --help. The man page for attach --auto says that it:
"Automatically attaches the *best-matched* compatible subscription or subscriptions to the system."
However, attach --help omits the word "best-matched". Today, my colleague wrongly assumed from --help that subscription-manager attaches all compatible subscriptions with the --auto option. This is not true though. It indeed attaches only the best-matched ones. This commit fixes the confusing --help text by adding the "best-matched" word to it.
Thanks @larskarlitski for pointing this out!
> improve the help message for attach --auto

- src/subscription_manager/utils.py
- test/test_utils.py
This does two things:
1) handle IOErrors and other exceptions whilst trying to get all running processes' names by ignoring these exceptions and logging a message noting the potentially missed process name.
2)  No longer keep files open any longer than necessary for reading the process name (by not yielding before closing the file)
> 1890080: Handle IOErrors and Exceptions when looking for process names

- subscription-manager.spec
* The subscription-manager RPM requires syspurpose RPM with
specific version and release
* The syspurpose RPM does not require subscription-manager at all
again, because syspurpose does not need subscription-manager for
base functionality.
> 1855437: Fixed rpm dependency of subscription-manager; ENT-3250

- src/daemons/rhsmcertd.c
* When log directory /var/log/rhsm does not exist, then
rhsmcertd tries to create this directory before
it tries to print anything to log file
> Create log dir by rhsmcertd, when log dir does not exist

- cockpit/src/subscriptions-client.js
- src/rhsmlib/dbus/objects/syspurpose.py
- src/rhsmlib/services/syspurpose.py
- src/subscription_manager/syspurposelib.py
- syspurpose/src/syspurpose/files.py
- syspurpose/test/syspurpose/test_syspurposefiles.py
- syspurpose/test/syspurpose/test_utils.py
* Added D-Bus method GetValidFields(). Thus it is
possible to get dictionary of valid attributes
and values in client applications using
D-Bus API.
* Added D-Bus method SetSyspurpose(). It is possible
to set syspurpose value without need of calling
syspurpose CLI tool
* Added one missing argument to GetSyspurposeStatus
* Fixed method get_owner_syspurpose_valid_fields in
service.sypurpose module
* Disabled in-memory caching in SyncedStore, because there were
only troubles with this in rhsm.service, because it runs
for very long time.
* Added exception for three-way merge conflict
* Added many unit tests for syspurpose.files
> Extended D-Bus API - syspurpose methods; ENT-2373 

- src/rhsm/connection.py
- src/subscription_manager/cache.py
- test/test_cache.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1894450
* The subscription-manager identity returned wrong values after
removing consumer from candlepin server. When there was
cache file /var/lib/rhsm/cache/current_owner.json, then
the identity command only returned content of this cache
file.
* The cache file can be used, when previous REST API call
using consumer cert/key was successful and the validity
of consumer UUID was proved.
* Added several unit tests
> 1894450: Fix issue with identity command; ENT-3235

- .tito/releasers.conf
This just removes f31 from our tito fedora releaser because f31 is no longer supported.
> Stop releasing to f31 (f31 is no longer supported)

- subscription-manager.spec
The rarian / scrollkeeper dependency has been moved to subscription-manager-gui
package as this is the package which actually makes use of it at this time.
> 1801570: drop scrollkeeper/rarian as a dependency from rhsm-gtk

- subscription-manager.spec
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1847910#c9
* Do not include plugin for DNF in libdnf RPM. This RPM should
include only libdnf plugin.
> 1847910: Do not include dnf plugins in libdnf RPM.

- src/subscription_manager/managercli.py
When the proxy configured is bad the call to check for the available orgs fails. Moving this inside the try block just below it's original position allows us to have consistent messaging about the proxy exception.
> 1904541: Catch ProxyException when checking available orgs

- etc-conf/cloud/aws.conf
- src/rhsmlib/cloud/README.md
- src/rhsmlib/cloud/colector.py
- src/rhsmlib/cloud/collector.py
- src/rhsmlib/cloud/detector.py
- src/rhsmlib/cloud/providers/aws.py
- src/rhsmlib/cloud/providers/azure.py
- src/rhsmlib/cloud/providers/gcp.py
- src/rhsmlib/cloud/utils.py
- src/rhsmlib/facts/all.py
- src/rhsmlib/facts/cloud_facts.py
- src/rhsmlib/facts/collector.py
- src/rhsmlib/facts/host_collector.py
- subscription-manager.spec
- test/rhsmlib_test/test_aws_instance.py
- test/rhsmlib_test/test_cloud.py
* Created new package rhsmlib.cloud. This package contains
two modules with base classes for:
- Detecting cloud providers (CloudDetector)
- Collecting metadata from cloud providers (CloudCollector)
* The Python package 'cloud' contains another package called 'providers'.
This package contains Python modules implementing subclasses of
CloudCollector. Each subclass implement detecting of one cloud
provider. Three main cloud providers are supported ATM:
- Amazone Web Services (AWS)
- Microsoft Azure
- Google Cloud Platform
* Each detector includes two methods for detecting cloud provider.
First method 'is_running_on_cloud()' uses some unique
system facts to identify cloud provider. Values of these
facts can change over time. For this reason there is
another method called …
> Detecting of cloud providers; ENT-3288

- etc-conf/subscription-manager.completion.sh
- man/subscription-manager.8
- src/subscription_manager/managercli.py
This adds a small section to the man page for subscription-manager to describe the current functionality of the "syspurpose" command. Additionally, this updates the bash completion to add the syspurpose command and updates the help text for current syspurpose-related commands to be more consistent.
> Fixup syspurpose module help text / bash completion

- integration-tests/run
python does not exist any more, and integration-tests/vm.install only
installs python3. The latter also calls `python3 ./setup.py`, so be
consistent.
----
This fixes the [current test failure](https://logs.cockpit-project.org/logs/pull-1519-20210105-092414-c8de93f2-rhel-8-3-candlepin-subscription-manager/log.html)
> cockpit: Invoke setup.py with python3

- Makefile
- po/zanata.xml
- syspurpose/po/zanata.xml
This simply removes the Zanata part of the operation. The gettext/update-po gets called in both subscription-manager and syspurpose with a single make target.
> Update project to use Weblate for translations ENT-3347

- integration-tests/check-subscriptions
- integration-tests/run
`wait_visible()` implies `wait_present()`, and the main point of an UI
element is to be actually visible; integration tests ordinarily
shouldn't just check for mere presence in the DOM.
This will allow us to bump cockpit's test API to something recent, to
make the tests compatible with the cockpit version in RHEL 8.4.
See https://github.com/cockpit-project/cockpit/pull/15062 and
https://github.com/cockpit-project/cockpit/pull/15128
> cockpit: Fix tests on RHEL 8.4

- Jenkinsfile
- build_ext/build_ext/lint.py
- jenkins/python3-stylish-tests.sh
- jenkins/python3-tests.sh
- jenkins/stylish-tests.sh
- jenkins/suse-tests.sh
- jenkins/tito-tests.sh
- src/rhsmlib/cloud/collector.py
- src/rhsmlib/cloud/detector.py
- src/rhsmlib/cloud/providers/aws.py
- src/rhsmlib/cloud/providers/azure.py
- src/rhsmlib/cloud/providers/gcp.py
- src/rhsmlib/cloud/utils.py
- test/rhsmlib_test/test_cloud.py
* Added support for collecting metadata for three
cloud providers:
- AWS 
- Azure
- Google Cloud Platform
* Implementation uses requests Python package
* Type hints are used in code
* Base class of collectors is implemented in: 
src/rhsmlib/cloud/collector.py
* AWS: Collecting metadata and signature supports both version
of IMDS
- Collector tries to use IMDSv1 first, when cached security
used by IMDSv2 is not found. IMDSv1 is prefered, because
it requires less communication with metadata server
- IMDSv1 can be disabled on some systems. In this situation
token has to be gathered and then it is possible to get 
metadata and signature
- Security token is cached for one hour
- Metadata is simple json document
- AWS supports three variants of signature. We get rsa2048
variant of signature
- …
> ENT-3191: Collect metadata of cloud providers

- src/daemons/rhsmcertd.c
- src/subscription_manager/scripts/rhsmcertd_worker.py
- subscription-manager.spec
* Improved logging of rhsmcertd, when we try to do
re-attempts of automatic registration
* Updated .spec file, because subscription-manager
requires rpm python-rquests
* Fixed one typo
> Improved loggin of rhsmcertd and spec file updated

- src/daemons/rhsmcertd.c
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1922173
This is a backport to 1.27 of the above!
> 1922173: Repeat auto-register only, when first attempt fail (#2420)

- Vagrantfile
Update our Vagrantfile to default to creating a fedora 32 machine.
This can be tested by temporarily making the following change to the ./vagrant/requirements.yml file:
```
diff --git a/vagrant/requirements.yml b/vagrant/requirements.yml
index 7ada67371..431dcbbf1 100644
--- a/vagrant/requirements.yml
+++ b/vagrant/requirements.yml
@@ -1,2 +1,3 @@
- src: https://github.com/candlepin/ansible-role-subman-devel.git
name: subman-devel
+  version: csnyder/support_f32
```
This PR requires https://github.com/candlepin/ansible-role-subman-devel/pull/8.
> Update our fedora target to fedora32, default to f32

- subscription-manager.spec
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1927245
* Several directories were marked as part of RPM
* Remove old empty sub-man-*-*.egg-info directories.
It could cause issues in the future.
> 1927245: Mark several dir as part of RPM; ENT-3555

- integration-tests/check-subscriptions
Most recent RHEL 8.4 cloud image does not enable it by default any more.
----
This got caught in the [most recent rhel-8-4 test image refresh](https://github.com/cockpit-project/bots/pull/1684), where [almost all sub-man tests fail](https://logs.cockpit-project.org/logs/pull-1684-20210216-175536-6f31a40d-rhel-8-4-candlepin-subscription-manager/log.html). I sent a similar PR for cockpit in https://github.com/cockpit-project/cockpit/pull/15356
> cockpit: Enable subscription-manager in dnf in tests

- .tito/releasers.conf
This adds the fedora 34 branch to our fedora releaser.
> Add f34 target to the fedora releaser

- subscription-manager.spec
* 1.28 backport
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1927245
* Card ID: ENT-3555
* Several directories were marked as part of RPM
* Remove old empty sub-man-*-*.egg-info directories.
It could cause issues in the future.
> 1927245: Mark several dirs as part of RPM

- integration-tests/check-subscriptions
Reverts candlepin/subscription-manager#2447
This was really the wrong thing to do. Ideally rhsm would revert the recent change that broke the default subscription-manager.conf, but if that really has to stay, then subscription-manager-cockpit needs another approach of figuring out whether subscriptions are really required.
> Revert "cockpit: Enable subscription-manager in dnf in tests"

- cockpit/npm-shrinkwrap.json
- cockpit/package.json
When working on the cockpit plugin, one needs webpack-cli
to be installed for our 'npm run watch' command as specified
in our README to work. This adds webpack-cli as a dep.
You can test this by running 'npm install' from the cockpit subdirectory.
After that 'webpack-cli' should be installed.
'npm run watch' should also work after this (this should run with no errors and js and html files should come out in ./dist folder).
I'm still working on an update to the ansible subman development role which will make use of this.
> Update webpack and require webpack-cli as a dev dep

- subscription-manager.spec
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1920568
* Card ID: ENT-3472
* There wasn't obsolete statement that old dnf-sub-man-plugin RPM
is obsoleted by libdnf-sub-man-plugin RPM
* The version of obsoleted dnf-sub-man-plugin RPM wasn't specified
* Fixed issue with updating debuginfo package. This issue was
solved by adding redefinition of libdnf-sub-man-plugin-debuginfo
package, which obsoletes old dnf-sub-man-plugin-debuginfo RPM.
We cannot solve this issue using different approach, because
old dnf-sub-man-plugin-debuginfo package has dependency to
old sub-man-debuginfo RPM which is replaced with new
sub-man-debuginfo RPM during RHEL upgrade and there will not
be any dnf-sub-man-debuginfo plugin in next RHEL major release
* Moved definition of requirements from …
> 1920568: Solve dependency between debuginfo packages

- src/rhsm/connection.py
- src/subscription_manager/certdirectory.py
- src/subscription_manager/release.py
- test/fixture.py
- test/stubs.py
- test/test_release.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1924921
* Card ID: ENT-3528
* When there was SCA certificate, then this cert was ignored
* Revert one change introduced during implementation of --token
- We try to use only entitlement cert for accessing CDN
that is related to installed product (not all entitlement
certs). It reduce failed connection attempts for long list
of installed entitlement certs.
* Added one unit test and fixed one existing unit test
> 1924921: Fix getting releases, when SCA is used

- src/subscription_manager/cli_command/attach.py
- src/subscription_manager/cli_command/cli.py
- src/subscription_manager/cli_command/register.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1928072
* When SCA mode is used for selected organization, then do
not try to do auto-attach at all and print info message
* We use the same message as is already used for
command attach --auto
* Implemented this functionality, because old message was
generated by candlepin server. Look at following candlepin PR:
https://github.com/candlepin/candlepin/pull/2947
> 1928072: Print warning message and don't do auto-attach

- .github/workflows/auto-assign.yml
This PR adds Nikos' PR auto assigner to the project.
It should, in combination with another change to the settings for this repo, allow us to have our PRs automatically assigned for review by a member of the 'client-tools' sub-team of the candlepin org.
You can check that the auto assignment with the round-robin setting has been enabled here: https://github.com/orgs/candlepin/teams/client-tools/edit/review_assignment
> Add nikos' auto assigner

- src/subscription_manager/certdirectory.py
- src/subscription_manager/release.py
- test/fixture.py
- test/stubs.py
- test/test_release.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1935592
* Card ID: ENT-3528
* Bug fix specific for RHEL7.9
* When there was SCA certificate, then this cert was ignored
* Revert one change introduced during implementation of --token
- We try to use only entitlement cert for accessing CDN
that is related to installed product (not all entitlement
certs). It reduce failed connection attempts for long list
of installed entitlement certs.
* Added one unit test and fixed one existing unit test
> 1935592: Fix getting releases, when SCA is used

- src/rhsm/certificate2.py
To test:
I used the Centos7 vagrant instance
Run as root:
rm -f /etc/pki/entitlement/*
umask 022
subscription-manager refresh
~~~
All local data refreshed
~~~
ls -al /etc/pki/entitlement/
~~~
-rw-r--r--.  1 root root  3243 Nov 10 08:30 7926654778781108730-key.pem
-rw-r--r--.  1 root root 28229 Nov 10 08:30 7926654778781108730.pem
~~~
rm -f /etc/pki/entitlement/*
umask 077
subscription-manager refresh
~~~
All local data refreshed
~~~
ls -al /etc/pki/entitlement/
~~~
-rw-r--r--.  1 root root  3243 Nov 10 08:32 7926654778781108730-key.pem
-rw-------.  1 root root 28229 Nov 10 08:32 7926654778781108730.pem <--------------This will change to 644 after applying the patch 
~~~
> 1896715: Set proper read permissions on certs - 1.24 [ENT-3274]

- man/subscription-manager.8
Spell "JSON" properly, and simplify the wording about it.
> 1924166: improve man text of syspurpose --show

- src/subscription_manager/cli_command/abstract_syspurpose.py
- test/test_managercli.py
Refactor an internal helper function to check for multiple values at once, rather than a single one; use it to validate the addons to add.
> 1880920 - print a warning for invalid addons

- integration-tests/check-subscriptions
https://github.com/cockpit-project/bots/pull/1768 moves the services
image from CentOS 7 to Fedora CoreOS and containerizes the candlepin
server. Adjust tests accordingly.
> cockpit: Adjust for changed services image

- src/subscription_manager/cli_command/config.py
Accidentally introduced with the refactoring of managercli.py, i.e.
commit 9a9b37c24f4d1fbe7acc69829f52b8bf082544fa
> Remove extra '%' in string

- src/rhsm/connection.py
- test/test_cache.py
As we were never setting "is_consumer_cert_key_valid" on the UEPConnections used for the cache in this branch, the cache was always considered obsolete. This broke the caching functionality.
Overall small change.
> Allow caches which depend on a valid consumer cert to operate

- src/subscription_manager/cli_command/abstract_syspurpose.py
Fixes commits c677ceebb254568e5f18a20eebea46df16e56c06.
As related consequence, `re` does not need to be imported anymore, as not mistakenly used.
> Fix variable for RestlibException exception

- integration-tests/check-subscriptions
Make sure that /etc/pki/product exist before copying certificates into
it, as minimal/KVM RHEL images do not have /etc/pki/product.
Card ID: ENT-3683
> 1930037: cockpit: ensure /etc/pki/product exist

- integration-tests/check-subscriptions
Make sure that /etc/pki/product exist before copying certificates into
it, as minimal/KVM RHEL images do not have /etc/pki/product.
Card ID: ENT-3683
(cherry picked from commit 2c178d5b9dce848fd2d8d8df6223994e873a8973)
> [1.28] 1930037: cockpit: ensure /etc/pki/product exist

- man/subscription-manager.8
- src/subscription_manager/cache.py
- src/subscription_manager/cli_command/refresh.py
- test/cli_command_test/test_refresh.py
This clears the content_access{_cache,_mode_cache} on each run of the refresh command and includes a very mocked test to show this is the case.
> 1886772: Clear content access mode cache on refresh

- src/subscription_manager/cli_command/abstract_syspurpose.py
Replace the placeholders in the translated string rather than the
English string, as the English string with replacements cannot be
translated.
RHBZ: 1663390, 1663402, 1663429
Card ID: ENT-2779
> ENT-2779: call format() on translated string

- src/subscription_manager/managercli.py
Replace the placeholders in the translated string rather than the
English string, as the English string with replacements cannot be
translated.
RHBZ: 1663390, 1663402, 1663429
Card ID: ENT-2779
(cherry picked from commit b5f9bbe8a4e0c8c07fb0a3ed8ad5acff0323b967)
Backport of #2557 to 1.28.
> [1.28] ENT-2779: call format() on translated string

- src/subscription_manager/repofile.py
In repolib the sections() method is used to find out which repositories
should be deleted. Because of the missing repo-id, removed subscriptions
will not be cleared and the repository sources list does list already
deleted repositories. 
In particular, the key fact is that, since AptRepoFile does not inherit from ConfigParser unlike YumRepoFile, then it has to provide behaviour-compatibile ConfigParser APIs. Hence, sections() must returns a list of (string) sections and not a list of Repo objects, and delete() must take a string with the section to remove and not a Repo object.
> To delete a deb repo the repo-id is required

- src/rhsm/profile.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1863039
* Card ID: ENT-2809
* When dnf/yum variable is created in /etc/dnf/vars or
/etc/yum/vars using echo "foo" > /etc/dnf/vars/variable,
then this variable is used by dnf plugin uploadprofile
* It is not possible to create unit tests for this case
and it is also not possible to create functional tests,
because non-root user cannot run such functional test
> 1863039: Fix issue with dnf/yum variables

- src/dnf-plugins/product-id.py
- src/dnf-plugins/subscription-manager.py
- src/dnf-plugins/upload-profile.py
The messages in the dnf plugins are extracted as part of our rhsm
catalog; hence, use the subscription-manager.i18n module to translate
them, rather than using dnfpluginscore (which uses a different catalog
name).
Card ID: ENT-3076
> 1878736: use our i18n functions instead of dnf ones

- src/dnf-plugins/product-id.py
- src/dnf-plugins/subscription-manager.py
- src/dnf-plugins/upload-profile.py
The messages in the dnf plugins are extracted as part of our rhsm
catalog; hence, use the subscription-manager.i18n module to translate
them, rather than using dnfpluginscore (which uses a different catalog
name).
Card ID: ENT-3076
(cherry picked from commit afd7137264feeffe1fe8d0b1cacb1505a00f9ee5)
Backport of #2565 to 1.28.
> [1.28] 1878736: use our i18n functions instead of dnf ones

- src/rhsm/profile.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1863039
* Card ID: ENT-2809
* When dnf/yum variable is created in /etc/dnf/vars or
/etc/yum/vars using echo "foo" > /etc/dnf/vars/variable,
then this variable is used by dnf plugin uploadprofile
* It is not possible to create unit tests for this case
and it is also not possible to create functional tests,
because non-root user cannot run such functional test
* Original PR #2569, cherry-picked commit: 2cd76421c9dfee334e0ef555df96263390918445
> 1863039: 1.28 Fix issue with dnf/yum variables

- cockpit/src/insights.jsx
Remove the extra _() marker/translation in strings of plural forms,
using cockpit.ngettext(): otherwise, they are extracted (and handled) as
single strings, and not plural forms.
(cherry picked from commit 3d6e3c49ba134ec2cce8e83339dab5cf634b2340)
Extracted from #2536.
> [1.28] cockpit: fix extraction of plural messages

- cockpit/src/insights.jsx
- cockpit/src/subscriptions-view.jsx
Compose a "Status: <status>" string at once avoiding the string puzzle; also, simplify the way it composed, and assembled later within <label> tags. The removal of the `...` markup also fixes the extraction of messages with xgettext; as it seems its JavaScript parser cannot handle `...`, and thus all the strings after it are not extracted.
Also, mark few more messages for translation.
Card ID: ENT-2265
> 1819555: cockpit: translate untranslatable messages

- cockpit/src/insights.jsx
- cockpit/src/subscriptions-view.jsx
Compose a "Status: <status>" string at once avoiding the string puzzle;
also, simplify the way it composed, and assembled later within <label>
tags. The removal of the `...` markup also fixes the extraction of
messages with xgettext; as it seems its JavaScript parser cannot handle
`...`, and thus all the strings after it are not extracted.
Also, mark few more messages for translation.
Card ID: ENT-2265
(cherry picked from commit c0328bfb773ad26c571fd48597568a7e19f66d3b)
Backport of #2574 to 1.28.
> [1.28] 1819555: cockpit: translate untranslatable messages

- src/rhsm/connection.py
Grab the missing contents of the prior commit (lost in all the rebuilds...).
We did not have the "is_consumer_cert_key_valid" attribute on the UEPconnection used when checking if the consumer cache is obsolete, hence we were always considering the cache obsolete.
You can check that this works by running "subscription-manager status" twice in a row from a clean install starting with no /var/lib/rhsm/cache/* files and looking for logging at the debug level from rhsm.connection module indicating that there is only one call to "/rhsm/consumers/{consumer_uuid}/owner".
> 1886772: check is_consumer_cert_key_valid

- integration-tests/check-subscriptions
- test/files/mock-insights
insights-client 3.0.217-1 dropped the `insecure_connection` option and
only accepts TLS. Change mock-insights to serve TLS. Re-use
cockpit-ws' certificate for that -- we have the key available, it
has the right properties (such as applying to localhost), and reliably
exists in the test environment.
Disable certificate verification, as apparently there is no way to
convince the later stages of insights-client to accept a locally added
CA.
-----
See the lengthy debugging in https://github.com/cockpit-project/bots/pull/1921 for some background. This blocks the [RHEL 8.4 image refresh](https://github.com/cockpit-project/bots/pull/1923), and will also fix your tests for 8.5.
> cockpit: Enable TLS for mock insights server

- integration-tests/check-subscriptions
- integration-tests/run
- test/files/mock-insights
Backport of #2504, #2408, and #2586 to 1.28 to fix (and then enable) the cockpit CI.
> [1.28] cockpit: backport CI fixes

- src/subscription_manager/managercli.py
- syspurpose/man/syspurpose.8
- syspurpose/src/syspurpose/cli.py
Backported [62f4ee8](https://github.com/candlepin/subscription-manager/commit/911221395339566890e6b5d049d3d8158a5eaf3e) Warning message about the Depreciation of Syspurpose
Also Backported: [9a9b37c](https://github.com/candlepin/subscription-manager/commit/a36e10ff9afb50ae7fa2f586cac45435f42cf8a8)
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1928072
When SCA mode is used for selected organization, then do
not try to do auto-attach at all and print info message
We use the same message as is already used for
command attach --auto
Implemented this functionality, because old message was
generated by candlepin server. Look at following candlepin PR:
candlepin/candlepin#2947
> ENT-3758: RHEL 8.5 Cherry pick Requests

- src/rhsm/profile.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1951053
* Card ID: ENT-2809
* When dnf/yum variable is created in /etc/dnf/vars or
/etc/yum/vars using echo "foo" > /etc/dnf/vars/variable,
then this variable is used by dnf plugin uploadprofile
* It is not possible to create unit tests for this case
and it is also not possible to create functional tests,
because non-root user cannot run such functional test
* PR for RHEL8.4. Original PR: #2569
(cherry picked from commit 2cd76421c9dfee334e0ef555df96263390918445)
> 1951053: Fix issue with dnf/yum variables

- src/rhsmlib/facts/hwprobe.py
- test/rhsmlib_test/test_hwprobe.py
Tweak the way we collect facts for IP v4/v6 addresses: instead of
directly adding the information to the dictionary of the returned facts,
collect them before and then assemble them as facts. This has two
advantages:
- we have all the collected keys at once, so we can use the first item
for single-value facts (like the primary IP v4/v6 address)
- there is no need to keep updating the facts dictionary
Adapt test_network_interfaces_multiple_ipv4 to the new behaviour, and
add a new test case for multiple IP v6 addresses of the same scope.
Card ID: ENT-1591
> 1898552: refactor/fix collection of IP v4/v6 address info

- contrib/debian/control
Add a dependency to the subscription-manager package for Debian and
Ubuntu to depend on apt-transport-katello which is necessary to receive content from Foreman.
This PR is a reaction to the following community feedback: 
> to be able to use the repository on the foreman host the package apt-transport-katello is also needed, could this package be a part of the dependencies when installing python3-subscription-manager?
See [Foreman Community Forum](https://community.theforeman.org/t/ubuntu-client/22691/4?u=maximilian)
> Add subscription-manager dependency to apt-katello-transport

- src/subscription_manager/cli_command/environments.py
- src/subscription_manager/cli_command/identity.py
- src/subscription_manager/cli_command/owners.py
Call `format()` on the strings, not on the return value of `log.error()` (which is `None`).
> 1952228: fix formatting of log error messages

- src/subscription_manager/managercli.py
- test/test_managercli.py
Refactor an internal helper function to check for multiple values at once, rather than a single one; use it to validate the addons to add.
Backport of #2486 to 1.28.
> [1.28] 1880920 - print a warning for invalid addons

- syspurpose/man/syspurpose.8
- enclose commands within double quotes
- fix value of the example role to something more actual
- end sentences with period
> 1950015: fix typos in syspurpose(8)

- etc-conf/subscription-manager.completion.sh
Adapt the sed regexp scraping the help text of config after the switch
from optparse to argparse. In particular, the help text for options with
arguments changed from "--foo=VALUE" to "--foo VALUE".
> 1953069: bash: fix listing of config options

- subscription-manager.spec
This moves the deletion/cleanup of old subman egg.info directories from %post (which was too early) to %posttrans which is after the uninstall of the old package. (Thanks Pino and Will)
> Cleanup old *.egg-info dirs in %post

- src/subscription_manager/managercli.py
- test/test_managercli.py
porting fix to subscription-manager-1.28
> [Cherry pick to 8.5] Bug 1879856 - Warning message shouldnot be displayed when user tries to set valid syspurpose attributes with random case

- subscription-manager.spec
Fix the %changelog for recent releases of 1.28.x:
- remove a changelog section without a version, effectively duplicate
of 1.28.15-1
- drop the mention of 1944093 from Weblate commits, as they are
unrelated to RHEL bugs
- remove the mention from the first commit dealing with 1636950, as it
was actually fixed only with the second commit (in 1.28.16-1)
> 1949492: remove bogus %changelog entries

- syspurpose/man/syspurpose.8
Incorrectly added a section to the Generic Commands.  Removed in this PR.
> 1637083: remove the unset PROPERTY VALUE from the Generic Commands

- cockpit/src/subscriptions-client.js
- src/rhsm/connection.py
- test/rhsm/unit/connection_tests.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1956654
* Originally it was reported in comment in this BZ:
https://bugzilla.redhat.com/show_bug.cgi?id=1744696#8
* When user decided to not use proxy in cockpit plugin despite
some proxy settings are set in rhsm.conf, then cockpit
plugin and rhsm.service still wanted to use proxy settings
from rhsm.conf. This issue is fixed in this commit
* Added some unit tests
* Fixed few unit tests related to HTTP_PROXY env. var. for the
case, when some proxy setting is in the /etc/rhsm.rhsm.conf
on testing machine (unit tests tried to read this
configuration file)
> 1956654: Fix issue with proxy and cockpit plugin

- .flake8
- Jenkinsfile
- src/subscription_manager/migrate/migrate.py
subscription-manager does not support Python 2 anymore, so switch the stylish script to the Python 3 version.
Also, stop using the `subman-centos7` agent for it, as it clearly does not support Python 3; the default `subman` agent will work fine.
> jenkins: switch stylish job to Python 3

- etc-conf/subscription-manager-cockpit.desktop.in
- integration-tests/vm.install
- subscription-manager.spec
Cockpit web UI pages should not depend on the cockpit web server. It is
perfectly reasonable and often desirable to not run the web server on a
managed machine, and log in through the host switcher and SSH instead.
However, in this case the dependency is there because of the cockpit
desktop integration. We mostly care about the default OS installation
there, so lower it to Recommends (which are installed by default) and
guard the .desktop file with a `TryExec=`.
> cockpit: Lower cockpit-ws dependency to Recommends

- man/subscription-manager.8
- src/subscription_manager/cache.py
- src/subscription_manager/entcertlib.py
- src/subscription_manager/injectioninit.py
- src/subscription_manager/managercli.py
- src/subscription_manager/utils.py
- test/fixture.py
- test/stubs.py
- test/test_managercli.py
- test/test_utils.py
…eeded
This stops bad cache values from incorrectly displaying that
the system is registered to an organization which is running
in Simple Content Access mode.
Now the organization's content access mode is cached only in memory
so as to limit the duration of it's validity to the lifetime of
any of our applications runtime.
> 1951057: Cherry Pick to Add in memory read of cache, delete SCA cert with not needed.

- build_ext/build_ext/i18n.py
- setup.py
Since we recently switched from optparse to argparse, we need to extract
the translatable messages in Python's argparse, rather than optparse.
Followup of commit eef1bb13f8924af9539f98330465c110f2df92b5.
> 1952879: extract messages from argparse instead of optparse

- src/subscription_manager/cli_command/abstract_syspurpose.py
Try to improve and make more coherent the messages for missing
syspurpose attributes in the current subscription, or for an empty list
of values available.
Updates commit f4d903a88422ee661dc66459305d993b892be91a.
> 1959048: improve wording for missing or empty syspurpose values

- src/subscription_manager/managercli.py
Try to improve and make more coherent the messages for missing
syspurpose attributes in the current subscription, or for an empty list
of values available.
Updates commit 83f6d70c4825074dadfa412044f11468bfce955f
(cherry picked from commit f6ec6a1afad622e948f9f4f5021db7bba5923917)
Backport of #2634 to 1.28.
> [1.28] 1897767: improve wording for missing or empty syspurpose values

- src/subscription_manager/cli_command/abstract_syspurpose.py
- src/subscription_manager/cli_command/service_level.py
- test/cli_command_test/test_addons.py
Improve a bit more the wording for invalid syspurpose values:
- drop the distinction between missing syspurpose attribute and empty list of available values for it, because it is not that needed in the end (hard to diagnose, and not actionable by the user anyway)
- adopt the same message also for "service_level", as it uses a slightly different implementation of a syspurpose command
> 1959048: improve wording for invalid syspurpose values

- integration-tests/run
python does not exist any more, and integration-tests/vm.install only
installs python3. The latter also calls `python3 ./setup.py`, so be
consistent.
(cherry picked from commit f9e6342d0262f0ef7576d06346f290dd87851c42)
Backport of one commit of #2380 to 1.28, to fix the cockpit CI.
> [1.28] cockpit: Invoke setup.py with python3

- src/subscription_manager/managercli.py
- test/test_managercli.py
Improve a bit more the wording for invalid syspurpose values:
- drop the distinction between missing syspurpose attribute and empty
list of available values for it, because it is not that needed in the
end (hard to diagnose, and not actionable by the user anyway)
- adopt the same message also for "service_level", as it uses a slightly
different implementation of a syspurpose command
Add a small test for this situation in the tests of the 'addons'
command, as it is one of the actual syspurpose implementations.
(cherry picked from commit c71ee8d0a68e60081d6a87444f83f7fbcffd0c5f)
Backport of #2656 to 1.28.
> [1.28] 1897767: improve wording for invalid syspurpose values

- subscription-manager.spec
Anaconda can subscribe a system during the installation, and there are
GUI bits to register a system anyway.
> 1941904: disable initial-setup in RHEL >= 9

- src/rhsm/config.py
- test/rhsm/unit/config_tests.py
This allows us to turn off subscription-manager's container detection for development and test purposes.
For the test to operate properly once in a container we need some other source of truth about whether we are in a container or not.
This is provided via the SUBMAN_TEST_IN_CONTAINER environment variable. As we have yet to containerize our test environment this defaults to False if not present in the environement.
> Enable subman to run normally in containers for development/test

- etc-conf/subscription-manager.completion.sh
- man/subscription-manager.8
- src/subscription_manager/cli.py
- src/subscription_manager/cli_command/abstract_syspurpose.py
- src/subscription_manager/cli_command/addons.py
- src/subscription_manager/cli_command/cli.py
- src/subscription_manager/cli_command/role.py
- src/subscription_manager/cli_command/service_level.py
- src/subscription_manager/cli_command/syspurpose.py
- src/subscription_manager/cli_command/usage.py
- test/cli_command_test/test_config.py
- test/cli_command_test/test_refresh.py
- test/cli_command_test/test_role.py
- test/test_plugins.py
- test/test_registration.py
- test/test_remove.py
- test/test_unregistration.py
As an effort to consolidate the handling of all the syspurpose attributes in a single place, make sure that all the syspurpose attributes are handled as subcommands of the `syspurpose` command (leaving the old commands as deprecated).
First of all, drop the command name from `args` when parsing them: according to the documentation, `ArgumentParser.parse_known_args()` seems to work without the command name as first argument. Since `CliCommand` is parsing the parameters of a specific command, we can drop the command itself in addition to the application name before calling `ArgumentParser.parse_known_args()`; this avoids the need to drop it after parsing. In addition, tweak the check for missing test arguments: `if not foo` is also matched by an empty list, which now is a valid list of …
> ENT-3328: 1898563: move syspurpose subcommands within the 'syspurpose' command

- src/subscription_manager/cli_command/cli.py
When describing the format of the argument for `--proxy`, use different
(and generic) placeholders to describe the format needed; do not use the
same names of configuration keys to avoid potential confusion.
> 1967780: improve placeholders in help text

- src/rhsmlib/facts/cloud_facts.py
- test/rhsmlib_test/test_cloud_facts.py
* When billingProducts is null, then None value is reported
* Forgot to add marketplaceProductCodes in facts
- I don't have any system for testing with non-null
value, but it should be list according AWS documentation:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html
* Fixed and extended unit tests to cover new behavior
> Fixed reporting of AWS cloud facts (null value)

- src/subscription_manager/managercli.py
When describing the format of the argument for '--proxy', use different
(and generic) placeholders to describe the format needed; do not use the
same names of configuration keys to avoid potential confusion.
(cherry picked from commit 7ea27a2ddd037b15fbbca56488882ed49b60e256)
Backport of #2665 to 1.28.
> [1.28] 1967780: improve placeholders in help text

- .flake8
- Jenkinsfile
- build_ext/setup.py
- jenkins/python3-stylish-tests.sh
- jenkins/python3-tests.sh
- src/rhsm/connection.py
- src/rhsm/m2cryptossl.py
- src/subscription_manager/managercli.py
- src/subscription_manager/migrate/migrate.py
- src/subscription_manager/scripts/rhn_migrate_classic_to_rhsm.py
- src/subscription_manager/scripts/rhsm_facts_service.py
- src/subscription_manager/scripts/sat5to6.py
- src/subscription_manager/scripts/subscription_manager_gui.py
- test-requirements.txt
Cherry picked commit from #2621
subscription-manager does not support Python 2 anymore, so switch the
stylish script to the Python 3 version.
Also, stop using the 'subman-centos7' agent for it, as it clearly does
not support Python 3; the default 'subman' agent will work fine.
> [1.28] jenkins: switch stylish job to Python 3

- syspurpose/man/syspurpose.8
- syspurpose/src/syspurpose/cli.py
Do not refer to the `syspurpose` module of `subscription-manager`, as it does not manage all the syspurpose attributes on its own.
Adopt a more generic text (kindly provided by John Sefler) that points to use the appropriate module of `subscription-manager`.
> [1.28] 1971693: syspurpose: adjust deprecation messages

- subscription-manager.spec
The previous change actually did the opposite, i.e. disable initial-setup
on RHEL _older_ than 9.
Also, extend the disabling to Fedora, as the same reasons for disabling
initial-setup in RHEL 9+ apply to recent Fedora versions.
> 1941904: actually disable initial-setup in RHEL >= 9, and Fedora too

- src/rhsm/config.py
- src/rhsm/logutil.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1967210
* Card ID: ENT-3927
* When not valid value of default_log_level is set in rhsm.conf
and valid values is provided using CLI option
--logging.default_log_level, then do not print warning message
in this case.
* It was necessary to check CLI options in rhsm Python
package in logutil.py module. This is little bit hackish,
because this module should be independent on CLI tools
> 1967210: Do not print warning, when valid value is provided

- src/rhsmlib/cloud/README.md
- src/rhsmlib/cloud/_base_provider.py
- src/rhsmlib/cloud/providers/aws.py
- src/rhsmlib/cloud/providers/azure.py
- src/rhsmlib/cloud/providers/gcp.py
- src/rhsmlib/facts/cloud_facts.py
- test/rhsmlib_test/test_cloud.py
- test/rhsmlib_test/test_cloud_facts.py
* Card ID: ENT-3444
* When we try to use too old API version that is not supported,
then try to get list of available API versions and try to
use the newest one
* Use requests Session to use benefit of keeping connection alive
* Added debug print for HTTP requests that is similar to
debug print that we use for subscription-manager, when it
communicates with candepin server. Debug print can be
enabled using environment variables. More details here:
https://www.candlepinproject.org/docs/subscription-manager/debug_http_traffic.html
* Use timeout for http requests, because when get_metadata()
would be called on VM not running in public cloud, then
we could wait too long for error. Timeout is higher for
Azure, because delays could be more than 1.0 second
in some cases.
* Added few unit tests
* …
> Make Azure cloud collector more reliable

- src/subscription_manager/cli_command/syspurpose.py
Create a custom `prog` placeholder for subparsers of the `syspurpose`
command: this way, they will not have the usage string of the
`syspurpose` command (which includes a `[OPTIONS]` help marker).
> 1975552: remove extra '[OPTIONS]' from syspurpose usage string

- syspurpose/man/syspurpose.8
- syspurpose/src/syspurpose/cli.py
We decided to avoid deprecating the old `syspurpose` executable until
the unified `syspurpose` command in subscription-manager is available.
> [1.28] 1971693: syspurpose: remove deprecation notices

- src/subscription_manager/cli_command/abstract_syspurpose.py
When listing syspurpose values, bring back the distinction between
"unavailable values" and "empty list of values" (reverting the part of
commit c71ee8d0a68e60081d6a87444f83f7fbcffd0c5f in
`AbstractSyspurposeCommand.list()`), so it is possible to keep different
diagnostic messages for them.
Also, improve the message for the error case, more in line with other
syspurpose-related messages.
> 1973807: fix wording on error when listing syspurpose values

- src/subscription_manager/managercli.py
When listing syspurpose values, bring back the distinction between
"unavailable values" and "empty list of values" (reverting the part of
commit a69c86a89e4aa0d50281c99d823a2b6a7bb81798 in
`AbstractSyspurposeCommand.list()`), so it is possible to keep different
diagnostic messages for them.
Also, improve the message for the error case, more in line with other
syspurpose-related messages.
(cherry picked from commit fe9a8e8a1d1528d21c8dc2e9ed4361e9538a9adf)
Backport of #2684 to 1.28.
> [1.28] 1973731: fix wording on error when listing syspurpose values

- man/rhsm.conf.5
Add a brief description of the format of the file, mentioning a couple
of known limitations.
(cherry picked from commit 3c7368f15c237925aea0af9f036295b92f77aeb8)
Backport of #2674 to 1.28.x
> [1.28] 1968420: improve description of rhsm.conf format

- src/subscription_manager/cli_command/syspurpose.py
Use a custom usage string for the 'syspurpose' command, so we can
mention that this command may take a submodule to use.
> 1975552: add '[SUBMODULE]' in syspurpose usage string

- src/cloud_what/README.md
- src/cloud_what/README.md.orig
- src/cloud_what/_base_provider.py
- src/cloud_what/fact_collector.py
- src/cloud_what/provider.py
- src/cloud_what/providers/aws.py
- src/cloud_what/providers/aws.py.orig
- src/cloud_what/providers/azure.py
- src/cloud_what/providers/azure.py.orig
- src/cloud_what/providers/gcp.py
- src/cloud_what/providers/gcp.py.orig
- src/cloud_what/setup.py
- src/rhsmlib/facts/cloud_facts.py
- src/subscription_manager/scripts/rhsmcertd_worker.py
- subscription-manager.spec
- test/cloud_what/test_cloud_what.py
- test/cloud_what/test_cloud_what.py.orig
- test/rhsmlib_test/test_cloud_facts.py
- test/test_auto_registration.py
* Card ID: ENT-3861
* Moved code from src/rhsmlibc/cloud to src/cloud_what
* Updated references to the package and modules in other
code and unit tests
* Changed User-Agent in http headers to cloud-what/1.0
* Moved one RHSM specific method to rhsmcertd_worker.py
* Moved unit tests specific for cloud collector and
cloud detector from test/rhsmlib_test/test_cloud.py
to test/cloud_what/test_cloud_what.py. This file
will be probably split into more files later.
* Moved unit tests related to automatic registration
to own file
* Added method for setting audience for GCPCloudProvider
* Modified .spec file to create python3-cloud-what
RPM package
* TODO: change default GCP audience ID to something
more generic, when it will be necessary
> Move cloud detector/collector to cloud-what package

- src/rhsmlib/facts/cloud_facts.py
- test/rhsmlib_test/test_cloud_facts.py
* Original PR to main branch: #2655
- Contains only one commit: 6dd156415d432d1e6e5034d9b4235fe845f4462b 
* When billingProducts is null, then None value is reported
* Forgot to add marketplaceProductCodes in facts
- I don't have any system for testing with non-null
value, but it should be list according AWS documentation:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-identity-documents.html
* Fixed and extended unit tests to cover new behavior
> [1.28] Fixed reporting of AWS cloud facts (null value)

- src/daemons/rhsmcertd.c
- src/dnf-plugins/product-id/CMakeLists.txt
- src/dnf-plugins/product-id/product-id.c
- src/dnf-plugins/product-id/productdb.c
- src/dnf-plugins/product-id/productdb.h
- src/dnf-plugins/product-id/test-product-id.c
- src/dnf-plugins/product-id/test-productdb.c
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1938878
* Card ID: ENT-3680
* Fixed several issues in C code discoved by static code
analyzers in rhsmcertd and libdnf plugin product-ide
* Fixed CMakeLists.txt: one testing data file (71.pem)
was not copied to 'cert_dir' directory
* Fixed unit test in test-product-id.c. It is not possible
to call pluginGetContext directly with new version
of libdnf
> 1938878: Fix issues discovered by static code analyzers

- subscription-manager.spec
When building cloud-what for different architectures we specifically need to require python3-dmidecode on certain arches.
This causes differences in the rpms built for different arches, which conflicts with the "noarch" BuildArch.
This PR removes the "BuildArch: noarch" to allow the cloud-what package to build slightly differently depending on arch.
> Remove no arch from python3-cloud-what package

- src/rhsmlib/facts/hwprobe.py
- test/rhsmlib_test/test_hwprobe.py
lscpu has a `-J`/`--json` option to output the data as JSON since util-linux 2.30. Since it is obviously meant for machine parsing, and the "human output" recently changed in ways that broke our simple parser, then switch to the JSON output.
Query lscpu to check whether it has a `--json` parameter; this is done scraping the `--help` text, which is not nice, however should do it; if `--json` is available, invoke lscpu that way, and parse the JSON output to populate the facts from it.
Card ID: ENT-4040
> 1976225: read lscpu from its JSON output if available

- src/rhsm/config.py
Assuming that a particualr directory was mounted in a container is not a strong way to detect whether we are running in a container. Check for well-known files of podman and docker first.
> Slightly improve our container detection

- src/cloud_what/provider.py
- src/rhsm/logutil.py
- src/rhsmlib/facts/cloud_facts.py
* Original PR for main branch: #2703 (contains only one commit: 913d1465afecab7a95b98a026fde243baba28e02)
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1976324
* Card ID: ENT-4066
* The cloud_what wasn't added to log root namespaces and for
this reason cloud_what log messages were not printed to
rhsm.log file. Error log messages were printed to stderr.
* Fixed some stylish issues in provider.py and cloud_facts.py
> [1.28] 1976324: Added cloud_what to log root namespaces

- src/cloud_what/provider.py
- src/rhsm/logutil.py
- src/rhsmlib/facts/cloud_facts.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1976324
* Card ID: ENT-4066
* The cloud_what wasn't added to log root namespaces and for
this reason cloud_what log messages were not printed to
rhsm.log file. Error log messages were printed to stderr.
* Fixed some stylish issues in provider.py and cloud_facts.py
> 1976324: Added cloud_what to log root namespaces

- subscription-manager.spec
* Original PR: #2700
* When building cloud-what for different architectures we specifically need to require python3-dmidecode on certain arches.
This causes differences in the rpms built for different arches, which conflicts with the "noarch" BuildArch.
* This PR removes the "BuildArch: noarch" to allow the cloud-what package to build slightly differently depending on arch.
> [1.28] Remove no arch from python3-cloud-what package

- src/cloud_what/providers/aws.py
- src/rhsm/profile.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1924126
* Card ID: ENT-3583
* Fix AWS RHUI repo url, when data for profile are gathered.
Replace REGION with value provided in AWS metadata
> 1924126: Fix profile upload on AWS systems

- src/rhsm/connection.py
- src/subscription_manager/cli_command/attach.py
- src/subscription_manager/exceptions.py
- test/test_exceptions.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1976240
* Card ID: ENT-3914
The error message in the attach command prints error code and a message
received from the server.
Instead of relying on internal RestlibException string representation
a less scary/more friendly format is used, by placing the error message
before the error code. It's also being translated with ExceptionMapper.
One property has been added to the RestlibException to prevent duplicate
code.
> 1976240: Improve HTTP code/message reporting in error strings

- subscription-manager.spec
The CentOS team currently applies manual debranding to remove the initial-setup-gui supplements from the initial-setup-addon subpackage.  After discussing this with @ptoscano, we agreed it made more sense to just disable the initial-setup-addon subpackage entirely when built for CentOS.
> Do not ship initial-setup in CentOS

- man/subscription-manager.8
- src/rhsm/logutil.py
- test/test_logutil.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1876828
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1890314
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1876841
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1947844
* Card ID: ENT-3051
* Card ID: ENT-3852
Before this change the only log location was /var/log/rhsm/rhsm.log. If the subscription-manager was run as non-root user (as dnf plugin, e.g. 'dnf list'), it sent several error messages to stderr, polluting the output.
Now the UID of the subman process is checked:
- If the program is run as root (UID 0), the log location is still /var/log/rhsm/rhsm.log.
- If the program is run as non-root (other UIDs), the log location is $XDG_CACHE_HOME/rhsm/rhsm.log (~/.cache/rhsm/rhsm.log in most cases).
- If the location is not …
> 1876828: Try to suppress errors in stderr when not run as root

- man/subscription-manager.8
- src/rhsm/logutil.py
- test/test_logutil.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1876828
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1890314
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1876841
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1947844
* Card ID: ENT-3051
* Card ID: ENT-3852
Before this change the only log location was /var/log/rhsm/rhsm.log. If
the subscription-manager was run as non-root user (as dnf plugin, e.g.
'dnf list'), it sent several error messages to stderr, polluting the
output.
Now the UID of the subman process is checked:
- If the program is run as root (UID 0), the log location is still
/var/log/rhsm/rhsm.log.
- If the program is run as non-root (other UIDs), the log location is
$XDG_CACHE_HOME/rhsm/rhsm.log (~/.cache/rhsm/rhsm.log in most cases).
- If the location is not …
> [1.28] 1876828: Try to suppress errors in stderr when not run as root

- src/rct/manifest_commands.py
- src/subscription_manager/migrate/migrate.py
Add quotes to a {filename} and remove an extra space.
> 1977452: typo in string format change

- etc-conf/subscription-manager.completion.sh
* Card ID: ENT-4013
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1974641
After the syspurpose was added as subcommand in 5406865 the 'prev'
variable was not always set correctly. For the first argument the
completion worked fine, but for the second (and further) the last
argument was picked up instead of the last subcommand.
This change iterates over the CLI arguments and uses the last word that
does not start with a dash, skipping all arguments and finding the last
subcommand.
> 1974641: Fix tab completion with multiple optional commands

- man/subscription-manager.8
- src/subscription_manager/cli_command/repos.py
- test/cli_command_test/test_repos.py
With the old `optparse` implementation, there was a single callback to
fill `repo_actions` with the various values of the `--enable` & `--disable`
options, in the same order they were specified on the command line.
Commit eef1bb13f8924af9539f98330465c110f2df92b5 switched to `argparse`,
and switched to different destination lists for `--enable` & `--disable`,
mixing them back to a single list with first all the repos to enabled
and then all the repos to disable. As result, the order of intermixed
`--enable` & `--disable` was lost.
To revert back to the wanted behaviour, implement a custom
`argparse.Action` for `--enable` & `--disable` that appends all the actions to
the same list in the same order they were specified. This removes the
need for post-processing later on.
Also, explicitly …
> 1984133: repos: respect order of --enable & --disable

- src/rhsmlib/facts/hwprobe.py
subscription-manager facts command shows the wrong value of cpu.cpu_socket(s)
on the Fujitsu A64FX machine.
```
...
cpu.cpu_socket(s): 4
```
A64FX is one socket architecture, so it should be cpu.cpu_socket(s): 1.
subscription-manager gets the wrong value because it counts the cores per
cpu by using /sys/devices/system/cpu/cpuX/topology/core_siblings_list.
For A64FX, the sysfs file shows the cores mask which are in the
same CMG (Core Memory Group), not the core mask per socket.
A64FX has always 4 CMGs on the socket [1], so we can get the number
of cores by:
```
count_cpumask_entries(, 'core_siblings_list') * 4CMGs
```
[1] :   [A64FX Microarchitecture Manual ](https://github.com/fujitsu/A64FX/blob/master/doc/A64FX_Microarchitecture_Manual_en_1.5.pdf)
1.2. A64FX Processor Specification
> hwprobe.py: Fix counting cores per cpu for Fujitsu A64FX CPU

- src/rhsm/profile.py
- test/test_cache.py
Katello has run into an issue where the package profile from sub-man includes inactive, but enabled module streams.  Here is the context:
A user enables the perl 5.26 module stream. It enables perl-IO-Socket-SSL as a dependent module stream.  In the background, with dnf, the system has 3 perl-IO-Socket-SSL modules streams enabled with the same name, stream, version, and arch, but different contexts. Only one is active, because only one actually belongs to the perl 5.26 module.  This is causing RPM applicability to break in Katello. Katello applicability is not considering that there could be multiple enabled module streams with the same NSVA but differing context.
I am not seeing the case where Katello needs to know about enabled and inactive module streams.  As such, to stop our …
> 1980418: Add 'active' field to module stream profile

- src/rhsm/profile.py
- test/test_cache.py
Katello has run into an issue where the package profile from sub-man includes inactive, but enabled module streams.  Here is the context:
A user enables the perl 5.26 module stream. It enables perl-IO-Socket-SSL as a dependent module stream.  In the background, with dnf, the system has 3 perl-IO-Socket-SSL modules streams enabled with the same name, stream, version, and arch, but different contexts. Only one is active, because only one actually belongs to the perl 5.26 module.  This is causing RPM applicability to break in Katello. Katello applicability is not considering that there could be multiple enabled module streams with the same NSVA but differing context.
I am not seeing the case where Katello needs to know about enabled and inactive module streams.  As such, to stop our …
> [1.28] 1980418: Add 'active' field to module stream profile

- Makefile
- cockpit/lib/packagekit.js
- docs/sphinx/conf.py
- docs/sphinx/index.rst
- etc-conf/rhsm.conf
- integration-tests/run
- man/subscription-manager.8
- pylintrc
- scripts/checkcommits.sh
- src/rhsmlib/facts/hwprobe.py
- src/subscription_manager/certdirectory.py
- src/subscription_manager/cli_command/override.py
- src/subscription_manager/cli_command/repos.py
- src/subscription_manager/i18n.py
- src/subscription_manager/productid.py
- test/rhsmlib_test/test_hwprobe.py
* Card ID: ENT-3764
Following changes were made:
- blacklist -> blocklist, block
- master -> main
- master device, slave device -> bond device, permanent device
Additional notes:
- cockpit/lib/packagekit.js: PackageKit URL has been updated to main; their primary branch is no longer called master
- itegration-tests/run: Cockpit URL has been updated to main; their primary branch is no longer called master
- src/subscription_manager/i18l.py: BLACKLISTED_LOCALES and the 'if' was removed (see https://bugzilla.redhat.com/show_bug.cgi?id=1857214), it was not run anyway because it was only executed on Python 2.
Words that were not replaced:
- subscription-manager.spec: This file contains changelog, which is not subject to these changes.
- pylintrc: MASTER ini heading
- docs/sphinx/conf.py: …
> Change comments and variables to follow Conscious language initiative

- src/rhsmlib/facts/cloud_facts.py
- test/rhsmlib_test/test_aws_instance.py
* Card ID: ENT-4106
* Backported support for marketplace ID to RHEL7
- Azure is supported fully
- AWS is supported using IMDSv1
* AWS do not use caching of AWS facts, because it could
cause some issues, when VM is migrated
* Modified some unit tests
> [1.24] Added support for marketplace ID on RHEL7.

- Jenkinsfile
- jenkins/libdnf-tests.sh
* Unit tests for libdnf are run in parallel with other tests,
because it is not related to other Python code
> Added new stage for running libdnf unit tests.

- man/subscription-manager.8
* Card ID: ENT-4150
Syspurpose was added as subscription-manager subcommand in 5406865.
Sections describing its subcommands were altered to match the update,
but 'syspurpose' itself was not added to the list of subcommands.
> Add 'syspurpose' to list of commands in manpage

- src/cloud_what/_base_provider.py
- src/cloud_what/providers/aws.py
- test/cloud_what/test_cloud_what.py
- test/rhsmlib_test/test_cloud_facts.py
- test/test_auto_registration.py
- test/test_cache.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1922151#c5
* In-memory cache wasn't used properly
* All instances of BaseCloudProvider and subclasses are sinletons
to be able to store in-memory cache easily. The code is not
thread safe at this momement, because it is not necessary now.
Making code thread safe will require more effort and it will
be solved in different PR/commit.
* Fixed unit tests, because singleton is used
* Added unit test for singleton and using in-memory cache
> 1922151: Use in-memory cache on AWS too

- Makefile
- subscription-manager.spec
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1922151#c6
* The /var/cache/cloud-what should be part of python3-cloud-what
RPM to be able to fix SELinux context.
* It will be necessary to create another PR to fix SELinux context
for this directory too, but it will be done in another PR
against another repository:  https://github.com/fedora-selinux/selinux-policy
> 1922151: Add /var/cache/cloud-what to python3-cloud-what RPM.

- src/cloud_what/_base_provider.py
- src/cloud_what/providers/aws.py
- test/cloud_what/test_cloud_what.py
- test/rhsmlib_test/test_cloud_facts.py
- test/test_auto_registration.py
- test/test_cache.py
* Cherry-pick of d0b2bb31ad5efcc0a4a7ce78467c64e28c1adf34 to 1.28 branch
* Original PR: #2730 
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1922151#c5
* In-memory cache wasn't used properly
* All instances of BaseCloudProvider and subclasses are sinletons
to be able to store in-memory cache easily. The code is not
thread safe at this momement, because it is not necessary now.
Making code thread safe will require more effort and it will
be solved in different PR/commit.
* Fixed unit tests, because singleton is used
* Added unit test for singleton and using in-memory cache
> [1.28] 1922151: Use in-memory cache on AWS too

- Makefile
- subscription-manager.spec
* Backport of 43dbd7bceef805ad0c6b8a48ba4001a7a2e3e80f to 1.28 branch
* Original PR: #2736
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1922151#c6
* The /var/cache/cloud-what should be part of python3-cloud-what
RPM to be able to fix SELinux context.
* Permissions for /var/cache/cloud-what: 750 (root:root)
* It will be necessary to create another PR to fix SELinux context
for this directory too, but it will be done in another PR
against another repository:
https://github.com/fedora-selinux/selinux-policy
* PR for selinux-policy here: https://github.com/fedora-selinux/selinux-policy/pull/836
> [1.28] 1922151: Add /var/cache/cloud-what to python3-cloud-what RPM.

- src/subscription_manager/cli_command/org.py
- src/subscription_manager/cli_command/service_level.py
- src/subscription_manager/cli_command/usage.py
* Card ID: ENT-4168
Before this change 'service-level' and 'usage' contained their own
description of the shared '--org' argument.
> ENT-4168: Unify description of --org argument in syspurpose subcommands

- src/subscription_manager/managercli.py
This is a backport of PR #2735.
* Card ID: ENT-4168
Before this change 'service-level' and 'usage' contained their own
description of the shared '--org' argument.
> [1.28] ENT-4168: Unify description of --org in syspurpose subcommands

- man/subscription-manager.8
- src/subscription_manager/cli_command/abstract_syspurpose.py
- src/subscription_manager/cli_command/service_level.py
- test/cli_command_test/test_role.py
- test/cli_command_test/test_service_level.py
* Card ID: ENT-2697
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1859569
- If the system is registered, abort if --username, --password, --token or --org are specified.
- In man page, the --org argument has been moved up so it is directly below other arguments usable on unregistered systems.
- For those arguments the description has been altered to clarify their meaning.
> 1859569: Abort on invalid username/token argument in syspurpose subcommands

- man/subscription-manager.8
- src/subscription_manager/managercli.py
- test/test_managercli.py
This is a backport of PR #2721.
* Card ID: ENT-2697
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1859569
- If the system is registered, abort if --username, --password, --token
or --org are specified.
- In man page, the --org argument has been moved up so it is directly
below other arguments usable on unregistered systems.
- For those arguments the description has been altered to clarify their
meaning.
> [1.28] 1859569: Abort on invalid username/token argument in syspurpose

- src/rhsmlib/facts/hwprobe.py
This change may require further testing before going to a new stable
release of RHEL, so let's pull it out for now.
This reverts commit a03992a84c624ac9ffede7f6faff5af9a1cf7f8e.
> Revert "hwprobe.py: Fix counting cores per cpu for Fujitsu A64FX CPU"

- src/rhsm/connection.py
- src/subscription_manager/exceptions.py
- src/subscription_manager/managercli.py
- test/test_exceptions.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1976240
* Card ID: ENT-4114
* Original commit: ab97ef6 in PR #2706
The error message in the attach command prints error code and a message
received from the server.
Instead of relying on internal RestlibException string representation
a less scary/more friendly format is used, by placing the error message
before the error code. It's also being translated with ExceptionMapper.
One property has been added to the RestlibException to prevent duplicate
code.
> [1.28] 1976240: Improve HTTP code/message reporting in error strings

- Jenkinsfile
(cherry picked from commit fc430a02fa617e62968a18cf46ad9a99b5e14ca7)
Backport of #2585.
> adding timoeout to jenkins pipeline (#2585)

- .flake8
They were present only in code parts that were recently dropped, so it
is possible to safely enable them again by default.
Card-ID: ENT-4081
Card-ID: ENT-4086
> flake8: enable E131, E714

- build_ext/build_ext/lint.py
- build_ext/setup.py
- tox.ini
* Card ID: ENT-4213
Package pep8 has been renamed to pycodestyle in 2017.
pycodestyle is a dependency for flake8, this will not alter any linting
behavior.
> ENT-4213: Remove deprecated pep8 package

- src/rhsm/config.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1983074
* Card ID: ENT-4174
'NOSET' is not supported log level, and should not be included in the
list of possible log level values.
> 1983074: Remove invalid log level

- src/rhsm/config.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1983074
* Card ID: ENT-4174
'NOSET' is not supported log level, and should not be included in the
list of possible log level values.
> [1.28] 1983074: Remove invalid log level

- build_ext/build_ext/template.py
- build_ext/build_ext/utils.py
`run_if_new()` will run the callback when the destination file is either
missing or older than the source file, and these are the only cases when
we have to make sure the directory of the destination file exists; in
case the destination file already exists, then also its directory exists
already, and we can avoid even trying to ensure it exists.
Remove TOCTOU issues when creating directories during the build process:
directly use `exist_ok=True` for `os.makedirs()`, so there is no need to
check for the existance of directories just before, risking a potential
race between check and creation (which will fail with `EEXIST`).
Additional note: this might fix, or at least reduce a bit, the "File exists" errors when building translations.
> build: try to reduce potential TOCTOU issues when creating destination directories

- src/rhsm/connection.py
- src/rhsmlib/client_info.py
- src/rhsmlib/dbus/__init__.py
- src/rhsmlib/dbus/base_object.py
- src/rhsmlib/dbus/dbus_utils.py
- src/rhsmlib/dbus/objects/attach.py
- src/rhsmlib/dbus/objects/config.py
- src/rhsmlib/dbus/objects/consumer.py
- src/rhsmlib/dbus/objects/entitlement.py
- src/rhsmlib/dbus/objects/products.py
- src/rhsmlib/dbus/objects/register.py
- src/rhsmlib/dbus/objects/syspurpose.py
- src/rhsmlib/dbus/objects/unregister.py
- src/rhsmlib/dbus/server.py
- src/rhsmlib/dbus/util.py
- src/rhsmlib/utils.py
- src/subscription_manager/cp_provider.py
- test/rhsmlib_test/base.py
- test/rhsmlib_test/test_utils.py
* When some application call D-Bus method, then the application
can be identified using sender argument of the method.
This argument used to be unused. The sender ID (e.g. ':1:3003')
can be used for finding of PID and this PID can be used for
finding command line used for starting the application that
sent the D-Bus method. This could be e.g.: 'dbus-send',
'cockpit-bridge', etc. (note: all command line options are
stripped for security reason to not send username nor password).
The command line of D-Bus sender is stored in singleton and
then this command line is added to User-Agent http header
as 'dbus_sender=cockpit-bridge'
* The sender argument is saved to singleton using decorator
dbus_handle_sender implemented in rhsmlib.dbus.util.
When it will not be desired to store sender for some …
> Include D-Bus sender in User-Agent http header

- src/rhsmlib/facts/collection.py
- src/rhsmlib/services/config.py
- test/test_productid.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1995465
* The `collections.MutableMapping` was deprecated in Python 3.3
and new `collections.abc.MutableMapping` should be used.
The old API will be completely removed in Python 3.10.
* Fixed another similar issue with `collections.Iterable`
in unit tests
> 1995465: Do not use deprecated collections.MutableMapping

- src/subscription_manager/cli_command/abstract_syspurpose.py
- src/subscription_manager/cli_command/cli.py
- src/subscription_manager/cli_command/environments.py
- src/subscription_manager/cli_command/facts.py
- src/subscription_manager/cli_command/identity.py
- src/subscription_manager/cli_command/owners.py
- src/subscription_manager/cli_command/refresh.py
- src/subscription_manager/cli_command/register.py
- src/subscription_manager/cli_command/remove.py
- src/subscription_manager/cli_command/service_level.py
- src/subscription_manager/exceptions.py
- test/test_exceptions.py
* Card ID: ENT-4228
Following PR #2706 (ab97ef6, ENT-3914) this change formats the rest of
rhsmlib exceptions with ExceptionMapper. It ensures that the exceptions
have unified format of "Message from candlepin. (HTTP error code XXX: YYY)".
> ENT-4228: Always format restlib exceptions

- src/subscription_manager/exceptions.py
- src/subscription_manager/managercli.py
- test/test_exceptions.py
* Card ID: ENT-4228
This is a backport into RHEL 8.
Following ENT-4114 this change formats the rest of rhsmlib exceptions
with ExceptionMapper. It ensures that the exceptions have unified
format of "Message from candlepin. (HTTP error code XXX: YYY)".
> [1.28] ENT-4228: Always format rhsmlib exceptions

- src/subscription_manager/cli_command/cli.py
- test/test_managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1983144
* Card ID: ENT-4233
When unknown subcommand or argument is supplied, an error message is
printed and sub-man exits. This commit changes the error message to be
the same as it was before we switched from optparse to argparse.
> 1983144: More useful feedback on unknown argument

- src/subscription_manager/cli_command/abstract_syspurpose.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1859157
* Card ID: ENT-2701
If the user has more than one organization the --org argument can be
used to specify one of them.
If the --org value was set to some invalid string, error message was
just a generic text that the list of valid values could not be obtained.
Now the proper message, returned by the server, is shown and EX_SOFTWARE
exit code is used.
> 1859157: Display better error message on incorrect --org

- src/subscription_manager/managercli.py
This is a backport of PR #2779.
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1859157
* Card ID: ENT-2701
If the user has more than one organization the --org argument can be
used to specify one of them.
If the --org value was set to some invalid string, error message was
just a generic text that the list of valid values could not be obtained.
Now the proper message, returned by the server, is shown and EX_SOFTWARE
exit code is used.
(cherry picked from 65ff3d9ffae6af4cbf4a208cd5bb04468da1d41f)
> [1.28] 1859157: Display better error message on incorrect --org

- build_ext/build_ext/template.py
- build_ext/build_ext/utils.py
`run_if_new()` will run the callback when the destination file is either
missing or older than the source file, and these are the only cases when
we have to make sure the directory of the destination file exists; in
case the destination file already exists, then also its directory exists
already, and we can avoid even trying to ensure it exists.
Remove TOCTOU issues when creating directories during the build process:
directly use `exist_ok=True` for `os.makedirs()`, so there is no need to
check for the existance of directories just before, risking a potential
race between check and creation (which will fail with `EEXIST`).
Additional note: this might fix, or at least reduce a bit, the "File exists" errors when building translations.
This is a backport of PR: #2722 to …
> [1.28] build: try to reduce potential TOCTOU issues when creating destination directories

- src/rhsmlib/dbus/objects/consumer.py
* Added new D-Bus method `GetOrg()` to interface
`com.redhat.RHSM1.Consumer`
* It is possible to get current organization (owner), when system
is already registered
* This method return string containing JSON document with information
about current organization. Information provided in returned JSON
document can be used for detection of SCA mode
* There is already method `GetOrgs()`, but it can be used for getting
list of valid organizations for given user. It is necessary to
provide username and password. Thus `GetOrg()` is intended for
clients that are already registered.
> New D-Bus method GetOrg()

- syspurpose/man/syspurpose.8
- syspurpose/src/syspurpose/cli.py
The standalone syspurpose tool is deprecated, as all the system purpose
handling is done with subscription-manager.
Card ID: ENT-4309
> 2000867: syspurpose: show deprecation notices

- cockpit/src/index.js
- cockpit/src/subscriptions-client.js
- cockpit/src/subscriptions-view.jsx
- cockpit/src/subscriptions.scss
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1979323
* Cockpit plugin has changed little bit since the bug report
was created. There is no red icon anymore, but red text
"Not subscribed" was displayed in the header of installed
product
* New method GetOrg is used for gathering information
about current organization. We can get information about
SCA mode from current ogranization (owner)
* When SCA mode is used, then just do not disaply any text
about subscription in the header of installed product
* When SCA mode is used, then following attributes are not
printed: Status, Starts and Ends
* When SCA mode is used, then Auto-attach button is not
displayed at all.
* Organization name is printed in the Overview card, because
we had to gather information about organization anyway.
When no …
> 1979323: Cockpit - do not show red red icon in SCA mode

- src/subscription_manager/managercli.py
- test/test_managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1924338
* PR for main branch: #2776
* Backported this change for 1.28 branch. Simple cherry-pick of 9c3823c75e91b5d75b300332d5a4e129f68ba653 was not possible, because there were only conflicts.
* Card ID: ENT-4058
* When SCA mode is enabled, then do not print: "Status",
"Status Details", Start date and End date, because it only
confused users
> 1924338: [1.28] list prints no status and dates in SCA mode

- src/subscription_manager/cli_command/org.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2003777
* Card ID: ENT-4316
If the user has more than one organization available and uses --list
to show one of system purposes they are asked to enter key of one of
their organizations.
Now, before they are prompted to enter the organization, a list of all
available organizations will be shown.
This functionality is already available in the 'register' command since
1ad8b33 (2020-02).
> 2003777: Show available organizations before asking for input

- test/rhsm/unit/pathtree_tests.py
- test/rhsmlib_test/test_attach.py
- test/rhsmlib_test/test_config.py
- test/rhsmlib_test/test_register.py
- test/rhsmlib_test/test_unregister.py
* Card ID: ENT-4274
Six library was used to provide compatibility layer between Python 2
and Python 3. subscription-manager is Python 3 only, so these functions
can be simply replaced with their PY3 versions with no change of
behavior.
> ENT-4274: Remove six.assert* methods

- src/plugins/dnf/subscription-manager.py
- src/rct/printing.py
- src/rhsm/connection.py
- src/rhsmlib/compat/subprocess_compat.py
- src/rhsmlib/dbus/dbus_utils.py
- src/subscription_manager/cli.py
- src/subscription_manager/i18n.py
- src/subscription_manager/identity.py
- src/subscription_manager/plugins.py
- src/subscription_manager/utils.py
- test/fixture.py
- test/rhsmlib_test/test_insights.py
- test/test_managercli.py
* Card ID: ENT-4272
In order to maintain compatibility between Python 2 and Python 3, the
six.PY2/six.PY3 variables were used to conditionally run a block of
code. Python 2 support has been dropped and they are no longer
necessary.
> ENT-4272: Remove Python 2 conditionals

- .flake8
- example-plugins/dbus_event.py
- src/rct/manifest_commands.py
- src/rhsm/certificate.py
- src/rhsm/utils.py
- src/rhsmlib/dbus/dbus_utils.py
- src/rhsmlib/facts/cleanup.py
- src/rhsmlib/facts/hwprobe.py
- src/subscription_manager/i18n_argparse.py
- src/subscription_manager/plugins.py
- src/subscription_manager/productid.py
- test/cli_command_test/test_release.py
- test/modelhelpers.py
- test/rhsm/unit/pathtree_tests.py
- test/rhsmlib_test/test_hwprobe.py
- test/stubs.py
- test/test_branding.py
- test/test_certlib.py
- test/test_certmgr.py
- test/test_facts.py
- test/test_identitycertlib.py
- test/test_managerlib.py
- test/test_ostree_content_plugin.py
- test/test_plugins.py
- test/test_po_files.py
- test/test_productid.py
- test/test_rct_manifest_command.py
- test/test_repolib.py
- test/test_validity.py
* Card ID: ENT-4082
E265: Block comment should start with '#'
Following files contained commented-out code that has not been changed
in a long time:
- src/rhsm/certificate.py: 22c26cc (2013-01)
- src/rhsm/utils.py: e7f88c6 (2013-12)
- src/rhsmlib/dbus/dbus_utils.py: 2aa48ef (2017-01)
- example-plugins/dbus_event.py: e706c53 (2014-02)
Commented-out code violating E265 have not been removed in test files,
only the spacing has been fixed. It should be investigated separately
why the lines are commented out.
> ENT-4082: Fix flake8 error E265

- test/fixture.py
* Caused by our effort of removing six (e.g. ENT-4272). One
unused import of six leaked in due to solving conflicts.
> Fixed one unused import of six

- src/rhsmlib/facts/dmiinfo.py
- src/subscription_manager/cache.py
- src/subscription_manager/entcertlib.py
- src/subscription_manager/healinglib.py
- src/subscription_manager/i18n.py
- src/subscription_manager/validity.py
- test/rhsmlib_test/test_entitlement.py
- test/rhsmlib_test/test_register.py
- test/test_utils.py
* Card ID: ENT-4340
This commit resolves some of the deprecation warnings that are being
emitted by parts of subscription-manager code. They can be seen, for
example, when 'pytest' is run.
Following changes have been made:
- 'assertRaisesRegex()' instead of 'assertRaisesRegexp()',
- 'assertEqual()' instead of 'assertEquals()',
- 'warning()' instead of 'warn()',
- 'bind_textdomain_codeset() is being removed.
The 'bind_textdomain_codeset' has been deprecated since Python 3.8 and
is being removed in Python 3.10. It only affects calls to 'l'-prefixed
functions of gettext ('lgettext()') which are not used in the code base.
> ENT-4340: Resolve deprecation warnings

- src/subscription_manager/cli_command/org.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2003777
* Card ID: ENT-4411
Recent patch (#2796) added a hint message to the --org argument.
This follow-up update slightly changes the behavior, so the hint is only
displayed when the user did not use the --org at all.
When they used it and it's valid, the hint is skipped and the syspurpose
subcommand is run as usual.
When they used it and it's invalid, the hint is skipped and formatted
RhsmlibException is printed saying that the organization could not be
found.
Now the behavior will be the same as it is in the register subcommand.
> 2003777: Only hint organizations if it's needed

- src/subscription_manager/cache.py
- src/subscription_manager/entcertlib.py
* Cherry-pick PR. Original PR: #2820
* Cherry-picked commit: 3567c93fb08ace29198bbeea6b0124af051ff6bd
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2014052
* Card ID: ENT-4469
In SCA enabled mode, Subscription manager and Yum are sending
redundant API calls (/accessible_content) to fetch the SCA
certificate from Candlepin and refresh the redhat.repo file
everytime unnecessarily which is also causing redundant
API calls (/content_overrides and /release) to the Candlepin.
Servers such as Satellite may encounter unnecessarily high
traffic loads when a lot of hosts are registering or patching
concurrently. This patch fixed the issue.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2010137
> [1.28] Fix redundant API calls to Candlepin

- subscription-manager.spec
There are no `.pem` files in `/etc/pki/entitlement` in case a system is not
registered; in that case, the shell expansion will error out, producing
an error message (ignored) during upgrades.
Instead, find the files manually and run chmod on whatever was found;
this way there is no behaviour change (the permissions of `.pem` files
are properly set), there is no message in case of no certificates, and
(bonus) the errors from chmod are no more ignored.
Card ID: ENT-4473
> 2015173: chmod /etc/pki/entitlement/*.pem only when existing

- subscription-manager.spec
Python 3.6 is the required Python version in `main`, hence drop the support for Python 2, and all the distributions that do not support Python 3; this means dropping the (already broken) support for:
- SUSE older than 15
- RHEL older than 8
- Fedora older than 33 (older versions are EOL)
> spec: drop support for old systems/bits

- subscription-manager.spec
There are no .pem files in /etc/pki/entitlement in case a system is not
registered; in that case, the shell expansion will error out, producing
an error message (ignored) during upgrades.
Instead, find the files manually and run chmod on whatever was found;
this way there is no behaviour change (the permissions of .pem files
are properly set), there is no message in case of no certificates, and
(bonus) the errors from chmod are no more ignored.
Card ID: ENT-4473
(cherry picked from commit cbf9ca2089282c3e1f77c000cbb9ff062031adb3)
Backport of PR #2858 to 1.28.
> [1.28] 2015173: chmod /etc/pki/entitlement/*.pem only when existing

- src/subscription_manager/cli_command/service_level.py
- test/cli_command_test/test_service_level.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1985845
* When candlepin has syspurpose capability, then use benefits
of SyncedStore
> 1985845: Fix sub-man service-level --show

- src/subscription_manager/managercli.py
- test/fixture.py
- test/test_managercli.py
The issue in the BZ is that the proxy is tested even if it is not needed. The test I removed was not taking the no_proxy value before determining if the test of the proxy server is useful.
Turns out that this test does not give us more information than we otherwise get, so it has been removed.
> 1859529: Remove proxy server test as it is unnecessary

- integration-tests/check-subscriptions
The cockpit CI currently assumes a Red Hat system, and it already sort of works on Fedora. The only bits specific to RHEL are the ones related to Red Hat Insights, which is easy enough to limit to RHEL.
With these simple changes, the cockpit CI will successfully run also on Fedora.
Card ID: ENT-4475
> cockpit CI: make it run on Fedora

- syspurpose/setup.py
- syspurpose/src/syspurpose/cli.py
Hopefully solve the issues related to the i18n of the `syspurpose` tool:
- extract also the messages of the Python `argparse` module, as Python does not have own translations; sub-man already does the same
- translate few UI strings that were not already translatable
- remove a redundant `_()` call
There will be a followup PR to update the translation catalogs in the `subscription-manager-1.28` branch.
Card ID: ENT-4494
Related BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2013162 (this PR alone cannot fix it completely)
> [1.28] syspurpose: solve i18n issues

- integration-tests/check-subscriptions
Now that the service image (with Candlepin) used in the cockpit CI exports the Candlepin CA certificates, use them to properly validate the SSL connections to Candlepin. This way, the tests behave almost like a production environment, where all the certificates are properly signed and valid.
Also, validate the SSL connections to the internal `mock-insights` service, for the same reasons as Candlepin.
> cockpit CI: fix SSL validation to Candlepin & mock-insights

- etc-conf/subscription-manager.completion.sh
* Card ID: ENT-4512
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2021982
This commit adds 'syspurpose' to bash completion top level output.
This is essentially a backport of c3f4534.
Completion of syspurpose subcommands already works, as it has been done
as part of the main backport in 4e29138 (PR #2745).
> [1.28] 2021982: Fix syspurpose bash completion

- src/rhsm/connection.py
In case the connection to the remote host fails and there is a proxy
server in use, assume it is a proxy error: errors from the actual
destination host are reported as `OSError`'s but not as `ConnectionError`'s
(as they rely error data coming from the established connection to the
proxy server).
> connection: recognize proxy errors

- src/subscription_manager/cli_command/abstract_syspurpose.py
- src/subscription_manager/syspurposelib.py
`AbstractSyspurposeCommand` tries to synchronize the syspurpose status
from the server. If the customer no more exists,
`SyspurposeSyncActionCommand.perform()` gets a `GoneException`, caught by
the generic `ConnectionException` handler (as `GoneException` is a indirect
subclass of `ConnectionException`). In that case, an error status report
is returned, which is not what `AbstractSyspurposeCommand` expects.
Since `SyspurposeSyncActionCommand` is indirectly used in other contexts
(e.g. rhsmcertd) than the syspurpose CLI, tweak a bit its exception
handling: add a custom parameter to request the passthrough of
`GoneException`'s, so they can be propagated back. `CliCommand.main()`,
which invokes the requested CLI command, already handles `GoneException`,
giving the proper diagnostic.
Card ID: …
> 2020248: handle server-side consumer deletion in syspurpose commands

- src/subscription_manager/managercli.py
- src/subscription_manager/syspurposelib.py
`AbstractSyspurposeCommand` tries to synchronize the syspurpose status
from the server. If the customer no more exists,
`SyspurposeSyncActionCommand.perform()` gets a `GoneException`, caught by
the generic `ConnectionException` handler (as `GoneException` is a indirect
subclass of `ConnectionException`). In that case, an error status report
is returned, which is not what `AbstractSyspurposeCommand` expects.
Since `SyspurposeSyncActionCommand` is indirectly used in other contexts
(e.g. rhsmcertd) than the syspurpose CLI, tweak a bit its exception
handling: add a custom parameter to request the passthrough of
`GoneException`'s, so they can be propagated back. `CliCommand.main()`,
which invokes the requested CLI command, already handles `GoneException`,
giving the proper diagnostic.
(cherry …
> [1.28] 2020284: handle server-side consumer deletion in syspurpose commands

- src/rhsmlib/facts/collection.py
- src/rhsmlib/services/config.py
- test/test_productid.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1995465
* The collections.MutableMapping was deprecated in Python 3.3
and new collections.abc.MutableMapping should be used.
The old API will be completely removed in Python 3.10.
* Fixed another similar issue with collections.Iterable
in unit tests
(cherry picked from commit 556aef8a8a6cd61d36f708f6cadfdeee159d6967)
Backport of PR #2753 to 1.28 to fix that branch with Python 3.10.
> [1.28] 1995465: Do not use deprecated collections.MutableMapping

- src/rhsm/connection.py
In case the connection to the remote host fails and there is a proxy
server in use, assume it is a proxy error: errors from the actual
destination host are reported as OSError's but not as ConnectionError's
(as they rely error data coming from the established connection to the
proxy server).
(cherry picked from commit 947e0712df7e8aa8d75b1674962d13c6e5969151)
Backport of PR #2874 to 1.28.
> [1.28] connection: recognize proxy errors

- src/plugins/libdnf/CMakeLists.txt
Merely append our custom CFLAGS to the ones inherited by the
environment, otherwise the latter are lost.
Card ID: ENT-4516
> 2023391: libdnf: respect environment CFLAGS

- src/dnf-plugins/product-id/CMakeLists.txt
Merely append our custom CFLAGS to the ones inherited by the
environment, otherwise the latter are lost.
Card ID: ENT-4516
(cherry picked from commit 2e9fe484d6c6d689170b3241f8ce46e60af9ca1f)
Backport of PR #2887 to 1.28.
> [1.28] 2023392: libdnf: respect environment CFLAGS

- Makefile
Due to spaces used to indent the commands, the "build" target
effectively did not run any command as part of it, with only its
"rhsmcertd" dependency being done.
Hence, properly use tabs for the make commands, and fix the syntax used
to pass $EXCLUDE_PACKAGES to the commands.
> 2024929: build: fix build on 'build' target

- cockpit/src/subscriptions-view.jsx
- integration-tests/check-subscriptions
* When no system purpose attributes are set, then it is
still usefull to display system purpose card, because
we still want to display system purpose status
* When no system purpose attributes are set, then simple
<EmptyState /> with following text is displayed
"No system purpose attributes set".
Note: The card with installed products has same behavior.
When there is not any installed products, then empty
state is also displayed and the card with installed
products does not disappear.
* Fixed integration test of cockpit plugin
> Cockpit plugin: display syspurpose card without attributes

- Makefile
Due to spaces used to indent the commands, the "build" target
effectively did not run any command as part of it, with only its
"rhsmcertd" dependency being done.
Hence, properly use tabs for the make commands, and fix the syntax used
to pass $EXCLUDE_PACKAGES to the commands.
(cherry picked from commit 4ce9da718589d5e6662dee806b810b1bd6913334)
Backport PR #2889 to 1.28.
> 2024930: build: fix build on 'build' target

- cockpit/src/subscriptions-client.js
- src/rhsmlib/dbus/objects/config.py
- src/rhsmlib/dbus/objects/register.py
- src/rhsmlib/dbus/server.py
- src/rhsmlib/file_monitor.py
- src/rhsmlib/services/attach.py
- src/rhsmlib/services/entitlement.py
- src/rhsmlib/services/register.py
- src/rhsmlib/services/syspurpose.py
- src/subscription_manager/cache.py
- test/rhsmlib_test/test_register.py
- test/test_cache.py
* Card ID: ENT-4410
* When consumer does not include information about
content access mode, then another REST API call is made
and this information is added to the dictionary
containing information about current consumer
* The cache was quite useless, because it did not read cached
information from file, but cached data were read only from
in-memory cache
* Added refresh() method to entitlement service 
* When Register() method is called with enable_content
option and this option is equal True, then auto-attach
is called in non-SCA mode and refresh in SCA mode
* When D-Bus method Register() was called, then
rhsm_service called almost 30 REST API calles
due to i-notify. It was reduced to 4 calls
* Added support of enable_content to cockpit plugin.
* When D-Bus method …
> Improvement of D-Bus Register() method

- cockpit/src/subscriptions-client.js
- cockpit/src/subscriptions-view.jsx
- integration-tests/check-subscriptions
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1999048
* Card ID: ENT-4288
* D-Bus method works as expected, but cockpit plugin just
ignored some information provided by this method
* Cockpit card with "Installed products" displays information
about partially subscribed products correctly with orange
text
* Information about status details is also not lost and all
reasons for partially or not subscribed products are
displayed in cockpit plugin too
> 1999048: Fixed partially subscribed product in Cockpit plugin

- src/rhsm/utils.py
- src/rhsmlib/facts/kpatch.py
- test/rhsm/unit/test_util.py
- test/rhsmlib_test/test_kpatch.py
Python 3.3 provides `shutil.which()`; since our required Python version is 3.6, then:
- switch all the usages of our custom `which()` to `shutil.which()`
- drop the custom `which()` and the tests for it
There should be no behaviour change, as `shutil.which()` does the right thing.
> Switch to shutil.which() & drop custom implementation

- test/modelhelpers.py
It is available since Python 2.5, and Python 3.6 is the current
requirement. Hence, use it unconditionally, dropping the old md5 bits.
> test: unconditionally use hashlib

- jenkins/python3-stylish-tests.sh
- jenkins/python3-tests.sh
- jenkins/stylish-tests.sh
- src/rhsm/connection.py
- src/subscription_manager/isodate.py
- test/rhsm/unit/test_connection.py
- test/test_isodate.py
The current way of formatting the datetime for the `If-Modified-Since` header does a couple of roundtrips that discard information on timezone, leading to convering an UTC timestamp back to the local time.
As a way to fix this:
- fix the `datetime.datetime` objects returned by `dateutil.parser.parse()`: they have dateutil timezone objects, which are not properly recognized by the Python standard library; hence, switch UTC timezone objects with standard `datetime.timezone.utc`
- use `email.utils.format_datetime()`, available since Python 3.3, that does the right thing with `datetime.datetime` objects
Also, since they got in my way when debugging and digging into the history, drop the useless leftovers of PyXML, which was dropped more than 7 years ago. Hopefully there should be less …
> 2026320: fix format of 'If-Modified-Since' header

- cockpit/src/subscriptions-view.jsx
- integration-tests/check-subscriptions
* Backport of #2794
* Commit: e39dfaae856ec9fd5610900d05a5ccb9a00d9961
* When no system purpose attributes are set, then it is
still usefull to display system purpose card, because
we still want to display system purpose status
* When no system purpose attributes are set, then simple
<EmptyState /> with following text is displayed
"No system purpose attributes set".
Note: The card with installed products has same behavior.
When there is not any installed products, then empty
state is also displayed and the card with installed
products does not disappear.
* Fixed integration test of cockpit plugin
> [1.28] Cockpit plugin: display syspurpose card without attributes

- cockpit/src/subscriptions-client.js
- cockpit/src/subscriptions-view.jsx
- integration-tests/check-subscriptions
* Backport of PR: #2893
* Original commit: e1ffd3f6f5327861783eba74f91ebba8acb9ac50
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2000326
* Card ID: ENT-4288
* D-Bus method works as expected, but cockpit plugin just
ignored some information provided by this method
* Cockpit card with "Installed products" displays information
about partially subscribed products correctly with orange
text
* Information about status details is also not lost and all
reasons for partially or not subscribed products are
displayed in cockpit plugin too
* Fixed cockpit integration tests
> 2000326: [1.28] Fixed partially subscribed product in Cockpit plugin

- src/subscription_manager/utils.py
Make use of `shutil.get_terminal_size()`, available since Python 3.3, to
replace the custom implementation to query the size of the current
terminal.
> utils: use `shutil.get_terminal_size()`

- etc-conf/subscription-manager.completion.sh
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2029927
* Card ID: ENT-4568
Previous loop was searching for words from the end. Because some
arguments (--user) take a value, this would break.
Now, the words are searched from the beginning and the loop stops when
it encounters the first optional argument (starting with a dash).
> 2029927: Fix bash autocompletion

- etc-conf/subscription-manager.completion.sh
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2029384
* Card ID: ENT-4568
Previous loop was searching for words from the end. Because some
arguments (--user) take a value, this would break.
Now, the words are searched from the beginning and the loop stops when
it encounters the first optional argument (starting with a dash).
This is a cherry-pick of 9cc980f.
> [1.28] 2029384: Fix bash autocompletion

- src/subscription_manager/repofile.py
- test/test_repolib.py
* Switch comma-separated join to space-separated join
* Implement Deb822 format correctly (refer to [manpages](https://manpages.debian.org/stretch/apt/sources.list.5.en.html))
> Fix Deb822 format implementation for Architectures field

- src/rhsmlib/dbus/objects/syspurpose.py
- src/rhsmlib/services/syspurpose.py
- src/subscription_manager/syspurposelib.py
- syspurpose/src/syspurpose/files.py
- syspurpose/test/syspurpose/test_syspurposefiles.py
- syspurpose/test/syspurpose/test_utils.py
* Origin PR: #2354
* One commit: 412d246b668bae3db0d89ea4983b8e4cf17432ba
* Card ID: ENT-4569
* Fixing following BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2028565
* Added D-Bus method GetValidFields(). Thus it is
possible to get dictionary of valid attributes
and values in client applications using
D-Bus API.
* Added D-Bus method SetSyspurpose(). It is possible
to set syspurpose value without need of calling
syspurpose CLI tool
* Added one missing argument to GetSyspurposeStatus
* Fixed method get_owner_syspurpose_valid_fields in
service.sypurpose module
* Disabled in-memory caching in SyncedStore, because there were
only troubles with this in rhsm.service, because it runs
for very long time.
* Removed report attribute from SyncedStore
* Added exception for three-way merge conflict …
> [1.28] Extended D-Bus API - syspurpose methods; ENT-2373

- src/rhsmlib/file_monitor.py
Thread has been providing a `name` property since at least Python 3.1;
considering that:
- subscription-manager requires Python 3.6
- `Thread.getName()` issues a `DeprecationWarning` since Python 3.10
then directly switch to the `name` property, which works the same.
> Switch away from `Thread.getName()`

- src/subscription_manager/cache.py
Remove an extra 'not' in a debug message, so the sentence makes sense.
Reported by: Chris Snyder
> cache: fix typo in debug message

- man/subscription-manager.8
- src/rhsmlib/dbus/objects/attach.py
- src/subscription_manager/cache.py
- src/subscription_manager/managercli.py
- src/subscription_manager/utils.py
- test/rhsmlib_test/test_attach.py
- test/test_managercli.py
* Card ID: ENT-4594
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2017795
* Manual attaching of pool using --pool CLI option is not
allowed now. When user tries to attach any pool in SCA
mode, then info message is printedn and subscription-manager
is terminated
* Added two unit tests for auto-attach ins SCA mode and
manual attach
* Added more debug prints for cache used by function
is_simple_content_access(), because I considered using
this method, when --help is used, but calling
subscription-manager attach --help would cause calling
one REST API endpoint
* Updated manual page about subscription-manager
Backport of PR #2890 to 1.28.
> [1.28] 2017795: Disallowed attaching pool in SCA mode:

- src/subscription_manager/cli_command/org.py
- src/subscription_manager/cli_command/service_level.py
- test/cli_command_test/test_role.py
Right now, commands that can take `--org` ignore its value in case the
user belongs to only a single organization; this means that wrong values
passed by the user are ignored in that case, unlike what happens in case
the user belongs to more than one organization.
As a way to unify the behaviour in all the cases, always accept the
`--org` specified by the user, trying the automatic setting or the user
query otherwise.
This also saves one call to the server in case `--org` is specified.
Remove also an useless check in the service-level implementation.
Card ID: ENT-4560
> 2026286: consider user-specified --org in any case

- src/subscription_manager/managercli.py
- test/test_managercli.py
Right now, commands that can take `--org` ignore its value in case the
user belongs to only a single organization; this means that wrong values
passed by the user are ignored in that case, unlike what happens in case
the user belongs to more than one organization.
As a way to unify the behaviour in all the cases, always accept the
`--org` specified by the user, trying the automatic setting or the user
query otherwise.
This also saves one call to the server in case `--org` is specified.
Remove also an useless check in the service-level implementation.
Card ID: ENT-4560
Backport of PR #2905 to 1.28.
> [1.28] 2026013: consider user-specified --org in any case

- src/rhsmlib/services/syspurpose.py
- src/subscription_manager/cli_command/abstract_syspurpose.py
- test/cli_command_test/test_role.py
* When subscription-manager detects conflict during three-way
merge, then advice how to resurect from the conflict
contain recommended command. This command did not mention
syspurpose sub-command (e.g. "subscription-manager role --set foo").
The advice was changed to: "subscription-manager syspurpose role ..."
* Added more debug log prints to be consistenst with other
syspurpose attributes
* Fixed one unit test
* Fixed type in one doc string
> Fix some minor issues related to syspurpose

- src/subscription_manager/injection.py
- src/subscription_manager/plugins.py
- test/stubs.py
* Card ID: ENT-4590
callable() is a built-in function that was not available in Python 3.0
and 3.1. We are not supporting these old versions, so we can use the
function directly.
> ENT-4590: Switch away from six.callable

- src/rhsm/bitstream.py
- src/rhsm/pathtree.py
- src/rhsmlib/dbus/base_object.py
- src/rhsmlib/dbus/dbus_utils.py
- src/rhsmlib/dbus/objects/config.py
- src/rhsmlib/services/config.py
- test/modelhelpers.py
* Card ID: ENT-4588
six.iteritems(), six.iterkeys() are no longer needed for Python 3 only
code.
six.Iterator is aliased to object in Python 3 and is no longer
necessary, too.
> ENT-4588: Switch away from six iterators

- src/subscription_manager/cli_command/refresh.py
- test/cli_command_test/test_refresh.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2026316
* Card ID: ENT-4537
* It is safe to not delete this cache file, when If-Modified-Since
HTTP header is used
* It wasn't necessary to modify repos command
* Modified one unit test to cover this case
> 2026316: Do not delete cache of content_access during refresh

- src/subscription_manager/repolib.py
It is a no-op in Python 3, which is required already.
> Drop usage of `six.python_2_unicode_compatible`

- src/rhsmlib/facts/dmiinfo.py
Make sure to encode bytes as unicode strings, so they get represented as
strings and not as bytes.
Fixes commit 95058ae7e2eaf8e98aa2f7e3b6ed32f6e1c0e5dc
> 2039322: fix string representation of DMI facts

- man/subscription-manager.8
- src/subscription_manager/cli_command/service_level.py
- test/cli_command_test/test_service_level.py
* Card ID: ENT-4567
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2028894
Setting server URL on registered systems results in 401: Unauthorized
answer. This commits adds an early prevention.
Users still has to unregister their machine first before querying other
servers. This commit only makes the subscription-manager return more
friendly output.
> 2028894: Don't allow service-level --serverurl on registered system

- Jenkinsfile
Backport of PR #2922 to the 1.28 branch, to fix the Jenkins/junit issue in that branch too.
> [1.28] Try to not use junit('coverage.xml')

- src/subscription_manager/managercli.py
- test/test_managercli.py
* https://bugzilla.redhat.com/show_bug.cgi?id=2024573
* Backport of PR: #2921. It was necessary to do manual backporting,  because cherry-picking was not possible
* Card ID: ENT-4537
* It is safe to not delete this cache file, when If-Modified-Since
HTTP header is used
* It wasn't necessary to modify repos command
* Modified one unit test to cover this case
> 2024573: [1.28] Do not delete cache of content_access during refresh

- cockpit/src/index.js
- cockpit/src/subscriptions-register.jsx
- integration-tests/check-subscriptions
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2037771
* Card ID: ENT-4617
* Enable by default checkbox "Connect this system to Red Hat Insights"
* It was little bit more tricky than expected. Why? When insights-client
is not installed, then auto-attach (enable_content) has to be
enabled to be able to install insights-client first. Thus when
auto-attach is not enabled, then it is not possible to connect
system to Red Hat Insights.
> 2037771: Cockpit registration dialog: enable insights by default

- src/subscription_manager/cache.py
- src/subscription_manager/entcertlib.py
In SCA enabled mode, Subscription manager and Yum are sending
redundant API calls (/accessible_content) to fetch the SCA
certificate from Candlepin and refresh the redhat.repo file
everytime unnecessarily which is also causing redundant
API calls (/content_overrides and /release) to the Candlepin.
Servers such as Satellite may encounter unnecessarily high
traffic loads when a lot of hosts are registering or patching
concurrently. This patch fixed the issue.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2044349
(cherry picked from commit 4096f5a4ccb251f79d91f4c455a48a3ec1d22513)
Backport of PR #2856 to 1.28.21.
> [1.28.21] Fix redundant API calls to Candlepin

- src/subscription_manager/cli_command/plugins.py
- src/subscription_manager/plugins.py
* Card ID: ENT-4618
As subscription-manager is Python 3 only we can use built-in functions.
> ENT-4618: Switch away from six.get_method_*

- Pipfile
- requirements.txt
- setup.py
- subscription-manager.spec
* Card ID: ENT-4650
python3-six is a package used as Python 2 - Python 3 compatibility
wrapper. It has been removed from the codebase step by step, and now it
is not required at all, and can be removed from dev and build systems.
> ENT-4650: Remove python-six from build system

- integration-tests/vm.install
It seems that newer versions of Python or setuptools create a different
layout in the Python site-package depending whether the installation is
direct to the specified prefix, or there is temporary location (a local
destdir). Because of this, force "--root /" when installing directly to
/usr for testing: this seems to use the same layout of the system
installation (via distribution packages), and thus the existing files
will be properly overwritten.
Another change is the location of the "subscription-manager" executable:
setuptools installs it in $prefix/bin, while our Makefile moves it to
$prefix/sbin; hence, move it to the desired place, so it properly
overwrites the package version.
(cherry picked from commit c7d74b75bdbd55cd1d1f760a894f154fbf293c1c)
Backport of one commit from PR …
> [1.28] cockpit: fix system installation of subscription-manager

- src/rhsm/connection.py
- Show proxy information if SUBMAN_DEBUG_PRINT_REQUEST is set.
- Save optional tracebacks to /tmp/rhsm/, not /tmp/sub-man/
(this makes our directory names more predictable).
- Only create /tmp/rhsm/ directory if we want to save some files
there (e.g. don't create it only because we enabled debug prints).
- Use pathlib.Path to write the output, instead of tempfile.
Another PR will go into 1.28 when this is accepted.
> Improve debug logging to stdout

- src/rhsmlib/facts/dmiinfo.py
Tweak the logging of the warnings in the dmidecode facts collector:
- switch all the `log.warn()` usages to `log.warning()`; followup of commit 32beefe1e5b2e520d7091819ccab72ab33391724
- do not translate the log messages, as they are untranslated everywhere else (and translated messages in the log file make it harder to read it)
- use f-strings to ease log printing
- do not print the exception information when printing the dmidecode warnings, as there is no exception at that point
- tweak the message used to print the dmidecode warnings, as they are not errors; also print them directly on own lines, so it's nicer to read
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2035662
Card ID: ENT-4637
> dmidecode facts: tweak logging of warnings

- src/rhsmlib/file_monitor.py
`pyinotify` uses `asyncore`, which was deprecated in Python 3.6. Since `pyinotify` has been (at the time of this writing) not active for 6 years and more, we will probably not get a newer version switching away from `asyncore` soon.
Hence, apply a localized hammer: temporarily disable the `DeprecationWarning` warnings when importing `pyinotify`.
> Squelch `DeprecationWarning`'s when importing `pyinotify`

- etc-conf/rhsm.conf
- man/subscription-manager.8
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2046302
* Card ID: ENT-4680
This is a partial backport of ENT-3764 (5b6db92), as it only changes the
words that are visible to the users: config files and man pages.
For maintenance and testing reasons no other changes have been made:
variable names and comments were not updated and have been kept the
same.
> [1.28] 2046302: Apply Conscious language initiative changes

- cockpit/src/subscriptions-view.jsx
The logic used to determine what to show as curtain view (i.e. before
all the subscription data & status were loaded) was partially flawed:
if a valid subscription status was determined not as very last data
at the very end of the loading phase, then the curtain view briefly
showed the "Unable to connect" error message, just to be quickly
replaced by the actual subscription view. This happended because the
logic used in `SubscriptionsView.renderCurtains()` did not know the valid
subscription statuses.
Shuffle the logic a bit to more to avoid such mistakes:
- move the check for the "Updating" view as first, using it when either
it is loaded w/o a valid state, or w/ a valid state and not fully
loaded; both situation are correct, as they represent that only some
data was fetched (and the …
> 2023430: cockpit: improve handling of main curtain view

- src/rhsm/connection.py
- src/subscription_manager/certdirectory.py
- src/subscription_manager/release.py
- test/fixture.py
- test/stubs.py
- test/test_release.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2044629
* Card ID: ENT-4699
* When there was SCA certificate, then this cert was ignored
* Revert one change introduced during implementation of --token
- We try to use only entitlement cert for accessing CDN
that is related to installed product (not all entitlement
certs). It reduce failed connection attempts for long list
of installed entitlement certs.
* Added one unit test and fixed one existing unit test
(cherry picked from commit 27399d4edcc6049c4bb6206babfd1cb3fe482cbe)
Backport of PR #2458 to subscription-manager-1.24.13 (for RHEL 7.7.z).
> 2044629: Fix getting releases, when SCA is used

- src/rhsmlib/dbus/objects/attach.py
- test/rhsmlib_test/test_attach.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2049139
* Card ID: ENT-4718
* Reverting of following commit:
29d800091867405446e2e4039a92791d1e34c870
* We were too aggressive, when we decided to disable this
auto-attaching and attaching of pool for D-Bus API, when SCA mode
is used.
* This reverting should give enough time for solving following BZs:
https://bugzilla.redhat.com/show_bug.cgi?id=2049101 (Anaconda)
https://bugzilla.redhat.com/show_bug.cgi?id=2049620 (Gnome)
> Reverting disabling AutoAttach() and PoolAttach() in SCA mode

- src/subscription_manager/cli_command/environments.py
In case an account registers to an organization without environments on
a Candlepin with "environments" capability, the list of environments for
it is null. Hence, fall back to an empty string, so that
`environments --list` properly reports the "no environments to report"
message rather erroring out because "NoneType has no len()".
> environments: fix list for account in env-less org

- cockpit/src/subscriptions-view.jsx
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2023430
* Card ID: ENT-2290
* When the decision is made using properties, then these
properties could be changed asynchronously during calling
function renderCurtains(). When you check these properties
again in the function renderCurtains(), then it can end up
to the state that is not defined. Example: the property
subscriptionsClient.config.loaded is false before calling
renderCurtains(), but this can become true in the
renderCurtains() and wrong state ("Unable to connect")
is rendered for a while.
> 2023430: Cockpit: another improvement of curtain view

- src/rhsmlib/dbus/objects/attach.py
- test/rhsmlib_test/test_attach.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2049101
* Card ID: ENT-4718
* Backport of original PR https://github.com/candlepin/subscription-manager/pull/2961 to 1.28.
* Reverting of following commit:
https://github.com/candlepin/subscription-manager/commit/a0b5d65e9afd89a609123919443dc2100c304f25
* We were too aggressive, when we decided to disable this
auto-attaching and attaching of pool for D-Bus API, when SCA mode
is used.
* This reverting should also give enough time for solving other BZs:
https://bugzilla.redhat.com/show_bug.cgi?id=2049101 (Anaconda)
https://bugzilla.redhat.com/show_bug.cgi?id=2049620 (Gnome)
> [1.28] Reverting disabling AutoAttach() and PoolAttach() in SCA mode

- cockpit/src/index.js
- cockpit/src/subscriptions-register.jsx
- integration-tests/check-subscriptions
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2049441
* Card ID: ENT-4723
* Original PR: #2929
* Cherry-picked commit: 35da66abf302509b696da52e9e543b0052f43f1e
* Enable by default checkbox "Connect this system to Red Hat Insights"
* It was little bit more tricky than expected. Why? When insights-client
is not installed, then auto-attach (enable_content) has to be
enabled to be able to install insights-client first. Thus when
auto-attach is not enabled, then it is not possible to connect
system to Red Hat Insights.
* Fixed cockpit integration tests
> 2049441: [1.28] Cockpit registration dialog: enable insights by default

- src/dnf-plugins/subscription-manager.py
- src/plugins/subscription-manager.py
- src/subscription_manager/utils.py
Commit 944756e8a4daf27f7339a1c6e8d182b6112c08a3 checked for SCA in the yum plugin, however the early return breaks the flow in case of entitlement mode.
To fix this, align the implementation in the 1.24.13 branches with the 1.24 branch:
- copy the helper `get_content_access_mode()` function directly from the 1.24 branch
- add an helper `is_simple_content_access()` using `get_content_access_mode()` rather than newer caches that are not available in this branch
- fix the yum and dnf plugins to use the new helpers
> [1.24.13] Fix the checking for SCA in yum/dnf plugins 

- test-requirements.txt
It seems like pytest 7 breaks pytest-forked somehow, as also reported in
https://github.com/pytest-dev/pytest/issues/9621
Hence, for now pin it to any version lower than 7 to keep the unit tests
working.
> build: pin pytest to < 7

- src/subscription_manager/cli_command/register.py
- test/test_registration.py
In case an activation key is used to register to a Candlepin with 'environments' resources, do not try to check/query for environments: the activation key carries the information on environments already.
To do the case easily, refactor a bit `RegisterCommand._process_environments()`:
- drop the `options` parameter, as it is the same as the `options` class variable that is already used inside `_process_environments()`
- factorize the behaviour for the "not supports_environments" case:
- still exit with an error if --environments was specified
- explicitly return early from the function with `None` otherwise, instead of doing it implicitly because of the lack of return in the "if supports_environments" that used to follow
- remove the "if supports_environments" check, as it is no more …
> Various fixes/improvements related to registration & environments

- src/subscription_manager/managercli.py
Fixes 4b2c3334eb44a0dc28b9859d53ddc72c60092d76 due to the different way
of using subscription_manager.injection in current main vs 1.28.
Card ID: ENT-4751
> [1.28] environments: fix usage of injection

- src/cloud_what/providers/azure.py
- test/cloud_what/test_cloud_what.py
The "is likely running on azure is error prone":
The issue is mainly because of this two checks:
```
if 'virt.host_type' in self.hw_info:
if 'hyperv' in self.hw_info['virt.host_type']:
probability += 0.3
```
```
if found_microsoft is True:
probability += 0.3
```
**With python3-dmidecode**:
Azure: 0.9 (virt.host_type 0.3, chassis 0.3, found_microsoft 0.3)
HyperV: 0.6 (virt.host_type 0.3 and found_microsoft 0.3) => Issue false positive 0.6 => threshold 0.5 => is cloud/azure host would be true
This needs to be prevented.
**Without python3-dmidecode**:
Azure: 0.3 (virt.host_type 0.3) => issue. No azure detection.
HyperV: 0.3 (virt.host_type 0.3)
This PR changes both probability calculation values from 0.3 to 0.2 (host_type) and 0.1 (microsoft). 
Additionally, it checks for waagent.log. The …
> Improve azure determination method

- src/cloud_what/_base_provider.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2056896
* When it is not possible to get data from server, then
do not print traceback, but print debug message
> 2056896: Handle all exceptions of gathering data properly

- etc-conf/rhsm.conf
> 2059631: rhsm.conf: fix typo in comment

- integration-tests/vm.install
Due to a recent change in Fedora 36 [1], the installation prefix is
mangled in certain scenarios [2].
Hence, set a `$RPM_BUILD_ROOT` environment variable when invoking
`setup.py install`, so it works again as it used in older versions of
Fedora. This script is used only for the cockpit CI testing, so there
is no change for usual builds.
[1] https://src.fedoraproject.org/rpms/python3.10/pull-request/63
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2026979
> cockpit: set `RPM_BUILD_ROOT` w/ installing

- integration-tests/check-subscriptions
- test/files/mock-insights
Running "insights-client --check-results" explicitly is no longer
necessary, it happens as part of the registration now.
The insights-client started to output harmless messages like
Error importing insights.client for pre_update as
/var/lib/insights/newest.egg: No module named 'insights'
These can avoided by not setting "gpg=False". See
https://bugzilla.redhat.com/show_bug.cgi?id=2022655
Setting "auto_updates=False" allows the mock-insights server to not
implement egg updates requests.  That has stopped working anyway with
the current insights-client version.
> integration-test: Updates for newer insights-client

- cockpit/src/subscriptions-register.jsx
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2018221
* Card ID: ENT-4359
* Display "Organization ID" in the label of cockpit UI and
do not display only "Organization", because it could
imply that user should type organization name.
> 2018221: Cockpit: use "Organization ID" in label

- src/cloud_what/provider.py
- src/rhsmlib/facts/cloud_facts.py
- test/cloud_what/test_cloud_what.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2057053
* When subscription-manager tries to collect information about
public clouds, then it tried to detect public cloud using
strong signs and when no public cloud was detected, then
subscription-manager tried to detect public cloud provider
using heuristics. It could cause false positive detection
and subscription-manager tried to get metadata from
IMDS servers. Using heuristics is not necessary, when we
try to collect system facts.
* Methods for detection has new parameter 'methods'. It has
default value ('strong', 'heuristics').
* When facts about public cloud is collected, then only
this argument is changed to ('strong').
* Added one unit test for new parameter.
> 2057053: Facts: do no use heuristics detection of cloud

- rel-eng/bugzilla-str.sh
- rel-eng/packages/python-rhsm
- rel-eng/packages/subscription-manager
- rel-eng/releasers.conf
- rel-eng/tito.props
tito 0.6.0 (released in June 2015) supports `.tito` as default & primary
location for its configuration; hence, the `rel-eng` directory (the old
location) is effectively unused, and can be safely removed. It only
contains symlinks to files in `.tito`, so there is nothing lost.
> Drop the `rel-eng` directory for old tito versions

- integration-tests/check-subscriptions
- test/files/mock-insights
This makes it work again on rhel-9-0.
There is a bug in sscg on rhel-9-0 that causes Cockpit to create its
certificates with openssl.  However, those don't work for
mock-insights, so let's just make a custom set just for it.
> integration-test: Use custom TLS certs for mock-insights

- cockpit/src/subscriptions-view.jsx
The logic used to determine what to show as curtain view (i.e. before
all the subscription data & status were loaded) was partially flawed:
if a valid subscription status was determined not as very last data
at the very end of the loading phase, then the curtain view briefly
showed the "Unable to connect" error message, just to be quickly
replaced by the actual subscription view. This happended because the
logic used in `SubscriptionsView.renderCurtains()` did not know the valid
subscription statuses.
Shuffle the logic a bit to more to avoid such mistakes:
- move the check for the "Updating" view as first, using it when either
it is loaded w/o a valid state, or w/ a valid state and not fully
loaded; both situation are correct, as they represent that only some
data was fetched (and the …
> [1.28] 1822242: cockpit: improve handling of main curtain view

- .gitignore
- Containerfile
- Jenkinsfile
- README.containers.md
- jenkins/run.sh
- jenkins/stylish.sh
- jenkins/tito.sh
- jenkins/unit.sh
- scripts/build_and_push.sh
This adds fedora based toolbox containers and
updates the jenkinsfile of the project so that
tests can be run in a similar environment both
on jenkins nodes and locally.
This allows test failures to be reproduced more
easily. See the included readme updates for
details on the operation of the containers.
The containers can also be used for development
as well.
Allow toolbox create to pull images automatically
> Adding containers for development and test

- src/cloud_what/provider.py
- src/rhsmlib/facts/cloud_facts.py
- test/cloud_what/test_cloud_what.py
* Backport PR for 1.28
* Original PR: #2987
* Original commits: 673fe74c12c0dbd6f8c6b880ea871ee1e6a6b6f3 c846e1e2854a54f12872049e412ff0e8ffd66669
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2057053
* When subscription-manager tries to collect information about
public clouds, then it tried to detect public cloud using
strong signs and when no public cloud was detected, then
subscription-manager tried to detect public cloud provider
using heuristics. It could cause false positive detection
and subscription-manager tried to get metadata from
IMDS servers. Using heuristics is not necessary, when we
try to collect system facts.
* Methods for detection has new parameter 'methods'. It has
default value ('strong', 'heuristics').
* When facts about public cloud is collected, then only
this …
> 2057053: [1.28] Facts: do no use heuristics detection of cloud

- src/subscription_manager/gui/registergui.py
As result of commit 4b2c3334eb44a0dc28b9859d53ddc72c60092d76 (i.e. the
changes for multi-environments), the GUI code was not adapted to the
renamed named argument of `UEPConnection.registerConsumer()`.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2064002
Card ID: ENT-4813
> 2064002: fix named argument for `registerConsumer()`

- src/subscription_manager/gui/registergui.py
As result of commit 4b2c3334eb44a0dc28b9859d53ddc72c60092d76 (i.e. the
changes for multi-environments), the GUI code was not adapted to the
renamed named argument of `UEPConnection.registerConsumer()`.
(cherry picked from commit 8cb89f7bb2766c14515deb9aa586a2e0ceadbb03)
Backport of PR #3009 to 1.28.29.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2064002
Card ID: ENT-4813
> [1.28.29] 2064002: fix named argument for `registerConsumer()`

- src/rhsm/profile.py
- test/rhsm/unit/test_profile.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2058662
* Card ID: ENT-4778
* When modulemd is not in enabled or disabled, then the default
status should be "default" not "unknown"
* Added file for unit tests of rhsm.profile and added several
unit tests
> 2058662: Fix inaccurate module status in combined profile

- src/rhsm/profile.py
- test/rhsm/unit/test_profile.py
* Original PR #3012
* Original commit: 03e74d5e8623b4ff3d7a5e121b53380459dab778
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2057732
* Card ID: ENT-4778
* When modulemd is not in enabled or disabled, then the default
status should be "default" not "unknown"
* The module can be also active despite the module is only
in default mode.
* Added file for unit tests of rhsm.profile and added several
unit tests to this file
> 2057732: [1.28] Fix inaccurate module status in combined profile

- jenkins/stylish.sh
- src/rhsm/bitstream.py
- test-requirements.txt
- test/test_cache.py
* Card ID: ENT-4847
The version is pinned for consistency. If you have different version
than the Jenkins does (because one of the systems was not updated while
the other one was), the build will fail even though your local Black
claims everything is in order.
For that reason it would be the best to use the version from PyPI via
pip and not system package version from repository, which may be out of
sync.
If this situation does happen and Black in CI finds some issues, it will
show a diff for the changes, so it can be fixed even manually. But the
best-case scenario is seamless check with the versions synchronized.
The repository was previously reformatted with black==21.12b0. Version
22.1.0+ removes spaces around operators if both operands are simple, and
those two files are affected.
> Add Black to CI

- src/rhsmlib/facts/cloud_facts.py
* Card ID: ENT-4862
* When RHEL7 system runs on GCP public cloud, then no marketplace
ID was included in reported facts. This commit adds support
for GCP marketplace ID for RHEL7.
* System facts contains now new fact gcp_instance_id.
> [1.24] Backport support for GCP marketplace ID

- .git-blame-ignore-revs
* Card ID: ENT-4846
Two giant commits reformatted whole repository with `black`. Their
hashes are being added to .git-blame-ignore-revs file, which can be used
by git to ignore them in `git blame` command:
$ git config blame.ignoreRevsFile .git-blame-ignore-revs
> Ignore black commit hashes

- src/rhsmlib/facts/hwprobe.py
- src/subscription_manager/repolib.py
- test/rhsmlib_test/test_hwprobe.py
- test/test_repolib.py
The change removes a warning in rhsm.log
More information: https://community.theforeman.org/t/subscription-manager-for-debian-ubuntu-on-apt-atix-de/20667/67
> Add check for systems which using yum or dnf

- Makefile
- subscription-manager.spec
Using `INCLUDE_SYSPURPOSE` to disable the syspurpose tool has the effect
of also disabling the `syspurpose` Python module. Since the backports
from main in the latest months assumed an always-available `syspurpose`
module, then building without it results in a broken
subscription-manager. [1]
Hence, simply drop `INCLUDE_SYSPURPOSE` from the Makefile, unconditionally
installing the syspurpose tool & module. Also hardcode `SUBPACKAGES` to
syspurpose, and drop the possibility of overriding it in the spec file.
[1] https://github.com/candlepin/subscription-manager/pull/2906
> [1.28] build: always build & ship syspurpose bits

- Makefile
- contrib/debian/rules
- setup.py
- src/rct/version.py
- src/rhsm/connection.py
- src/subscription_manager/api/__init__.py
- src/subscription_manager/utils.py
- src/subscription_manager/version.py
- test/test_api.py
- test/test_utils.py
Currently the version of subscription-manager isn't set during the build of the deb package. As a result the subscription-manager version is empty when running `subscription-manager version` on deb based systems.
As a first step **rpm-version** is refactored to **pkg-version** as the set version relates to both rpm and deb packages.
Secondly the version is passed to **make** in _contrib/debian/rules_ using **pkg-info.mk**.
> Set version of deb packages during build

- src/cloud_what/providers/gcp.py
- src/rhsmlib/facts/cloud_facts.py
- test/cloud_what/test_cloud_what.py
- test/rhsmlib_test/test_cloud_facts.py
* Card ID: ENT-4825
* When system is running on Google Cloud Platform, then add
information about license codes to system facts
* List of codes (IDs) is separated by spaces
* The list is gathered from metadata, but it was necessary
to modify little bit URL (&licenses=TRUE at the end
of the URL template)
* Modified unit tests a little bit
> Add gcp_license_codes to system facts.

- src/subscription_manager/managercli.py
Commit dd6eba0b1d6722d06967e1a7e8e65ccb9ba00858 fixed the usage of the
status cache, making sure it is properly used in more cases. One side
effect it happened was that the release status cache was used as it was,
and since nothing invalidates it, any release change (done with
`release --set/--unset`) was never reflected.
Hence, whenever the release is successfully changed (via
updateConsumer()), delete the release status cache: the cache will be
refreshed whenever there is the need for it (e.g. when trying to expand
"$releasever" in repository URLs). Remove the cache before
RepoActionInvoker.update() is invoked, as it will update the
repositories, potentially asking for the release version to expand.
Remove also the release status cache on refresh, to make sure we fetch
it in case in the …
> [1.28] 2074111: clear the release cache on release change

- src/subscription_manager/cli_command/refresh.py
- src/subscription_manager/cli_command/release.py
Commit 7c764615e1c6208be6fd646c84edddd9ba75ee70 fixed the usage of the
status cache, making sure it is properly used in more cases. One side
effect it happened was that the release status cache was used as it was,
and since nothing invalidates it, any release change (done with
`release --set/--unset`) was never reflected.
Hence, whenever the release is successfully changed (via
updateConsumer()), delete the release status cache: the cache will be
refreshed whenever there is the need for it (e.g. when trying to expand
"$releasever" in repository URLs). Remove the cache before
RepoActionInvoker.update() is invoked, as it will update the
repositories, potentially asking for the release version to expand.
Remove also the release status cache on refresh, to make sure we fetch
it in case in the …
> [1.29.26] 2073551: clear the release cache on release change

- src/subscription_manager/managercli.py
Commit dd6eba0b1d6722d06967e1a7e8e65ccb9ba00858 fixed the usage of the
status cache, making sure it is properly used in more cases. One side
effect it happened was that the release status cache was used as it was,
and since nothing invalidates it, any release change (done with
`release --set/--unset`) was never reflected.
Hence, whenever the release is successfully changed (via
updateConsumer()), delete the release status cache: the cache will be
refreshed whenever there is the need for it (e.g. when trying to expand
"$releasever" in repository URLs). Remove the cache before
RepoActionInvoker.update() is invoked, as it will update the
repositories, potentially asking for the release version to expand.
Remove also the release status cache on refresh, to make sure we fetch
it in case in the …
> [1.28.29] 2073558: clear the release cache on release change

- src/cloud_what/providers/gcp.py
- src/rhsmlib/facts/cloud_facts.py
- test/cloud_what/test_cloud_what.py
- test/rhsmlib_test/test_cloud_facts.py
* Backport PR for 1.28 branch. Original PR: #3023
* Original commit: 33e50de1751bb527e0c9a438ac26ec86f4a1f63e
* Card ID: ENT-4825
* When system is running on Google Cloud Platform, then add
information about license codes to system facts
* List of codes (IDs) is separated by spaces
* The list is gathered from metadata, but it was necessary
to modify little bit URL (&licenses=TRUE at the end
of the URL template)
* Modified unit tests a little bit
> 1.28 Add gcp_license_codes to system facts.

- src/cloud_what/providers/gcp.py
- src/rhsmlib/facts/cloud_facts.py
- test/cloud_what/test_cloud_what.py
- test/rhsmlib_test/test_aws_instance.py
* Backport PR for 1.28 branch. Original PR: #3023
* Original commit: 33e50de1751bb527e0c9a438ac26ec86f4a1f63e
* Card ID: ENT-4825
* When system is running on Google Cloud Platform, then add
information about license codes to system facts
* List of codes (IDs) is separated by spaces
* The list is gathered from metadata, but it was necessary
to modify little bit URL (&licenses=TRUE at the end
of the URL template)
* Modified unit tests a little bit
> 1.24 Add gcp_license_codes to system facts.

- cockpit/src/insights.jsx
Permissions of that directory have recently been narrowed.  The page
needs to be reloaded when the superuser level changes, so this
component does not need to follow along dynamically.
> cockpit: Read files in /var/lib/insights as superuser

- test/syspurpose/test_syspurposefiles.py
- test/test_lock.py
- test/test_ostree_content_plugin.py
- test/test_repolib.py
- test/test_rhsm_debug_command.py
- test/test_utils.py
Unless I missed something, they were used for debugging and there is no
reason to keep them.
> Remove print statements from test suite

- jenkins/unit.sh
When tests produce some unexpected output ("write to closed file") or
print a traceback, it is difficult to pinpoint which of them is the
cause, because we're randomizing their order every time.
By using verbose mode, we'll see exactly which test is misbehaving and
we can skip the part where we have to go looking for it.
> Run CI's pytest with verbose flag

- .flake8
- build_ext/build_ext/lint.py
- setup.py
- test-requirements.txt
- include `debian-stuff/katello` among the files checked by default by flake8
- switch from `exclude` to `extend-exclude` to not override the default excludes
- exclude possible virtualenvs
- simply call `flake8` to check for flake8 issues, rather than using its API (we don't have plugins)
- no more need to pin "flake8" to versions older than 4, as we can simply use it without issues now
> Test-related flake8 changes

- .flake8
Make sure to not run flake8 on the Python sources in the build
directory, which is "build" by default.
Spotted while reviewing other PRs.
> flake8: ignore the build directory

- subscription-manager.spec
* Card ID: ENT-1590
* Group tag should not be part of .spec file. Almost all RPMs
do not have this tag on Fedora (99%). The most of RPMs (56%)
do not have it to on RHEL8 too.
* More details here:
https://fedoraproject.org/wiki/Changes/Remove_Group_Tag
* I left this tag for suse.
> Remove Group tag from .spec file for RHEL/Fedora

- src/rhsmlib/services/refresh.py
- src/subscription_manager/cli_command/refresh.py
- src/subscription_manager/cli_command/status.py
- test/cli_command/test_status.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2073354
* Card ID: ENT-4885
* When content access mode has changed from SCA mode to
entitlement mode, then sub-man should resurrect from this
situation gracefully, when status command is triggered
* Added new service refresh, because it is necessary to
refresh certificate not only from refresh command, but
status needs this functionality in edge cases too
* Refactored code of status command
* Fixed some unit tests
* Added unit tests for status command and for this case
> 2073354: Print correct status, when access mode has changed

- src/rhsmlib/services/refresh.py
- src/subscription_manager/managercli.py
- test/test_managercli.py
* Commit back-porting changes to 1.28 branch.
* Original PR: #3046
* Original commit: 78b720c5e2c409d6a8c2aa2f34dcb77b5f3ba225
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2073347
* Card ID: ENT-4885
* When content access mode has changed from SCA mode to
entitlement mode, then sub-man should resurrect from this
situation gracefully, when status command is triggered
* Added new service refresh, because it is necessary to
refresh certificate not only from refresh command, but
status needs this functionality in edge cases too
* Refactored code of status command
* Fixed some unit tests
* Added unit tests for status command and for this case
> 2073347: [1.28] Print correct status, when access mode has changed

- subscription-manager.spec
This directory now is owned by subscription-manager-rhsm-certificates.
This PR is opened based on a suggestion during the fedora review of the subscription-manager-rhsm-certificates package (see https://bugzilla.redhat.com/show_bug.cgi?id=2078592).
It likely shouldn't be merged until the subscription-manager-rhsm-certificates package is available in fedora.
> Remove ownership of /etc/rhsm

- src/subscription_manager/certdirectory.py
- src/subscription_manager/entcertlib.py
* Card ID: ENT-4726
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2043331
* This issue happens really rarely, but it can be pretty confusing.
When SCA entitlement has changed during registration, then it
could lead to deleting installed SCA certificate. Why?
The subscription-manager asks for the list of available SCA
certificate. Candlepin server responses with the list of
serial numbers. The subscription-manager ask for the
entitlement certificate(s) and candlepin returns certs. Problem
is that candlepin server returns SCA certificate despite
requested serial number does not exists, because the SCA
certificate has changed meanwhile. The subscription-manager
later compares serial number of returned certificate and
it deletes just installed SCA cert, because it is not in
the original …
> 2043331: Do not delete installed SCA cert during registration

- subscription-manager.spec
Soon subscription-manager-rhsm-certificates will be moved to an own
repository with a different versioning scheme, and thus the strict
versioning here will not work.
subscription-manager-rhsm-certificates contains only certificates for
the remote RHSM server, so there is no need to require a strict version
anyway.
(cherry picked from commit 4ca19853199f60c59e6a6f9fdadfa684a96335b5)
Backport to 1.28 of one commit from PR #3004 to ease future downstream work.
> [1.28] spec: relax subscription-manager-rhsm-certificates requires

- src/subscription_manager/repofile.py
- src/subscription_manager/repolib.py
- test/test_repolib.py
An upcoming change to Candlepin is the addition of a capability to 
advertize the possibility to perform OCSP checking when connecting to 
its repositories. If it is possible, set the "sslverifystatus" repo key
to "1", as dnf supports it already.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2075455
Card ID: ENT-4928
The corresponding implementation in Candlepin is done by:
- PR: https://github.com/candlepin/candlepin/pull/3332
> 2075455: enable sslverifystatus on repos if advertized by CP

- src/rhsm/profile.py
* Card ID: ENT-4700
'imp' module is deprecated since Python 3.4, and will be removed in near
future (it was initially scheduled to be removed in 3.8). Because we are
just testing if 'zypp_plugin' exists, we can use plain importlib call.
> ENT-4700: Switch away from 'imp'

- cockpit/src/insights.jsx
- cockpit/src/subscriptions-view.jsx
Recent versions of insights-client started to produce the errors messages on stdout rather than stderr, and thus nothing was shown anymore to the users on failures.
To fix this, massage a bit the code that handles the failures of `cockpit.spawn()`:
- merge stderr with stdout
- add (and use) an helper function to properly format an error string from the catch() handler of a `cockpit.spawn()` promise, properly using the process stdout/stderr
- fix the multiline display for errors in the floating `<Alert>`
- properly handle the error message from actions in the Insights dialog itself
Please refer to the single commits for longer explanations.
This is how the floating `<Alert>` appears:
This is how the Insights dialog appears:
The only problem is that, due to the current version of the …
> [1.28] cockpit: insights: fix displaying of `insights-client` errors/messages

- src/rhsm/utils.py
- test/fixture.py
- test/rhsm/unit/test_connection.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2092014
* Card ID: ENT-240
This is addition to the main PR #3003. subscription-manager may be not
available in some cases, rhsm can be used on its own. We need to take
into account these situations.
By having a fallback scenario we can ensure that this module will work
as intended.
> 2092014: Disable progress messages when sub-man RPM is not installed

- src/subscription_manager/repofile.py
- src/subscription_manager/repolib.py
- test/test_repolib.py
An upcoming change to Candlepin is the addition of a capability to 
advertize the possibility to perform OCSP checking when connecting to 
its repositories. If it is possible, set the "sslverifystatus" repo key
to "1", as dnf supports it already.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2076522
Card ID: ENT-4996
The corresponding implementation in Candlepin is done by:
- PR: https://github.com/candlepin/candlepin/pull/3332
Backport of PR #3050 to 1.28.
> [1.28] 2076522: enable sslverifystatus on repos if advertized by CP

- src/subscription_manager/repofile.py
- src/subscription_manager/repolib.py
- test/test_repolib.py
An upcoming change to Candlepin is the addition of a capability to 
advertize the possibility to perform OCSP checking when connecting to 
its repositories. If it is possible, set the "sslverifystatus" repo key
to "1", as dnf supports it already.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2095301
Card ID: ENT-4996
The corresponding implementation in Candlepin is done by:
- PR: https://github.com/candlepin/candlepin/pull/3332
Backport of PR #3050 to 1.29.26.
> [1.29.26] 2095301: enable sslverifystatus on repos if advertized by CP

- cockpit/src/subscriptions-view.jsx
Even after commit 30bf4e9f1bcc106c4658cb5a04a3827d7e93c6c9 and
commit 6b544fda121c7c4fe3fa6a617f4e5bf7f007d520, the situation of the
main curtain view still remained a bit flaky: in particular, if the
configuration was loaded before the subscription status, there would be
a (brief) flash of the view "couldn't get system subscription status".
There is a bit of duplicated logic for loaded & status in `render()` and
`renderCurtains()`, plus the logic did not even consider all the cases
correctly, so let's try to reorganize & simplify this a bit.
In particular:
- split the creation of a "loading view" and an "error view" in own
function: this will make it easier to call the right one when needed
- move all the checks for the status (excluding the ones needed for the
actual error to show in …
> [1.28] 1822242: cockpit: fix/simplify the loading/error view checks

- build_ext/build_ext/i18n.py
- cockpit/src/subscriptions-view.jsx
Fix i18n issues in the cockpit plugin, so it is possible to run a proper message extraction (and thus translate all the messages):
- backport one commit from subscription-manager-cockpit:
- https://github.com/candlepin/subscription-manager-cockpit/commit/acf48e9876416440563d100ab74504483a28a300
- switch to "C" as language for the JS sources, as "JavaScript" does not work properly with React
> [1.28] i18n fixes for cockpit

- src/subscription_manager/certdirectory.py
- src/subscription_manager/entcertlib.py
* Backport of #3039
* Original commit: f21da0a92d2a1702c77a6f33a804964bb5256978
* Card ID: ENT-4810
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2043331
* This issue happens really rarely, but it can be pretty confusing.
When SCA entitlement has changed during registration, then it
could lead to deleting installed SCA certificate. Why?
The subscription-manager asks for the list of available SCA
certificate. Candlepin server responses with the list of
serial numbers. The subscription-manager ask for the
entitlement certificate(s) and candlepin returns certs. Problem
is that candlepin server returns SCA certificate despite
requested serial number does not exists, because the SCA
certificate has changed meanwhile. The subscription-manager
later compares serial number of returned …
> 2043331: [1.28] Do not delete installed SCA cert during registration

- src/cloud_what/fact_collector.py
- src/cloud_what/setup.py
- src/plugins/zypper/services/rhsm
- src/rhsmlib/facts/dmidecodeparser.py
- src/rhsmlib/facts/dmiinfo.py
- src/rhsmlib/facts/firmware_info.py
- subscription-manager.spec
- test/rhsmlib/facts/dmidecodedata/aarch64-baremetal-1.txt
- test/rhsmlib/facts/dmidecodedata/aarch64-baremetal-2.txt
- test/rhsmlib/facts/dmidecodedata/aarch64-qemu-1.txt
- test/rhsmlib/facts/dmidecodedata/x86_64-aws-1.txt
- test/rhsmlib/facts/dmidecodedata/x86_64-baremetal-1.txt
- test/rhsmlib/facts/dmidecodedata/x86_64-esx6.7-1.txt
- test/rhsmlib/facts/dmidecodedata/x86_64-qemu-1.txt
- test/rhsmlib/facts/test_dmifacts.py
The python-dmidecode module has currently not received work upstream in the last 7 years, and it starts to fails in some situations (e.g. Kernel Lockdown, when /dev/mem cannot be read). Hence, we cannot keep using python-dmidecode anymore.
As way forward, create a parser to parse the output of `dmidecode(1)`, and a fact collector that uses this parser to provide `"dmi.*"` facts.
The parser and the facts collector are tested using collected outputs (and anonymized) of `dmidecode(1)`, so it is easy to check whether changes will break existing outputs.
Cloud-what has its own facts collector using python-dmidecode in case subscription-manager is not installed. In it, manually query `dmidecode(1)` for known DMI strings used by the cloud detection, so it should work in that case too.
Please …
> New dmidecode-based DMI facts collector

- test/test_cache.py
Previously, the tests could fail on injections because they are being
setup in SubManFixture's setUp().
> Make TestProfileManager subclass of SubManFixture

- src/subscription_manager/repolib.py
- test/test_repolib.py
* Card ID: ENT-5215
On invalid proxy configuration (e.g. bad port or credentials, ...) our
DNF plugin would silently fail. Every time DNF is run, sub-man checks
its configuration and updates 'redhat.repo' file if there are changes.
One of recent changes was support for 'ssl_verify_status' capability,
providing OCSP stapling. When sub-man cannot contact its server due to
being misconfigured, exception is raised. DNF suppresses all exceptions
raised by its plugins, so the user was not notified of the crash.
Because the crash happened, 'redhat.repo' file was not updated and was
kept in original state. This commit now catches these exceptions, logs
them and disables the SSL verification for this invocation.
> ENT-5215: Handle errors raised in DNF plugin

- src/subscription_manager/repolib.py
* Card ID: ENT-5215
Multiple exceptions can be raised by the network, and these exceptions
should not prevent the functions from using caches or updating repo
files.
> ENT-5215: Handle all exceptions caused by network problems

- src/rhsm/connection.py
Spellcheck run by QE flagged this as an issue. We should be using
American English for spelling.
> ENT-5271: Fix spelling of Candlepin API endpoint description

- cockpit/webpack.config.js
CentOS/RHEL 9 switched to OpenSSL 3, which does not support the `md4`
hash any more. webpack 5 hardcodes that in no less than 21 places, so
monkey-patch `crypto.createHash()` to substitute sha256 for md4.
Hack to work around https://github.com/webpack/webpack/issues/13572
Cherry-picked from subscription-manager-cockpit commit 8e480295a89
---
This branch currently [fails to build](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3640-20220725-045106-a60ac424-rhel-8-5-candlepin-subscription-manager-subscription-manager-1.28.21/log.html) on our infra, as the cockpit/tasks container moved to Fedora 36.
> [1.28.21] webpack: Avoid md4 hash for OpenSSL 3 compatibility

- etc-conf/zypper.conf
Increase the security mechanism for zypper repositories manged by subscription-manager.
gpgcheck should be done automatically, if the server is capable to do it. Setting gpgcheck to 0 does completely disable the gpgcheck.
According to https://github.com/openSUSE/libzypp/blob/master/zypp/media/MediaManager.h#L377 the gpg key validation 'host' check should work for private/public ssl certs. 
Additionally, the values need to be without the quotes - otherwise the download of the gpg key would fail.
> Increase security level for zypper repos managed by sub-man

- integration-tests/run
In particular this improves the run-tests scheduler to work better on
our current infrastructure:
https://github.com/cockpit-project/cockpit/commit/49a7122df2
Backported from https://github.com/candlepin/subscription-manager-cockpit/commit/0dd1b1f5a6f7a6
> [1.29.26] Bump cockpit test API to 273 + run-tests scheduler fix

- integration-tests/run
In particular this improves the run-tests scheduler to work better on
our current infrastructure:
https://github.com/cockpit-project/cockpit/commit/49a7122df2
Backported from https://github.com/candlepin/subscription-manager-cockpit/commit/0dd1b1f5a6f7a6
> [1.28.29] Bump cockpit test API to 273 + run-tests scheduler fix

- integration-tests/check-subscriptions
- integration-tests/run
In particular this improves the run-tests scheduler to work better on
our current infrastructure:
https://github.com/cockpit-project/cockpit/commit/49a7122df2
Backported from https://github.com/candlepin/subscription-manager-cockpit/commit/0dd1b1f5a6f7a6
> [1.28] Bump cockpit test API to 273 + run-tests scheduler fix

- src/cloud_what/_base_provider.py
- src/cloud_what/providers/aws.py
- src/rhsm/config.py
- src/rhsm/connection.py
- src/rhsm/logutil.py
- src/rhsm/utils.py
- src/subscription_manager/cache.py
* Card ID: ENT-5286
Make all environment variables false-y when they contain empty string.
This commit unifies the behavior, as SMDEV_CONTAINER_OFF already behaves
like this and is used by RHOSP as a workaround for Podman BZ 2097694.
> ENT-5286: Unify environment variable evaluation

- test/syspurpose/test_utils.py
- test/test_logutil.py
Several tests fail when 'pytest' is run under root, even if they work
correctly when run as non-root user. By adding the new pytest marker
we can ensure that these tests are skipped, instead of raising false
alarms.
---
The usecase of these changes is rather small, this PR can be closed
if deemed not necessary. But recently I needed to run tests on RHEL
VM to find a bug source, and they kept failing. I could have created
non-root account, but setting it up would take a time in which I could
have solved the issue.
> Ensure tests don't fail when run under root

- subscription-manager.spec
After the removal of the cockpit plugin (which is LGPL), all the
remaining bits are GPL-2, which is already specified for the source.
Hence, remove the License tag from python3-cloud-what, as it is exactly
as the License already specified.
> spec: remove redundant License from python3-cloud-what

- src/rhsm/connection.py
- src/rhsmlib/dbus/server.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2111035
* The rhsm.service usually opens new TCP connection for each
D-Bus method call, but when rhsm.service tries to do some
REST API call due to i-notify event, then multiple threads
can try to do two REST API calls on the same connection
in almost the same time. This caused raising
CannotSendRequest, because one thread sent HTTP request
and the second thread sent another HTTP request on the
same HTTP connection before first thread received response.
* Partially fixes another BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2101510
> 2111035: Do not allow reusing TCP connection for rhsm.service

- test/cli_command/test_attach.py
- test/cli_command/test_service_level.py
- test/rhsm/unit/test_connection.py
- test/rhsmlib/facts/test_kpatch.py
- test/stubs.py
- test/test_lock.py
- test/test_rct_manifest_command.py
- test/test_repolib.py
- test/test_utils.py
* Card ID: ENT-4664
By using high-level NamedTemporaryFile and TemporaryDirectory we can
prevent files from being left in /tmp, as they are deleted automatically
as soon as their objects are deleted.
> ENT-4664: Ensure tests clean up after themselves

- src/rhsm/connection.py
* Card ID: ENT-5311
* When connection is not shared between request, then do not
try to parse Keep-Alive HTTP header and do not try to save
parsed values to non-existing shared connection
> Fix issue, when connection is not shared

- INSTALL.md
- README.md
- TESTING.md
- INSTALL.md updates original text from [candlepinproject.org/pull/263 ](https://github.com/candlepin/candlepinproject.org/pull/263) and moves it here to be closer to the source code.
- README.md links to this file and removes some obviously deprecated notes; but there is a space to make more changes.
- TESTING.md now does not contain notes on removed Vagrant setup; we may want to link to README.containers.md or draft something new instead.
> Update repository documentation

- src/rhsmlib/dbus/objects/register.py
- test/rhsmlib/dbus/test_register.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2101510
* Card ID: ENT-5185
* When D-Bus method Register() was called with argument
enable_content == True and entitlement mode was used, then
entitlement certificates were not installed on the system
* The rhsm.service usually opens new TCP connection for each
D-Bus method call, but when rhsm.service tries to do some
REST API call due to i-notify event, then multiple threads
can try to do two REST API calls on the same connection
in almost the same time. This caused raising
CannotSendRequest, because one thread sent HTTP request
and the second thread sent another HTTP request on the
same HTTP connection before first thread received response.
> 2101510: Fix D-Bus Register() and update entitlement certs 

- build_ext/build_ext/lint.py
- rpmlint.config
* Backported two commits: 4af3f18f50c2e30090f7ae28df2e8e45c695348c and 1400a3e2ec537e76801027bc6c9b82573c82bfef
> [1.28] Fix rpmlint

- integration-tests/check-subscriptions
- test/files/mock-insights
With a recent rhel-8-7 refresh, the subscription-manager-1.28 branch seems to need some of the updates we did on main for newer versions of Insights.
rhel-8-7 update: https://github.com/cockpit-project/bots/pull/3818
> Test updates for the 1.28 branch

- src/subscription_manager/managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2097672
* Origin PR for main: #3116
* Not possible to do simple cherry-pick
* Card ID: ENT-5115
* Changed warning message according suggestion in BZ bug report.
* Refactored code a little (fixed typo in method name)
> 2097672: [RFE] [1.28] Improve the message, when SCA is enabled

- src/rhsmlib/dbus/objects/register.py
- test/rhsmlib_test/test_register.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2101510
* Backport of PR #3080
* It wasn't possible to do simple cherry-pick
* Card ID: ENT-5185
* When D-Bus method Register() was called with argument
enable_content == True and entitlement mode was used, then
entitlement certificates were not installed on the system
* Added several unit tests
> 2101510: [1.28] Fix D-Bus Register() and update entitlement certs

- integration-tests/run
By default, cockpit's run-tests tries to get the list of tests that
changed in the branch being tested; since we run the test suite of
subscription-manager-cockpit from the local clone of it, that repository
will definitely not contain subscription-manager branches.
As a possible solution, disable the reference branch for run-tests
(using an empty string): we are not changing sub-man-cockpit tests from
this repository, so there are definitely no changes in its tests.
> cockpit: disable the reference branch for sub-man-cockpit

- integration-tests/run
By default, cockpit's run-tests tries to get the list of tests that changed in the branch being tested; since we run the test suite of subscription-manager-cockpit from the local clone of it, that repository will definitely not contain subscription-manager branches.
As a possible solution, disable the reference branch for run-tests (using an empty string): we are not changing sub-man-cockpit tests from this repository, so there are definitely no changes in its tests.
(cherry picked from commit b672c31823e99ba9aac204ee4fb6697b659d94ad)
Backport of #3126 to 1.29.30.
> [1.29.30] cockpit: disable the reference branch for sub-man-cockpit

- src/rhsmlib/facts/dmidecodeparser.py
The function was not using the parameter it was being passed, but some other local variable at its scope. Changing the name to ensure the right string is compared.
Backport of #3128
> [1.29.30] Fix possible parsing issues of dmidecode output

- src/rhsmlib/facts/dmidecodeparser.py
The function was not using the parameter it was being passed, but some other local variable at its scope. Changing the name to ensure the right string is compared.
Backport of #3128
> [1.29.26] Fix possible parsing issues of dmidecode output

- src/rhsmlib/facts/dmidecodeparser.py
The function was not using the parameter it was being passed, but some other local variable at its scope. Changing the name to ensure the right string is compared.
> Fix possible parsing issues of dmidecode output

- src/subscription_manager/cli_command/attach.py
- Updated the expected message from a user's manual attach request (`--pool`) when SCA is enabled for the organization.
**Current error message:** 
`
Ignoring request to attach. It is disabled for org $ORGID because of the content access mode setting.
`
**Expected error message:**
`
Ignoring the request to attach. Attaching subscriptions is disabled for organization $ORGID because Simple Content Access (SCA) is enabled.
`
- Card ID: ENT-5443
- BZ 2094942: https://bugzilla.redhat.com/show_bug.cgi?id=2094942
> ENT-5443 [2094942]: Fixed expected message for manual attach case

- src/subscription_manager/managercli.py
- Updated the expected message from a user's manual attach request (--pool) when SCA is enabled for the organization.
- Manual backport of changes made in https://github.com/candlepin/subscription-manager/pull/3143
- Original commit: 4d89c1b1544b969941000d273dcc05ae23448d99
- Card ID: ENT-5443
- BZ 2097672: https://bugzilla.redhat.com/show_bug.cgi?id=2097672
> 2097672: [1.28] Fixed expected message for manual attach case

- src/plugins/dnf/subscription-manager.py
- Updated dnf plugin to no longer display registration warnings to non-root guest users.
**before fix dnf/yum usage as non-root user:**
```
$ yum install haproxy
Not root, Subscription Management repositories not updated
This system is not registered with an entitlement server. You can use subscription-manager to register.
Error: This command has to be run with superuser privileges (under the root user on most systems).
```
**after fix dnf/yum usage as root user:**
```
$ yum install haproxy
Not root, Subscription Management repositories not updated
Error: This command has to be run with superuser privileges (under the root user on most systems).
```
- Card ID: ENT-5412
- BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2125227
> 2125227: Fixed incorrect registration warning with yum/dnf

- src/dnf-plugins/subscription-manager.py
- Updated dnf plugin to no longer display registration warnings to non-root guest users.
- Backport of changes made in https://github.com/candlepin/subscription-manager/pull/3146
- Original commit: 71410e3f2616c45022666955a49cd22c9397a746
- Card ID: ENT-5412
- BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2134165
> 2134165: [1.28] Fixed incorrect registration warning with yum/dnf

- man/subscription-manager.8
- src/subscription_manager/cli_command/register.py
- src/subscription_manager/cli_command/user_pass.py
- src/subscription_manager/utils.py
- Resolved the script hanging issue caused by the script waiting on user inputs for information not specified through command line arguments by checking if the session is interactive and raising an error detailing the missing command line argument if not.
- Updated the man page "commands and options" section with a note to document this behavior.
- BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2097679
- Card ID: ENT-5117
> 2097679: Fixed script hang in non-interactive execution

- man/subscription-manager.8
- src/subscription_manager/managercli.py
- src/subscription_manager/utils.py
- Resolved the script hanging issue caused by the script waiting on user inputs for information not specified through command line arguments by checking if the session is interactive and raising an error detailing the missing command line argument if not.
- Updated the man page "commands and options" and "register" sections with a note to document this behavior.
- Manual backport of changes made in https://github.com/candlepin/subscription-manager/pull/3148
- Original commit: cedc35f890ff3938d3a9bb14c3c80de4d197113e
... and in https://github.com/candlepin/subscription-manager/pull/3153
- BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2096852
- Card ID: ENT-5117
> 2096852: [1.28] Fixed script hang in non-interactive execution

- etc-conf/rhsm.conf
- src/daemons/rhsmcertd.c
* When `default_log_level` was set to `DEBUG` or any other value, then it was just not read by `rhsmcertd`. Thus it was not possible to get debug messages to rhsm.log from `rhsmcertd`, when `rhsmcertd` was started using: `systemctl start rhsmcertd.service` without hacking `rhsmcertd.service` file
* The `rhsmcertd` is able to read `default_log_level` from `rhsm.conf` now. It supports following log levels: `ERROR`, `WARN`, `INFO` and `DEBUG`. Default value is `INFO`.
* When `rhsmcertd` is started from command line with `--debug` option, then it overrides `default_log_level` value from `rhsm.conf`
* Added few more usages of `debug ()` for testing purpose.
> rhsmcertd reads default_log_level from rhsm.conf

- src/rhsm/utils.py
* BZ: 2136694
* Card ID: ENT-5468
Multi-byte progress messages, such as Japanese, were not being cleared correctly. The number of characters was lower than the number of bytes written to the console, so we weren't clearing enough.
Escape code 0K should handle this properly, as it will delete all the content on current line.
> 2136694: Clear progress messages properly

- src/subscription_manager/cli.py
- src/subscription_manager/cli_command/abstract_syspurpose.py
- src/subscription_manager/cli_command/cli.py
- src/subscription_manager/cli_command/environments.py
- src/subscription_manager/cli_command/facts.py
- src/subscription_manager/cli_command/identity.py
- src/subscription_manager/cli_command/override.py
- src/subscription_manager/cli_command/owners.py
- src/subscription_manager/cli_command/refresh.py
- src/subscription_manager/cli_command/register.py
- src/subscription_manager/cli_command/remove.py
- src/subscription_manager/cli_command/service_level.py
- test/test_managercli.py
Card ID: ENT-4286
- Updated system_exit() function to directly accept an exception to
format the exception message using ExceptionMapper before printing it.
- Updated various exception handlers to directly pass exceptions
to system_exit() where ExceptionMapper was used to
format the message of that exception.
- Removed list of exceptions and messages support
and removed related test cases for system_exit() function.
- Added new unit tests for system_exit() function.
> ENT-4286: Simplify exception reporting with system_exit()

- src/certificate.c
- src/rhsm/certificate2.py
- src/rhsm/connection.py
- src/subscription_manager/cli_command/abstract_syspurpose.py
- src/subscription_manager/cli_command/cli.py
- src/subscription_manager/cli_command/service_level.py
- src/subscription_manager/exceptions.py
- src/subscription_manager/utils.py
- test/rhsm/unit/test_certificate2.py
- test/rhsm/unit/test_connection.py
- test/test_exceptions.py
- test/test_managercli.py
- test/test_repolib.py
- test/test_utils.py
Some of the messages that subscription-manager prints in certain error situations, mostly related to networking, are generic and unhelpful. This  means that the users have little idea of what went wrong, and in certain cases even looking at the log file (`rhsm.log`) does not provide more clues. Since subscription-manager actually has more details on the failures, let's make it print what it knows about a certain failure.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2126981
Card ID: ENT-5345
Some internal classes, mostly in `rhsm.connection`, were extended to carry more details/info. Those new bits are used later on to produce more detailed error messages.
There were changes in the C `_certificates` extension: in particular, a new exception, `CertificateLoadingError`, is added for …
> [2126981] ENT-5345: improve various error messages

- src/subscription_manager/cli_command/register.py
- Reverted the removal of a mapped message with ExceptionMapper in cli_command/register.py
- Resolves additional issue discovered in previously merged PR: https://github.com/candlepin/subscription-manager/pull/3152
- Card ID: ENT-4286
> ENT-4286: Additional fix for exception handling

- src/subscription_manager/identity.py
They are now raisen in case of loading failure of certificates.
This avoids tracebacks when trying to do operations that load the identity certificate, in case it is not valid:
- register a system
- corrupt `/etc/pki/consumer/cert.pem` in any way so it is no more valid
- run e.g. `subscription-manager clean`
Fixes commit 05f20b9713e4bb629243da947da9d53226ba9877.
> Catch also CertificateLoadingError for identity cert loading

- src/rhsmlib/dbus/objects/register.py
- test/rhsmlib/dbus/test_register.py
- Card ID: ENT-5350
- BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2121350
- Implemented missing behavior of the "force" option in Dbus API by unregistering the system if already registered and re-registering the system.
This implementation can be tested in either Python or CLI by sending a register command with the "force" option enabled to the rhsm dbus python binding as seen below:
**Testing with a shell script**
- Use this script: https://github.com/jirihnidek/rhsm-dbus-examples/blob/main/register-org-username-password-force.sh
**Testing with a python script** 
- Modified script from original BZ reproduction steps:
```python
import dbus
REGISTER_OPTS_DICT = dbus.Dictionary({"force": True}, signature="ss")
system_bus = dbus.SystemBus()
register_server = …
```
> 2121350: Implement "force" register option in rhsm dbus python binding

- src/rhsm/utils.py
* BZ: 2142611
* Card ID: ENT-5468
Multi-byte progress messages, such as Japanese, were not being cleared correctly. The number of characters was lower than the number of bytes written to the console, so we weren't clearing enough.
Escape code 0K should handle this properly, as it will delete all the content on current line.
Cherry picked from 62652ba.
> [1.29.30] 2142611: Clear progress messages properly

- src/rhsmlib/dbus/objects/register.py
- test/rhsmlib_test/test_register.py
- Card ID: ENT-5350
- BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2118486
- Manual backport of changes made in https://github.com/candlepin/subscription-manager/pull/3160
- Original commit: 60470ebfaa4e4f1c81305526b1a8a1c73e0ccd39
- Refer to the linked PR for testing instructions.
- Implemented missing behavior of the "force" option
in Dbus API by unregistering the system if already registered
and re-registering the system.
> 2118486: [1.28] Implement "force" register option in rhsm dbus python binding

- cockpit/src/subscriptions-client.js
- src/rhsm/connection.py
- test/rhsm/unit/test_connection.py
- Resolved issue where proxy settings set in rhsm.conf were still being used by cockpit when cockpit disabled using proxy settings for registration, resulting in registration errors.
- Manual backport of changes made by Jiri in https://github.com/candlepin/subscription-manager/pull/2580
- BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1956654
- Card ID: ENT-5510
> ENT-5510: [1.28] Fix issues with proxy and cockpit interaction

- src/rhsm/connection.py
- src/subscription_manager/cli_command/cli.py
- src/subscription_manager/exceptions.py
- src/subscription_manager/utils.py
- test/test_exceptions.py
In case `HTTPSConnection.connect()` fails for reasons different than syscall failures, the raisen `OSError` has the `errno` field set to `None`; this typically happens for proxy/tunnel connection failures.
Since we want to diagnose those cases accurately, then
- introduce a new exception, `ConnectionOSErrorException`, to represent this situation
- catch the specific situation we want from `HTTPSConnection.connect()`, passing through the other exceptions as done so far
- format `ConnectionOSErrorException` properly
This can be tested by e.g. trying to register by specifying a wrong `server.hostname` and connecting via proxy:
```bash
```
> Catch generic `OSError` during `HTTPSConnection.connect()`

- Containerfile
- jenkins/run.sh
- jenkins/unit.sh
- src/rhsmlib/dbus/server.py
- test/rhsmlib/base.py
- test/rhsmlib/dbus/test_register.py
Our test that checks if it is possible to connect to newly created socket started failing with 'Permission denied' when the code tried to use it. Pytest cannot write into '/run', moving it to '/tmp' solves the issue.
> Fix failures of D-Bus' Register tests

- src/rhsm/config.py
- test/rhsm/unit/test_config.py
Containers/pods running in OCP (OpenShift Container Platform) need to be
considered as standalone systems, that can either register by themselves
or can get credentials using a mounted secret object to access an
already subscribed content.
Hence, tweak the container detection a bit: in case we are detecting the
system runs in a container, checks for Kubernetes/OCP environment
variables as canary way to detect this situation, and switch back to
"not container".
The tests were extended for the untested cases, to be able to easily add a new test case for the changes.
The effect of this PR is that it is possible to run `subscription-manager` commands in a Red Hat based container (RHEL, CentOS, etc) that runs as pod in OpenShift Container Platform. Other container usages (e.g. running a RHEL …
> 2108549: do not detect containers in OCP as such

- src/cloud_what/_base_provider.py
* When it is not possible to write token to cache file, then cloud-what is able to resurrect gracefully.
* This change fixes few unit tests, when /var/cache/cloud-what/ exists and non-root user is not able to read/write to this directory.
Cherry-picked from 5989527fc027d031cd8332b9c265dc25df243a13
> [1.28] Cloud-what: Make saving token file more robust

- test/test_async_utils.py
They work when run separately, but they crash when they are both run. Since the sub-man GUI has to be tested manually, it is not worth the effort finding the source of the issue (as it is caused by changes of Python or GLib/GObject).
> [1.28] Skip AsyncPool tests

- src/daemons/rhsmcertd.c
- src/subscription_manager/cli_command/register.py
* Card ID: ENT-5532
* When configuration option report_package_config is set to 0, then package profile should not be usually reported. It only has to be reported during registration regardless the value of report_package_config option. For this reason the rhsm-package-profile-uploader is always spawned with --force-upload CLI option.
* Note: if you want to use this approach for other cases, then it is necessary to check if value of report_package_config is equal and then it is possible to send SIGUSR1 signal to rhsmcertd.
* Small changes:
- Removed unused definition in rhsmcertd.c
- Emphasize that update_check() is called with force=True
> ENT-5532: Call rhsm-package-profile-uploader with --force-upload

- test/rhsmlib/base.py
This small patch ensures all injections have been initialized before running the test suite. Without them, inheriting from SubManFixture would have no effect.
This is an addition to #3181, found during its #3176 backport to 1.28.
> Call parent methods in DBusServerStubProvider

- test/fixture.py
- test/test_cp_provider.py
When tests were run in container, without having sub-man packages installed, two things happened:
- Container detection kicked in and prevented CPProvider from being created. NOTE: rhsm/unit/test_config.py::InContainerTests do not inherit from fixture.py::SubManFixture and are not affected by this patch.
- TCP handshake was attempted by opening a connection. Because the connection requires RHSM certificates to be installed on the system, this step crashed, when subscription-manager-rhsm-certificates (e.g., /etc/rhsm/ca/ directory) was not present.
> Handle tests in containers better

- src/subscription_manager/repolib.py
- test/rhsmlib/test_file_monitor.py
* Card ID: ENT-5536
These tree commits address issues that were found when the test suite was run in a container.
UPDATE: The hwprobe commit was removed and will be opened individually, as it requires more testing.
> Fix further test issues when run in container

- .github/workflows/pytest.yml
- TESTING.md
- scripts/container-pre-test.sh
- test/rhsmlib/dbus/test_facts.py
> ENT-3759: Test on GitHub Actions

- .github/workflows/pytest.yml
- test-requirements.txt
* Card ID: ENT-5541
Publish coverage report as a comment under the PR.
- To send the comment only once, not for every matrix system, only
'Fedora latest' is used as a data source.
- Because of how GitHub permissions work, the comment is only sent if
the PR originates from a feature branch; nothing will be sent for a PR
originating from some fork. Full coverage is still displayed in CI
output, it is just not sent as a comment.
- Package 'pytest-cov' is used instead of 'coverage'. It is still using
coverage in a background, but it runs it as a pytest addon instead,
allowing us to pass its arguments into pytest, instead of wrapping
whole pytest call inside of a coverage invocation.
> ENT-5541: Publish PR coverage

- .github/workflows/pytest.yml
- test-requirements.txt
* Card ID: ENT-5541
Publish coverage report as a comment under the PR.
- To send the comment only once, not for every matrix system, only 'Fedora latest' is used as a data source.
- Because of how GitHub permissions work, the comment is only sent if the PR originates from a feature branch; nothing will be sent for a PR originating from some fork. Full coverage is still displayed in CI output, it is just not sent as a comment.
- Package 'pytest-cov' is used instead of 'coverage'. It is still using coverage in a background, but it runs it as a pytest addon instead, allowing us to pass its arguments into pytest, instead of wrapping whole pytest call inside of a coverage invocation.
(Cherry-picked from ea495a6)
> [1.28] ENT-5541: Publish PR coverage

- src/plugins/libdnf/product-id.c
- src/plugins/libdnf/product-id.h
- src/plugins/libdnf/test-product-id.c
`findProductId()` returns an int, either -1 or 1 depending on whether it was possible to find the product ID in the specified certificate. The problem with this kind of return value is that's very easy to mistake for a boolean, and indeed `installProductId()` has a boolean-like check that it is always true, no matter the return value of `findProductId()`.
As a fix, change the return type of `findProductId()` to gboolean, with true returned whether the search succeeded:
- reduce the scope of the `ret_val` variable, so there are less chances to use it wrongly
- make `ret_val` false by default, only changing it to true in the only place where it needs to be like that
- adapt the tests accordingly
Reported-by: Matyas Horky
> libdnf: fix return value of `findProductId()`

- .github/workflows/pytest.yml
- scripts/container-pre-test.sh
First commit addresses one test that was being skipped on Fedora images. By including dnf-plugins-core package there as well, we can run it.
Second commit removes the excluded tests on CentOS 9 Stream, as https://bugzilla.redhat.com/show_bug.cgi?id=2167468 is now fixed.
> Enhancement and fix for containerized pytest

- .github/workflows/pytest.yml
- scripts/container-pre-test.sh
First commit addresses one test that was being skipped on Fedora images. By including dnf-plugins-core package there as well, we can run it.
Second commit removes the excluded tests on CentOS 9 Stream, as https://bugzilla.redhat.com/show_bug.cgi?id=2167468 is now fixed.
Backport of PR #3214.
> [1.28] Enhancement and fix for containerized pytest

- src/cloud_what/fact_collector.py
- src/cloud_what/setup.py
- src/rhsmlib/facts/dmidecodeparser.py
- src/rhsmlib/facts/dmiinfo.py
- src/rhsmlib/facts/firmware_info.py
- src/zypper/services/rhsm
- subscription-manager.spec
- test/rhsmlib_test/dmidecodedata/aarch64-baremetal-1.txt
- test/rhsmlib_test/dmidecodedata/aarch64-baremetal-2.txt
- test/rhsmlib_test/dmidecodedata/aarch64-qemu-1.txt
- test/rhsmlib_test/dmidecodedata/x86_64-aws-1.txt
- test/rhsmlib_test/dmidecodedata/x86_64-baremetal-1.txt
- test/rhsmlib_test/dmidecodedata/x86_64-esx6.7-1.txt
- test/rhsmlib_test/dmidecodedata/x86_64-qemu-1.txt
- test/rhsmlib_test/test_collector.py
- test/rhsmlib_test/test_dmifacts.py
The python-dmidecode module has currently not received work upstream in the last 7 years, and it starts to fails in some situations (e.g. Kernel Lockdown, when /dev/mem cannot be read). Hence, we cannot keep using python-dmidecode anymore.
As way forward, create a parser to parse the output of `dmidecode(1)`, and a fact collector that uses this parser to provide `"dmi.*"` facts.
The parser and the facts collector are tested using collected outputs (and anonymized) of `dmidecode(1)`, so it is easy to check whether changes will break existing outputs.
Cloud-what has its own facts collector using python-dmidecode in case subscription-manager is not installed. In it, manually query `dmidecode(1)` for known DMI strings used by the cloud detection, so it should work in that case too.
The …
> [1.28] New dmidecode-based DMI facts collector; use it on aarch64

- src/subscription_manager/cli_command/register.py
- test/test_registration.py
When we prompt the user for multiple environments, in the input string any space is removed before further internal processing.  Most likely this was done to minic the non-multi-environment case that strips the input to ensure it is not empty; sadly this makes more than that, making it impossible to interactively type environment names that contain a space, as it will be removed.
Since the result of `_prompt_for_environment()` is passed to `check_set_environment_names()`, which `strip()`s any environment after splitting the input string by comma, we can simply `strip()` the input string in both multi-environments and non-multi-environments cases: it will be enough to ensure that it is non-empty.
Add a simple test to check a couple of these whitespace situations, i.e. in the middle after a …
> 2174297: register: do a simple `strip()` on environment(s) input

- src/rhsmlib/dbus/objects/config.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2093883
* Card ID: ENT-5383
* When logging level was changed using D-Bus method `SetAll()`, then exception was raised and it wasn't possible to change log level. This has happened very rarely.
* The race condition was caused probably by this case. When logging level was changed by `SetAll()` method and it was necessary to re-initialized logging, then some other process changed `rhsm.conf` and [logging] section was removed from this file. When iniparse tried to get section logging, then this section wasn't there and it caused exceptions.
* Fixed same issue for `Set()` D-Bus method too.
> 2093883: Fix issue with race condition in rhsm.service

- src/rhsmlib/dbus/objects/config.py
* Backport commit
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2076948
* Card ID: ENT-5383
* When logging level was changed using D-Bus method `SetAll()`, then exception was raised and it wasn't possible to change log level. This has happened very rarely.
* The race condition was caused probably by this case. When logging level was changed by SetAll() method and it was necessary to re-initialized loggin, then some other process changed rhsm.conf and [logging] section was removed from this file. When iniparse tried to get section logging, then this section wasn't there and it caused exceptions.
* Fixed same issue for `Set()` D-Bus method too.
Backport of PR #3151 to 1.28.
> 2076948: [1.28] Fix issue with race condition in rhsm.service

- src/rhsm/connection.py
* When debugging of http traffic is enabled and responses are printed to console, then color of response is set to gray. Thus it is easier to distinguish standard output to console and debug print of response. It should work on dark and light backgrounds of terminal.
> Small improvement of debugging of http traffic

- test/test_cert_sorter.py
Create a new unit test that setups an SCA-like environment to test the fix for 2178610.
Followup of commit ff10c63cbe3822e927a943b24af4e22a35f43dc5.
> test: add simple test for 2178610

- src/subscription_manager/lock.py
- test/test_lock.py
* Card ID: ENT-5077
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2093291
* When the /run is mounted read-only, then try to create lock
file in /run/users, which should never be mounted as
read-only. The path to user's runtime directory should be
defined in $XDG_RUNTIME_DIR
* Added some doc strings and type hints for LockFile class
and added more debug prints
* Added some unit tests
> 2093291: Make locking more reliable

- .github/workflows/tito.yml
"npm" recently became broken in Fedora and doesn't provide the "npm"
binary any more. As a workaround, switch the "npm" build dependency to
"nodejs-npm" on Fedora to fix the build with tito.
Split the npm installation to a separate step, so "npm" is still 
installed on CentOS.
> [1.28] ci: install nodejs-npm on Fedora

- src/rhsmlib/dbus/server.py
- test/rhsmlib/dbus/test_server.py
Catching all the exceptions in `DomainSocketServer.run()` has two big drawbacks in case anything in it fails:
- the error is logged, and then nothing is done with it
- callers of it cannot even know that an issue happened
- even worse: `run()` returns a string in case of no errors, whereas the exception case did not return anything (thus None), causing type issues in callers
The only user of `DomainSocketServer` is `RegisterDBusObject`, and all the D-Bus methods already catch all the exceptions that happen during their execution (turning them into D-Bus exceptions). Hence, it is possible to safely drop all the exception handling in `DomainSocketServer.run()`, letting errors that happen in it properly propagate back as error reply to D-Bus.
> dbus: don't catch exceptions in DomainSocketServer.run()

- Makefile
- etc-conf/rhsm.conf
- setup.py
- src/daemons/rhsmcertd.c
- src/rhsm/profile.py
- src/subscription_manager/managercli.py
- src/subscription_manager/utils.py
- subscription-manager.spec
- test/test_utils.py
* Backport to 1.28 branch.
* Original PRs:
* #3139
* #3179 
* #3142
* Original commits:
* b70c0d524675a0cb3b7971df56ffcb588ad52df6
* cc3f24c2107ccf0ed43026d7daceb5e533b8df8d
* 43e7905cc935226a394832ecb872e94694bbde03
* 3a8e42afb855f4f7378a862a0445348d14728b49
* d3075accf0bb3b0c5f49eb185312480f3d6ee620
* 1bb1850325f9b157b8111e871e1193a33cd7b484
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2132242
* Card ID: ENT-5530
* The subscription-manager tries to upload combined DNF profile at the end of registration process. Gathering of this profile can take very long time. It can be several minutes in some edge cases. This blocked registration process and the activity of gathering DNF profile was not communicated using live status message like other activities.
* This commit uses novel …
> 2132242: [1.28] Outsource uploading DNF profile to rhsmcertd

- po/keys.pot
No new or changed strings; this mostly includes the removal of rshm_icon and rhn-migrate-classic-to-rhsm, and the drop of a couple of DMI-related log messages that were wrongly translated.
> [1.28] New extraction for translatable strings

- subscription-manager.spec
When subscription-manager-migration was dropped, the Obsoletes for it in subscription-manager was not added; since sub-man-migration had a strict dependency on sub-man, adding the Obsoletes helps during upgrades.
Followup of commit 5c792d4e97c0fe5e09b7c6b17f54afafdaa203d7.
> spec: Obsolete subscription-manager-migration

- subscription-manager.spec
When subscription-manager-migration was dropped, the Obsoletes for it in subscription-manager was not added; since sub-man-migration had a strict dependency on sub-man, adding the Obsoletes helps during upgrades.
Followup of commit 1b4a84147734a6d777309866e3e353d023798ff2.
(cherry picked from commit 77a650d995e5871906ed9b8b82746b0c3d933583)
Backport of #3265 to 1.28.
> [1.28] spec: Obsolete subscription-manager-migration

- test/cloud_what/test_cloud_what.py
- test/fixture.py
- test/rhsm/unit/test_profile.py
- test/rhsmlib_test/test_cloud_facts.py
- test/test_auto_registration.py
Tests for Cloud collector were not properly cleaned up. When they were
run before ModulesProfile tests, they caused them to fail, because they
are altering the global state by manipulating the singleton instances.
---
_Previous description:_
From time to time (`--randomly-seed=571057011`), the four tests in `TestModulesProfile` would fail.
Some AWS test is not properly un-mocked, which causes the tests in
test_profile to fail. It is because the unknown test leaves the global
state dirty, which makes the rest of the code think we are running on
AWS. This makes `AWSCloudProvider.rhui_repos()` iterate over a mock which
does not support it, making it fail.
The traceback is:
```
ModulesProfile.__init__()
ModulesProfile.__generate()
ModulesProfile.fix_aws_rhui_repos(base=$MOCK) …
```
> [1.28] Prevent Mock failures for ModulesProfile tests

- test/cloud_what/test_cloud_what.py
- test/fixture.py
- test/rhsm/unit/test_profile.py
- test/rhsmlib/facts/test_cloud_facts.py
- test/test_auto_registration.py
Tests directly and indirectly using Cloud What were not being properly cleaned up. When they were run before ModulesProfile (and other) tests, they caused them to fail, because they are altering the global state by manipulating the singleton instances.
(Adapted from 2b35656)
Note: The issues were not showing up in this branch, because test_cloud_what.py was already resetting the singletons in tearDown(). However, to keep this from happening in another situation, this patch is ensuring that those classes are reset every time, even if they do not cause errors.
> Prevent Mock failures for ModulesProfile tests 

- test/cli_command/test_attach.py
There are a couple of test cases for the "attach" command that check the behaviour for `--auto` and `--pool POOL_ID` in case of SCA; the problem is that they were broken until now for a couple of reasons:
- the `main()` method of a command class (derived from `AbstractCLICommand`) takes a list of strings, and not a single string; since `ArgumentParser.parse_known_args()` iterates on its `args` argument, and iterating over a `str` is possible in Python 3, this "runs fine", however it matches nothing, exiting with an usage message
- as consequence/related to the above, the two tests assumed the runs would fail, whereas because of the behaviour change they now cause a clean exit (with exit code 0)
Hence, repair these two tests so they work:
- pass the arguments to `main()` properly as list …
> tests: repair attach cases in SCA mode

- test/test_managercli.py
There are a couple of test cases for the "attach" command that check the behaviour for `--auto` and `--pool POOL_ID` in case of SCA; the problem is that they were broken until now for a couple of reasons:
- the `main()` method of a command class (derived from `AbstractCLICommand`) takes a list of strings, and not a single string; since `ArgumentParser.parse_known_args()` iterates on its `args` argument, and iterating over a `str` is possible in Python 3, this "runs fine", however it matches nothing, exiting with an usage message
- as consequence/related to the above, the two tests assumed the runs would fail, whereas because of the behaviour change they now cause a clean exit (with exit code 0)
Hence, repair these two tests so they work:
- pass the arguments to `main()` properly as list …
> [1.28] tests: repair attach cases in SCA mode

- man/subscription-manager.8
- src/rhsmlib/dbus/objects/attach.py
- src/subscription_manager/cache.py
- src/subscription_manager/managercli.py
- src/subscription_manager/utils.py
- test/rhsmlib_test/test_attach.py
- test/test_managercli.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2182768
* Manual attaching of pool using --pool CLI option is not
allowed now. When user tries to attach any pool in SCA
mode, then info message is printedn and subscription-manager
is terminated
* Added two unit tests for auto-attach ins SCA mode and
manual attach
* Added more debug prints for cache used by function
is_simple_content_access(), because I considered using
this method, when --help is used, but calling
subscription-manager attach --help would cause calling
one REST API endpoint
* Updated manual page about subscription-manager
* Make sure to not disallow auto-attach in the D-Bus interface, to avoid breaking users
Backport to 1.24 of the following PRs (backported from 1.28 to ease the backport changed needed):
- an own commit …
> [1.24] 2182768: Disallowed attaching pool in SCA mode

- subscription-manager.spec
Update the dependencies of libdnf-plugin-subscription-manager (which
contains the C plugin using libdnf), removing old or unneeded ones:
- drop 'dnf', as the plugin needs the library and not dnf itself
- drop 'libdnf' & 'json-c', as the right shared libs dependencies will
be added automatically, and the 'libdnf' version pinned here is super
old; the versioned 'libdnf-devel' 'will ensure the build against a
needed version
Switch the manual 'dnf' dependency in subscription-manager with 
'python3-dnf', which is what is actually needed (since there are Python
plugins).
There should be no behaviour changes.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2209387
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2209411
> spec: update deps for dnf or in libdnf packages

- integration-tests/run
The most recent Chromium 113 does not work any more with sizzle, tests
were hanging as soon as they switched to a frame. The latest cockpit
testlib applied a workaround [1]. As the latest Cockpit library also
moved to PatternFly 5, but that would be prohibitively expensive for
sub-man's stable branch, switch to the (temporary) "274+chromium-sizzle"
branch, which has that workaround backported.
[1] https://github.com/cockpit-project/cockpit/pull/18812
---
This will fix the [current test failure](https://cockpit-logs.us-east-1.linodeobjects.com/pull-4847-20230606-073138-c9c1f2f3-rhel-8-4-candlepin-subscription-manager-subscription-manager-1.28/log.html), which started to happen with the update to Chromium 113. This blocks https://github.com/cockpit-project/bots/pull/4847
> [1.28] Update cockpit test lib for Chromium 113 fix

- integration-tests/run
The most recent Chromium 113 does not work any more with sizzle, tests were hanging as soon as they switched to a frame. The latest cockpit testlib applied a workaround [1]. As the latest Cockpit library also moved to PatternFly 5, but that would be prohibitively expensive for sub-man's stable branch, switch to the (temporary) "274+chromium-sizzle" branch, which has that workaround backported.
[1] https://github.com/cockpit-project/cockpit/pull/18812
----
Same as #3276 for the 1.28.36 branch.
> [1.28.36] Update cockpit test lib for Chromium 113 fix

- integration-tests/run
The most recent Chromium 113 does not work any more with sizzle, tests were hanging as soon as they switched to a frame. The latest cockpit testlib applied a workaround [1]. As the latest Cockpit library also moved to PatternFly 5, but that would be prohibitively expensive for sub-man's stable branch, switch to the (temporary) "274+chromium-sizzle" branch, which has that workaround backported.
[1] https://github.com/cockpit-project/cockpit/pull/18812
----
Same as #3276 for the 1.29.26 branch.
> [1.29.26] Update cockpit test lib for Chromium 113 fix

- .github/workflows/libdnf.yml
- .github/workflows/pytest.yml
- .github/workflows/tito.yml
This branch is aimed at RHEL 8.8.x, so the only testing needed is on CentOS Stream 8.
Modify the coverage reporting to use CentOS Stream 8, rather than Fedora latest.
> [1.28.36] ci: run jobs only on CentOS Stream 8

- src/subscription_manager/managercli.py
Recent PRs in the 1.24 branch (#3261 & #3271) changed how a `RestlibException` is formatted when exiting with an error; since 1.24 is a long-lived maintenance branch, the expectation is that the error reporting stays unchanged when possible.
Hence, update the error reporting for `RestlibException` in a couple of places to be back how it used to be before commit 3b3eda26eb058ab20fde1edf25e8a5b5cb9d3200 & commit c4c120a007f8b97bc41335f095ccee3e19dec94f.
> [1.24] Update RestlibException error reporting

- src/rhsmlib/facts/cloud_facts.py
- test/rhsmlib/facts/test_cloud_facts.py
* Azure internal metadata API provides the Subscription ID for the running Virtual Machine just need to capture the fact
* This subscription ID can be used to connect the system to an associated marketplace offer
> Collect Azure Subscription ID as a cloud fact

- src/rhsmlib/facts/cloud_facts.py
- test/rhsmlib/facts/test_cloud_facts.py
* Collect the project_id from the processed JWT
* Collect the project_number from the processed JWT
* This project identifiers can be used to connect the system to an associated marketplace offer
> Collect GCP Project information as cloud facts

- src/rhsm/config.py
- test/rhsm/unit/test_config.py
* Card ID: ENT-5603
UBI images (by accident or oversight) come with /etc/rhsm-host/ directory already existing. This makes our detection fire every time, even if the host mapping is disabled and this directory is empty.
This patch also uses /etc/pki/entitlement-host/ to perform container detection, not just /etc/rhsm-host/.
> ENT-5603: Explicitly check for provided entitlement certificates

- src/subscription_manager/i18n.py
- test/test_i18n.py
Previous to this change we were reading the language that we should
translate to from the `LANG` env var, disregarding other locale related
variables of higher precedence like `LC_MESSAGES` and `LC_ALL`.  This change
fixes that by getting the language to translate to from
`locale.setlocale()` which is calculated from all of the relevant user
environment variables.
* Remove the warning about using a fallback of `C.UTF-8` if the user's
environment variables did not specify a language code valid for the
system.
* Retrieve the language to translate to using
`locale.setlocale("LC_MESSAGES")`.  This is better than using
`os.environ.get("LANG")` because `setlocale()` accounts for all of the
environment variables that are part of deciding which language the
system gettext will use, not just …
> Fix order of language variables

- src/rhsm/config.py
* Card ID: ENT-5582
SMDEV_CONTAINER_OFF used to be a environment variable an user could set to overwrite subscription-manager's detection of container runtime.
Initially a developer feature, it ended up being used by customers who wanted to run RHEL UBI images on top of registered RHEL hosts independently. It was evaluated that the extended container detection is not worth and causes more issues than it solves.
After reverting back to /etc/* (config and certificate) based detection we can remove the environment variable.
The only supported way of overwriting this settings now will be removing the secrets from within the container:
```
```
> ENT-5582: Remove container detection envvar overwrite

- scripts/build_updates_img.sh
- scripts/container-pre-test.sh
- setup.py
* Card ID: ENT-5099
This is a follow-up to 4c81d7c and #3284.
While the ethtool dependency was dropped from the .spec file, it was not completely removed from the rest of the build files. This commit fixes that.
> Drop further ethtool dependency mentions

- pytest.ini
- src/rhsmlib/dbus/base_object.py
- src/rhsmlib/dbus/facts/base.py
- src/rhsmlib/dbus/objects/attach.py
- src/rhsmlib/dbus/objects/config.py
- src/rhsmlib/dbus/objects/consumer.py
- src/rhsmlib/dbus/objects/entitlement.py
- src/rhsmlib/dbus/objects/products.py
- src/rhsmlib/dbus/objects/register.py
- src/rhsmlib/dbus/objects/syspurpose.py
- src/rhsmlib/dbus/objects/unregister.py
- src/rhsmlib/dbus/server.py
- src/rhsmlib/dbus/service_wrapper.py
- src/rhsmlib/services/products.py
- test-requirements.txt
- test/__init__.py
- test/rhsmlib/base.py
- test/rhsmlib/dbus/test_attach.py
- test/rhsmlib/dbus/test_config.py
- test/rhsmlib/dbus/test_consumer.py
- test/rhsmlib/dbus/test_entitlement.py
- test/rhsmlib/dbus/test_facts.py
- test/rhsmlib/dbus/test_products.py
- test/rhsmlib/dbus/test_register.py
- test/rhsmlib/dbus/test_server.py
- test/rhsmlib/dbus/test_unregister.py
For a long time, D-Bus tests had to be run in a separate threads, otherwise they were bringing down whole pytest process. Even that wasn't ideal and over time we started seeing various problems with it.
This new code makes a difference between the logic (which makes sub-man do stuff) and the API (which is published to D-Bus) to make it easily testable.
- The logic layer (`*DBusImplementation`) performs the Candlepin API calls and local changes to the system.
- The API layer (`*DBusObject`) manages l10n, sender and serialization into/from D-Bus and Python objects.
This makes it possible to test logic without having to use threads and workarounds.
> Simplify D-Bus tests

- src/plugins/dnf/subscription_manager.py
- src/subscription_manager/cli_command/cli.py
- test/test_managercli.py
> ENT-5581: Update messaging around the "container mode"

- src/rhsmlib/facts/cloud_facts.py
- test/rhsmlib_test/test_cloud_facts.py
* Card ID: ENT-5606
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2218282
* Backport two PRs to 1.28 branch:
* (Azure) https://github.com/candlepin/subscription-manager/pull/3285
* (GCP) https://github.com/candlepin/subscription-manager/pull/3287
* Squashed commits a little bit (fixing typo, etc.)
> 2218282: [1.28] report extra facts from VMs running on public clouds

- requirements.txt
- test/test_managercli.py
It is not used by default (and not supported anymore at this point), so do not install it.
> [1.24] Stop using M2Crypto

- test/rhsmlib/facts/test_insights.py
* Card ID: ENT-5622
When the testing system contains a file with Insights ID, the tests fails. This is caused by insufficient mocking (probably because none of the testing systems have insights-client installed and registered).
> Mock IOError for Insights fact collection tests

- test/rhsmlib_test/test_insights.py
* Card ID: ENT-5622
When the testing system contains a file with Insights ID, the tests fails. This is caused by insufficient mocking (probably because none of the testing systems have insights-client installed and registered).
(Cherry-picked from a005037)
> [1.28] Mock IOError for Insights fact collection tests

- src/rhsm/config.py
- src/subscription_manager/cli_command/abstract_syspurpose.py
> ENT-5624: Properly translate error strings

- src/rhsmlib/dbus/objects/syspurpose.py
- src/subscription_manager/managercli.py
> [1.28] ENT-5624: Properly translate error strings

- src/rhsmlib/dbus/objects/attach.py
- src/rhsmlib/dbus/objects/register.py
- test/rhsmlib/dbus/test_register.py
There are a couple of regressions introduced by a recent D-Bus refactoring (#3283):
- on `PoolAttach`, `EntCertActionInvoker` was not used anymore
- the `force` option for `Register` and `RegisterWithActivationKeys` was looked into the connection options rather than the registration options, making it no more effective
See the individual commit messages for longer explanations.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2232316
> 2232316: fix D-Bus regressions

- .github/workflows/libdnf.yml
- .github/workflows/pytest.yml
- .github/workflows/tito.yml
The Actions are implicitly using 'docker.io/library/fedora:rawhide', which is not the latest possible build. This makes the CI fail even when there is a fix in upstream image already.
> Use Fedora registry to pull container images

- .github/workflows/pytest.yml
- TESTING.md
- scripts/container-pre-test.sh
We are not using D-Bus during tests anymore. The D-Bus packages and `run-dbus-session` workaround inside of a container are no longer necessary.
This PR is blocked by https://github.com/candlepin/subscription-manager/pull/3313 (we need all branches passing).
> TESTING: Update testing requirements

- etc-conf/dbus/system.d/com.redhat.RHSM1.conf
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2225446
* Added patch file, modified spec file: changed release number, added changelog, added autopatch macro
> 2225446: Hotfix of D-Bus policy

- etc-conf/dbus/system.d/com.redhat.RHSM1.conf
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2225443
* Added patch file, modified spec file: changed release number, added changelog, added autopatch macro
> 2225443: [1.28] Hotfix of D-Bus policy

- etc-conf/dbus/system.d/com.redhat.RHSM1.conf
* Backport to RHEL 9.0 branch:
* Original PR: https://github.com/candlepin/subscription-manager/pull/3317
* Original commit: 17c40d5e43e927a2382104ea6f9d18eefda2b863
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2225444 …
> 2225444: [1.29.26] Hotfix of D-Bus policy

- etc-conf/dbus/system.d/com.redhat.RHSM1.conf
* Backport to RHEL 9.2 branch:
* Original PR: https://github.com/candlepin/subscription-manager/pull/3317
* Original commit: 17c40d5e43e927a2382104ea6f9d18eefda2b863
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2225445 …
> 2225445: [1.29.33] Hotfix of D-Bus policy

- etc-conf/dbus/system.d/com.redhat.RHSM1.conf
* Backport to RHEL 8.6 branch:
* Original PR: https://github.com/candlepin/subscription-manager/pull/3318
* Original commit: d9f9be830f5f571400b6b9cc6ff48ed74e56662e
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2225441 …
> 2225441: [1.28.29] Hotfix of D-Bus policy

- etc-conf/dbus/system.d/com.redhat.RHSM1.conf
* Backport to RHEL 8.8 branch:
* Original PR: https://github.com/candlepin/subscription-manager/pull/3318
* Original commit: d9f9be830f5f571400b6b9cc6ff48ed74e56662e
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2225442 …
> 2225442: [1.28.36] Hotfix of D-Bus policy

- etc-conf/dbus/system.d/com.redhat.RHSM1.conf
* Backport to RHEL 8.2 branch:
* Original PR: https://github.com/candlepin/subscription-manager/pull/3318
* Original commit: d9f9be830f5f571400b6b9cc6ff48ed74e56662e
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2229754 …
> 2229754: [1.26] Hotfix of D-Bus policy

- etc-conf/dbus/system.d/com.redhat.RHSM1.conf
* Backport to RHEL 8.1 branch:
* Original PR: https://github.com/candlepin/subscription-manager/pull/3318
* Original commit: d9f9be830f5f571400b6b9cc6ff48ed74e56662e
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2229753 …
> 2229753: [1.25] Hotfix of D-Bus policy

- etc-conf/dbus/system.d/com.redhat.RHSM1.conf
* Backport to RHEL 7.9 branch:
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2229752
* Added patch file, modified spec file: changed release number, added changelog, added autopatch macro
> 2229752: [1.24] Hotfix of D-Bus policy

- src/rhsm/config.py
* Card ID: ENT-5603
The meaning of the entire comment is true, but the last path contains a dash instead of a forward slash.
> ENT-5603: Fix a typo in a comment

- src/rhsm/config.py
- src/subscription_manager/cli_command/abstract_syspurpose.py
> [1.29.33] ENT-5624: Properly translate error strings

- src/subscription_manager/cli_command/abstract_syspurpose.py
> [1.29.30] ENT-5624: Properly translate error strings

- src/subscription_manager/cli_command/abstract_syspurpose.py
> [1.29.26] ENT-5624: Properly translate error strings

- src/rhsmlib/dbus/objects/syspurpose.py
- src/subscription_manager/managercli.py
- src/subscription_manager/migrate/migrate.py
> [1.28.36] ENT-5624: Properly translate error strings

- src/rhsmlib/dbus/objects/syspurpose.py
- src/subscription_manager/managercli.py
- src/subscription_manager/migrate/migrate.py
> [1.28.29] ENT-5624: Properly translate error strings

- src/subscription_manager/managercli.py
> [1.26] ENT-5624: Properly translate error strings

- src/subscription_manager/managercli.py
- src/subscription_manager/migrate/migrate.py
> [1.28.13] ENT-5624: Properly translate error strings

- src/rhsm/connection.py
- src/rhsm/utils.py
- src/subscription_manager/cli_command/cli.py
- test/cli_command/test_override.py
- test/rhsm/unit/test_connection.py
- test/rhsm/unit/test_utils.py
- test/test_utils.py
* BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2225403
* Allow parsing of URLs containing IPv6 address like http://user:pass@[2001:db8::dead:beef:1]:3128/prefix
* Use properties of urllib.parse to get username, password, hostname, port and prefix
* Fixed `--proxy` CLI option to use parse_url() function
* Print IPv6 addresses correctly
* Fixed unit tests for the case "https://www.redhat.com:/en", because it is correct URL
> 2225403: Parse URL properly

- subscription-manager.spec
setuptools is not used on runtime at all.
pkg_resources (part of the python3-setuptools package) is used in 2 places:
- console_scripts entry points (/usr/bin/*) on Python < 3.8
- subscription_manager.utils:get_client_versions
- conditional on subscription_manager.version.pkg_version presence
- hence never imported from the RPM package
Hence, this is really only needed on RHEL 8 or lower, but the specfile conditionals do not seem to support RHEL 7 at all.
No idea about SUSE but if they have at least Python 3.8 they should be good as well.
This is from https://src.fedoraproject.org/rpms/subscription-manager/pull-request/36
> RPM: Avoid needless runtime requirement on python3-setuptools

- src/subscription_manager/productid.py
While triaging your project, our bug fixing tool generated the following message(s)-
> In file: [productid.py](https://github.com/candlepin/subscription-manager/tree/main/src/subscription_manager/productid.py#L688), method: update_removed, a logical expression uses the identity operator. A new object is created inside the identity check operation and then used for matching identity. Since this is a distinct, new object, it will not match with anything else. As a result, the identity check will have a logical short circuit and the program may have unintended behavior. iCR suggested that the logical operation should be reviewed for correctness.
- Replaced `is []` with `== []` 
*This section is only relevant if your project requires contributors to sign a Contributor License Agreement (CLA) …
> Fixed inappropriate logical expression

- src/cloud_what/providers/aws.py
- src/cloud_what/providers/azure.py
- src/cloud_what/providers/gcp.py
- src/rhsmlib/client_info.py
- src/subscription_manager/productid.py
- src/syspurpose/files.py
* Card ID: CCT-118
E721: do not compare types, for exact checks use `is` / `is not`
> CCT-118: Fix flake8 error E721

- src/cloud_what/providers/aws.py
- src/rhsm/profile.py
- test/test_auto_registration.py
* Card ID: RHEL-9435
Even though both versions are officially supported, the AWS teams are tracking connections making v1 requests as WARNINGs [0].
This patch switches the order to try to use IMDSv2 first.
[0]: https://github.com/aws/aws-imds-packet-analyzer
> RHEL-9435: Get AWS metadata via IMDSv2

- src/cloud_what/providers/aws.py
- test/test_auto_registration.py
* Card ID: RHEL-9435
Even though both versions are officially supported, the AWS teams are tracking connections making v1 requests as WARNINGs [0].
This patch switches the order to try to use IMDSv2 first.
[0]: https://github.com/aws/aws-imds-packet-analyzer
Cherry-picked from 953f2df.
> [1.28] RHEL-9435: Get AWS metadata via IMDSv2

- src/plugins/dnf/subscription_manager.py
* When system is not registered, then we print hint how to register the system. We mention only "subscription-manager", but there is no information about "rhc", when "rhc" is installed.
* This patch adds "rhc" to this message.
* When "rhc" is not installed, then original message is displayed.
> RHEL-7206: Small change of message printed by dnf plugin

- .github/workflows/libdnf.yml
- .github/workflows/pytest.yml
- .github/workflows/tito.yml
Even if it can be useful for testing on developers' system, in practice the 1.28 branch lags a lot behind in terms of changes for newer versions of Python.
Since the branch is stable, and targets only old versions of RHEL 8, then drop the testing on Fedora.
> [1.28] ci: stop testing on Fedora

- src/cloud_what/_base_provider.py
- src/rhsm/connection.py
- src/rhsm/utils.py
This change clearly labels each section that's printed to make it easier to identify the interesting parts.
This also adds SUBMAN_DEBUG_PRINT_TRACEBACKS flag to print the traceback directly to stdout.
---
Example:
(the white horizontal line is just result of putting two screenshots together, the traceback was too long)
> Improve debug logging

- src/cloud_what/_base_provider.py
The `requests.PreparedRequest` may not have any `.body` attribute set. This happens when unit tests are run, for example. In that case the test would crash.
This is a follow-up to #3361
> Fix an error in debug logging of cloud-what

- etc-conf/dbus/system.d/com.redhat.RHSM1.conf
- src/rhsmlib/dbus/dbus_utils.py
- src/rhsmlib/dbus/objects/register.py
- src/rhsmlib/dbus/server.py
- test/rhsmlib/dbus/test_register.py
* We were too agresive, when we fixed CVE in this PR: https://github.com/candlepin/subscription-manager/pull/3317
* It is still safe to allow non-root user to create abstract socket using Start() on interface com.redhat.RHSM1.RegisterServer and destroy it later using Stop(). This abstract socket could be later used by root user for calling e.g. Register() on interface com.redhat.RHSM1.Register. This is way how it works for gsd-subman (run by non-root user) and gsd-subman-helper (run by root user).
> RHEL-15110: Fix issue with registration using gsd-subman

- test-requirements.txt
Previously, in f801b69, we had to limit pytest to version <7 because our tests were using pytest-forked to run D-Bus unit tests and pytest was crashing on that.
We have since changed the way we test D-Bus by not starting a server for each test case, and aren't constrained by the pytest regression anymore.
> Remove version constraint of pytest

- src/rhsmlib/facts/host_collector.py
- test/rhsm/unit/test_connection.py
- test/rhsmlib/facts/test_host_collector.py
These functions are deprecated since Python 3.11.
- `getdefaultlocale()` can be replaced with `getlocale(category=)`
- `resetlocale()` can be replaced with `setlocale(category=, locale=)`
> Remove deprecated `locale.*()` functions

- subscription-manager.spec
GLib is required to build `rhsmcertd(8)`.  When building with DNF support, `glib2-devel` is pulled in by `libdnf-devel`.  However, turning off DNF support doesn't disable building `rhsmcertd(8)`.  Therefore, the depedency needs to be listed explicitly.
> spec: Add missing GLib dependency when building without DNF

- etc-conf/dbus/system.d/com.redhat.RHSM1.conf
- src/rhsmlib/dbus/dbus_utils.py
- src/rhsmlib/dbus/objects/register.py
- src/rhsmlib/dbus/server.py
- test/rhsmlib_test/test_register.py
* Backport to 1.28 branch. Original PR: https://github.com/candlepin/subscription-manager/pull/3350
* Original commits:
* https://github.com/candlepin/subscription-manager/commit/ba1e0e419b5fe5bf6742d3341481279180110a23
* https://github.com/candlepin/subscription-manager/commit/bc3377669a1ac3766842fe81f2b341c014df0429
* We were too agresive, when we fixed CVE in this PR:
https://github.com/candlepin/subscription-manager/pull/3318
* It is still safe to allow non-root user to create abstract
socket using `Start()` on interface `com.redhat.RHSM1.RegisterServer`
and destroy it later using `Stop()`. This abstract socket
could be later used by root user for calling e.g. `Register()`
on interface `com.redhat.RHSM1.Register`. This is way how
it works for `gsd-subman` (run by non-root user) and …
> RHEL-21049: [1.28] Fix issue with registration using gsd-subman 

- scripts/container-pre-test.sh
- test-requirements.txt
The `lxml` library pushed a new version that does not support Python 2. The package does not use the package qualifiers like `python_requires` to limit the supported versions of Python understandable by Pip or PyPI, so we need to fix this manually.
This issue has also shown that we were missing the `intltool` dependency.
> Fix CentOS 7 CI for tests

- subscription-manager.spec
* Card ID: RHEL-11947
* RPM package python-requests was not required, but "requests" Python package is used by auto-registration code
> [1.24] fix: Add python-requests to the list of required RPMs

- src/rhsm/connection.py
- test/rhsm/unit/test_connection.py
* Card ID: CCT-266
- The flag `PROTOCOL_SSLv23` is an alias to `PROTOCOL_TLS` since Python 3.6.
- The flag `PROTOCOL_TLS` is deprecated since Python 3.10.
- The flag `PROTOCOL_TLS_CLIENT` has been introduced in Python 3.6 and should be used for client-side contexts.
This patch uses `PROTOCOL_TLS_CLIENT` instead of `PROTOCOL_SSLv23`.
- There is no need to use `OP_NO_SSLv2` and `OP_NO_SSLv3` flags explicitly now; SSLContext disables these by default.
- The flag `PROTOCOL_TLS_CLIENT` enables the `check_hostname` by default. For insecure contexts we need to disable this flag explicitly.
> CCT-266: Update TLS flags

- src/rhsm/connection.py
The current log message includes the floats with 19 decimal points of precision for no good reason.
> Update the log message containing response time statistics

- src/rhsmlib/facts/hwprobe.py
It doesn't make sense to be logging full output of lscpu output in the log file -- it doesn't bring any new information when investigating issues. Only when it is not possible to decode it into dictionary we should include the raw output.
> Stop logging full lscpu output

- src/daemons/rhsmcertd.c
- src/plugins/dnf/subscription_manager.py
- src/rhsm/connection.py
- src/rhsmlib/services/register.py
- src/subscription_manager/cache.py
- src/subscription_manager/entcertlib.py
- src/subscription_manager/identity.py
- src/subscription_manager/identitycertlib.py
- src/subscription_manager/managerlib.py
- src/subscription_manager/scripts/rhsmcertd_worker.py
- test/test_auto_registration.py
- test/test_cache.py
This PR implements the v2 flow for automatic cloud registration. Please see the individual commits for comments, I've tried to keep them all separate to describe the tasks that needed to happen. And I'd like to specifically ask for detailed review of the C code, that may need adjustments.
---
Verify steps:
1. Point `candlepin.local` to a running instance of `ghcr.io/ptoscano/candlepin-unofficial:latest` using your `/etc/hosts` (make sure the instance is set into Hosted mode)
2. Copy the certificate from running Candlepin into your local filesystem and to `/etc/rhsm/ca/`
3. Point sub-man to your local Candlepin through the `rhsm.conf`
4. Patch `cloud-what`'s `aws.py` to point to local mock HTTP server for AWS metadata.
5. Create local facts file to trigger cloud detection rules
6. Make …
> CCT-67: Anonymous registration

- src/plugins/libdnf/CMakeLists.txt
- src/plugins/libdnf/test-productdb.c
- do not build a test source in the libdnf plugin itself
- use `g_clear_error()` instead of `g_error_free()` in tests, in case a `GError*` is reused for more calls
Card IDs: CCT-367 CCT-368
> libdnf: small test fixes

- src/plugins/libdnf/product-id.c
- src/plugins/libdnf/product-id.h
- src/plugins/libdnf/productdb.c
- src/plugins/libdnf/test-product-id.c
- src/plugins/libdnf/test-productdb.c
* Removed unused includes of .h files
* Fixed deprecated function prototype
* Fixed few memory leaks in productdb.c
* Fixed few memory leaks in test-productdb.c
> Small fixes of libdnf plugins

- src/rhsm/certificate.py
- src/rhsm/certificate2.py
- src/rhsm/connection.py
- src/rhsmlib/facts/hwprobe.py
- test/rhsm/unit/test_connection.py
- test/stubs.py
This function is deprecated since Python 3.12.
`datetime.datetime.now(datetime.UTC)` is a timezone-aware equivalent.
> Remove deprecated `datetime.datetime.utcnow()`

- src/plugins/dnf/subscription_manager.py
- src/subscription_manager/cache.py
* Card ID: CCT-171
* New feature: when a release is set by subscription-manager, then dnf plugin "subscription-manager" prints warning about this release
* The information about release is read only from cache file to not slow down DNF.
> feat: Add warning message about release version to dnf plugin

- src/rhsmlib/facts/cloud_facts.py
- test/rhsmlib/facts/test_cloud_facts.py
* Added fact about zone, where the instance is located
* Extended unit test covering this new fact
* Note: GCP does not provide any information about instance type
> feat: Added zone GCP fact

- src/rhsmlib/facts/cloud_facts.py
- test/rhsmlib_test/test_cloud_facts.py
* Original PR: #3388
* Original commit: 2d04f776fe2464432821631805be1d494a9b05ec
* Card ID: CCT-385
* Added fact about zone, where the instance is located
* Extended unit test covering this new fact
* Note: GCP does not provide any information about instance type
> feat: 1.28 Added zone GCP fact

- src/rhsmlib/facts/cloud_facts.py
- test/rhsmlib_test/test_cloud_facts.py
* Backport to 1.28 branch
* Original PR: #3387
* Original commit: df5776aa3debac8fff3fe795ca5701cdbf879aec
* Card Id: CCT-366
* Added two options "aws_region" and "aws_instance_type" to cloud facts to be able to provide better business intelligence
* Extended unit tests
> feat: 1.28 Added more AWS cloud facts

- .github/workflows/libdnf.yml
- .github/workflows/pytest.yml
- .github/workflows/tito.yml
- scripts/container-pre-test.sh
- Test on CentOS Stream 10 instead of 9 RHEL 9 has been branched off to `subscription-manager-1.29`
- Rawhide runs dnf5, we need to install builddep subcommand
> feat(ci): Update testing matrix

- .github/workflows/libdnf.yml
- .github/workflows/pytest.yml
- .github/workflows/tito.yml
* This branch is intended only for RHEL 9. It does not make sense to try to test this for Fedora rawhide, which contains too many things not compatible with RHEL 9
> fix: 1.29 Do not try to test this branch on Fedora rawhide

- man/subscription-manager.8
- src/subscription_manager/cli_command/remove.py
* Card ID: CCT-403
* Modified short description of command
* Modified description in manual page of subscription-manager
> 1.29 Deprecate remove sub-command

- src/plugins/subscription-manager.py
* Card ID: CCT-322
* Card ID: RHEL-7199
When `dnf` is run in a container that gets its content from a host, extra messages were displayed:
```
- Updating Subscription Management repositories.
> Unable to read consumer identity
- subscription-manager is operating in container mode.
> This system is not registered with an entitlement server. You can use
subscription-manager to register.
```
Only the first line and third should be displayed; the second and fourth are not relevant in container mode.
> [1.28] fix: Hide subscription management "errors" in container mode

- src/plugins/dnf/subscription_manager.py
* Card ID: CCT-322
* Card ID: RHEL-7199
When `dnf` is run in a container that gets its content from a host, extra messages were displayed:
```
- Updating Subscription Management repositories.
> Unable to read consumer identity
- subscription-manager is operating in container mode.
> This system is not registered with an entitlement server. You can use
subscription-manager to register.
```
Only the first line and third should be displayed; the second and fourth are not relevant in container mode.
(Cherry-picked from a3265e48c9339bf0ee7428c51fe89d410e8a20d3)
> [1.29] fix: Hide subscription management "errors" in container mode

- .github/workflows/libdnf.yml
- .github/workflows/pytest.yml
- .github/workflows/tito.yml
- scripts/container-pre-test.sh
CentOS Stream 8 reached EOL on 2024-05-31. This patch ensures we can still run EL8-equivalent tests on frozen version of Stream 8.
Since 1.28 only tracks EL8, CentOS Stream 9 specific code is being dropped as well.
> chore(ci): Use Vault for CentOS Stream 8

- src/cloud_what/providers/aws.py
- src/cloud_what/providers/azure.py
- src/cloud_what/providers/gcp.py
* This change allow to run smoke tests of cloud provider with custom facts. Examples of custom facts are described in comments for each cloud provider
> feat: Add option to run smoke tests with fake IMDS servers.

- .github/workflows/pytest.yml
- .github/workflows/tito.yml
- scripts/container-pre-test.sh
CentOS Stream 8 reached EOL on 2024-05-31. This patch ensures we can still run EL8-equivalent tests on frozen version of Stream 8.10.
(Cherry-picked from b1beb790)
> [8.2] chore(ci): Use Vault for CentOS Stream 8

- .github/workflows/pytest.yml
- .github/workflows/tito.yml
- scripts/container-pre-test.sh
CentOS Stream 8 reached EOL on 2024-05-31. This patch ensures we can still run EL8-equivalent tests on frozen version of Stream 8.10.
(Cherry-picked from b1beb790)
> [8.4] chore(ci): Use Vault for CentOS Stream 8

- .github/workflows/libdnf.yml
- .github/workflows/pytest.yml
- .github/workflows/tito.yml
- scripts/container-pre-test.sh
CentOS Stream 8 reached EOL on 2024-05-31. This patch ensures we can still run EL8-equivalent tests on frozen version of Stream 8.10.
(Cherry-picked from b1beb790)
> [8.8] chore(ci): Use Vault for CentOS Stream 8

- .github/workflows/libdnf.yml
- .github/workflows/pytest.yml
- .github/workflows/tito.yml
- scripts/container-pre-test.sh
CentOS Stream 8 reached EOL on 2024-05-31. This patch ensures we can still run EL8-equivalent tests on frozen version of Stream 8.10.
(Cherry-picked from b1beb790)
> [8.6] chore(ci): Use Vault for CentOS Stream 8

- man/subscription-manager.8
- src/subscription_manager/cli_command/attach.py
- src/subscription_manager/cli_command/autoheal.py
- src/subscription_manager/cli_command/register.py
This update aims to add deprecation notices to the attach/auto-attach commands.
- Added deprecation notices to man page.
- Added deprecation notice to `attach` and `auto-attach` module descriptions.
- Added deprecation notice to `--auto-attach` and `--autosubscribe` register options help text.
- Moved the `attach` module from the 'Primary Modules' section in the sub-man help text to 'Other Modules'.
Resolves: CCT-401
> [1.29] feat: deprecate attach/auto-attach

- man/subscription-manager.8
- src/subscription_manager/cli_command/redeem.py
* Card ID: CCT-400
* Modified short description of command
* Modified description in manual page of subscription-manager
* Information about "remove" command introduced in this commit:
ceacba0bb21a98153bc9c1bb3f0adafbf907ed79 wasn't 100% correct.
This should fix this issue.
> feat: 1.29 Deprecate redeem sub-command

- src/subscription_manager/cache.py
- src/subscription_manager/repolib.py
* Card ID: CCT-570
* When consumer certificate is not installed, then StatusCache
should not try to get data from server, because
subscription-manager cannot assemble valid REST API endpoint
and it also does not have valid consumer cert key for mTLS
handshake
* Changed order of two checks in `repolib` module
> fix: Cache shouldn't try to get data from server without UUID 

- src/subscription_manager/cache.py
This is a "regression" exposed by the recent commit 4801f23913a3ebf30d9c39d25ed75fe5d9b4db48:
- `_sync_with_server()` is now called only when the system has an identity
- in `SyspurposeComplianceStatusCache`,` _sync_with_server()` also creates `syspurpose_service`
- calling `get_overall_status()` in a system without an identity tries to use `self.syspurpose_service` which is not defined
Call the `Syspurpose.get_overall_status()` method as proper class method (as it is declared as such), rather than calling it as instance method; this way, it works even when the `syspurpose_service` object was not created. This fixes the usage of `get_overall_status()` in case the system does not have an identity.
Card ID: CCT-589
> fix: make SyspurposeComplianceStatusCache.get_overall_status() always usable

- man/subscription-manager.8
- src/subscription_manager/cli_command/import_cert.py
This update aims to add deprecation notices to the import command.
Changes Made
Added deprecation notices to man page.
Added deprecation notice to import module description.
Resolves: CCT-591
> feat: Deprecate import command

- src/subscription_manager/cache.py
- src/subscription_manager/repolib.py
- avoid Cache fetches from server in case the system is not registered (i.e. there is no identity/UUID)
- fix `SyspurposeComplianceStatusCache` to work in this situation
Backport to 1.29.x:
- #3420
- #3421
> [1.29] fix cache handling for unregistered systems

- man/subscription-manager.8
It was the old name of "redeem", and it was removed long ago.
> doc: drop references to "activate"

- etc-conf/subscription-manager.completion.sh
- man/subscription-manager.8
- src/subscription_manager/cli_command/syspurpose.py
- src/subscription_manager/managercli.py
- test/cli_command/test_addons.py
- test/cli_command/test_role.py
- test/cli_command/test_service_level.py
Removes _addons_, _role_, _service-level_, and _usage_ commands. These are deprecated as top-level commands as they’ve been moved to the _syspurpose_ command as sub-commands.
[CCT-402](https://issues.redhat.com/browse/CCT-402)
> feat: Remove deprecated syspurpose top-level commands

- integration-tests/check-subscriptions
- test/files/mock-insights
Backport some commits from the separate subscription-manager-cockpit repository to fix the CI jobs, especially after recent-ish changes to insights-client/insights-core.
> [1.28] tests: cockpit: backport CI fixes from subscription-manager-cockpit

- src/rhsmlib/facts/cloud_facts.py
- test/rhsmlib/facts/test_cloud_facts.py
* Obtain the VM Name from the instance metadata API
* Obtain the Resource Group Name from the instance metadata API
* These items will improve deduplication logic within Subscription Watch metering
> Collect Azure VM Name and Resource Group Name as a cloud fact.

- cockpit/src/insights.jsx
- integration-tests/check-subscriptions
- test/files/mock-insights
Backport a fix for cockpit, and some fixes to CI bits to help with non-legacy-upload, and CERT-based authentication; the PRs are:
- https://github.com/candlepin/subscription-manager-cockpit/pull/71
- https://github.com/candlepin/subscription-manager-cockpit/pull/72
- https://github.com/candlepin/subscription-manager-cockpit/pull/74
> [1.28.36] cockpit: code fix and CI fixes from subscription-manager-cockpit

- INSTALL.md
- TESTING.md
The installation [instructions](https://github.com/candlepin/subscription-manager/blob/a01dabd2b6f8f6078661b671c5431d601c8171ea/INSTALL.md) now support RHEL in addition to Fedora. The guide has been tested on RHEL 9.2.
There are small touches to the commands in [`INSTALL.md`](https://github.com/candlepin/subscription-manager/blob/a01dabd2b6f8f6078661b671c5431d601c8171ea/INSTALL.md) too:
* `PYTHONPATH` is not a shell command, it doesn’t require explicit `./` for the current directory.
* An alias pointing to the python executable in the virtual environment makes it work without having to activate it.
The testing [guide](https://github.com/candlepin/subscription-manager/blob/a01dabd2b6f8f6078661b671c5431d601c8171ea/TESTING.md) explicitly mentions requirements in the test-requirements.txt …
> doc: Update install and testing guide 

- man/subscription-manager.8
This patch updates the subscription-manager-1.29 man page 
with typo corrections, improved language, and additions of 
deprecation notices for the following options:
* redeem
* attach/auto-attach
* remove
* import
Card ID: CCT-558
> [1.29] feat: update man page with deprecation notices

- src/rhsmlib/services/register.py
- test/rhsmlib/services/test_register.py
- test/stubs.py
> feat: Require SCA for registration

- src/rhsm/connection.py
- src/subscription_manager/scripts/rhsmcertd_worker.py
- call the cloud endpoint without the new version, and with the Accept for the existing endpoint
- use `cache.CloudTokenCache._get_from_server()` directly: the v1 autoregistration does not need any caching of the received token, so use the internal API of `CloudTokenCache` only to fetch the token
- the received token is the JWT token to use directly, without any inspection or unpacking: pass it directly to `_auto_register_standard()`
- drop the leftover commented code for autoregistration v2 for now
(cherry picked from commit 2c559a3f7af7fb128e85ba2239fe8180b80bc5fe)
Backport of PR #3448 to 1.29.x
> [1.29] feat: forcefully switch automatic cloud registration to v1

- scripts/container-pre-test.sh
C10S, being a development build, doesn't always have all packages set up correctly. As of now, two packages (rpm-devel, python3-rpm) depend on different releases of rpm-libs, making the dnf command fail.
To make these issues more obvious next time, `set -euo pipefail` will ensure the script fails instead of continuing.
> test(ci): Improve container pre-test script

- man/rhsm.conf.5
This is the backport of https://github.com/candlepin/subscription-manager/pull/3443
Change "reverse proxy" in rhsm.conf man page to simply "proxy"
Fixes: https://issues.redhat.com/browse/RHEL-52660
Fixes: https://issues.redhat.com/browse/CCT-682
> [1.29] docs: Change reverse proxy to proxy in man page

- man/subscription-manager.8
I'm leaving this PR as a draft until the following PRs are merged:
- **Remove 'redeem' command:** https://github.com/candlepin/subscription-manager/pull/3446
- **Remove 'remove' command:** https://github.com/candlepin/subscription-manager/pull/3444
- **Remove 'attach' command:** https://github.com/candlepin/subscription-manager/pull/3409
- **Remove 'auto-attach' command:** https://github.com/candlepin/subscription-manager/pull/3451
This PR contains some redundant commits to visualize the final man page modifications after the above PRs are merged. I will rebase and squash this PR on top of the other man page changes, so there might not be much changes in this PR when all is said and done except some small modifications to language/wording.
Card ID: CCT-545
> docs: man page modifications after removal of deprecated commands

- src/plugins/dnf/subscription_manager.py
* Card ID: CCT-505, RHEL-35656
* When rhsmcertd is running, then uploading of profile is
outsourced to rhsmcertd process simply by sending SIGUSR1
signal and dnf is not blocked by this activity
* This should also fix issue described in RHEL-35656
> feat: dnf plugin - outsource uploading of profile to rhsmcertd.

- Makefile
- etc-conf/rhsm-sysuser.conf
- src/subscription_manager/identity.py
- src/subscription_manager/managerlib.py
- subscription-manager.spec
* Card ID: CCT-652
* Add rhsm group during installation of subman RPM
* rhsm group is created during installation of
subscription-manager rpm
* System user conf file is installed to /usr/lib/sysuser.d
directory.
* Existing consumer certs and keys are updated during
installation process of rpm. It means that group owner
of all pem files in /etc/pki/consumer is changed to rhsm
and group can read these files. It is important for
systems that are already registered.
* Create consumer cert & key owned by rhsm group
* When consumer certificate or key is created, then try to use
rhsm group as a owner. When this group does not exist, then
0 guid is used
* Modified also function checking and correcting permissions
to consumer cert & key
* Not added any unit test for this case, because it would …
> feat: Use rhsm group for concumer cert and key

- src/rhsmlib/services/register.py
- test/rhsmlib/services/test_register.py
Open questions:
- If the user specifies an activation key with one environment, and manually specifies a different environment, what should  happen? Should this PR handle that case?
- Should the validation be removed from the CLI too? Or just the internal DBus method?
* Card-ID: CCT-762
* Removes validation to prevent specifying environment during registration with activation key
> feat: support registering specifying environments with activation keys

- src/subscription_manager/scripts/rhsmcertd_worker.py
The initial delay when performing the standard autoregistration used to
be done directly in rhsmcertd (the C daemon). When the anonymous
autoregistration was implemented, since it has to start immediately,
that delay in rhsmcertd was dropped in favour of doing it "inline"
during the autoregistration. The waiting was added only during the
anonymous autoregistration flow and not during the standard
autoregistration.
Hence, add the autoregistration wait/delay before performing the
standard autoregistration, restoring the previous behaviour.
There is a small commit factorizing the code to an helper function.
> fix: perform autoreg waiting when performing standard autoreg

- src/subscription_manager/scripts/rhsmcertd_worker.py
The initial delay when performing the standard autoregistration used to
be done directly in rhsmcertd (the C daemon). When the anonymous
autoregistration was implemented, since it has to start immediately,
that delay in rhsmcertd was dropped in favour of doing it "inline"
during the autoregistration. The waiting was added only during the
anonymous autoregistration flow and not during the standard
autoregistration.
Hence, add the autoregistration wait/delay before performing the
standard autoregistration, restoring the previous behaviour.
There is a small commit factorizing the code to an helper function.
Backport of PR #3461 to 1.29.
> [1.29] fix: perform autoreg waiting when performing standard autoreg

- src/rhsm/connection.py
- src/subscription_manager/scripts/rhsmcertd_worker.py
- test/rhsm/unit/test_connection.py
* Card ID: CCT-759
We have to ensure we normalize the headers before we search for the `Retry-After` header.
> fix: Handle Retry-After headers better for 429 responses

- src/rhsm/connection.py
- src/subscription_manager/scripts/rhsmcertd_worker.py
- test/rhsm/unit/test_connection.py
* Card ID: CCT-759
We have to ensure we normalize the headers before we search for the `Retry-After` header.
Backport of PR #3464 to 1.29.
> [1.29] fix: Handle Retry-After headers better for 429 responses

- man/subscription-manager.8
- src/subscription_manager/cli_command/list.py
Options 
```
--available 
--all 
--ondate 
--servicelevel 
--no-overlap
--match-install 
--pool-only 
--afterdate
``` 
were marked as deprecated
in ListCommand definition of their help string.
The options were marked as deprecated in list command manuald page.
> [1.29] feat/cct-868: Subset of list command options marked as deprecated

- etc-conf/subscription-manager.completion.sh
Autocompletion for option `--servicelevel` (`sub-man register --servicelevel`) was removed.
> feat/cct-874: Autocompletion for option --servicelevel was removed

- src/rhsm/config.py
That configuration option was recently removed, so there is no more need to specify a default value for it.
Fixes CCT-966
Followup of commit c124784a20276f1877248f15ed706050b7400dd5.
> fix: drop "autoattachinterval" from the rhsmcertd defaults

- src/rhsm/connection.py
- src/rhsmlib/dbus/objects/register.py
- src/rhsmlib/services/environment.py
- test/rhsmlib/dbus/test_register.py
- test/rhsmlib/services/test_environment.py
Card-ID: CCT-764
This implements the functionality requested in the card, but I would like to get guidance on how to architect the implementation. Perhaps I should be implementing an environments class? The `get_environments` method I created makes multiple calls to the candlepin API, which I don't see precedence for looking at the other DBus methods.
> feat: add GetEnvironments method to DBus register

- src/rhsm/logutil.py
In `subscription-manager/src/rhsm/logutil.py`:
* New loggin formatter class `RhsmISO8601Formatter` is made to ensure that time stamp entry is in ISO-8810 format and that it contains info about milliseconds and time zone.
* Then variable `LOG_FORMATTER` is made and `RhsmISO8601Formatter(LOG_FORMAT)` is assigned to it. Then distributed to places where `.setFormatter(Formatter(LOG_FORMAT, ...))` occured.
CARD CCT-965
> Feat CCT-965: Include timezone in the logs

- etc-conf/subscription-manager.completion.sh
- man/subscription-manager.8
- src/rhsmlib/services/register.py
- src/subscription_manager/cli_command/abstract_syspurpose.py
- src/subscription_manager/cli_command/environments.py
- src/subscription_manager/cli_command/identity.py
- src/subscription_manager/cli_command/owners.py
- src/subscription_manager/cli_command/register.py
- src/subscription_manager/cli_command/service_level.py
- src/subscription_manager/cli_command/user_pass.py
- test/cli_command/test_identity.py
- test/cli_command/test_owners.py
- test/cli_command/test_register.py
- test/cli_command/test_role.py
- test/cli_command/test_service_level.py
* Card ID: CCT-1038
The token-based authentication method was deprecated in RHEL 9.2 and RHEL 8.8. As this feature is no longer relevant, and due to its deprecation, it is safe to remove `--token` starting with RHEL 10.
> chore: Remove the --token authentication

- src/rhsm/connection.py
- src/rhsmlib/services/register.py
- test/rhsmlib/services/test_register.py
* Allow to register also with environment names. It is possible
to use environment names with username & password and
activation-keys & organization authentication
* It is not allowed to use `environmets` and `environment_names`
registration options together, because it is not possible to use
env. IDs and names together on candlepin server
* Introduce environment_type as another registration_option
* When consumer object is returned and it contains environments,
then all environments are checked if type of environment
matches given environment_type. If type is missing or is
different, then system is unregistered and exception is
raised
* Modified few unit tests related to environments
* Added few unit tests
> feat: Enable register with environment names & type

- .github/workflows/libdnf.yml
- .github/workflows/pytest.yml
- .github/workflows/tito.yml
Now that CentOS Stream 10 is officially released, switch to it from the old development version of it.
> ci: use official c10s container image

- .github/workflows/tito.yml
Due to RHEL-73048, `gdb` does not work without `which`. While that bug is being addressed, temporarily install `which` so subscription-manager can be built with `tito`.
> ci: temporarily install 'which' on CentOS Stream 10

- src/daemons/rhsmcertd.c
Print the timestamp in the `rhsmcertd.log` log file using an ISO 8601
format with subseconds precision. The implementation needs multiple
passes/fixes due to the limitations of the C APIs.
Card ID: CCT-965
> rhsmcertd: use ISO 8601 timestamps for the log file

- src/plugins/dnf/subscription_manager.py
* Card ID: CCT-505
* When `rhsm.report_package_profile` is disabled in `rhsm.conf` and `rhsm.package_profile_on_trans` is enabled, then profile should not be uploaded, because the `rhsm.report_package_profile` has higher priority as it is described in man page of `rhsm.conf`
> fix: Do not upload profile from DNF, when it is disabled in conf

- subscription-manager.spec
* Card ID: CCT-1027
Following the installation of the subscription-manager package, the dbus service was not loaded as expected. This update addresses the problem by ensuring that the dbus service is properly restarted after the installation or upgrade process.
> fix: Restart rhsm service after installation

- man/subscription-manager.8
The requrements are to put statements containing additional info about `subscription-manager repo-override --list` and about `subscription-manager repo-override --remove` to respective parts of man pages.
**Additional info for --list:**
> Source of the listed overrides is a union of the override specified at the system itself and all the overrides set in the environment(s) system belongs in.
**Additional info for --remove:**
> Source of the override that is attempted to be removed may be one of the environment(s) the system belongs in. It can only be removed by either: removing the override from the environment it originates from or removing the system from the environment the override
> originates from.
CARD CCT-467
> Feat/CCT-467: Add explanatory info about srcs of overrides in repo-override cmd

- src/plugins/zypper/commit/product-id
- src/rhsmlib/candlepin/api.py
- src/rhsmlib/facts/custom.py
- src/rhsmlib/facts/virt.py
- src/subscription_manager/identity.py
- src/subscription_manager/managerlib.py
- src/subscription_manager/plugin/container/__init__.py
- src/subscription_manager/plugin/ostree/action_invoker.py
- src/subscription_manager/plugin/ostree/config.py
- src/subscription_manager/repolib.py
- src/subscription_manager/utils.py
The `warn()` method is officially marked as deprecated since Python 3.2, and `warning()` is the proper method to use. Starting from Python 3.12, the usage of `warn()` triggers deprecation warnings. Hence switch from `warn()` to `warning()`.
There are no behaviour changes.
> chore: logging.warn() -> logging.warning()

- src/rhsm/connection.py
- src/subscription_manager/scripts/rhsmcertd_worker.py
After being reverted for release in 8b25a8512002e2f078857b3abb1ab77a26e63efe and 548a2790597af5195bc780a4d8c6b9edb511b4ae, we can enable it again.
* Card ID: RHEL-74396
> [1.29] feat: Enable automatic cloud registration v2 again

- src/rhsmlib/dbus/objects/register.py
- test/rhsmlib/dbus/test_register.py
* Allow to call D-Bus method `RegisterWithActivationKeys()` with
register option `enable_content`. When this option is not set,
then behavior is still the same. It means that content is
enabled by default, when system is registered with this D-Bus
method.
* Some refactoring and bug fixes in separate commits
> Allow to call RegisterWithActivationKeys() with enable_content

- src/rhsmlib/dbus/objects/register.py
- test/rhsmlib/dbus/test_register.py
* CCT-1005
* When D-Bus method Register() or RegisterWithActivationKeys() is
called with "enable_content": false, rhsm.service will not
download and install SCA cerificate, but it is not enough,
because later rhsmcertd or "subscription-manager status"
will download SCA certificate and it will generated redhat.repo
file
* For this reason, when "enable_content" is false, then
manage_repos will be set to 0 to be sure that redhat.repo
will not be generated later
* TODO: Do not download SCA certificate, when manage_repos is
equal to "0", because it is useless activity and it
consumes resources on candlepin server
> fix: Really disable content

- src/rhsm/connection.py
- src/rhsmlib/services/register.py
- test/rhsmlib/services/test_register.py
These are the features needed to support content templates
> [1.29] Backport of support for content templates

- src/plugins/dnf/subscription_manager.py
* Card-ID: CCT-1111
* Original PRs:
* https://github.com/candlepin/subscription-manager/pull/3141
* https://github.com/candlepin/subscription-manager/pull/3496
* Original commits: 87da3ec8ea941416c01d545dd125bbf220548e0f 29e68c4a1180b6e632d6c80a519d8b92f2a8c692
* When rhsmcertd is running, then uploading of profile is
outsourced to rhsmcertd process simply by sending SIGUSR1
signal and dnf is not blocked by this activity
* This should also fix issue described in [RHEL-35656](https://issues.redhat.com/browse/RHEL-35656)
* When rhsm.report_package_profile is disabled in rhsm.conf and rhsm.package_profile_on_trans is enabled, then profile should not be uploaded, because the rhsm.report_package_profile has higher priority as it is described in man page of rhsm.conf
> feat: [1.29] dnf plugin - outsource uploading of profile to rhsmcertd

- etc-conf/subscription-manager.completion.sh
- man/subscription-manager.8
- src/subscription_manager/cli_command/status.py
- test/cli_command/test_status.py
- test/stubs.py
- test/test_identitycertlib.py
- test/test_printing_utils.py
The message printed for the "overall status" comes directly from the compliance status of the system. Compliance is a concept strictly specific to entitlement mode, and in case of SCA there is nothing to be said, and thus the "unknown" status gets used. While this is technically correct, in practice it tends to confuse users a lot, as it does not clearly give the important detail about the system properly registered.
Hence, in case the content access mode is really SCA (after checking the certificates, potentially refreshing caches and status), use the simple status string "registered" for a system in SCA mode. This, together with the message already printed out about the fact that the host should get access to content, should improve the feedback that users get when reading the output of …
> feat: new status messages for SCA & unregistered systems; removal of SCA support in status

- etc-conf/subscription-manager.completion.sh
- man/subscription-manager.8
- src/subscription_manager/cli_command/status.py
- test/cli_command/test_status.py
After the recent simplification of the "status" command, checks for the subscription/compliance status at arbitrary dates are no more supported, and thus the --ondate option was no more used.
Because of that, drop the --ondate option altogether.
Card ID: CCT-1158.
> feat: drop the --ondate option of "status"

- subscription-manager.spec
This is an architecture-specific package (ie., not noarch).  According to the Fedora [packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/), when a subpackage requires an architecture-specific base package, it MUST do so using a fully versioned archicture-specific dependency.
> spec: Require the base package with architecture-specific dependencies

- cockpit-tests/vm.install
Newer versions of Fedora implement:
https://fedoraproject.org/wiki/Changes/Unify_bin_and_sbin Because of that, now the "subscription-manager" executable is installed in `/usr/bin`, and the old usermode symlink is gone. To properly handle those changes, then:
- remove all the "subscription-manager" executables before installing subscription-manager from the wanted sources
- use "-n" when moving the "subscription-manager" executable to not error out in case the "sbin" install location is set to be "bin"
Backport of https://github.com/candlepin/subscription-manager-cockpit/pull/90.
> build: cockpit: fix installation of sub-man with newer Fedora

- .github/workflows/libdnf.yml
- .github/workflows/pytest.yml
- .github/workflows/stylish.yml
- .github/workflows/tito.yml
- `ci: bump actions/checkout from 3 to 4`
- `ci: bump actions/upload-artifact from 3 to 4`
> [1.28] ci: backport dependabot updates

- .github/workflows/tito.yml
The underlying issue (i.e. https://issues.redhat.com/browse/RHEL-73048) was fixed a couple of weeks ago, so this workaround is no more needed.
This reverts commit 2a5904c92ebc74afe25fc9db1640d6d9d6029772.
> Revert "ci: temporarily install 'which' on CentOS Stream 10"

- src/rhsmlib/facts/collection.py
- src/subscription_manager/facts.py
* Card ID: CCT-1023
This update appends two additional CPU-related facts to the graylist. The graylist currently includes `cpu.cpu_mhz` and `lscpu.cpu_mhz`, but RHEL 9.6 and 10.0 add more CPU facts that also vary frequently.
> fix: Append two additional facts to the graylist

- src/subscription_manager/repofile.py
- test/test_repolib.py
This change allows 'AptRepoFiles' to handle URL parameters for "Components" and "Suites" giving it more flexibility rather than always using a fixed default value. If the URL supplied by Candlepin does not have any such URL parameters, then everything defaults back to the way it was before.
This change is needed to enable the following Katello feature: https://github.com/Katello/katello/pull/11058
That being said, this change is fully backwards compatible and defines an interface that the Katello side PR will need to respect. The Katello PR is dependent on this PR, not the other way around.
This PR replaces the previous draft PR here: https://github.com/candlepin/subscription-manager/pull/3223
My apologies for the switch, the idea is to have both this and the Katello PR in the same hand, …
> Handle URL params for AptRepoFiles

- src/subscription_manager/cli_command/status.py
- test/cli_command/test_status.py
- test/stubs.py
- test/test_identitycertlib.py
- test/test_printing_utils.py
The message printed for the "overall status" comes directly from the compliance status of the system. Compliance is a concept strictly specific to entitlement mode, and in case of SCA there is nothing to be said, and thus the "unknown" status gets used. While this is technically correct, in practice it tends to confuse users a lot, as it does not clearly give the important detail about the system properly registered.
Hence, in case the content access mode is really SCA (after checking the certificates, potentially refreshing caches and status), use the simple status string "registered" for a system in SCA mode. This, together with the message already printed out about the fact that the host should get access to content, should improve the feedback that users get when reading the output of …
> [1.29] feat: new status messages for SCA & unregistered systems

- src/subscription_manager/managercli.py
- test/stubs.py
- test/test_identitycertlib.py
- test/test_managercli.py
The message printed for the "overall status" comes directly from the compliance status of the system. Compliance is a concept strictly specific to entitlement mode, and in case of SCA there is nothing to be said, and thus the "unknown" status gets used. While this is technically correct, in practice it tends to confuse users a lot, as it does not clearly give the important detail about the system properly registered.
Hence, in case the content access mode is really SCA (after checking the certificates, potentially refreshing caches and status), use the simple status string "registered" for a system in SCA mode. This, together with the message already printed out about the fact that the host should get access to content, should improve the feedback that users get when reading the output of …
> [1.28] feat: new status messages for SCA & unregistered systems

- integration-tests/requirements.txt
Now it lives in the RedHatInsights organization.
> tests: update location of pytest-client-tools

- .github/workflows/pytest.yml
This branch tests only on CentOS Stream 9, so use it as reference for the coverage reporting.
Fixes commit f1138bd7eb608feaa8b502ef286d82cf895543e2
> [1.29] ci: use the right distro for coverage reporting

- .github/workflows/pytest.yml
This branch tests only on CentOS Stream 9, so use it as reference for the coverage reporting.
Fixes commit f1138bd7eb608feaa8b502ef286d82cf895543e2
> [1.29.45] ci: use the right distro for coverage reporting

- integration-tests/requirements.txt
Now it lives in the RedHatInsights organization.
Backport of PR #3533 to 1.30.6.
> [1.30.6] tests: update location of pytest-client-tools

- .github/workflows/stylish.yml
We use Fedora packages for flake8 and rpmlint checks; since new versions of Fedora may break this old branch, use a stable Fedora to avoid surprises in the future.
> [1.29.33] ci: use Fedora 40 for stylish test

- .github/dependabot.yml
A number of branches follow old RHEL versions which are still supported; to ease maintaining the GitHub actions used there, enhance the dependabot configuration to track also those branches.
> ci: track also active stable branches with dependabot for GitHub actions

- src/plugins/dnf/subscription_manager.py
- src/rhsmlib/facts/hwprobe.py
- src/subscription_manager/branding/__init__.py
- src/subscription_manager/branding/redhat_branding.py
- src/subscription_manager/cli_command/identity.py
- src/subscription_manager/cli_command/register.py
- src/subscription_manager/utils.py
- test/test_utils.py
Satellite 5 is EOL for some years now, so there is no more need to ensure that systems to be registered to RHSM/Candlepin are not also registered to Satellite 5.
As result, also drop branding strings that are no more needed.
> feat: drop ClassicCheck

- .github/dependabot.yml
- drop the 1.24 branch for now: changes in the hosted GitHub runners [1][2][3] make it hard to test that branch based on EL 7
- demote the update frequency for branches different than "main" to monthly rather than weekly, as there is no rush to switch all of them to newer versions of actions
[1] https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
[2] https://github.com/actions/checkout/issues/1809
[3] https://github.com/actions/runner/pull/3503
> ci: tweak the dependabot config for branches a bit

- subscription-manager.spec
This cleans up the spec file a bit, dropping support for old stuff, and directly using better RPM variables; the general summary of the changes is:
- drop EL 8 bits
- drop old `rhsmd` migration
- drop old `libdnf-plugin-subscription-manager-debuginfo` migration
- consolidate `BuildRequires` for dnf support in one place
- `%py_package_prefix` -> `python3`
- switch from unversioned python RPM variables to python3 ones
- use `%_rundir` instead of own version
See the messages of the individual commits for more detailed explanations.
> spec: drop old bits, cleanups, etc

- src/rhsm/connection.py
> [1.29.33] fix: Handle improperly closed connections

- integration-tests/test_unregister.py
- systemtest/tests/integration/test.sh
Card-ID: CCT-738
integration tests for DBus Unregister call
there are two tests in the PR
- when a system is registered
- when a system is not registered
> integration tests for DBus Unregister call

- integration-tests/test_register_with_activation_keys.py
- systemtest/tests/integration/test.sh
Card-ID: CCT-1051
see https://www.candlepinproject.org/docs/subscription-manager/dbus_objects.html
It is a DBus Method RegisterWithActivationKeys.
This PR covers happy path and wrong path for registering with activation keys.
There can be even wrong organization in a case with activation keys. 
The method should provides a useful response when something wrong was used in arguments of the method.
> Integration Tests for DBus Call RegisterWithActivationKeys

- src/rhsm/connection.py
> fix: Handle improperly closed connections

- test/rhsm/unit/test_connection.py
* When locale was not en_US, then unit test failed due to fact that testing timestamp follwed locale, but it is expected that real time stamp returned from server follow RFC 1123 format. If corner case happens, then it would be OK to print traceback to log file.
> fix: Unit test should ignore locale, when generating test timestamp

- src/rhsm/connection.py
* Card ID: RHEL-85106
(cherry picked from commit 82671638a86894098fe584192cbe2b196518bff4)
> [9.6] fix: Handle improperly closed connections

- src/rhsm/connection.py
* Card ID: RHEL-85104
(cherry picked from commit 82671638a86894098fe584192cbe2b196518bff4)
> [9.4] fix: Handle improperly closed connections

- src/rhsm/connection.py
* Card ID: RHEL-85108
(cherry picked from commit 82671638a86894098fe584192cbe2b196518bff4)
> [10.0] fix: Handle improperly closed connections

- integration-tests/pytest.ini
- integration-tests/test_register_with_activation_keys.py
- integration-tests/utils.py
- systemtest/tests/integration/main.fmf
- systemtest/tests/integration/test.sh
Card-ID: CCT-1051
A DBus API provides  a way to specify environment when using activation keys to register a system.
This PR provides integration tests to verify the way.
I've fixed a file 'integration-tests/README.md' - there were wrong activation keys specified.
It will be necessary to merge the fix into previous PR's that has something to do with activation keys.
A test:
Given a DBus Call RegisterWithActivationKeys is used to register a system
and the system is unregistered
When an argument 'environments' is filled with the proper environments
Then the application registers the system
and the environments are active property of a system identity.
Another test verifies a case when nonexisting environment is used for registration.
> integration tests for register with activation keys and environments

- src/plugins/dnf/subscription_manager.py
- src/rhsm/connection.py
* Card ID: CCT-1424
* Backport to 1.29 branch (RHEL 9)
* Original PR: 3567
* Original commit: 4a9f7a55006548e1930ad156b11a3f0a3f89deb3
* When the time drift between server and client is bigger then two seconds, then subscription-manager dnf plugin prints warning message about this issue.
* The latest time drift is stored in BaseRestLib class to be easily accessible using class method get_time_drift()
* Decreased thresholds for printing warning (15 minutes) and debug (2 seconds) messages to rhsm.log for each REST API call
> feat: [1.29] Added dnf4 warning about skewed clock
